import json

def enrich_genres(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    genre_map = {
        "30 Seconds To Mars": "Rock",
        "50 Cent": "Hip-Hop",
        "A Fine Frenzy": "Indie Pop",
        "A Place To Bury Strangers": "Shoegaze",
        "A-Trak": "Electronic",
        "ABBA": "Pop",
        "AFI": "Punk Rock",
        "AaRON": "Alternative Rock",
        "Across Five Aprils": "Post-Hardcore",
        "Adam Lambert": "Pop Rock",
        "Adaya": "World",
        "Addiction Crew": "Nu Metal",
        "Adema": "Nu Metal",
        "Aesop Rock": "Hip-Hop",
        "Against Me!": "Punk Rock",
        "Agnes": "Pop",
        "Air": "Electronic",
        "Akala": "Hip-Hop",
        "Akon": "R&B",
        "Alain Bashung": "Chanson",
        "Alanis Morissette": "Alternative Rock",
        "Alborosie": "Reggae",
        "Alejandro Sanz": "Latin Pop",
        "Alesha Dixon": "R&B",
        "Alexisonfire": "Post-Hardcore",
        "Ali Ali": "Unknown",
        "Ali Project": "Dark Wave",
        "Alicia Keys": "R&B / Soul",
        "Alien Ant Farm": "Nu Metal",
        "Alizée": "Pop",
        "All Time Low": "Pop Punk",
        "Aloe Blacc": "Soul",
        "Alphabeat": "Pop",
        "Aly & AJ": "Pop Rock",
        "Amarasri": "Unknown",
        "American Princes": "Indie Rock",
        "Amerie": "R&B",
        "Amon Amarth": "Melodic Death Metal",
        "Amy MacDonald": "Folk Rock",
        "Amy Winehouse": "Soul / R&B",
        "Ana Johnsson": "Pop Rock",
        "Anberlin": "Alternative Rock",
        "And One": "Synthpop",
        "Andrew Bird": "Indie Folk",
        "Angels & Airwaves": "Rock",
        "Ani DiFranco": "Folk",
        "Animal Collective": "Experimental Pop",
        "Anita O'Day": "Jazz",
        "Anna Tsuchiya": "J-Rock",
        "Antony and the Johnsons": "Chamber Pop",
        "Apocalyptica": "Symphonic Metal",
        "Apples In Stereo": "Indie Pop",
        "Arcade Fire": "Indie Rock",
        "Arch Enemy": "Melodic Death Metal",
        "Architecture In Helsinki": "Indie Pop",
        "Arctic Monkeys": "Indie Rock",
        "Armin van Buuren": "Trance",
        "Army Of Anyone": "Rock",
        "Arsonists Get All The Girls": "Deathcore",
        "As I Lay Dying": "Metalcore",
        "Ash": "Indie Rock",
        "Ashlee Simpson": "Pop Rock",
        "Ashley Tisdale": "Pop",
        "Asian Kung-Fu Generation": "J-Rock",
        "Asobi Seksu": "Shoegaze",
        "Atreyu": "Metalcore",
        "Audio Bullys": "Electronic",
        "Augustana": "Pop Rock",
        "Autechre": "Electronic",
        "Avenged Sevenfold": "Heavy Metal",
        "Avril Lavigne": "Pop Punk",
        "Ayumi Hamasaki": "J-Pop",
        "Babyshambles": "Indie Rock",
        "Backstreet Boys": "Pop",
        "Bad Religion": "Punk Rock",
        "Band Of Horses": "Indie Rock",
        "Barenaked Ladies": "Alternative Rock",
        "Basement Jaxx": "House",
        "Bassnectar": "Electronic",
        "Bat For Lashes": "Indie Pop",
        "Battles": "Math Rock",
        "Beastie Boys": "Hip-Hop",
        "Beatsteaks": "Punk Rock",
        "Beautiful Creatures": "Hard Rock",
        "Behemoth": "Death Metal",
        "Beirut": "Indie Folk",
        "Ben Harper": "Folk Rock",
        "Ben Lee": "Indie Pop",
        "Ben's Brother": "Pop Rock",
        "Benga": "Dubstep",
        "Benjamin Biolay": "Chanson",
        "Benny Benassi": "House",
        "Berryz Kobo": "J-Pop",
        "Between The Buried And Me": "Progressive Metal",
        "Beyoncé": "R&B / Pop",
        "Biffy Clyro": "Rock",
        "Big & Rich": "Country",
        "Birdman": "Hip-Hop",
        "Björk": "Electronic",
        "Black Kids": "Indie Pop",
        "Black Lips": "Garage Rock",
        "Black Rebel Motorcycle Club": "Garage Rock",
        "Black Stone Cherry": "Rock",
        "Black Veil Brides": "Glam Metal", # Early stuff
        "Blakanova": "Unknown",
        "Bleeding Through": "Metalcore",
        "Bloc Party": "Indie Rock",
        "Blonde Redhead": "Indie Rock",
        "Blood Red Shoes": "Indie Rock",
        "Blue Man Group": "Experimental",
        "Blue October": "Alternative Rock",
        "Blutengel": "Dark Wave",
        "Bob Sinclar": "House",
        "Bobby Valentino": "R&B",
        "Bon Iver": "Indie Folk",
        "Bon Jovi": "Rock",
        "Bone Thugs-N-Harmony": "Hip-Hop",
        "Booka Shade": "Electronic",
        "Bow Wow": "Hip-Hop",
        "Bowling For Soup": "Pop Punk",
        "Boys Like Girls": "Pop Punk",
        "Boyz II Men": "R&B",
        "Brad Paisley": "Country",
        "Brand New": "Emo",
        "Breaking Benjamin": "Post-Grunge",
        "Bree Sharp": "Pop Rock",
        "Brian McKnight": "R&B",
        "Bright Eyes": "Indie Folk",
        "Britney Spears": "Pop",
        "Broken Social Scene": "Indie Rock",
        "Brother Ali": "Hip-Hop",
        "Bruce Springsteen": "Rock",
        "Buckcherry": "Hard Rock",
        "Busta Rhymes": "Hip-Hop",
        "C-Note": "Unknown",
        "Café Tacvba": "Alternative Rock",
        "Cage The Elephant": "Indie Rock",
        "Cajan": "Unknown",
        "Cake": "Alternative Rock",
        "Calvin Harris": "Electronic",
        "Camera Obscura": "Indie Pop",
        "Camila": "Latin Pop",
        "Candie Payne": "Pop",
        "Caribou": "Electronic",
        "Carrie Underwood": "Country",
        "Cartel": "Pop Punk",
        "Casiotone For The Painfully Alone": "Indie Pop",
        "Cassie": "R&B",
        "Cat Power": "Indie Rock",
        "Cee-Lo Green": "Soul / Hip-Hop",
        "Celine Dion": "Pop",
        "Chaka Khan": "R&B / Funk",
        "Chamillionaire": "Hip-Hop",
        "Chapeaumelon": "Pop",
        "Chase & Status": "Drum and Bass",
        "Chemical Brothers, The": "Big Beat",
        "Chevelle": "Alternative Metal",
        "Chicane": "Trance",
        "Chimaira": "Groove Metal",
        "Chris Brown": "R&B",
        "Chris Cornell": "Rock",
        "Chrisette Michele": "R&B",
        "Christian Walz": "Pop Soul",
        "Christina Aguilera": "Pop",
        "Chromeo": "Funk / Electronic",
        "Ciara": "R&B",
        "Cinematic Orchestra, The": "Nu Jazz",
        "City And Colour": "Acoustic",
        "Claude VonStroke": "House",
        "Clawfinger": "Rap Metal",
        "Client": "Electronic",
        "Clipse": "Hip-Hop",
        "Cobrastyle": "Electronic",
        "CocoRosie": "Freak Folk",
        "Coheed And Cambria": "Progressive Rock",
        "Colbie Caillat": "Pop",
        "Cold War Kids": "Indie Rock",
        "Coldplay": "Alternative Rock",
        "Common": "Hip-Hop",
        "Control Machete": "Hip-Hop",
        "Corinne Bailey Rae": "Soul",
        "Cornelius": "Experimental",
        "Craig Morgan": "Country",
        "Cradle of Filth": "Extreme Metal",
        "Crash Romeo": "Pop Punk",
        "Crossfade": "Post-Grunge",
        "Crystal Castles": "Electronic",
        "Cupid": "R&B",
        "Cute Is What We Aim For": "Pop Punk",
        "Cyndi Lauper": "Pop",
        "D-Tent Boys": "Unknown",
        "DJ Khaled": "Hip-Hop",
        "DJ Shadow": "Trip Hop",
        "DJ Tiesto": "Trance",
        "Daft Punk": "House",
        "Damien Rice": "Folk",
        "Dan Deacon": "Electronic",
        "Danity Kane": "Pop / R&B",
        "Dark Tranquillity": "Melodic Death Metal",
        "Datarock": "Dance-Punk",
        "Daughtry": "Rock",
        "Dave Gahan": "Synthpop",
        "Dave Matthews": "Rock",
        "Dave Matthews Band": "Rock",
        "David Guetta": "House",
        "David Vendetta": "House",
        "De La Soul": "Hip-Hop",
        "Deadmau5": "House",
        "Death Cab For Cutie": "Indie Rock",
        "Debbie Harry": "Pop / New Wave",
        "Deerhunter": "Indie Rock",
        "Deftones": "Alternative Metal",
        "Delta Goodrem": "Pop",
        "Demon Hunter": "Metalcore",
        "Dengue Fever": "Psychedelic Rock",
        "Depeche Mode": "Synthpop",
        "Despina Vandi": "Pop",
        "Devendra Banhart": "Folk",
        "DevilDriver": "Groove Metal",
        "Diplo": "Electronic",
        "Dir en grey": "Metal",
        "Dierks Bentley": "Country",
        "Digitalism": "Electronic",
        "Dilated Peoples": "Hip-Hop",
        "Dimmu Borgir": "Black Metal",
        "Dinosaur Jr.": "Alternative Rock",
        "Disco Drive": "Dance-Punk",
        "Dizzee Rascal": "Grime",
        "Dolly Parton": "Country",
        "Don Omar": "Reggaeton",
        "Donkeyboy": "Pop",
        "Down Low": "Hip-Hop",
        "Dragonette": "Electropop",
        "Drake": "Hip-Hop",
        "Dream Theater": "Progressive Metal",
        "Dropkick Murphys": "Celtic Punk",
        "Duffy": "Soul",
        "Duran Duran": "New Wave",
        "Dusty Rhodes And The River Band": "Indie Rock",
        "Dwight Yoakam": "Country",
        "Dying Fetus": "Death Metal",
        "EL-P": "Hip-Hop",
        "Eastern Conference Champions": "Indie Rock",
        "Editors": "Indie Rock",
        "Eilay Butner": "Unknown",
        "Elisa": "Pop Rock",
        "Elliott Smith": "Indie Folk",
        "Emilie Simon": "Electronic",
        "Emily Haines & The Soft Skeleton": "Indie Pop",
        "Eminem": "Hip-Hop",
        "Emma Bunton": "Pop",
        "Emma Pollock": "Indie Rock",
        "Emmon": "Synthpop",
        "Emmure": "Metalcore",
        "End Of Fashion": "Rock",
        "Enrique Iglesias": "Latin Pop",
        "Enter Shikari": "Post-Hardcore",
        "Entombed": "Death Metal",
        "Epica (2)": "Symphonic Metal",
        "Epsilons": "Garage Rock",
        "Eros Ramazzotti": "Pop",
        "Escape The Fate": "Post-Hardcore",
        "Estelle": "R&B",
        "Evanescence": "Rock / Goth",
        "Eve": "Hip-Hop",
        "Evermore": "Rock",
        "Every Time I Die": "Metalcore",
        "Ex-Otago": "Indie Pop",
        "Example": "Electronic",
        "Explosions In The Sky": "Post-Rock",
        "Fabolous": "Hip-Hop",
        "Fabri Fibra": "Hip-Hop",
        "Faith No More": "Alternative Metal",
        "Faker": "Indie Rock",
        "Fall Out Boy": "Pop Punk",
        "Fam-Lay": "Hip-Hop",
        "Fantasia": "R&B",
        "Fatal Bazooka": "Comedy",
        "Fear Factory": "Industrial Metal",
        "Feist": "Indie Pop",
        "Fergie": "Pop",
        "Fibes, Oh Fibes!": "Pop",
        "Fine Arts Showcase, The": "Indie Rock",
        "Finger Eleven": "Alternative Rock",
        "Finley": "Pop Punk",
        "Firewind": "Power Metal",
        "Five Finger Death Punch": "Heavy Metal",
        "Flight of the Conchords": "Comedy / Folk",
        "Florent Pagny": "Chanson",
        "Flyleaf": "Alternative Metal",
        "Foals": "Indie Rock",
        "Foo Fighters": "Rock",
        "Forgive Durden": "Indie Rock",
        "Freakadelika": "House",
        "Freemasons": "House",
        "Freeway": "Hip-Hop",
        "Fright Ranger": "Unknown",
        "Fuel": "Post-Grunge",
        "Full Blown Chaos": "Metalcore",
        "G. Love": "Alternative Hip-Hop",
        "Gabriella Cilmi": "Pop",
        "Gallows": "Hardcore Punk",
        "Garbage": "Alternative Rock",
        "Geisha": "Pop",
        "Gemelli Diversi": "Hip-Hop",
        "Genki Rockets": "Electronic",
        "Ghost Frequency, The": "Indie Rock",
        "Gianna Nannini": "Rock",
        "Giardini Di Mirò": "Post-Rock",
        "Giorgia (2)": "Pop",
        "Girlband": "Pop",
        "Girls Aloud": "Pop",
        "Gloria Estefan": "Latin Pop",
        "Gnarls Barkley": "Soul / Pop",
        "Gob (3)": "Pop Punk",
        "Godsmack": "Nu Metal",
        "Gogol Bordello": "Gypsy Punk",
        "Gonzales": "Electronic",
        "Good Charlotte": "Pop Punk",
        "Gorillaz": "Alternative",
        "Gotye": "Indie Pop",
        "Graham Colton": "Pop Rock",
        "Grandi Animali Marini": "Pop",
        "Green Day": "Punk Rock",
        "Gregory Darling": "Pop",
        "Grinderman": "Garage Rock",
        "Grizzly Bear": "Indie Folk",
        "Groove Coverage": "Eurodance",
        "Guy Sebastian": "Pop",
        "Gwen Stefani": "Pop",
        "Gym Class Heroes": "Hip-Hop / Rock",
        "Gyroscope (2)": "Rock",
        "Günther": "Eurodance",
        "H-Blockx": "Crossover",
        "HER": "R&B", # H.E.R. is much later usually... check if this is a diff artist or early work? Probably a mistake or diff artist. Assuming specific artist for 2007.
        "HIM": "Gothic Rock",
        "Hanson": "Pop Rock",
        "Hard-Fi": "Indie Rock",
        "Harlequin League": "Indie Rock",
        "HateSphere": "Thrash Metal",
        "Hedley": "Pop Punk",
        "Hej Matematik": "Pop",
        "Helloween": "Power Metal",
        "Hellyeah": "Heavy Metal",
        "Herbert Grönemeyer": "Pop Rock",
        "Hey Rosetta!": "Indie Rock",
        "High On Fire": "Stoner Metal",
        "Hilary Duff": "Pop",
        "Hinder": "Post-Grunge",
        "Hot Gossip": "Unknown",
        "Hot Hot Heat": "Indie Rock",
        "Hunter Valentine": "Indie Rock",
        "I Was A Teenage Satan Worshipper": "Electronic",
        "Ian Brown": "Indie Rock",
        "Il Teatro Degli Orrori": "Alternative Rock",
        "Illa Brown": "Unknown",
        "Immanuel Casto": "Pop",
        "In One Year": "Unknown",
        "In This Moment": "Metalcore",
        "Incubus": "Alternative Rock",
        "Indochine": "New Wave",
        "Infieri": "Unknown",
        "Information Society": "Synthpop",
        "Interpol": "Post-Punk Revival",
        "Invitro": "Rock",
        "Iron & Wine": "Indie Folk",
        "Israel Houghton": "Gospel",
        "J. Holiday": "R&B",
        "JC Anderson": "Unknown",
        "Ja Rule": "Hip-Hop",
        "Jacinto Canek": "Unknown",
        "Jack Black": "Comedy Rock",
        "Jack Johnson": "Folk Rock",
        "Jade MacRae": "R&B",
        "Jae Millz": "Hip-Hop",
        "Jagged Edge": "R&B",
        "Jake Owen": "Country",
        "Jamelia": "R&B",
        "James Blunt": "Pop Rock",
        "Jamie T": "Indie Rock",
        "Janusz Radek": "Pop",
        "Jason Michael Carroll": "Country",
        "Jay Z": "Hip-Hop",
        "Jeezy": "Hip-Hop",
        "Jennifer Lopez": "Pop / R&B",
        "Jesse & Joy": "Latin Pop",
        "Jewel": "Folk / Pop",
        "Jim Jones": "Hip-Hop",
        "Jimi Blue": "Pop",
        "Joe": "R&B",
        "Joe Nichols": "Country",
        "John Fogerty": "Rock",
        "John Legend": "R&B",
        "John Mellencamp": "Rock",
        "John Vanderslice": "Indie Rock",
        "Johnny Dread": "Reggae",
        "Johnny Hallyday": "Rock",
        "Jon Lajoie": "Comedy",
        "Jon McLaughlin": "Pop Rock",
        "Jonna Lee": "Electronic",
        "Jordan Galland": "Indie Pop",
        "Josh Groban": "Pop",
        "Josh Turner": "Country",
        "Joss Stone": "Soul",
        "Joy Electric": "Synthpop",
        "Juanes": "Latin Pop",
        "Juli": "Pop Rock",
        "Julien Doré": "Pop",
        "Justice": "Electronic",
        "Justin Martin": "House",
        "Justin Timberlake": "Pop",
        "KRYŠTOF": "Pop Rock",
        "KT Tunstall": "Pop Rock",
        "Kaal": "Unknown",
        "Kaiser Chiefs": "Indie Rock",
        "Kano (6)": "Grime",
        "Kanye West": "Hip-Hop",
        "Kassi": "Unknown",
        "Kat DeLuna": "Pop",
        "Kate & Ben": "Unknown",
        "Kate Nash": "Indie Pop",
        "Kate Tucker": "Indie Rock",
        "Katharine McPhee": "Pop",
        "Katy Perry": "Pop", # Early Katy
        "Keith Urban": "Country",
        "Kele Le Roc": "R&B",
        "Kellie Pickler": "Country",
        "Kelly Clarkson": "Pop Rock",
        "Kelly Rowland": "R&B",
        "Ken": "J-Rock",
        "Kenna": "Electronic",
        "Kenny Chesney": "Country",
        "Kent": "Indie Rock",
        "Kerli": "Pop",
        "Keshia Chanté": "R&B",
        "Kid Rock": "Rock / Hip-Hop",
        "Kid Sister": "Hip-Hop",
        "Killswitch Engage": "Metalcore",
        "Kimberley Locke": "Pop",
        "Kings Of Leon": "Rock",
        "Kirk Franklin": "Gospel",
        "Kissaway Trail, The": "Indie Rock",
        "Klaxons": "Indie Rock",
        "Korn": "Nu Metal",
        "Kreesha Turner": "Pop",
        "Kristin Chenoweth": "Pop",
        "Kristin Hersh": "Alternative Rock",
        "Krypteria": "Symphonic Metal",
        "Kula Shaker": "Psychedelic Rock",
        "Kylie Minogue": "Pop",
        "L'Aura": "Pop",
        "LCD Soundsystem": "Dance-Punk",
        "LP": "Indie Pop",
        "LP (6)": "Unknown",
        "La Fouine": "Hip-Hop",
        "Lacuna Coil": "Gothic Metal",
        "Lanre": "Unknown",
        "Laura Pausini": "Pop",
        "Laura Veirs": "Folk",
        "Lauryn Hill": "R&B",
        "Le Vibrazioni": "Rock",
        "Le man avec les lunettes": "Indie Pop",
        "LeAnn Rimes": "Country",
        "Lee Brice": "Country",
        "Lemon Ice": "Pop",
        "Leona Lewis": "Pop",
        "Lexington Bridge": "Pop",
        "Liars": "Experimental Rock",
        "Lifehouse": "Alternative Rock",
        "Lifetime": "Melodic Hardcore",
        "Ligabue": "Rock",
        "Lil Mama": "Hip-Hop",
        "Lil Rob": "Hip-Hop",
        "Lil' Boosie": "Hip-Hop",
        "Lily Allen": "Pop",
        "Linkin Park": "Nu Metal",
        "Lisa Loeb": "Pop",
        "Lissat & Voltaxx": "House",
        "Little Dragon": "Electronic",
        "Liz Pappademas": "Singer-Songwriter",
        "Lizette &": "Unknown",
        "Lloyd": "R&B",
        "Locos por Juana": "Latin Alternative",
        "Logan Lynn": "Electronic",
        "Los Campesinos!": "Indie Pop",
        "Los Creadorez Del Pasito Duranguense": "Regional Mexican",
        "Los Tigres Del Norte": "Norteño",
        "Lostprophets": "Rock",
        "Louise Attaque": "Folk Rock",
        "Low": "Slowcore",
        "Ludacris": "Hip-Hop",
        "Lupe Fiasco": "Hip-Hop",
        "Luvi De Andrè": "Folk",
        "Lyfe Jennings": "R&B",
        "Lykke Li": "Indie Pop",
        "Lymbyc Systym": "Post-Rock",
        "M.I.A.": "Hip-Hop / Electronic",
        "MC Frontalot": "Nerdcore",
        "MIKA": "Pop",
        "Macy Gray": "R&B",
        "Madcon": "Hip-Hop",
        "Madonna": "Pop",
        "Mala Rodríguez": "Hip-Hop",
        "Manchester Orchestra": "Indie Rock",
        "Mandy Moore": "Pop",
        "Mange Schmidt": "Hip-Hop",
        "Manic Street Preachers": "Alternative Rock",
        "Marianas Trench": "Pop Rock",
        "Marilyn Manson": "Industrial Metal",
        "Mario": "R&B",
        "Marion Raven": "Pop Rock",
        "Mark Gormley": "Outsider",
        "Mark Mallman": "Indie Rock",
        "Mark Ronson": "Pop / Soul",
        "Marlene Kuntz": "Alternative Rock",
        "Maroon 5": "Pop Rock",
        "Marques Houston": "R&B",
        "Marquess (2)": "Pop",
        "Marta Sánchez": "Pop",
        "Martijn ten Velden": "House",
        "Martina McBride": "Country",
        "Marvin The Robot": "Unknown",
        "Mastodon": "Metal",
        "Mat Kearney": "Pop Rock",
        "Matchbox Twenty": "Alternative Rock",
        "Matthew West": "Christian",
        "Max De Angelis": "Pop",
        "Max Pezzali": "Pop",
        "Maxïmo Park": "Indie Rock",
        "Maya Saban": "Pop",
        "Mayday Parade": "Pop Punk",
        "Meg & Dia": "Indie Rock",
        "Megadeth": "Thrash Metal",
        "Meko": "Dance",
        "Melanie C": "Pop",
        "Melissa Etheridge": "Rock",
        "Melody & Mezzo": "Unknown",
        "Melvins": "Sludge Metal",
        "Menomena": "Indie Rock",
        "Metric": "Indie Rock",
        "Michael Bublé": "Jazz / Pop",
        "Michael Mind": "House",
        "Michael W. Smith": "Christian",
        "Mickey Avalon": "Hip-Hop",
        "Micky Green": "Pop",
        "Micol Barsanti": "Pop",
        "Midnight Juggernauts": "Electronic",
        "Miley Cyrus": "Pop",
        "Mindcrime (2)": "Unknown",
        "Mindless Self Indulgence": "Electronic Rock",
        "Miranda Cosgrove": "Pop",
        "Miranda Lambert": "Country",
        "Misha Al Arouj": "Unknown",
        "Mobile": "Alternative Rock",
        "Moby": "Electronic",
        "Modest Mouse": "Indie Rock",
        "Moneybrother": "Rock",
        "Monrose": "Pop",
        "Moonbabies": "Indie Pop",
        "Morgan (2)": "Pop",
        "Mother Mother": "Indie Rock",
        "Mr. Capone-E": "Hip-Hop",
        "Muck Sticky": "Hip-Hop",
        "Mudvayne": "Nu Metal",
        "Murder City Sparrows": "Unknown",
        "Murs & 9th Wonder": "Hip-Hop",
        "Muse": "Alternative Rock",
        "Mushroomhead": "Industrial Metal",
        "MxPx": "Punk Rock",
        "My Chemical Romance": "Emo / Rock",
        "My First Tooth": "Indie Folk",
        "Mya": "R&B",
        "NLT": "Pop",
        "Nadàr Solo": "Indie Rock",
        "Nas": "Hip-Hop",
        "Natali Dizdar": "Pop",
        "Natalie Imbruglia": "Pop",
        "Natasha Bedingfield": "Pop",
        "Nathan Wiley": "Folk",
        "Ne-Yo": "R&B",
        "Negligence": "Thrash Metal",
        "Nelly Furtado": "Pop",
        "Nena": "Neue Deutsche Welle",
        "Nesli": "Hip-Hop",
        "New Crash Position": "Unknown",
        "New Years Day": "Rock",
        "Newton": "Unknown",
        "Newton Faulkner": "Folk",
        "Nickelback": "Post-Grunge",
        "Nico Vega": "Rock",
        "Nicole Atkins": "Indie Pop",
        "Nicole Scherzinger": "Pop",
        "Nightwish": "Symphonic Metal",
        "Nina Kristin": "Pop",
        "Nine Black Alps": "Alternative Rock",
        "Nine Inch Nails": "Industrial Rock",
        "No More Kings": "Indie Rock",
        "Noah And The Whale": "Indie Folk",
        "Noel Gourdin": "R&B",
        "Noisettes": "Indie Rock",
        "Norah Jones": "Jazz / Pop",
        "November Növelet": "Electronic",
        "Nu GeVe Netcheru": "Unknown",
        "Numero6": "Indie Pop",
        "Nx Zero": "Rock",
        "Of Montreal": "Indie Pop",
        "Ohad Hitman": "Pop",
        "Old Crow Medicine Show": "Folk",
        "One Night Only": "Indie Rock",
        "Outlandish": "Hip-Hop",
        "Ozzy Osbourne": "Heavy Metal",
        "PJ Harvey": "Alternative Rock",
        "Panic! at the Disco": "Pop Punk / Emo",
        "Paolo Nutini": "Pop Rock",
        "Papa Roach": "Nu Metal",
        "Paradise Lost": "Gothic Metal",
        "Paramore": "Pop Punk",
        "Pascal Obispo": "Pop",
        "Patrick Nuo": "Pop",
        "Paul McCartney": "Rock",
        "Paulina Rubio": "Latin Pop",
        "Pendulum (3)": "Drum and Bass",
        "Per Gessle": "Pop",
        "Peter Björn and John": "Indie Pop",
        "Petrol (2)": "Unknown",
        "Petros Gaitanos": "Unknown",
        "Petter": "Hip-Hop",
        "Pharoahe Monch": "Hip-Hop",
        "Philip Morax": "Unknown",
        "Phoenix": "Indie Pop",
        "Pierce The Veil": "Post-Hardcore",
        "Pink": "Pop",
        "Pissed Jeans": "Hardcore Punk",
        "Pitty": "Rock",
        "Placebo": "Alternative Rock",
        "Plain White T's": "Pop Punk",
        "Planes Mistaken For Stars": "Post-Hardcore",
        "PlanningToRock": "Electronic",
        "Point Blank": "Unknown",
        "Poison": "Glam Metal",
        "Populous": "Electronic",
        "Porter": "Indie Rock",
        "Powerspace": "Pop Punk",
        "Pquadro": "Pop",
        "Prairie Oyster": "Country",
        "Prince": "Funk / Pop",
        "Private": "Electronic",
        "Project 86": "Nu Metal",
        "Psilodump": "Electronic",
        "Puddle Of Mudd": "Post-Grunge",
        "Queen": "Rock",
        "Queens Of The Stone Age": "Stoner Rock",
        "R. Kelly": "R&B",
        "RAH Band": "Electronic",
        "RBD": "Pop",
        "RJD2": "Hip-Hop",
        "Radiohead": "Alternative",
        "Raf": "Pop",
        "Rakes, The": "Indie Rock",
        "Randy Rogers Band": "Country",
        "Rapsoul": "Hip-Hop",
        "Ray Lavender": "R&B",
        "Reba McEntire": "Country",
        "Red Hot Chili Peppers": "Funk Rock",
        "Regina Spektor": "Indie Pop",
        "Reh Dogg": "Outsider",
        "Reik": "Pop",
        "Resident Hero": "Rock",
        "Rick Ross": "Hip-Hop",
        "Ricki-Lee": "Pop",
        "Rihanna": "Pop / R&B",
        "Rise Against": "Punk Rock",
        "Robbie Williams": "Pop",
        "Robert Francis": "Folk Rock",
        "Robin Thicke": "R&B",
        "Robyn": "Pop",
        "Roger Cicero": "Jazz Pop",
        "Rogue Traders": "Electronic Rock",
        "Rogue Wave": "Indie Rock",
        "Roma": "Indie Pop",
        "Romina Falconi": "Pop",
        "Room 2012": "Pop",
        "Rooney": "Indie Rock",
        "RuPaul": "Dance",
        "Rufus Wainwright": "Baroque Pop",
        "Róisín Murphy": "Electronic",
        "SHO": "Unknown",
        "SIA": "Pop", # Sia
        "SSION": "Electronic",
        "Saliva": "Nu Metal",
        "Santana": "Rock",
        "Sara Bareilles": "Pop Rock",
        "Sara Evans": "Country",
        "Sarah Connor": "Pop",
        "Scissor Sisters": "Pop / Disco",
        "Scooter": "Techno",
        "Scorpions": "Rock",
        "Scouting For Girls": "Indie Pop",
        "Sea Wolf": "Indie Folk",
        "Seal": "Soul",
        "Sean Kingston": "Reggae Fusion",
        "Sean Paul": "Dancehall",
        "Sean Ward": "Unknown",
        "Seether": "Post-Grunge",
        "Semi Precious Weapons": "Glam Rock",
        "Serj Tankian": "Alternative Metal",
        "Seventeen Evergreen": "Experimental",
        "Shadows Fall": "Metalcore",
        "Shakira": "Latin Pop",
        "Shanadoo": "Eurodance",
        "Shayne Ward": "Pop",
        "She Wants Revenge": "Post-Punk Revival",
        "Sheek Louch": "Hip-Hop",
        "Sheryl Crow": "Rock",
        "Shiny Toy Guns": "Electronic Rock",
        "Shroud": "Metal",
        "Sick Puppies": "Rock",
        "Silbermond": "Pop Rock",
        "Silent Civilian": "Metalcore",
        "Silicon Fly": "Unknown",
        "Silverchair": "Alternative Rock",
        "Simian Mobile Disco": "Electronic",
        "Simple Plan": "Pop Punk",
        "Simply Red": "Soul",
        "Sinéad O'Connor": "Alternative Rock",
        "Siouxsie Sioux": "Post-Punk",
        "Sirens (5)": "Unknown",
        "Sisqó": "R&B",
        "Skinnen Bones MC": "Unknown",
        "Slim Thug": "Hip-Hop",
        "Slipknot": "Nu Metal",
        "Smoke'n'Soul": "Unknown",
        "Smugg Juggler": "Unknown",
        "Snoop Dogg": "Hip-Hop",
        "Soilwork": "Melodic Death Metal",
        "Sonic Boom Six": "Ska Punk",
        "Sonic Syndicate": "Melodic Death Metal",
        "Sophia Segal": "Unknown",
        "Sophie Ellis-Bextor": "Pop / Disco",
        "Soular": "Unknown",
        "Soulja Boy": "Hip-Hop",
        "Spice Girls": "Pop",
        "Spoon": "Indie Rock",
        "Stafrænn Hákon": "Post-Rock",
        "Static-X": "Industrial Metal",
        "Stephanie Mcintosh": "Pop",
        "Stephen Fretwell": "Singer-Songwriter",
        "Sterling Simms": "R&B",
        "Stone Sour": "Hard Rock",
        "Stray Dog Cafe": "Unknown",
        "Strayday": "Unknown",
        "Streetlight Manifesto": "Ska Punk",
        "Styles P": "Hip-Hop",
        "Subsonica": "Electronic Rock",
        "Sugababes": "Pop",
        "Sugarland": "Country",
        "Sum 41": "Pop Punk",
        "Sunblock (2)": "Dance",
        "Sunny Sweeney": "Country",
        "Superbus (2)": "Pop Rock",
        "Suspekt (2)": "Unknown",
        "Switchfoot": "Alternative Rock",
        "Swizz Beatz": "Hip-Hop",
        "Syria": "Pop",
        "System 7": "Electronic",
        "T-Pain": "R&B / Hip-Hop",
        "T.I.": "Hip-Hop",
        "Tacks, the Boy Disaster": "Indie Pop",
        "Take That": "Pop",
        "Tay Zonday": "Internet",
        "Taylor Swift": "Country / Pop",
        "Ted Leo and The Pharmacists": "Indie Rock",
        "Teddybears": "Electronic Rock",
        "Teenagers, The (2)": "Indie Pop",
        "Tegan and Sara": "Indie Pop",
        "The Academy Is...": "Pop Punk",
        "The Almost": "Alternative Rock",
        "The BossHoss": "Country Rock",
        "The Boswells": "Unknown",
        "The Bravery": "Post-Punk Revival",
        "The Brilliant Things": "Pop",
        "The Brunettes": "Indie Pop",
        "The Bumblebeez": "Electronic",
        "The Chemical Brothers": "Big Beat",
        "The Click Five": "Power Pop",
        "The Creepshow": "Psychobilly",
        "The Daylights": "Indie Rock",
        "The Dear & Departed": "Rock",
        "The Devil Wears Prada": "Metalcore",
        "The Dresden Dolls": "Dark Cabaret",
        "The Drones": "Rock",
        "The Fratellis": "Indie Rock",
        "The Game": "Hip-Hop",
        "The Gathering": "Alternative Rock",
        "The Good, the Bad & the Queen": "Alternative",
        "The Hives": "Garage Rock",
        "The Hoosiers": "Indie Pop",
        "The Horrors": "Garage Rock",
        "The Indelicates": "Indie Pop",
        "The Irrepressibles": "Chamber Pop",
        "The Jackal Headed Front": "Unknown",
        "The Killers": "Indie Rock",
        "The Kills": "Indie Rock",
        "The Knife": "Electronic",
        "The Last Goodnight": "Pop Rock",
        "The Lonely Island": "Comedy",
        "The Mountain Goats": "Indie Folk",
        "The New Pornographers": "Indie Rock",
        "The Old Ceremony": "Indie Pop",
        "The Owls": "Indie Pop",
        "The Perishers": "Indie Pop",
        "The Rabble": "Unknown",
        "The Replicants": "Unknown",
        "The Rushes": "Unknown",
        "The Smashing Pumpkins": "Alternative Rock",
        "The Steamy Bohemians": "Unknown",
        "The Stirring": "Unknown",
        "The Strokes": "Indie Rock",
        "The Subways": "Indie Rock",
        "The Sunshine": "Indie Pop",
        "The Thrills": "Indie Rock",
        "The Twang": "Indie Rock",
        "The Used": "Post-Hardcore",
        "The Veronicas": "Pop Rock",
        "The View": "Indie Rock",
        "The Walkmen": "Indie Rock",
        "The Weepies": "Folk Pop",
        "The White Stripes": "Garage Rock",
        "The Willowz": "Garage Rock",
        "The Wombats": "Indie Rock",
        "The-Dream": "R&B",
        "They Live By Night": "Unknown",
        "This Providence": "Pop Punk",
        "Three Days Grace": "Rock",
        "Three-6 Mafia": "Hip-Hop",
        "Throwdown (2)": "Hardcore",
        "Thunder Express": "Rock",
        "Tia Lily": "Unknown",
        "Tim Rogers": "Rock",
        "Timbaland": "Hip-Hop / R&B",
        "Timbiriche": "Latin Pop",
        "Tiziano Ferro": "Pop",
        "Toby Keith": "Country",
        "Toby Love": "Bachata",
        "Tocotronic": "Indie Rock",
        "Tokio Hotel": "Pop Rock",
        "Tool": "Progressive Metal",
        "Tori Amos": "Alternative",
        "Travis": "Indie Rock",
        "Tre Allegri Ragazzi Morti": "Indie Rock",
        "Trisha Yearwood": "Country",
        "Trucker": "Rock",
        "Tupelo Honey": "Rock",
        "Twenty 4 Seven": "Eurodance",
        "Twista": "Hip-Hop",
        "Type O Negative": "Gothic Metal",
        "U$O": "Hip-Hop",
        "UGK": "Hip-Hop",
        "UNKLE": "Electronic",
        "US 5": "Pop",
        "Ultra Naté": "House",
        "Ultrabeat (2)": "Dance",
        "UnkleJam": "Pop",
        "Usher": "R&B",
        "Valgeir Sigurdsson": "Electronic",
        "Vampire Weekend": "Indie Rock",
        "Van She": "Electronic",
        "Van Zant": "Southern Rock",
        "Vanessa Carlton": "Pop",
        "Vanilla Sky (2)": "Pop Punk",
        "Vasilis Papageorgiou": "Unknown",
        "Velvet (2)": "Pop",
        "Velvet Revolver": "Hard Rock",
        "Verdena": "Grunge",
        "Volbeat": "Metal",
        "We The Kings": "Pop Punk",
        "Weird Al Yankovic": "Comedy",
        "Whitest Boy Alive": "Indie Pop",
        "Wisin & Yandel": "Reggaeton",
        "Within Temptation": "Symphonic Metal",
        "Wyclef Jean": "Hip-Hop",
        "Xiu Xiu": "Experimental",
        "YELLE": "Pop",
        "Yeah Yeah Yeahs": "Indie Rock",
        "Yelawolf": "Hip-Hop",
        "Yellowcard": "Pop Punk",
        "Young & Restless": "Unknown",
        "Young Buck": "Hip-Hop",
        "Young Divas": "Pop",
        "Young Knives, The": "Indie Rock",
        "Yumm Yumm": "Unknown",
        "Yung Joc": "Hip-Hop",
        "Zarman": "Unknown",
        "Zucchero": "Blues Rock",
        "múm": "Electronic",
        "t.A.T.u.": "Pop",
        "will.i.am": "Hip-Hop"
    }

    for entry in data:
        artist_name = entry.get('artist_name')
        if artist_name in genre_map:
            entry['artist_genre'] = genre_map[artist_name]
        elif entry.get('artist_genre') == 'Desconhecido':
             # pass
             pass

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    enrich_genres('data/2007.json')
