import json

def enrich_genres(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    genre_map = {
        "2Pac": "Hip-Hop",
        "3 Doors Down": "Rock",
        "30 Seconds To Mars": "Rock",
        "A New Found Glory": "Pop Punk",
        "Aaliyah": "R&B",
        "Ago": "Dance",
        "Akeboshi": "J-Pop",
        "Alanis Morissette": "Alternative Rock",
        "Alcazar": "Pop / Dance",
        "Alexisonfire": "Post-Hardcore",
        "Alizee": "Pop",
        "All-American Rejects": "Pop Punk",
        "American Head Charge": "Nu Metal",
        "Amerie": "R&B",
        "Amon Tobin": "Electronic",
        "Anastacia": "Pop",
        "Andrew W.K.": "Rock",
        "Angels & Airwaves": "Rock",
        "Angie Stone": "R&B",
        "Anna Nalex": "Pop Rock",
        "Apoptygma Berzerk": "Synthpop",
        "Appleton": "Pop",
        "Aqualung": "Indie Pop",
        "Arctic Monkeys": "Indie Rock",
        "Armin van Buuren": "Trance",
        "Ashanti": "R&B",
        "Ash": "Indie Rock",
        "Atomic Kitten": "Pop",
        "Audioslave": "Rock",
        "Audiovent": "Rock",
        "Avril Lavigne": "Pop Punk",
        "B2K": "R&B",
        "BBMak": "Pop",
        "Babariba": "Pop",
        "Badly Drawn Boy": "Indie Pop",
        "Bajofondo": "Tango / Electronic",
        "Barenaked Ladies": "Alternative Rock",
        "Basement Jaxx": "House",
        "Beenie Man": "Reggae",
        "Ben Kweller": "Indie Rock",
        "Ben Lee": "Indie Pop",
        "Beulah": "Indie Pop",
        "Beyoncé": "R&B / Pop",
        "Big Tymers": "Hip-Hop",
        "Björk": "Electronic",
        "Black Label Society": "Heavy Metal",
        "Black Stone Cherry": "Rock",
        "Blindside": "Post-Hardcore",
        "Blink-182": "Pop Punk",
        "Blue": "Pop",
        "Boards of Canada": "Electronic",
        "Bon Jovi": "Rock",
        "Bone Thugs-N-Harmony": "Hip-Hop",
        "Boomkat": "Pop / Electronic",
        "Bow Wow": "Hip-Hop",
        "Box Car Racer": "Pop Punk",
        "Brand New": "Emo / Rock",
        "Brandy": "R&B",
        "Breaking Benjamin": "Rock",
        "Bright Eyes": "Indie Folk",
        "Broken Social Scene": "Indie Rock",
        "Bruce Springsteen": "Rock",
        "Bryan Adams": "Rock",
        "Bube": "Pop",
        "Bugo": "Indie Rock",
        "Busta Rhymes": "Hip-Hop",
        "Buster Poindexter": "Pop",
        "Cam'ron": "Hip-Hop",
        "Cardigans": "Pop Rock",
        "Carlos Santana": "Rock",
        "Cassius": "House",
        "Chad Kroeger": "Rock",
        "Chantal Kreviazuk": "Pop Rock",
        "Charlotte Church": "Classical Crossover",
        "Chayanne": "Latin Pop",
        "Chely Wright": "Country",
        "Chevelle": "Rock",
        "Chick Corea": "Jazz",
        "Christina Aguilera": "Pop",
        "Clipse": "Hip-Hop",
        "Coldplay": "Alternative Rock",
        "Common": "Hip-Hop",
        "Counting Crows": "Alternative Rock",
        "Craig David": "R&B",
        "Creed": "Post-Grunge",
        "DJ Sammy": "Eurodance",
        "DMX": "Hip-Hop",
        "Daddy Yankee": "Reggaeton",
        "Daniel Bedingfield": "Pop",
        "Danko Jones": "Rock",
        "Danzig": "Heavy Metal",
        "Darren Hayes": "Pop",
        "Dashboard Confessional": "Emo",
        "Dave Matthews Band": "Rock",
        "David Bowie": "Rock",
        "David Gray": "Folk Rock",
        "David Guetta": "House",
        "Death Cab For Cutie": "Indie Rock",
        "Def Leppard": "Rock",
        "Delta Goodrem": "Pop",
        "Demon Hunter": "Metalcore",
        "Despina Vandi": "Pop",
        "Dirty Vegas": "House",
        "Disturbed": "Nu Metal",
        "Do": "Pop",
        "Donots": "Punk Rock",
        "Dr. Dre": "Hip-Hop",
        "Dream Theater": "Progressive Metal",
        "E-40": "Hip-Hop",
        "Elisa": "Pop Rock",
        "Elvis Presley": "Rock",
        "Eminem": "Hip-Hop",
        "Enrique Iglesias": "Latin Pop",
        "Enya": "New Age",
        "Erykah Badu": "Neo Soul",
        "Eve": "Hip-Hop",
        "Fabolous": "Hip-Hop",
        "Fat Joe": "Hip-Hop",
        "Fatboy Slim": "Big Beat",
        "Feeder": "Rock",
        "Finch": "Post-Hardcore",
        "Fischerspooner": "Electroclash",
        "Flaming Lips": "Neo-Psychedelia",
        "Floetry": "Neo Soul",
        "Foo Fighters": "Rock",
        "Fountains Of Wayne": "Power Pop",
        "Garbage": "Alternative Rock",
        "Gareth Gates": "Pop",
        "George Michael": "Pop",
        "Giorgia (2)": "Pop",
        "Girls Aloud": "Pop",
        "Glassjaw": "Post-Hardcore",
        "Goapele": "Neo Soul",
        "Godsmack": "Nu Metal",
        "Goo Goo Dolls": "Alternative Rock",
        "Good Charlotte": "Pop Punk",
        "Gorillaz": "Alternative",
        "Gotthard": "Hard Rock",
        "Green Day": "Punk Rock",
        "Groove Armada": "Electronic",
        "H.E.R.": "R&B",
        "H2O": "Punk",
        "Hard-Fi": "Indie Rock",
        "Hell Is For Heroes": "Post-Hardcore",
        "Holly Valance": "Pop",
        "Hot Hot Heat": "Indie Rock",
        "Hoobastank": "Rock",
        "Idlewild": "Indie Rock",
        "Ill Niño": "Nu Metal",
        "Imogen Heap": "Electronic",
        "Incubus": "Alternative Rock",
        "India.Arie": "Neo Soul",
        "Indochine": "New Wave",
        "Interpol": "Post-Punk Revival",
        "Inujima": "Unknown",
        "Iron Maiden": "Heavy Metal",
        "Ismael Lo": "World",
        "Ja Rule": "Hip-Hop",
        "Jack Johnson": "Folk Rock",
        "Jaheim": "R&B",
        "James Taylor": "Folk Rock",
        "Jay-Z": "Hip-Hop",
        "Jennifer Lopez": "Pop / R&B",
        "Jennifer Love Hewitt": "Pop",
        "Jerry Cantrell": "Grunge",
        "Jewel": "Folk / Pop",
        "Jimmy Eat World": "Emo / Rock",
        "JoeyStarr": "Hip-Hop",
        "John Mayer": "Pop Rock",
        "Johnny Cash": "Country",
        "Juanes": "Latin Pop",
        "Judas Priest": "Heavy Metal",
        "Junior Senior": "Pop",
        "Jurassic 5": "Hip-Hop",
        "Justin Timberlake": "Pop",
        "K-Ci & JoJo": "R&B",
        "KRYŠTOF": "Pop Rock",
        "Kelly Rowland": "R&B",
        "Kenna": "Alternative",
        "Kenny Chesney": "Country",
        "Kent": "Indie Rock",
        "Kid Rock": "Rock / Hip-Hop",
        "Killing Joke": "Post-Punk",
        "Kinky": "Electronic",
        "Korn": "Nu Metal",
        "Kylie Minogue": "Pop",
        "LCD Soundsystem": "Dance-Punk",
        "LL Cool J": "Hip-Hop",
        "Las Ketchup": "Pop",
        "Lasgo": "Trance",
        "Laura Pausini": "Pop",
        "LeAnn Rimes": "Country",
        "Lemon Jelly": "Downtempo",
        "Lenny Kravitz": "Rock",
        "Liberty X": "Pop",
        "Lifehouse": "Alternative Rock",
        "Lil' Kim": "Hip-Hop",
        "Lil' Romeo": "Hip-Hop",
        "Linkin Park": "Nu Metal",
        "Lisa Marie Presley": "Pop Rock",
        "Live": "Alternative Rock",
        "Lou Reed": "Rock",
        "Low": "Indie Rock",
        "Ludacris": "Hip-Hop",
        "M2M": "Pop",
        "Mad'house": "House",
        "Madonna": "Pop",
        "Maná": "Latin Rock",
        "Mariah Carey": "R&B / Pop",
        "Mario": "R&B",
        "Maroon 5": "Pop Rock",
        "Mary J. Blige": "R&B",
        "Matchbox Twenty": "Alive Rock",
        "Matt Nathanson": "Folk Rock",
        "McFly": "Pop Punk",
        "Meshuggah": "Metal",
        "Metro Station": "Pop",
        "Michael Jackson": "Pop",
        "Michelle Branch": "Pop Rock",
        "Missy Elliott": "Hip-Hop",
        "Moby": "Electronic",
        "Modest Mouse": "Indie Rock",
        "Moloko": "Electronic",
        "Monica": "R&B",
        "Morcheeba": "Trip Hop",
        "Ms. Dynamite": "R&B / Hip-Hop",
        "Mudvayne": "Nu Metal",
        "Murderdolls": "Horror Punk",
        "Muse": "Alternative Rock",
        "Musiq": "R&B",
        "My Chemical Romance": "Emo / Rock",
        "Myslovitz": "Indie Rock",
        "N.E.R.D.": "Hip-Hop / Rock",
        "Nelly": "Hip-Hop",
        "Nelly Furtado": "Pop",
        "Nena": "Pop",
        "New Found Glory": "Pop Punk",
        "Nickelback": "Post-Grunge",
        "Nightwish": "Symphonic Metal",
        "Nine Days": "Rock",
        "Nirvana": "Grunge",
        "No Doubt": "Ska / Pop",
        "Nonpoint": "Nu Metal",
        "Norah Jones": "Jazz / Pop",
        "Nuttea": "Reggae",
        "O-Town": "Pop",
        "OK Go": "Indie Rock",
        "Oasis": "Britpop",
        "OneRepublic": "Pop Rock",
        "Opeth": "Progressive Metal",
        "Otep": "Nu Metal",
        "Our Lady Peace": "Alternative Rock",
        "OutKast": "Hip-Hop",
        "Outlandish": "Hip-Hop",
        "P.O.D.": "Nu Metal",
        "Papa Roach": "Nu Metal",
        "Paul Oakenfold": "Trance",
        "Pearl Jam": "Grunge",
        "Peter Gabriel": "Rock",
        "Petey Pablo": "Hip-Hop",
        "Phish": "Jam Band",
        "Pink": "Pop",
        "Placebo": "Alternative Rock",
        "Plain White T's": "Pop Punk",
        "Porcupine Tree": "Progressive Rock",
        "Primal Scream": "Alternative Rock",
        "Puddle Of Mudd": "Post-Grunge",
        "Pulp": "Britpop",
        "Quarashi": "Rap Rock",
        "Queen": "Rock",
        "Queens Of The Stone Age": "Stoner Rock",
        "R. Kelly": "R&B",
        "Radiohead": "Alternative Rock",
        "Raiko": "Dance",
        "Rammstein": "Industrial Metal",
        "Rascal Flatts": "Country",
        "Rascalz": "Hip-Hop",
        "Red Hot Chili Peppers": "Funk Rock",
        "Rednex": "Eurodance",
        "Relient K": "Pop Punk",
        "Remy Zero": "Alternative Rock",
        "Robbie Williams": "Pop",
        "Robert Plant": "Rock",
        "Röyksopp": "Electronic",
        "Rush": "Progressive Rock",
        "Ryan Adams": "Alt-Country",
        "S Club 7": "Pop",
        "Saliva": "Nu Metal",
        "Santana": "Rock",
        "Sara Bareilles": "Pop",
        "Sara Evans": "Country",
        "Sarah McLachlan": "Pop",
        "Sash!": "Trance",
        "Satyricon": "Black Metal",
        "Scarface": "Hip-Hop",
        "Scooter": "Techno",
        "Seether": "Post-Grunge",
        "Sevendust": "Nu Metal",
        "Shakira": "Latin Pop",
        "Shandon": "Ska Punk",
        "Shania Twain": "Country",
        "Sheryl Crow": "Rock",
        "Sigur Rós": "Post-Rock",
        "Simple Plan": "Pop Punk",
        "Sixpence None The Richer": "Pop",
        "Skepta": "Grime",
        "Skin": "Rock",
        "Slayer": "Thrash Metal",
        "Sleater-Kinney": "Indie Rock",
        "Snoop Dogg": "Hip-Hop",
        "Sophie Ellis-Bextor": "Pop / Disco",
        "Soulfly": "Metal",
        "Soundgarden": "Grunge",
        "Sparta": "Post-Hardcore",
        "Spoon": "Indie Rock",
        "Staind": "Post-Grunge",
        "Starfield": "Christian Rock",
        "Starsailor": "Indie Rock",
        "Stereophonics": "Rock",
        "Stone Sour": "Hard Rock",
        "Subzonic": "Rock",
        "Sugababes": "Pop",
        "Sum 41": "Pop Punk",
        "Supergrass": "Britpop",
        "System of a Down": "Nu Metal",
        "T.I.": "Hip-Hop",
        "TLC": "R&B",
        "Taking Back Sunday": "Emo",
        "Taproot": "Nu Metal",
        "Tatu": "Pop",
        "Tenacious D": "Comedy Rock",
        "The 5.6.7.8's": "Rock",
        "The All-American Rejects": "Pop Punk",
        "The Ataris": "Pop Punk",
        "The Avalanches": "Electronic",
        "The Black Eyed Peas": "Hip-Hop / Pop",
        "The Calling": "Rock",
        "The Chemical Brothers": "Big Beat",
        "The Corrs": "Pop Rock",
        "The Cranberries": "Alternative Rock",
        "The Distillers": "Punk Rock",
        "The Flaming Lips": "Neo-Psychedelia",
        "The Jon Spencer Blues Explosion": "Blues Rock",
        "The Killer Barbies": "Punk",
        "The Music": "Rock",
        "The O.C. Supertones": "Ska",
        "The Pattern": "Garage Rock",
        "The Polyphonic Spree": "Choral Rock",
        "The Prodigy": "Big Beat",
        "The Raveonettes": "Indie Rock",
        "The Roc Project": "House",
        "The Rolling Stones": "Rock",
        "The Roots": "Hip-Hop",
        "The Shins": "Indie Rock",
        "The Sounds": "New Wave",
        "The Starting Line": "Pop Punk",
        "The Streets": "UK Garage",
        "The Strokes": "Indie Rock",
        "The Supermen Lovers": "House",
        "The The": "Post-Punk",
        "The Tragically Hip": "Rock",
        "The Used": "Post-Hardcore",
        "The Vampire Lestat": "Rock",
        "The Wallflowers": "Rock",
        "The White Stripes": "Garage Rock",
        "The X-Ecutioners": "Hip-Hop",
        "The Zutons": "Indie Rock",
        "Theatre Of Tragedy": "Gothic Metal",
        "Tift Merritt": "Country",
        "Timo Maas": "Electronic",
        "Tina Arena": "Pop",
        "Toby Keith": "Country",
        "Toni Braxton": "R&B",
        "Toni L.": "Hip-Hop",
        "Tony Touch": "Hip-Hop",
        "Tool": "Progressive Metal",
        "Toploader": "Alternative Rock",
        "Tori Amos": "Alternative Rock",
        "Travis Tritt": "Country",
        "Tre Allegri Ragazzi Morti": "Indie Rock",
        "Treble Charger": "Pop Punk",
        "Turin Brakes": "Indie Folk",
        "Tweet": "R&B",
        "Tyrese": "R&B",
        "U2": "Rock",
        "UPA Dance": "Pop",
        "Uncle Kracker": "Rock / Country",
        "Underoath": "Metalcore",
        "Utada Hikaru": "J-Pop",
        "Vanessa Carlton": "Pop",
        "Velvet (2)": "Pop",
        "Verdena": "Grunge",
        "Victoria Beckham": "Pop",
        "Vitas": "Pop",
        "Voltaj": "Pop Rock",
        "Voodoo Glow Skulls": "Ska Punk",
        "Waikiki": "Rock",
        "Weezer": "Alternative Rock",
        "Wheatus": "Pop Rock",
        "Wild Strawberries": "Pop",
        "Will Smith": "Hip-Hop",
        "Will Young": "Pop",
        "Willie Nelson": "Country",
        "Within Temptation": "Symphonic Metal",
        "Wyclef Jean": "Hip-Hop",
        "Xavier Naidoo": "Soul",
        "Xiu Xiu": "Experimental",
        "Xzibit": "Hip-Hop",
        "Yamboo": "Eurodance",
        "Ying Yang Twins": "Hip-Hop",
        "YoungBloodZ": "Hip-Hop",
        "Zero 7": "Downtempo",
        "[spunge]": "Ska Punk",
        "a-ha": "Pop",
        "k-os": "Hip-Hop",
        "múm": "Electronica",
        "t.A.T.u.": "Pop"
    }

    for entry in data:
        artist_name = entry.get('artist_name')
        if artist_name in genre_map:
            entry['artist_genre'] = genre_map[artist_name]
        elif entry.get('artist_genre') == 'Desconhecido':
             # Keep Desconhecido if not in map, or maybe set a default?
             # For now, leaving as Desconhecido if not found in map is safer than guessing wrong.
             pass

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    enrich_genres('data/2002.json')
