import json

def enrich_genres(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    genre_map = {
        "+44": "Pop Punk",
        "30 Seconds To Mars": "Rock",
        "36 Crazyfists": "Metalcore",
        "AFI": "Punk Rock",
        "Abingdon Boys School": "J-Rock",
        "Above & Beyond": "Trance",
        "Access": "Electronic",
        "Across Five Aprils": "Post-Hardcore",
        "Aiden": "Post-Hardcore",
        "Air": "Electronic",
        "Akon": "R&B",
        "Albert Hammond Jr.": "Indie Rock",
        "Alexisonfire": "Post-Hardcore",
        "Ali Ali": "Unknown",
        "Ali Project": "Dark Wave",
        "Alice In Chains": "Grunge",
        "Alien Ant Farm": "Nu Metal",
        "All That Remains": "Metalcore",
        "All-American Rejects": "Pop Punk",
        "Aly & AJ": "Pop Rock",
        "Amel Bent": "R&B",
        "Amy Winehouse": "Soul",
        "Ana Johnsson": "Pop Rock",
        "Anaïs": "Chanson",
        "Andain": "Trance",
        "Andrea Bocelli": "Classical Crossover",
        "Angels & Airwaves": "Rock",
        "Angra": "Power Metal",
        "Anti-Flag": "Punk Rock",
        "Arctic Monkeys": "Indie Rock",
        "Army Of Anyone": "Rock",
        "Atreyu": "Metalcore",
        "Audioslave": "Rock",
        "August Burns Red": "Metalcore",
        "Avant": "R&B",
        "Avenged Sevenfold": "Heavy Metal",
        "B5": "R&B",
        "Babyshambles": "Indie Rock",
        "Backyard Babies": "Rock",
        "Band Of Horses": "Indie Rock",
        "Barenaked Ladies": "Alternative Rock",
        "Basement Jaxx": "House",
        "Basshunter": "Eurodance",
        "Beastie Boys": "Hip-Hop",
        "Beatsteaks": "Punk Rock",
        "Beck": "Alternative",
        "Bela B.": "Rock",
        "Belle & Sebastian": "Indie Pop",
        "Belphegor": "Black Metal",
        "Ben Harper": "Folk Rock",
        "Ben Kweller": "Indie Rock",
        "Ben الوحده": "Unknown",
        "Berryz Kobo": "J-Pop",
        "Beyoncé": "R&B / Pop",
        "Billy Talent": "Punk Rock",
        "Björk": "Electronic",
        "Black Label Society": "Heavy Metal",
        "Black Rebel Motorcycle Club": "Garage Rock",
        "Black Stone Cherry": "Rock",
        "Blind Guardian": "Power Metal",
        "Blindside": "Post-Hardcore",
        "Blue October": "Alternative Rock",
        "Blues Traveler": "Rock",
        "Bob Sinclar": "House",
        "Bon Jovi": "Rock",
        "Bonnie 'Prince' Billy": "Folk",
        "Bowling For Soup": "Pop Punk",
        "Boys Like Girls": "Pop Punk",
        "Brand New": "Emo",
        "Breaking Benjamin": "Post-Grunge",
        "Bright Eyes": "Indie Folk",
        "Bring Me The Horizon": "Metalcore",
        "Broken Social Scene": "Indie Rock",
        "Brooks & Dunn": "Country",
        "Bubba Sparxxx": "Hip-Hop",
        "Buckcherry": "Hard Rock",
        "Bullet For My Valentine": "Metalcore",
        "Bun B": "Hip-Hop",
        "Burt Bacharach": "Pop",
        "Busta Rhymes": "Hip-Hop",
        "Calexico": "Indie Rock",
        "Camera Obscura": "Indie Pop",
        "Camille": "Chanson",
        "Cannibal Corpse": "Death Metal",
        "Captain": "Alternative Rock",
        "Cartel": "Pop Punk",
        "Cascada": "Eurodance",
        "Cassie": "R&B",
        "Cat Power": "Indie Rock",
        "Celtic Frost": "Extreme Metal",
        "Chamillionaire": "Hip-Hop",
        "Chantal Kreviazuk": "Pop Rock",
        "Charlotte Gainsbourg": "Pop",
        "Cheap Trick": "Rock",
        "Chemical Brothers, The": "Big Beat",
        "Cherish": "R&B",
        "Chicago": "Rock",
        "Chingy": "Hip-Hop",
        "Chris Brown": "R&B",
        "Chris Cornell": "Rock",
        "Chris Daughtry": "Rock",
        "Christina Aguilera": "Pop",
        "Ciara": "R&B",
        "Cirkus": "Trip Hop",
        "Clipse": "Hip-Hop",
        "Cold War Kids": "Indie Rock",
        "Coldplay": "Alternative Rock",
        "Corinne Bailey Rae": "Soul",
        "Counting Crows": "Alternative Rock",
        "Cradle Of Filth": "Extreme Metal",
        "Cunninlynguists": "Hip-Hop",
        "Cute Is What We Aim For": "Pop Punk",
        "Daddy Yankee": "Reggaeton",
        "Damian Marley": "Reggae",
        "Damien Rice": "Folk",
        "Danity Kane": "Pop / R&B",
        "Dashboard Confessional": "Emo",
        "Daughter": "Indie Folk", # Might be too early?
        "Dave Matthews Band": "Rock",
        "David Gilmour": "Rock",
        "David Guetta": "House",
        "David Hasselhoff": "Pop",
        "De La Soul": "Hip-Hop",
        "Dead 50s": "Ska", # Typo?
        "Dead 60s": "Ska / Punk",
        "Death Cab For Cutie": "Indie Rock",
        "Deathstars": "Industrial Metal",
        "Deep Dish": "House",
        "Deerhoof": "Indie Rock",
        "Deftones": "Alternative Metal",
        "Deichkind": "Hip-Hop / Electronic",
        "Delays": "Indie Rock",
        "Dem Franchize Boyz": "Hip-Hop",
        "Demon Hunter": "Metalcore",
        "Depeche Mode": "Synthpop",
        "D4L": "Hip-Hop",
        "Dhany": "Dance",
        "Diamond Rio": "Country",
        "Diane": "Pop",
        "Diecast": "Metalcore",
        "Dino-Mike": "Comedy",
        "Disturbed": "Nu Metal",
        "Dixie Chicks": "Country",
        "DolceNera": "Pop",
        "Don Omar": "Reggaeton",
        "Doris": "Pop",
        "Dorit Chrysler": "Electronic",
        "Drake Bell": "Pop Rock",
        "Dream Evil": "Power Metal",
        "Dujeous": "Hip-Hop",
        "Dukie Dread": "Reggae",
        "E-40": "Hip-Hop",
        "Early Dolphin": "Unknown",
        "East Clubbers": "House",
        "Electric Six": "Garage Rock",
        "Elefant": "Indie Pop",
        "Elisa": "Pop Rock",
        "Elton John": "Pop Rock",
        "Emerson Drive": "Country",
        "Emilie Simon": "Electronic",
        "Emily Haines & The Soft Skeleton": "Indie Pop",
        "Eminem": "Hip-Hop",
        "Emma Bunton": "Pop",
        "End Of Fashion": "Rock",
        "Enter Shikari": "Post-Hardcore",
        "Eric Church": "Country",
        "Erick E": "House",
        "Europe": "Rock",
        "Evanescence": "Rock / Goth",
        "Every Time I Die": "Metalcore",
        "Example": "Electronic",
        "Exilia": "Nu Metal",
        "Eyes Set To Kill": "Post-Hardcore",
        "Eyes of Fire": "Sludge Metal",
        "FLOW": "J-Rock",
        "Faith Hill": "Country",
        "Faithless": "Electronic",
        "Fake Oddity": "Rock",
        "Faktion": "Rock",
        "Fall Out Boy": "Pop Punk",
        "Fantasia": "R&B",
        "Fatboy Slim": "Big Beat",
        "Fedde Le Grand": "House",
        "Feeder": "Rock",
        "Fergie": "Pop",
        "Fiamma Fumana": "Folk / Electronic",
        "Fibes, Oh Fibes!": "Pop",
        "Field Mob": "Hip-Hop",
        "Finley": "Pop Punk",
        "Fiona Apple": "Alternative",
        "Fireflight": "Christian Rock",
        "Firefox AK": "Electronic",
        "Firewind": "Power Metal",
        "Fishbone": "Ska Punk",
        "Five For Fighting": "Pop Rock",
        "Five O'Clock Heroes": "Indie Rock",
        "Flipsyde": "Hip-Hop / Rock",
        "Florent Pagny": "Chanson",
        "Flyleaf": "Alternative Metal",
        "Fonzerelli": "House",
        "Foo Fighters": "Rock",
        "Fort Minor": "Hip-Hop",
        "Fountains Of Wayne": "Power Pop",
        "Frankie J": "R&B",
        "Franky Lee": "Rock",
        "Franz Ferdinand": "Indie Rock",
        "Freemasons": "House",
        "Fu Manchu": "Stoner Rock",
        "G. Love": "Alternative Hip-Hop",
        "Garou": "Pop",
        "Gary Nichols": "Country",
        "Gene Loves Jezebel": "Gothic Rock",
        "George Michael": "Pop",
        "George Strait": "Country",
        "Ghostface Killah": "Hip-Hop",
        "Ghostigital": "Electronic",
        "Ghoultown": "Gothabilly",
        "Gianna Nannini": "Rock",
        "Gianni Morandi": "Pop",
        "Ginuwine": "R&B",
        "Girls Aloud": "Pop",
        "Gloria Trevi": "Pop",
        "Gnarls Barkley": "Soul / Pop",
        "God Forbid": "Metalcore",
        "Godhead": "Industrial Rock",
        "Godsmack": "Nu Metal",
        "Gojira": "Death Metal",
        "Goldfrapp": "Electronic",
        "Goleo VI": "Pop",
        "Gomez": "Indie Rock",
        "Goo Goo Dolls": "Alternative Rock",
        "Good Charlotte": "Pop Punk",
        "Good Shoes": "Indie Rock",
        "Gorillaz": "Alternative",
        "Gotan Project": "Tango / Electronic",
        "Gotye": "Indie Pop",
        "Grandi Animali Marini": "Pop",
        "Gregory Darling": "Pop",
        "Gretchen Wilson": "Country",
        "Groove Coverage": "Eurodance",
        "Guillemots": "Indie Pop",
        "Gustavo Cerati": "Rock",
        "Guy Sebastian": "Pop",
        "Gwen Stefani": "Pop",
        "Gym Class Heroes": "Hip-Hop / Rock",
        "Gyroscope (2)": "Rock",
        "HIM": "Gothic Rock",
        "Hailer": "Unknown",
        "Hard-Fi": "Indie Rock",
        "Hatebreed": "Metalcore",
        "Hawthorne Heights": "Emo",
        "Head Automatica": "Pop Punk",
        "Heather Small": "Soul",
        "Heaven Shall Burn": "Metalcore",
        "Hedley": "Pop Punk",
        "Hello Saferide": "Indie Pop",
        "Hellogoodbye": "Pop Punk",
        "Helloween": "Power Metal",
        "Helmet (2)": "Alternative Metal",
        "Herbert Grönemeyer": "Pop Rock",
        "Hilary Duff": "Pop",
        "Hinder": "Post-Grunge",
        "Hoobastank": "Rock",
        "Hot Chip": "Electronic",
        "Hundred Reasons": "Alternative Rock",
        "Hyung Young": "Pop",
        "I Am Ghost": "Post-Hardcore",
        "Ice Cube": "Hip-Hop",
        "Idiot Pilot": "Electronic / Rock",
        "If Hope Dies Last": "Post-Hardcore",
        "Ihsahn": "Black Metal",
        "Il Divo": "Classical Crossover",
        "Ima Robot": "Indie Rock",
        "Immanuel Casto": "Pop",
        "Imogen Heap": "Electronic",
        "In Flames": "Melodic Death Metal",
        "Incubus": "Alternative Rock",
        "Indochine": "New Wave",
        "Into Eternity": "Melodic Death Metal",
        "Iron Maiden": "Heavy Metal",
        "Islands": "Indie Rock",
        "J Dilla": "Hip-Hop",
        "Jack Johnson": "Folk Rock",
        "Jack's Mannequin": "Piano Rock",
        "Jagged Edge": "R&B",
        "Jahzz": "Unknown",
        "Jakalope": "Pop / Rock",
        "Jake Owen": "Country",
        "Jamelia": "R&B",
        "James Blunt": "Pop Rock",
        "James Morrison": "Pop Soul",
        "Jamie Cullum": "Jazz Pop",
        "Jamie Foxx": "R&B",
        "Jamiroquai": "Funk / Acid Jazz",
        "Janet Jackson": "R&B / Pop",
        "Jars Of Clay": "Christian Rock",
        "Jarvis Cocker": "Indie Pop",
        "Jay Z": "Hip-Hop",
        "Jeanette": "Pop",
        "Jeezy": "Hip-Hop",
        "Jennifer Lopez": "Pop / R&B",
        "Jenny Lewis": "Indie Folk",
        "Jern Eye": "Hip-Hop",
        "Jesse McCartney": "Pop",
        "Jessica Simpson": "Pop",
        "Jet": "Rock",
        "Jewel": "Folk / Pop",
        "JoJo": "R&B / Pop",
        "Joan Jett & The Blackhearts": "Rock",
        "Jody Watley": "R&B",
        "Joe": "R&B",
        "Joe Nichols": "Country",
        "JoeyStarr": "Hip-Hop",
        "John Legend": "R&B",
        "John Mayer": "Pop Rock",
        "John Mellencamp": "Rock",
        "Johnny Cash": "Country",
        "Jon McLaughlin": "Pop Rock",
        "Jonas Brothers": "Pop Rock",
        "Jordan Galland": "Indie Pop",
        "Jordan Pruitt": "Pop",
        "Josh Groban": "Pop",
        "Josh Turner": "Country",
        "Joshua Radin": "Folk",
        "Jota Mayúscula": "Hip-Hop",
        "Juanes": "Latin Pop",
        "Juli": "Pop Rock",
        "Julie's Haircut": "Indie Rock",
        "Juliet Simms": "Rock",
        "Jully Black": "R&B",
        "Justin Timberlake": "Pop",
        "KRYŠTOF": "Pop Rock",
        "KT Tunstall": "Pop Rock",
        "Kabát": "Rock",
        "Kaci Brown": "Pop",
        "Kai Niemann": "Pop",
        "Kaiser Chiefs": "Indie Rock",
        "Kanye West": "Hip-Hop",
        "Karmah": "Pop",
        "Kasabian": "Indie Rock",
        "Kashmir (2)": "Indie Rock",
        "Kate Hall": "Pop",
        "Kavinsky": "Electronic",
        "Keane": "Piano Rock",
        "Keisha White": "R&B",
        "Keith Urban": "Country",
        "Kelis": "R&B",
        "Kellie Pickler": "Country",
        "Kelly Clarkson": "Pop Rock",
        "Kennedy": "Rock",
        "Kenny Chesney": "Country",
        "Keshia Chanté": "R&B",
        "Kill Hannah": "Alternative Rock",
        "Killerpilze": "Pop Punk",
        "Killswitch Engage": "Metalcore",
        "Kim Wilde": "Pop",
        "Kiri Te Kanawa": "Opera",
        "Klaxons": "Indie Rock",
        "Kleerup": "Electronic",
        "Korn": "Nu Metal",
        "Kr!s": "Unknown",
        "Kreator": "Thrash Metal",
        "Krisiun": "Death Metal",
        "Kubichek!": "Indie Rock",
        "Kultama": "Hip-Hop",
        "Kyosuke Himuro": "Rock",
        "L'Aura": "Pop",
        "L'Âme Immortelle": "Electronic / Gothic",
        "LL Cool J": "Hip-Hop",
        "La Crus": "Pop Rock",
        "La Fouine": "Hip-Hop",
        "Lacuna Coil": "Gothic Metal",
        "Lamb Of God": "Groove Metal",
        "Laura Pausini": "Pop",
        "Le Mani": "Pop Rock",
        "LeAnn Rimes": "Country",
        "LeToya Luckett": "R&B",
        "Lee Ann Womack": "Country",
        "Lee Ryan": "Pop",
        "Leela James": "Soul",
        "Lemar": "R&B",
        "Lemon Ice": "Pop",
        "Lena & Laurin": "Pop",
        "Leona Lewis": "Pop",
        "Less Than Jake": "Ska Punk",
        "Ligabue": "Rock",
        "Lil Kim": "Hip-Hop",
        "Lil Wayne": "Hip-Hop",
        "Lil' Boosie": "Hip-Hop",
        "Lil' Jon": "Hip-Hop",
        "Lil' Rob": "Hip-Hop",
        "Lily Allen": "Pop",
        "Lindsay Pagano": "Pop",
        "Linea 77": "Nu Metal",
        "Lionel Richie": "R&B",
        "Liv Kristine": "Gothic Metal",
        "Live": "Alternative Rock",
        "Liza Li": "Pop",
        "Lloyd Banks": "Hip-Hop",
        "Logan Lynn": "Electronic",
        "Lolly Pop": "Pop",
        "Lordi": "Hard Rock",
        "Lori Meyers": "Indie Rock",
        "Los Rakas": "Hip-Hop",
        "Los Tigres Del Norte": "Norteño",
        "Los Tucanes De Tijuana": "Norteño",
        "Lostprophets": "Rock",
        "Lou Bega": "Mambo",
        "Luca Carboni": "Pop",
        "Lucie Silvas": "Pop",
        "Lucky Jim": "Folk",
        "Lud (2)": "Unknown",
        "Ludacris": "Hip-Hop",
        "Luis Fonsi": "Latin Pop",
        "Lulu Mushi": "Unknown",
        "Lupe Fiasco": "Hip-Hop",
        "Luvi De Andrè": "Folk",
        "Lyfe Jennings": "R&B",
        "M.Craft": "Indie Folk",
        "M.I.A.": "Hip-Hop / Electronic",
        "MICC": "Unknown",
        "MIKA": "Pop",
        "Maarja": "Pop",
        "Madeleine Peyroux": "Jazz",
        "Madlib": "Hip-Hop",
        "Madonna": "Pop",
        "Madvillain": "Hip-Hop",
        "Mafy": "Unknown",
        "Manchester": "Indie Rock",
        "Manic Street Preachers": "Alternative Rock",
        "Manntis": "Metalcore",
        "Marc Terenzi": "Pop",
        "Marco Antonio Solís": "Latin Pop",
        "Marco Parente": "Indie Rock",
        "Margaret Cho": "Comedy",
        "Maria Mena": "Pop",
        "Mariah Carey": "R&B / Pop",
        "Marianas Trench": "Pop Rock",
        "Mario Vazquez": "R&B",
        "Mario Venuti": "Pop",
        "Mark 'Oh": "Techno",
        "Marlon (5)": "Unknown",
        "Marquess (2)": "Pop",
        "Mary J. Blige": "R&B",
        "Massive Attack": "Trip Hop",
        "Mastodon": "Metal",
        "Mat Kearney": "Pop Rock",
        "Mates Of State": "Indie Pop",
        "Matisyahu": "Reggae",
        "Mau Mau (2)": "Unknown",
        "Max De Angelis": "Pop",
        "Maxfield (2)": "Unknown",
        "Maximilian Hecker": "Indie Pop",
        "Maxïmo Park": "Indie Rock",
        "Mayra Veronica": "Pop",
        "Meat Loaf": "Rock",
        "Meet Me In St Louis": "Post-Hardcore",
        "Melanie C": "Pop",
        "Melanie Durrant": "R&B",
        "Melissa Etheridge": "Rock",
        "Memphis Bleek": "Hip-Hop",
        "Meshuggah": "Metal",
        "Metric": "Indie Rock",
        "Mew": "Indie Rock",
        "Mic Little": "Hip-Hop",
        "Michael Bublé": "Jazz / Pop",
        "Michael W. Smith": "Christian",
        "Michel Polnareff": "Pop",
        "Michelle Branch": "Pop Rock",
        "Midnight Juggernauts": "Electronic",
        "Mila J": "R&B",
        "Milk & Honey (2)": "Pop",
        "Mindless Self Indulgence": "Electronic Rock",
        "Minisztár": "Unknown",
        "Missy Elliott": "Hip-Hop",
        "Mobb Deep": "Hip-Hop",
        "Mobile": "Alternative Rock",
        "Modà": "Pop Rock",
        "Mogwai": "Post-Rock",
        "Mondo Marcio": "Hip-Hop",
        "Monica": "R&B",
        "Monster Zoku Onsomb!": "Unknown",
        "Moonspell": "Gothic Metal",
        "Morrissey": "Indie Pop",
        "Morten Abel": "Pop",
        "Motel Connection": "Electronic",
        "Motion City Soundtrack": "Pop Punk",
        "Motörhead": "Heavy Metal",
        "Mr Skillz And His Crazy Girls": "Unknown",
        "Muha Blackstazy": "Unknown",
        "Murder City Sparrows": "Unknown",
        "Muse": "Alternative Rock",
        "Mushroomhead": "Industrial Metal",
        "My Chemical Romance": "Emo / Rock",
        "Myndsight": "Unknown",
        "Myslovitz": "Indie Rock",
        "N'fa": "Hip-Hop",
        "N-Euro": "Eurodance",
        "N.A.M.B": "Unknown",
        "Nadja Benaissa": "Pop",
        "Nadàr Solo": "Indie Rock",
        "Naglfar": "Black Metal",
        "Namosh": "Electronic",
        "Napalm Death": "Grindcore",
        "Nas": "Hip-Hop",
        "Natasha": "Pop",
        "Natasha St-Pier": "Pop",
        "Ne-Yo": "R&B",
        "Negative (4)": "Glam Rock",
        "Negramaro": "Pop Rock",
        "Nelly Furtado": "Pop",
        "Nerina Pallot": "Pop Rock",
        "Nesti": "Hip-Hop",
        "Nevermore": "Metal",
        "New Order": "Post-Punk / Electronic",
        "New Radiant Storm King": "Indie Rock",
        "New Young Pony Club": "Indie Rock",
        "Niccolò Fabi": "Pop",
        "Nick Cannon": "R&B",
        "Nickelback": "Post-Grunge",
        "Nik & Jay": "Pop",
        "Nocturnal Rites": "Power Metal",
        "Noisettes": "Indie Rock",
        "Norah Jones": "Jazz / Pop",
        "Nouvelle Vague (2)": "Bossa Nova",
        "Nu GeVe Netcheru": "Unknown",
        "Numero6": "Indie Pop",
        "Nx Zero": "Rock",
        "OK Go": "Indie Rock",
        "OOMPH!": "Industrial Metal",
        "Oasis": "Britpop",
        "Obie Trice": "Hip-Hop",
        "Old Crow Medicine Show": "Folk",
        "Omarion": "R&B",
        "OneRepublic": "Pop Rock",
        "OutKast": "Hip-Hop",
        "Outlandish": "Hip-Hop",
        "Outwork": "House",
        "P. Diddy": "Hip-Hop",
        "P.O.D.": "Nu Metal",
        "P.O.S.": "Hip-Hop",
        "Pacifico": "Indie Pop",
        "Pam Hogg": "Post-Punk",
        "Panic! at the Disco": "Pop Punk / Emo",
        "Paolo Nutini": "Pop Rock",
        "Papa Roach": "Nu Metal",
        "Paramore": "Pop Punk",
        "Paris Hilton": "Pop",
        "Parlour Boys": "Unknown",
        "Patrick Bruel": "Chanson",
        "Patrick Wolf": "Indie Pop",
        "Paul Weller": "Rock",
        "Paulina Rubio": "Latin Pop",
        "Pearl Jam": "Grunge",
        "Peeping Tom": "Alternative",
        "People In Planes": "Indie Rock",
        "Perturbazione": "Indie Rock",
        "Pet Shop Boys": "Synthpop",
        "Pete Yorn": "Alternative Rock",
        "Peter Björn and John": "Indie Pop",
        "Pharrell Williams": "Hip-Hop",
        "Phoenix": "Indie Pop",
        "Piero Pelù": "Rock",
        "Pillar": "Christian Rock",
        "Pink": "Pop",
        "Pitbull": "Hip-Hop",
        "Pitty": "Rock",
        "Placebo": "Alternative Rock",
        "Plain White T's": "Pop Punk",
        "PlanningToRock": "Electronic",
        "Platinum Weird": "Pop Rock",
        "Pohlmann": "Pop",
        "Poison": "Glam Metal",
        "Poisonblack": "Gothic Metal",
        "Powerman 5000": "Industrial Metal",
        "Primal Scream": "Alternative Rock",
        "Prince": "Funk / Pop",
        "Projector": "Rock",
        "Psicotropia": "Rock",
        "Psilodump": "Electronic",
        "Punchline": "Pop Punk",
        "Punish The Atom": "Electronic",
        "Pure H": "Unknown",
        "Queens Of The Stone Age": "Stoner Rock",
        "Queensrÿche": "Progressive Metal",
        "Quietdrive": "Pop Punk",
        "R'n'G": "Hip-Hop",
        "R.E.M.": "Alternative Rock",
        "RBD": "Pop",
        "RadU": "Unknown",
        "Raf": "Pop",
        "Raheem DeVaughn": "R&B",
        "Rammstein": "Industrial Metal",
        "Randy Rogers Band": "Country",
        "Rapsoul": "Hip-Hop",
        "Raptile": "Hip-Hop",
        "Rascal Flatts": "Country",
        "Razorlight": "Indie Rock",
        "Reba McEntire": "Country",
        "Red Hot Chili Peppers": "Funk Rock",
        "Regina Spektor": "Indie Pop",
        "Reh Dogg": "Outsider",
        "Reik": "Pop",
        "Relient K": "Pop Punk",
        "Rezophonic": "Rock",
        "Richard Ashcroft": "Britpop",
        "Rick Ross": "Hip-Hop",
        "Ricki-Lee": "Pop",
        "Ricky Martin": "Latin Pop",
        "Rihanna": "Pop / R&B",
        "Rinôçérôse": "Electronic Rock",
        "Rise Against": "Punk Rock",
        "Rob Zombie": "Industrial Metal",
        "Robbie Williams": "Pop",
        "Robert Randolph": "Funk",
        "Robyn": "Pop",
        "Rod Stewart": "Rock",
        "Roger Cicero": "Jazz Pop",
        "Rogue Traders": "Electronic Rock",
        "Ronan Keating": "Pop",
        "Rooney": "Indie Rock",
        "Rooster": "Rock",
        "Rose": "Pop",
        "Roxette": "Pop Rock",
        "RuPaul": "Dance",
        "Ruben Studdard": "R&B",
        "Röyksopp": "Electronic",
        "SHINHWA": "K-Pop",
        "SSION": "Electronic",
        "Sabaton": "Power Metal",
        "Sam Roberts": "Rock",
        "Samantha Jade": "Pop",
        "Sambomaster": "Rock",
        "Sammie (2)": "R&B",
        "Saosin": "Post-Hardcore",
        "Sarah Connor": "Pop",
        "Satyricon": "Black Metal",
        "Saving Jane": "Pop Rock",
        "Say Anything": "Pop Punk",
        "Scissor Sisters": "Pop / Disco",
        "Scuola Furano": "Electronic",
        "Sean Lennon": "Indie Rock",
        "Sean Paul": "Dancehall",
        "Second Monday": "Unknown",
        "Secondsmile": "Post-Hardcore",
        "Seether": "Post-Grunge",
        "Senta-Sofia": "Pop",
        "Sergio Cammariere": "Jazz Pop",
        "Seth Lakeman": "Folk",
        "Shadows Fall": "Metalcore",
        "Shakira": "Latin Pop",
        "Shanadoo": "Eurodance",
        "Shawnna": "Hip-Hop",
        "Shayne Ward": "Pop",
        "She Wants Revenge": "Post-Punk Revival",
        "Sheryl Crow": "Rock",
        "Shiny Toy Guns": "Electronic Rock",
        "Shurman": "Country Rock",
        "Sick Puppies": "Rock",
        "Sigur Rós": "Post-Rock",
        "Silbermond": "Pop Rock",
        "Silversun Pickups": "Alternative Rock",
        "Simian Mobile Disco": "Electronic",
        "Simple Plan": "Pop Punk",
        "Simply Red": "Soul",
        "Singuila": "R&B",
        "Siobhan Donaghy": "Pop",
        "Skin": "Rock",
        "Slayer": "Thrash Metal",
        "Sneaky Sound System": "Dance",
        "Snoop Dogg": "Hip-Hop",
        "Snow Patrol": "Indie Rock",
        "Snowkel": "J-Rock",
        "Sohodolls": "Electronic",
        "Sonic Youth": "Alternative Rock",
        "Sophie Ellis-Bextor": "Pop / Disco",
        "Sparks": "Pop",
        "Stabilo (2)": "Rock",
        "Stacie Orrico": "Pop",
        "Staind": "Post-Grunge",
        "Stars": "Indie Pop",
        "Starsailor": "Indie Rock",
        "SteelA": "Reggae",
        "Stefy": "Pop",
        "Steve Holy": "Country",
        "Stolen Babies": "Avant-Garde Metal",
        "Stone Sour": "Hard Rock",
        "Strapping Young Lad": "Industrial Metal",
        "Stylus": "Funk",
        "Subsonica": "Electronic Rock",
        "Sugababes": "Pop",
        "Sugarland": "Country",
        "Sunblock (2)": "Dance",
        "Super Elastic Bubble Plastic": "Unknown",
        "Superbus (2)": "Pop Rock",
        "Supernafamacho": "Hip-Hop",
        "Susumu Hirasawa": "Electronic",
        "Switchfoot": "Alternative Rock",
        "System Of A Down": "Nu Metal",
        "Sébastien Tellier": "Electronic",
        "T.I.": "Hip-Hop",
        "Taio Cruz": "R&B",
        "Take That": "Pop",
        "Taking Back Sunday": "Emo",
        "Talib Kweli": "Hip-Hop",
        "Taylor Swift": "Country / Pop",
        "Tenacious D": "Comedy Rock",
        "Texas": "Pop Rock",
        "Thalía": "Latin Pop",
        "The All-American Rejects": "Pop Punk",
        "The Alpine": "Indie Rock",
        "The Argonauts": "Unknown",
        "The Beatles": "Rock",
        "The Beautiful South": "Pop Rock",
        "The Black Keys": "Blues Rock",
        "The Bravery": "Post-Punk Revival",
        "The Butterfly Effect": "Progressive Rock",
        "The Charlatans": "Indie Rock",
        "The Cumshots": "Metal",
        "The Darkness": "Glam Rock",
        "The Dresden Dolls": "Dark Cabaret",
        "The Fire": "Rock",
        "The Flaming Lips": "Neo-Psychedelia",
        "The Fratellis": "Indie Rock",
        "The Futureheads": "Post-Punk Revival",
        "The Game": "Hip-Hop",
        "The Gathering": "Alternative Rock",
        "The Haunted": "Thrash Metal",
        "The Heights": "Unknown",
        "The Horrors": "Garage Rock",
        "The Human Abstract": "Progressive Metal",
        "The Hush Sound": "Indie Pop",
        "The Killers": "Indie Rock",
        "The Knife": "Electronic",
        "The Kooks": "Indie Rock",
        "The Like": "Indie Rock",
        "The Lonely Island": "Comedy",
        "The Males": "Unknown",
        "The New Cars": "Rock",
        "The New Pornographers": "Indie Rock",
        "The Notorious B.I.G.": "Hip-Hop",
        "The Nudie Suits": "Indie Rock",
        "The Pack": "Hip-Hop",
        "The Panic Channel": "Rock",
        "The Perishers": "Indie Pop",
        "The Pink Spiders": "Pop Punk",
        "The Provocateurs": "Unknown",
        "The Pussycat Dolls": "Pop / R&B",
        "The Rabble": "Unknown",
        "The Raconteurs": "Rock",
        "The Reduction Agents": "Indie Rock",
        "The Retrosic": "Industrial",
        "The Rifles": "Indie Rock",
        "The Sounds": "New Wave",
        "The Stills": "Indie Rock",
        "The Streets": "UK Garage",
        "The Strokes": "Indie Rock",
        "The Subways": "Indie Rock",
        "The Summer Obsession": "Pop Punk",
        "The Sunshine Underground": "Indie Rock",
        "The Teddybears": "Electronic Rock",
        "The Underdog Project": "House",
        "The Used": "Post-Hardcore",
        "The Veronicas": "Pop Rock",
        "The View": "Indie Rock",
        "The Vines": "Garage Rock",
        "The Weepies": "Folk Pop",
        "The Wreckers": "Country",
        "The Zutons": "Indie Rock",
        "Theatre Of Tragedy": "Gothic Metal",
        "Thirteen Senses": "Indie Rock",
        "Three Days Grace": "Rock",
        "Three-6 Mafia": "Hip-Hop",
        "Thrice": "Post-Hardcore",
        "Thunder": "Hard Rock",
        "Tiga": "Electronic",
        "Tilly And The Wall": "Indie Pop",
        "Tina Arena": "Pop",
        "Tiziano Ferro": "Pop",
        "Toby Keith": "Country",
        "Tokio Hotel": "Pop Rock",
        "Tom Helsen": "Indie Rock",
        "Tomoyasu Hotei": "Rock",
        "Toni Collette": "Pop",
        "Trailing Laces": "Unknown",
        "Trey Songz": "R&B",
        "Trick Daddy": "Hip-Hop",
        "Trivium": "Metalcore",
        "Tunng": "Folktronica",
        "Tyrese": "R&B",
        "U2": "Rock",
        "US 5": "Pop",
        "Underoath": "Metalcore",
        "Uochi Toki": "Hip-Hop",
        "User (5)": "Unknown",
        "VHS Or Beta": "Dance-Punk",
        "Van Canto": "A Cappella Metal",
        "Vandalism": "Electronic",
        "Vanlustbader": "Unknown",
        "Vega 4": "Alternative Rock",
        "Vibekingz": "Pop",
        "Vitas": "Pop",
        "Vittorio Grigolo": "Opera",
        "Voom": "Indie Pop",
        "WHY?": "Indie Rock",
        "Wax Tailor": "Trip Hop",
        "Weird Al Yankovic": "Comedy",
        "White Rose Movement": "Post-Punk Revival",
        "Will Young": "Pop",
        "Willie Nelson": "Country",
        "Wisin & Yandel": "Reggaeton",
        "Wolfmother": "Hard Rock",
        "Xiu Xiu": "Experimental",
        "Xzibit": "Hip-Hop",
        "Yann Tiersen": "Soundtrack",
        "Yeah Yeah Yeahs": "Indie Rock",
        "Young Buck": "Hip-Hop",
        "Young Divas": "Pop",
        "Young Knives, The": "Indie Rock",
        "Yusuf Islam": "Folk",
        "Zombie Ghost Train": "Psychobilly",
        "Zwan": "Alternative Rock",
        "a-ha": "Pop",
        "k-os": "Hip-Hop",
        "t.A.T.u.": "Pop"
    }

    for entry in data:
        artist_name = entry.get('artist_name')
        if artist_name in genre_map:
            entry['artist_genre'] = genre_map[artist_name]
        elif entry.get('artist_genre') == 'Desconhecido':
             # pass
             pass

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    enrich_genres('data/2006.json')
