import json

def enrich_genres(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    genre_map = {
        "30 Seconds To Mars": "Rock",
        "3OH!3": "Electronic Pop",
        "50 Cent": "Hip-Hop",
        "A Day To Remember": "Metalcore / Pop Punk",
        "A Fine Frenzy": "Indie Pop",
        "A Place To Bury Strangers": "Shoegaze",
        "A-Trak": "Electronic",
        "A.R. Rahman": "Soundtrack / World",
        "AC/DC": "Rock",
        "Ace Hood": "Hip-Hop",
        "Adam Lambert": "Pop Rock",
        "Adele": "Soul",
        "Afrojack": "Electronic",
        "After School (2)": "K-Pop",
        "Against Me!": "Punk Rock",
        "Agnes": "Pop",
        "Air": "Electronic",
        "Airborne Toxic Event, The": "Indie Rock",
        "Akala": "Hip-Hop",
        "Akon": "R&B",
        "Alain Bashung": "Chanson",
        "Alanis Morissette": "Alternative Rock",
        "Alcazar": "Eurodance",
        "Alejandro Sanz": "Latin Pop",
        "Alela Diane": "Folk",
        "Alesha Dixon": "R&B",
        "Alexisonfire": "Post-Hardcore",
        "Ali Ali": "Unknown",
        "Ali Project": "Dark Wave",
        "Alicia Keys": "R&B / Soul",
        "Alien Ant Farm": "Nu Metal",
        "Alizée": "Pop",
        "All Time Low": "Pop Punk",
        "All-American Rejects, The": "Pop Punk",
        "Allen Toussaint": "R&B / Jazz",
        "Aloe Blacc": "Soul",
        "Alphabeat": "Pop",
        "Aly & AJ": "Pop Rock",
        "Amanda Blank": "Hip-Hop / Electronic",
        "Amaral": "Pop Rock",
        "Amarasri": "Unknown",
        "American Princes": "Indie Rock",
        "Amerie": "R&B",
        "Amon Amarth": "Melodic Death Metal",
        "Amy MacDonald": "Folk Rock",
        "Amy Winehouse": "Soul / R&B",
        "Ana Johnsson": "Pop Rock",
        "Anberlin": "Alternative Rock",
        "And One": "Synthpop",
        "Andrew Bird": "Indie Folk",
        "Angels & Airwaves": "Rock",
        "Ani DiFranco": "Folk",
        "Animal Collective": "Experimental Pop",
        "Anita O'Day": "Jazz",
        "Anna Tsuchiya": "J-Rock",
        "Annie Lennox": "Pop",
        "Antony and the Johnsons": "Chamber Pop",
        "Anvil": "Heavy Metal",
        "Apocalyptica": "Symphonic Metal",
        "Apples In Stereo": "Indie Pop",
        "Arcade Fire": "Indie Rock",
        "Arch Enemy": "Melodic Death Metal",
        "Architects": "Metalcore",
        "Architecture In Helsinki": "Indie Pop",
        "Arctic Monkeys": "Indie Rock",
        "Armin van Buuren": "Trance",
        "Army Of Anyone": "Rock",
        "Arsonists Get All The Girls": "Deathcore",
        "As I Lay Dying": "Metalcore",
        "Asher Roth": "Hip-Hop",
        "Ashanti": "R&B",
        "Ashlee Simpson": "Pop Rock",
        "Ashley Tisdale": "Pop",
        "Asian Kung-Fu Generation": "J-Rock",
        "Asobi Seksu": "Shoegaze",
        "Atmosphere": "Hip-Hop",
        "Atreyu": "Metalcore",
        "Audio Bullys": "Electronic",
        "Augustana": "Pop Rock",
        "Autechre": "Electronic",
        "Avenged Sevenfold": "Heavy Metal",
        "Avett Brothers, The": "Folk Rock",
        "Avril Lavigne": "Pop Punk",
        "Ayumi Hamasaki": "J-Pop",
        "B.o.B": "Hip-Hop",
        "Babyshambles": "Indie Rock",
        "Backstreet Boys": "Pop",
        "Bad Religion": "Punk Rock",
        "Band Of Horses": "Indie Rock",
        "Barenaked Ladies": "Alternative Rock",
        "Basement Jaxx": "House",
        "Basshunter": "Eurodance",
        "Bassnectar": "Electronic",
        "Bat For Lashes": "Indie Pop",
        "Battles": "Math Rock",
        "Beastie Boys": "Hip-Hop",
        "Beatsteaks": "Punk Rock",
        "Beautiful Creatures": "Hard Rock",
        "Beck": "Alternative",
        "Behemoth": "Death Metal",
        "Beirut": "Indie Folk",
        "Belanova": "Latin Pop",
        "Belly": "Hip-Hop",
        "Ben Folds": "Alternative Rock",
        "Ben Harper": "Folk Rock",
        "Ben Lee": "Indie Pop",
        "Ben's Brother": "Pop Rock",
        "Benga": "Dubstep",
        "Benjamin Biolay": "Chanson",
        "Benny Benassi": "House",
        "Berryz Kobo": "J-Pop",
        "Between The Buried And Me": "Progressive Metal",
        "Beyoncé": "R&B / Pop",
        "Bibio": "Electronic",
        "Biffy Clyro": "Rock",
        "Big & Rich": "Country",
        "Big Boi": "Hip-Hop",
        "Birdman": "Hip-Hop",
        "Björk": "Electronic",
        "Black Eyed Peas": "Pop / Hip-Hop",
        "Black Kids": "Indie Pop",
        "Black Lips": "Garage Rock",
        "Black Rebel Motorcycle Club": "Garage Rock",
        "Black Stone Cherry": "Rock",
        "Black Veil Brides": "Glam Metal",
        "Blakanova": "Unknown",
        "Bleeding Through": "Metalcore",
        "Bloc Party": "Indie Rock",
        "Blonde Redhead": "Indie Rock",
        "Blood Red Shoes": "Indie Rock",
        "Blue Man Group": "Experimental",
        "Blue October": "Alternative Rock",
        "Blutengel": "Dark Wave",
        "Bob Dylan": "Rock / Folk",
        "Bob Sinclar": "House",
        "Bobby Valentino": "R&B",
        "Bombay Bicycle Club": "Indie Rock",
        "Bon Iver": "Indie Folk",
        "Bon Jovi": "Rock",
        "Bone Thugs-N-Harmony": "Hip-Hop",
        "Booka Shade": "Electronic",
        "Boomkat": "Pop",
        "Bowling For Soup": "Pop Punk",
        "Bow Wow": "Hip-Hop",
        "Boys Like Girls": "Pop Punk",
        "Boyz II Men": "R&B",
        "Brad Paisley": "Country",
        "Brand New": "Emo",
        "Breaking Benjamin": "Post-Grunge",
        "Bree Sharp": "Pop Rock",
        "Brian McKnight": "R&B",
        "Bright Eyes": "Indie Folk",
        "Bring Me The Horizon": "Metalcore",
        "Britney Spears": "Pop",
        "Broken Social Scene": "Indie Rock",
        "Brooke White": "Pop",
        "Brother Ali": "Hip-Hop",
        "Bruce Springsteen": "Rock",
        "Buckcherry": "Hard Rock",
        "Bun B": "Hip-Hop",
        "Buraka Som Sistema": "Electronic",
        "Busta Rhymes": "Hip-Hop",
        "Busy Signal": "Dancehall",
        "C-Note": "Unknown",
        "Caleb Kane": "Pop",
        "Café Tacvba": "Alternative Rock",
        "Cage The Elephant": "Indie Rock",
        "Cajan": "Unknown",
        "Cake": "Alternative Rock",
        "Calvin Harris": "Electronic",
        "Camera Obscura": "Indie Pop",
        "Camila": "Latin Pop",
        "Camron": "Hip-Hop",
        "Candie Payne": "Pop",
        "Cannibal Corpse": "Death Metal",
        "Caribou": "Electronic",
        "Carrie Underwood": "Country",
        "Cartel": "Pop Punk",
        "Cascada": "Eurodance",
        "Casiotone For The Painfully Alone": "Indie Pop",
        "Cassie": "R&B",
        "Cat Power": "Indie Rock",
        "Cee-Lo Green": "Soul / Hip-Hop",
        "Celine Dion": "Pop",
        "Chairlift": "Indie Pop",
        "Chaka Khan": "R&B / Funk",
        "Chamillionaire": "Hip-Hop",
        "Chapeaumelon": "Pop",
        "Chase & Status": "Drum and Bass",
        "Cheap Trick": "Rock",
        "Chevelle": "Alternative Metal",
        "Chicane": "Trance",
        "Chickenfoot": "Hard Rock",
        "Chimaira": "Groove Metal",
        "Chris Brown": "R&B",
        "Chris Cornell": "Rock",
        "Chris Young": "Country",
        "Chrisette Michele": "R&B",
        "Christian Walz": "Pop Soul",
        "Christina Aguilera": "Pop",
        "Chromeo": "Funk / Electronic",
        "Ciara": "R&B",
        "Cinematic Orchestra, The": "Nu Jazz",
        "City And Colour": "Acoustic",
        "City Sleeps": "Rock",
        "Clutch": "Stoner Rock",
        "Claude VonStroke": "House",
        "Clawfinger": "Rap Metal",
        "Client": "Electronic",
        "Clipse": "Hip-Hop",
        "Cobrastyle": "Electronic",
        "CocoRosie": "Freak Folk",
        "Cody Simpson": "Pop",
        "Coheed And Cambria": "Progressive Rock",
        "Colbie Caillat": "Pop",
        "Cold War Kids": "Indie Rock",
        "Coldplay": "Alternative Rock",
        "Colegio Cardenal Spellman Quito": "Unknown",
        "Common": "Hip-Hop",
        "Consequence": "Hip-Hop",
        "Control Machete": "Hip-Hop",
        "Corinne Bailey Rae": "Soul",
        "Cornelius": "Experimental",
        "Courtney Jaye": "Folk",
        "Craig Morgan": "Country",
        "Cradle of Filth": "Extreme Metal",
        "Crash Romeo": "Pop Punk",
        "Credence Clearwater Revival": "Rock",
        "Creed": "Post-Grunge",
        "Crooked X": "Hard Rock",
        "Crossfade": "Post-Grunge",
        "Crystal Castles": "Electronic",
        "Culcha Candela": "Dancehall / Hip-Hop",
        "Cupid": "R&B",
        "Cursive": "Indie Rock",
        "Cute Is What We Aim For": "Pop Punk",
        "Cyndi Lauper": "Pop",
        "D-Tent Boys": "Unknown",
        "DJ Khaled": "Hip-Hop",
        "DJ Shadow": "Trip Hop",
        "DJ Tiesto": "Trance",
        "Daft Punk": "House",
        "Damien Rice": "Folk",
        "Dan Black": "Electronic",
        "Dan Deacon": "Electronic",
        "Daniel Merriweather": "R&B",
        "Danity Kane": "Pop / R&B",
        "Darius Rucker": "Country",
        "Dark Tranquillity": "Melodic Death Metal",
        "Dashboard Confessional": "Emo",
        "Datarock": "Dance-Punk",
        "Daughtry": "Rock",
        "Dave Gahan": "Synthpop",
        "Dave Matthews": "Rock",
        "Dave Matthews Band": "Rock",
        "David Archuleta": "Pop",
        "David Banner": "Hip-Hop",
        "David Gray": "Folk Rock",
        "David Guetta": "House",
        "David Vendetta": "House",
        "Davide Van De Sfroos": "Folk",
        "De La Soul": "Hip-Hop",
        "Dead By Sunrise": "Rock",
        "Deadmau5": "House",
        "Death Cab For Cutie": "Indie Rock",
        "Debbie Harry": "Pop / New Wave",
        "Deerhunter": "Indie Rock",
        "Deftones": "Alternative Metal",
        "Delain": "Symphonic Metal",
        "Delta Goodrem": "Pop",
        "Demi Lovato": "Pop",
        "Demon Hunter": "Metalcore",
        "Dengue Fever": "Psychedelic Rock",
        "Depeche Mode": "Synthpop",
        "Despina Vandi": "Pop",
        "Devendra Banhart": "Folk",
        "DevilDriver": "Groove Metal",
        "Diana Krall": "Jazz",
        "Dido": "Pop",
        "Die Toten Hosen": "Punk Rock",
        "Dierks Bentley": "Country",
        "Digitalism": "Electronic",
        "Dilated Peoples": "Hip-Hop",
        "Dimmu Borgir": "Black Metal",
        "Dinosaur Jr.": "Alternative Rock",
        "Dirty Projectors": "Indie Rock",
        "Disco Drive": "Dance-Punk",
        "Dizzee Rascal": "Grime",
        "Dolly Parton": "Country",
        "Don Omar": "Reggaeton",
        "Donkeyboy": "Pop",
        "Dorrough": "Hip-Hop",
        "Doves": "Indie Rock",
        "Down Low": "Hip-Hop",
        "Dr. Dre": "Hip-Hop",
        "Dragonette": "Electropop",
        "Drake": "Hip-Hop",
        "Dream Theater": "Progressive Metal",
        "Dropkick Murphys": "Celtic Punk",
        "Dropline": "Rock",
        "Duffy": "Soul",
        "Duran Duran": "New Wave",
        "Dusty Rhodes And The River Band": "Indie Rock",
        "Dwight Yoakam": "Country",
        "Dying Fetus": "Death Metal",
        "E-40": "Hip-Hop",
        "EL-P": "Hip-Hop",
        "EUGY": "Unknown",
        "Eagles Of Death Metal": "Rock",
        "Eastern Conference Champions": "Indie Rock",
        "Editors": "Indie Rock",
        "Eels": "Alternative Rock",
        "Eilay Butner": "Unknown",
        "El Guincho": "Indie Pop",
        "Elisa": "Pop Rock",
        "Elliott Smith": "Indie Folk",
        "Emilie Simon": "Electronic",
        "Emily Haines & The Soft Skeleton": "Indie Pop",
        "Eminem": "Hip-Hop",
        "Emma Bunton": "Pop",
        "Emma Pollock": "Indie Rock",
        "Emmon": "Synthpop",
        "Emmure": "Metalcore",
        "Empire Of The Sun": "Electronic Pop",
        "End Of Fashion": "Rock",
        "Enrique Iglesias": "Latin Pop",
        "Enter Shikari": "Post-Hardcore",
        "Entombed": "Death Metal",
        "Enya": "New Age",
        "Epica (2)": "Symphonic Metal",
        "Epsilons": "Garage Rock",
        "Eros Ramazzotti": "Pop",
        "Es Mee": "Unknown",
        "Escape The Fate": "Post-Hardcore",
        "Esmee Denters": "Pop",
        "Estelle": "R&B",
        "Evanescence": "Rock / Goth",
        "Eve": "Hip-Hop",
        "Evermore": "Rock",
        "Every Time I Die": "Metalcore",
        "Ex-Otago": "Indie Pop",
        "Example": "Electronic",
        "Explosions In The Sky": "Post-Rock",
        "Fabolous": "Hip-Hop",
        "Fabri Fibra": "Hip-Hop",
        "Faith No More": "Alternative Metal",
        "Faker": "Indie Rock",
        "Fall Out Boy": "Pop Punk",
        "Fam-Lay": "Hip-Hop",
        "Family Force 5": "Crunk Rock",
        "Fantasia": "R&B",
        "Fat Joe": "Hip-Hop",
        "Fatal Bazooka": "Comedy",
        "Fatboy Slim": "Big Beat",
        "Fatima Rainey": "Pop",
        "Fear Factory": "Industrial Metal",
        "Federico Aubele": "Downtempo",
        "Feist": "Indie Pop",
        "Felix Da Housecat": "Electronic",
        "Fergie": "Pop",
        "Fever Ray": "Electronic",
        "Fibes, Oh Fibes!": "Pop",
        "Fidelity (2)": "Unknown",
        "Fightstar": "Post-Hardcore",
        "Fine Arts Showcase, The": "Indie Rock",
        "Finger Eleven": "Alternative Rock",
        "Finley": "Pop Punk",
        "Firewind": "Power Metal",
        "Fischerspooner": "Electclash",
        "Five Finger Death Punch": "Heavy Metal",
        "Flight of the Conchords": "Comedy / Folk",
        "Flo Rida": "Hip-Hop",
        "Flobots": "Hip-Hop / Rock",
        "Florence + The Machine": "Indie Pop",
        "Florent Pagny": "Chanson",
        "Flyleaf": "Alternative Metal",
        "Foals": "Indie Rock",
        "Folis Zois": "Unknown",
        "Foo Fighters": "Rock",
        "Foreigner": "Rock",
        "Forgive Durden": "Indie Rock",
        "Four Year Strong": "Pop Punk",
        "Francesca Battistelli": "Christian Pop",
        "Frank Turner": "Folk Punk",
        "Frankmusik": "Electropop",
        "Franz Ferdinand": "Indie Rock",
        "Freakadelika": "House",
        "Freemasons": "House",
        "Freeway": "Hip-Hop",
        "Friendly Fires": "Indie Pop",
        "Fright Ranger": "Unknown",
        "Fuel": "Post-Grunge",
        "Full Blown Chaos": "Metalcore",
        "G. Love": "Alternative Hip-Hop",
        "Gabriella Cilmi": "Pop",
        "Gallows": "Hardcore Punk",
        "Garbage": "Alternative Rock",
        "Gavin DeGraw": "Pop Rock",
        "Geisha": "Pop",
        "Gemelli Diversi": "Hip-Hop",
        "General Fiasco": "Indie Rock",
        "Genki Rockets": "Electronic",
        "George Strait": "Country",
        "Ghost Frequency, The": "Indie Rock",
        "Ghostface Killah": "Hip-Hop",
        "Gianna Nannini": "Rock",
        "Giardini Di Mirò": "Post-Rock",
        "Giorgia (2)": "Pop",
        "Girls": "Indie Rock",
        "Girls Aloud": "Pop",
        "Girls Generation": "K-Pop",
        "Glasvegas": "Indie Rock",
        "Glee Cast": "Pop",
        "Gloria Estefan": "Latin Pop",
        "Gloriana": "Country",
        "Gnarls Barkley": "Soul / Pop",
        "Go:Audio": "Pop Punk",
        "Gob (3)": "Pop Punk",
        "Godsmack": "Nu Metal",
        "Gogol Bordello": "Gypsy Punk",
        "Gojira": "Death Metal",
        "Goldfinger": "Ska Punk",
        "Goldfrapp": "Electronic",
        "Gomez": "Indie Rock",
        "Gonzales": "Electronic",
        "Good Charlotte": "Pop Punk",
        "Gorillaz": "Alternative",
        "Gossip": "Indie Rock",
        "Gotye": "Indie Pop",
        "Graham Colton": "Pop Rock",
        "Grandi Animali Marini": "Pop",
        "Green Day": "Punk Rock",
        "Gregory Darling": "Pop",
        "Grinderman": "Garage Rock",
        "Grizzly Bear": "Indie Folk",
        "Groove Coverage": "Eurodance",
        "Grouplove": "Indie Pop",
        "Gucci Mane": "Hip-Hop",
        "Guillemots": "Indie Pop",
        "Guns N' Roses": "Hard Rock",
        "Guy Sebastian": "Pop",
        "Gwen Stefani": "Pop",
        "Gym Class Heroes": "Hip-Hop / Rock",
        "Gyroscope (2)": "Rock",
        "Günther": "Eurodance",
        "H-Blockx": "Crossover",
        "HER": "R&B",
        "HIM": "Gothic Rock",
        "Hadouken!": "Grime / Indie",
        "Halestorm": "Hard Rock",
        "Hammerfall": "Power Metal",
        "Hanson": "Pop Rock",
        "Hard-Fi": "Indie Rock",
        "Harlequin League": "Indie Rock",
        "Harry Connick, Jr.": "Jazz / Pop",
        "HateSphere": "Thrash Metal",
        "Health": "Noise Rock",
        "Heartless Bastards": "Rock",
        "Heaven & Hell": "Heavy Metal",
        "Hedley": "Pop Punk",
        "Hej Matematik": "Pop",
        "Hello Saferide": "Indie Pop",
        "Helloween": "Power Metal",
        "Hellyeah": "Heavy Metal",
        "Herbert Grönemeyer": "Pop Rock",
        "Hey Rosetta!": "Indie Rock",
        "High On Fire": "Stoner Metal",
        "Hilary Duff": "Pop",
        "Hinder": "Post-Grunge",
        "Hockey": "Indie Pop",
        "Hole": "Alternative Rock",
        "Hollywood Undead": "Rap Rock",
        "Hoobastank": "Rock",
        "Hot Chelle Rae": "Pop Rock",
        "Hot Gossip": "Unknown",
        "Hot Hot Heat": "Indie Rock",
        "House of Heroes": "Alternative Rock",
        "Howie Day": "Pop Rock",
        "Hudson Mohawke": "Electronic",
        "Hunter Valentine": "Indie Rock",
        "Hurts": "Synthpop",
        "I Was A Teenage Satan Worshipper": "Electronic",
        "Ian Brown": "Indie Rock",
        "Ida Maria": "Indie Rock",
        "Il Teatro Degli Orrori": "Alternative Rock",
        "Illa Brown": "Unknown",
        "Imelda May": "Rockabilly",
        "Immanuel Casto": "Pop",
        "Imogen Heap": "Pop / Electronic",
        "In One Year": "Unknown",
        "In This Moment": "Metalcore",
        "Incubus": "Alternative Rock",
        "Indochine": "New Wave",
        "Infieri": "Unknown",
        "Information Society": "Synthpop",
        "Inna": "Dance",
        "Interpol": "Post-Punk Revival",
        "Invitro": "Rock",
        "Iron & Wine": "Indie Folk",
        "Israel Houghton": "Gospel",
        "It's A Musical": "Indie Pop",
        "Iyaz": "R&B / Reggae",
        "J. Holiday": "R&B",
        "JC Anderson": "Unknown",
        "JLS": "Pop",
        "Ja Rule": "Hip-Hop",
        "Jabberwocky": "Electronic",
        "Jack Black": "Comedy Rock",
        "Jack Johnson": "Folk Rock",
        "Jack Peñate": "Indie Rock",
        "Jade MacRae": "R&B",
        "Jae Millz": "Hip-Hop",
        "Jagged Edge": "R&B",
        "Jake Owen": "Country",
        "Jakobínarína": "Indie Rock",
        "Jamelia": "R&B",
        "James Blunt": "Pop Rock",
        "James Morrison": "Pop Soul",
        "James Yuill": "Folktronica",
        "Jamie Foxx": "R&B",
        "Jamie T": "Indie Rock",
        "Janelle Monáe": "R&B / Funk",
        "Janet Jackson": "R&B / Pop",
        "Janusz Radek": "Pop",
        "Japandroids": "Indie Rock",
        "Jarvis Cocker": "Alternative Rock",
        "Jason Aldean": "Country",
        "Jason Derulo": "Pop / R&B",
        "Jason Michael Carroll": "Country",
        "Jason Mraz": "Pop",
        "Jay Reatard": "Garage Punk",
        "Jay Z": "Hip-Hop",
        "Jay-J": "House",
        "Jazmine Sullivan": "R&B",
        "Jeanette": "Pop",
        "Jeezy": "Hip-Hop",
        "Jennifer Hudson": "R&B",
        "Jennifer Lopez": "Pop / R&B",
        "Jennifer Paige": "Pop",
        "Jeremih": "R&B",
        "Jeremy Camp": "Christian",
        "Jesse & Joy": "Latin Pop",
        "Jesse McCartney": "Pop",
        "Jessica Mauboy": "Pop",
        "Jessica Simpson": "Pop",
        "Jessie James": "Pop Country",
        "Jet": "Rock",
        "Jewel": "Folk / Pop",
        "Jim Jones": "Hip-Hop",
        "Jimi Blue": "Pop",
        "JoJo": "Pop / R&B",
        "Joe": "R&B",
        "Joe Nichols": "Country",
        "John Fogerty": "Rock",
        "John Legend": "R&B",
        "John Mayer": "Pop Rock",
        "John Mellencamp": "Rock",
        "John Vanderslice": "Indie Rock",
        "Johnny Dread": "Reggae",
        "Johnny Hallyday": "Rock",
        "Jojo": "Pop / R&B",
        "Jon Lajoie": "Comedy",
        "Jon McLaughlin": "Pop Rock",
        "Jonas Brothers": "Pop Rock",
        "Jonna Lee": "Electronic",
        "Jordan Galland": "Indie Pop",
        "Jordin Sparks": "Pop / R&B",
        "Josh Groban": "Pop",
        "Josh Turner": "Country",
        "Joss Stone": "Soul",
        "Joy Electric": "Synthpop",
        "Juanes": "Latin Pop",
        "Julian Casablancas": "Rock",
        "Julian Plenti": "Indie Rock",
        "Julianne Hough": "Country",
        "Julien Doré": "Pop",
        "Juliette Lewis": "Rock",
        "Junior Boys": "Electronic",
        "Just Jack": "Hip-Hop",
        "Justice": "Electronic",
        "Justin Bieber": "Pop",
        "Justin Martin": "House",
        "Justin Moore": "Country",
        "Justin Timberlake": "Pop",
        "K'naan": "Hip-Hop",
        "K.I.Z.": "Hip-Hop",
        "KRYŠTOF": "Pop Rock",
        "KT Tunstall": "Pop Rock",
        "Kaal": "Unknown",
        "Kaiser Chiefs": "Indie Rock",
        "Kano (6)": "Grime",
        "Kanye West": "Hip-Hop",
        "Kari Jobe": "Christian",
        "Karina": "Pop",
        "Kasabian": "Indie Rock",
        "Kassi": "Unknown",
        "Kat DeLuna": "Pop",
        "Kate & Ben": "Unknown",
        "Kate Nash": "Indie Pop",
        "Kate Tucker": "Indie Rock",
        "Katharine McPhee": "Pop",
        "Katy Perry": "Pop",
        "Kayne West": "Hip-Hop",
        "Ke$ha": "Pop",
        "Keane": "Piano Rock",
        "Keith Urban": "Country",
        "Kele Le Roc": "R&B",
        "Kellie Pickler": "Country",
        "Kelly Clarkson": "Pop Rock",
        "Kelly Rowland": "R&B",
        "Keri Hilson": "R&B",
        "Kevin Rudolf": "Rock / Hip-Hop",
        "Kid Cudi": "Hip-Hop",
        "Kid Rock": "Rock / Hip-Hop",
        "Kid Sister": "Hip-Hop",
        "Killswitch Engage": "Metalcore",
        "Kings Of Leon": "Rock",
        "Kissy Sell Out": "Electronic",
        "Klaxons": "Indie Rock",
        "Koko Von Napoo": "Unknown",
        "Korn": "Nu Metal",
        "Kris Allen": "Pop Rock",
        "Kristin Chenoweth": "Pop",
        "Kristin Hersh": "Alternative Rock",
        "Kryptic Minds": "Dubstep",
        "Kylie Minogue": "Pop",
        "La Fouine": "Hip-Hop",
        "La Roux": "Syntax Pop",
        "Lacuna Coil": "Gothic Metal",
        "Lady Antebellum": "Country",
        "Lady Gaga": "Pop / Dance",
        "Ladytron": "Electronic",
        "Lamb Of God": "Groove Metal",
        "Lambda": "Unknown",
        "Landon Pigg": "Pop",
        "Larry Hernández": "Regional Mexican",
        "Lasgo": "Eurodance",
        "Last Day Before Holiday": "Unknown",
        "Laura Izibor": "R&B",
        "Laura Jansen": "Pop",
        "Laura Pausini": "Pop",
        "Lauren Briant": "Unknown",
        "Lazarus A.D.": "Thrash Metal",
        "Le Luci Della Centrale Elettrica": "Indie Rock",
        "Le man avec les lunettes": "Indie Pop",
        "LeToya Luckett": "R&B",
        "Lebowski (2)": "Unknown",
        "Ledisi": "R&B",
        "Lee Ann Womack": "Country",
        "Leki": "R&B",
        "Lemar": "R&B",
        "Lenny Kravitz": "Rock",
        "Leona Lewis": "Pop",
        "Liam Hayes": "Indie Pop",
        "Lifehouse": "Alternative Rock",
        "Lights": "Electropop",
        "Lil Kim": "Hip-Hop",
        "Lil Wayne": "Hip-Hop",
        "Lil' Jon": "Hip-Hop",
        "Lily Allen": "Pop",
        "Linea 77": "Nu Metal",
        "Linkin Park": "Nu Metal",
        "Lion Sitté": "Reggae",
        "Lionel Richie": "R&B",
        "Lisa Hannigan": "Folk",
        "Little Boots": "Electropop",
        "Little Dragon": "Electronic",
        "Living Things": "Rock",
        "Lizette &": "Unknown",
        "Logan Lynn": "Electronic",
        "Lollobrigida": "Electropop",
        "Lolly Jane Blue": "Unknown",
        "Lookbook": "Synthpop",
        "Los Creadorez Del Pasito Duranguense": "Regional Mexican",
        "Los Enanitos Verdes": "Rock en Español",
        "Los Tigres Del Norte": "Norteño",
        "Lost Valentinos": "Indie Rock",
        "Lostprophets": "Rock",
        "Love and Theft": "Country",
        "LoveHateHero": "Post-Hardcore",
        "Lovestruck Robot": "Pop",
        "Lucio Arce": "Unknown",
        "Lucky Princess": "Unknown",
        "Lucy and the Teenage Monster": "Indie Pop",
        "Ludacris": "Hip-Hop",
        "Luke": "Rock",
        "Lyrics Born": "Hip-Hop",
        "M83": "Electronic",
        "MGMT": "Indie Pop",
        "MICC": "Unknown",
        "MIKA": "Pop",
        "Mac Miller": "Hip-Hop",
        "Mack 10": "Hip-Hop",
        "Mad Juana": "Gypsy Punk",
        "Madonna": "Pop",
        "Magneta Lane": "Indie Rock",
        "Major Lazer": "Electronic / Dancehall",
        "Malika Ayane": "Pop",
        "Mams Taylor": "Hip-Hop",
        "Man Man": "Experimental Rock",
        "Manchester Orchestra": "Indie Rock",
        "Mandy Moore": "Pop",
        "Manian": "Hands Up",
        "Manic Street Preachers": "Alternative Rock",
        "Manuel Carrasco": "Pop",
        "Maradona (2)": "Unknown",
        "Marcella & the Forget Me Nots": "Pop / Cabaret",
        "Marco Borsato": "Pop",
        "Marco Carta": "Pop",
        "Margaret Berger": "Electropop",
        "Margaret Lee": "Unknown",
        "Maria Mena": "Pop",
        "Mariachi El Bronx": "Mariachi / Punk",
        "Mariah Carey": "R&B / Pop",
        "Marianas Trench": "Pop Rock",
        "Marie Serneholt": "Pop",
        "Marilyn Manson": "Industrial Metal",
        "Marina & The Diamonds": "Pop",
        "Mario": "R&B",
        "Markus Schulz": "Trance",
        "Marques Houston": "R&B",
        "Marracash": "Hip-Hop",
        "Marsheaux": "Synthpop",
        "Marta Sánchez": "Pop",
        "Martina McBride": "Country",
        "Marvalous": "Unknown",
        "Mary J. Blige": "R&B",
        "Masoko": "Unknown",
        "Massari": "R&B / Pop",
        "Massive Attack": "Trip Hop",
        "Master Blaster": "Eurodance",
        "Master Shortie": "Hip-Hop",
        "Mastodon": "Metal",
        "Mat Kearney": "Pop Rock",
        "Matisyahu": "Reggae / Rock",
        "Matt Dusk": "Jazz / Pop",
        "Matteo Pelli": "Unknown",
        "Max Gazzé": "Pop Rock",
        "Maximilian Hecker": "Indie Pop",
        "Maximum Penalty": "Hardcore",
        "Maxwell": "Neo-Soul",
        "Maxïmo Park": "Indie Rock",
        "Mayday Parade": "Pop Punk",
        "Mean Jeans": "Punk Rock",
        "Mechanical Hands Electric Heart": "Unknown",
        "Meeting Of Important People": "Indie Pop",
        "Meko": "Dance",
        "Melanie Fiona": "R&B",
        "Melody Gardot": "Jazz",
        "Mercenary": "Melodic Death Metal",
        "Mercury Drops": "Unknown",
        "Metallica": "Heavy Metal",
        "Method Man & Redman": "Hip-Hop",
        "Metric": "Indie Rock",
        "Mew": "Indie Rock",
        "Mia Doi Todd": "Folk",
        "Miami Horror": "Electronic",
        "Michael Bolton": "Pop",
        "Michael Bublé": "Jazz / Pop",
        "Michael Franti": "Hip-Hop / Folk",
        "Michael Jackson": "Pop",
        "Michael Tolcher": "Pop Rock",
        "Mickey Avalon": "Hip-Hop",
        "Miike Snow": "Indie Pop",
        "Mika Miko": "Punk",
        "Mike Mitctlan": "Hip-Hop",
        "Mike Posner": "Pop / Hip-Hop",
        "Miley Cyrus": "Pop",
        "Millionaires": "Electronic",
        "Milow": "Pop",
        "Ministri": "Indie Rock",
        "Miranda Cosgrove": "Pop",
        "Miranda Lambert": "Country",
        "Mishon": "R&B",
        "Missincat": "Pop",
        "Mistabishi": "Drum and Bass",
        "Mistress Stephanie & Her Melodic Cat": "Unknown",
        "Moby": "Electronic",
        "Modest Mouse": "Indie Rock",
        "Modà": "Pop Rock",
        "Mona Lisa Overdrive (4)": "Unknown",
        "Monaural": "Shoegaze",
        "Moneen": "Emo",
        "Monique": "Unknown",
        "Monte negro": "Rock",
        "Montgomery Gentry": "Country",
        "Montt Mardié": "Indie Pop",
        "Monty": "Unknown",
        "Moray McLaren": "Indie Pop",
        "Morgan (2)": "Pop",
        "Morrissey": "Indie Pop",
        "Mos Def": "Hip-Hop",
        "Motionless In White": "Metalcore",
        "Motorama (3)": "Post-Punk",
        "Mozella": "Pop",
        "Mr Hudson": "R&B / Pop",
        "Mr. Big": "Hard Rock",
        "Mr. Lif": "Hip-Hop",
        "MsWhite": "Unknown",
        "Muck Sticky": "Hip-Hop",
        "Mudcrutch": "Rock",
        "Mudvayne": "Nu Metal",
        "Mumford & Sons": "Folk Rock",
        "Munk Tung": "Unknown",
        "Muse": "Alternative Rock",
        "Music Go Music": "Prog Rock / Pop",
        "My Awesome Mixtape": "Indie Pop",
        "My Chemical Romance": "Emo / Rock",
        "Mystery Jets": "Indie Pop",
        "Mötley Crüe": "Glam Metal",
        "N.A.S.A. (4)": "Hip-Hop / Electronic",
        "Nadia Ali": "Trance",
        "Naive New Beaters": "Electronic Rock",
        "Natalia Lafourcade": "Indie Pop",
        "Natalie Imbruglia": "Pop",
        "Nathan Ferraro": "Pop Rock",
        "Nawal Al Kuwaitia": "World",
        "Ne-Yo": "R&B",
        "Nek": "Pop Rock",
        "Neko Case": "Alt-Country",
        "Nelly Furtado": "Pop",
        "Nena (4)": "Neue Deutsche Welle",
        "Neo": "Unknown",
        "Nephew": "Rock",
        "Nerina Pallot": "Pop",
        "Never Shout Never": "Acoustic Pop",
        "New Found Glory": "Pop Punk",
        "New Kids On The Block": "Pop",
        "Newton Faulkner": "Folk",
        "Nick Finochio": "Unknown",
        "Nickelback": "Post-Grunge",
        "Nico Vega": "Rock",
        "Nicole Atkins": "Indie Pop",
        "Nina Sky": "R&B",
        "Ninja Dolls": "Punk Rock",
        "Nipsey Hussle": "Hip-Hop",
        "No Age": "Noise Rock",
        "No? i Dan": "Unknown",
        "Noah And The Whale": "Indie Folk",
        "Noisettes": "Indie Rock",
        "Nolwenn Leroy": "Chanson",
        "Norglen": "Unknown",
        "Numbers Game": "Unknown",
        "Numero6": "Indie Pop",
        "Nuno & The End": "Unknown",
        "Nx Zero": "Rock",
        "OCNH": "Unknown",
        "OK Go": "Alternative Rock",
        "Oasis": "Britpop",
        "Obituary": "Death Metal",
        "Obscura (3)": "Death Metal",
        "October Sky": "Rock",
        "Of Montreal": "Indie Pop",
        "Offlaga Disco Pax": "Electronic / Spoken Word",
        "Oi Va Voi": "World",
        "Old Crow Medicine Show": "Folk",
        "Omar Simons": "Unknown",
        "One Eskimo": "Indie Pop",
        "OneRepublic": "Pop Rock",
        "Opensouls": "Soul / Funk",
        "Oren Lavie": "Singer-Songwriter",
        "Oreskaband": "Ska",
        "Orianthi": "Rock",
        "Otep": "Nu Metal",
        "Our Lady Peace": "Alternative Rock",
        "Ours": "Alternative Rock",
        "Outcry Collective": "Rock",
        "Owl City": "Electronica",
        "P.O.D.": "Nu Metal",
        "PG": "Unknown",
        "PJ Harvey": "Alternative Rock",
        "Pac Div": "Hip-Hop",
        "Pale": "Indie Rock",
        "Paloma Faith": "Pop / Soul",
        "Panic! at the Disco": "Pop Punk / Emo",
        "Pantheon I": "Black Metal",
        "Paolo Nutini": "Pop Rock",
        "Papa Roach": "Nu Metal",
        "Parachute": "Pop Rock",
        "Paradise Lost": "Gothic Metal",
        "Parallel Dance Ensemble": "Electronic",
        "Parallels": "Synthpop",
        "Paramore": "Pop Punk",
        "Parov Stelar": "Electro Swing",
        "Parry Gripp": "Comedy",
        "Passion Pit": "Indie Pop",
        "Patrick Wolf": "Indie Pop",
        "Paul McCartney": "Rock",
        "Paul Weller": "Rock",
        "Paula Abdul": "Pop",
        "Paulina Rubio": "Latin Pop",
        "Peaches": "Electronic",
        "Pearl Jam": "Grunge",
        "Pendulum (3)": "Drum and Bass",
        "Penfold Gate": "Unknown",
        "Pet Shop Boys": "Synthpop",
        "Pete Yorn": "Alternative Rock",
        "Peter Björn and John": "Indie Pop",
        "Peter Daily": "Hip-Hop",
        "Phantogram": "Electronic Rock",
        "Phil Vassar": "Country",
        "Phoenix": "Indie Pop",
        "Pierre Lewis": "R&B",
        "Pink": "Pop",
        "Pistol Youth": "Indie Rock",
        "Pitbull": "Hip-Hop",
        "Pitty": "Rock",
        "Pixie Lott": "Pop",
        "Placebo": "Alternative Rock",
        "Plain White T's": "Pop Punk",
        "Plan-B": "Hip-Hop",
        "Planet Funk": "Electronic",
        "Pleasure P": "R&B",
        "Plushgun": "Synthpop",
        "Poets Of The Fall": "Rock",
        "Pompeya": "Indie Pop",
        "Ponytail": "Art Rock",
        "Pooh": "Pop Rock",
        "Pop Evil": "Rock",
        "Postal_m@rket": "Unknown",
        "Powerman 5000": "Industrial Metal",
        "Preston": "Pop",
        "Priki": "Unknown",
        "Primal Scream": "Indie Rock",
        "Prime Circle": "Rock",
        "Prince": "Funk / Pop",
        "Princess Chelsea": "Indie Pop",
        "Private": "Electronic",
        "Professor Green": "Hip-Hop",
        "Project Pat": "Hip-Hop",
        "Protest The Hero": "Progressive Metal",
        "Pryzless": "Unknown",
        "Psarantonis": "Folk",
        "Psicosuono": "Unknown",
        "Puddle Of Mudd": "Post-Grunge",
        "Q-Tip": "Hip-Hop",
        "Qua": "Electronic",
        "Quadron": "Soul",
        "Quarter the Villain": "Unknown",
        "Queensrÿche": "Progressive Metal",
        "R. Kelly": "R&B",
        "RBD": "Pop",
        "RC": "Unknown",
        "Radio Killer": "Dance",
        "Radiocore": "Unknown",
        "Raekwon": "Hip-Hop",
        "Raf": "Pop",
        "Rafale (2)": "Electronic",
        "Rambo Amadeus": "Jazz / Rock",
        "Ramirez": "Unknown",
        "Rammstein": "Industrial Metal",
        "Ramona Falls": "Indie Rock",
        "Range": "Unknown",
        "Raphael Saadiq": "R&B / Soul",
        "Rascal Flatts": "Country",
        "Ray Davies (3)": "Rock",
        "Ray Nitti": "Hip-Hop",
        "Razorlight": "Indie Rock",
        "Reba McEntire": "Country",
        "Recolector": "Unknown",
        "Redman": "Hip-Hop",
        "Regina Spektor": "Indie Pop",
        "Reh Dogg": "Outsider",
        "Reik": "Pop",
        "Renato Zero": "Pop",
        "Renaud": "Chanson",
        "Rev Theory": "Rock",
        "Revocation": "Technical Death Metal",
        "Rex Mundi": "Trance",
        "Rezophonic": "Rock",
        "Ricardo Autobahn": "Electronic",
        "Richard Hawley": "Indie Rock",
        "Richgirl": "R&B",
        "Rick Ross": "Hip-Hop",
        "Ricki-Lee": "Pop",
        "Righchus": "Hip-Hop",
        "Rihanna": "Pop / R&B",
        "Rise Against": "Punk Rock",
        "Riton": "Electronic",
        "Rizon": "Unknown",
        "Rob Thomas": "Pop Rock",
        "Robbie Williams": "Pop",
        "Robin Thicke": "R&B",
        "Rocco DeLuca And The Burden": "Rock",
        "Rogue Traders": "Electronic Rock",
        "Romantic Emily": "Emo",
        "Ronan Keating": "Pop",
        "Rotfront": "World / Ska",
        "RuPaul": "Dance",
        "Ryan Lewis": "Hip-Hop",
        "Rye Rye": "Hip-Hop",
        "Röyksopp": "Electronic",
        "SHO": "Unknown",
        "SIA": "Pop",
        "SSION": "Electronic",
        "STYGG": "Unknown",
        "Sabrina Starke": "Soul",
        "Sadistik": "Hip-Hop",
        "SafetySuit": "Rock",
        "Saint Motel": "Indie Pop",
        "Saint Saviour": "Electropop",
        "Saliva": "Nu Metal",
        "Sally Shapiro": "Synthpop",
        "Saltatio Mortis": "Folk Metal",
        "Sammy Decoster": "Folk",
        "Sandee (2)": "Pop",
        "Sarah Blasko": "Indie Pop",
        "Sarah MacDougall": "Folk",
        "Say Anything": "Pop Punk",
        "School of Seven Bells": "Shoegaze",
        "Scooter": "Techno",
        "Sean Kingston": "Reggae Fusion",
        "Sean Paul": "Dancehall",
        "Seether": "Post-Grunge",
        "Sefe": "Unknown",
        "Selena Gomez": "Pop",
        "Senit": "Pop",
        "September": "Dance",
        "Serial G": "Unknown",
        "Set It Off": "Pop Punk",
        "Sex Slaves": "Punk Rock",
        "Shad": "Hip-Hop",
        "Shakespear's Sister": "Pop",
        "Shakira": "Latin Pop",
        "Shawn Madden": "Unknown",
        "She & Him": "Indie Folk",
        "Shontelle": "R&B",
        "Sick Puppies": "Rock",
        "Sick Tamburo": "Alternative Rock",
        "Sigala": "House",
        "Sigur Rós": "Post-Rock",
        "Silbermond": "Pop Rock",
        "Silverstein": "Post-Hardcore",
        "Silversun Pickups": "Alternative Rock",
        "Simian Mobile Disco": "Electronic",
        "Simple Minds": "Rock",
        "Simple Plan": "Pop Punk",
        "Simply Red": "Soul",
        "Sing It Loud": "Pop Punk",
        "Singuila": "R&B",
        "Sirenia": "Gothic Metal",
        "Sito Rocks": "Unknown",
        "Skarhead": "Hardcore",
        "Skillet": "Rock",
        "Skunk Anansie": "Rock",
        "Slayer": "Thrash Metal",
        "Sliimy": "Pop",
        "Slipknot": "Nu Metal",
        "Sloan": "Indie Rock",
        "Smashproof": "Hip-Hop",
        "Smiley": "Pop",
        "Smoke Fairies": "Folk",
        "Snafu": "Unknown",
        "Sneaky Sound System": "Electronic",
        "Snow Patrol": "Indie Rock",
        "Soap&Skin": "Experimental",
        "Soilwork": "Melodic Death Metal",
        "Solange": "R&B",
        "Song Sparrow Research": "Unknown",
        "Sonic Syndicate": "Melodic Death Metal",
        "Soulja Boy": "Hip-Hop",
        "Soulsavers, The": "Electronic / Rock",
        "Sour": "Indie Rock",
        "Spinnerette": "Alternative Rock",
        "Stalley": "Hip-Hop",
        "Stan Walker": "Pop",
        "Star Fucking Hipsters": "Ska Punk",
        "Starseed": "Rock",
        "Static-X": "Industrial Metal",
        "Steel Panther": "Glam Metal",
        "Stevie Stone": "Hip-Hop",
        "Stiff All Stars": "Ska",
        "Sub Focus": "Drum and Bass",
        "Subsonica": "Electronic Rock",
        "Sugababes": "Pop",
        "Sugarland": "Country",
        "Super C": "Unknown",
        "Superbus (2)": "Pop Rock",
        "Supersubmarina": "Indie Rock",
        "Sweethead": "Rock",
        "Syconaut": "Unknown",
        "Syria": "Pop",
        "Sébastien Tellier": "Electronic",
        "Søs Fenger": "Pop",
        "T.I.": "Hip-Hop",
        "T13C": "Unknown",
        "TAT": "Punk Rock",
        "Tahiti Boy and the Palmtree Family": "Indie Pop",
        "TaintStick": "Comedy Rock",
        "Taio Cruz": "R&B",
        "Take That": "Pop",
        "Taylor Hicks": "Soul",
        "Taylor Swift": "Country / Pop",
        "Tegan and Sara": "Indie Pop",
        "Telekinesis": "Indie Rock",
        "Tenth Avenue North": "Christian Rock",
        "Tesla Boy": "Synthpop",
        "The Academy Is...": "Pop Punk",
        "The Airborne Toxic Event": "Indie Rock",
        "The All-American Rejects": "Pop Punk",
        "The Almost": "Alternative Rock",
        "The Aston Shuffle": "House",
        "The Bastard Sons of Dioniso": "Rock",
        "The Beth Edges": "Indie Rock",
        "The Big Lick": "Unknown",
        "The Big Pink": "Indie Rock",
        "The Bird and the Bee": "Indie Pop",
        "The Black Heart Procession": "Indie Rock",
        "The Blackout": "Post-Hardcore",
        "The Bloody Beetroots": "Electronic",
        "The BossHoss": "Country Rock",
        "The Bravery": "Post-Punk Revival",
        "The Breeders": "Alternative Rock",
        "The Bronx": "Punk Rock",
        "The Brunettes": "Indie Pop",
        "The Builders And The Butchers": "Folk Rock",
        "The Butterfly Effect": "Progressive Rock",
        "The Cab": "Pop Punk",
        "The Cataracs": "Hip-Hop",
        "The Chapman Family": "Indie Rock",
        "The Classic Crime": "Rock",
        "The Correspondents": "Electro Swing",
        "The Crystal Method": "Big Beat",
        "The Cumshots": "Metal",
        "The Dark Esquire": "Unknown",
        "The Dead Weather": "Rock",
        "The Devil Wears Prada": "Metalcore",
        "The Fabulous Miss Wendy": "Rock",
        "The Fray": "Pop Rock",
        "The Game": "Hip-Hop",
        "The Gathering": "Alternative Rock",
        "The Gay Blades": "Indie Rock",
        "The Golden Filter": "Electronic",
        "The Good China": "Unknown",
        "The Heavy": "Indie Rock",
        "The Hidden Cameras": "Indie Pop",
        "The Higher": "Pop Rock",
        "The Hives": "Garage Rock",
        "The Horrors": "Garage Rock",
        "The John Butler Trio": "Roots Rock",
        "The John Steel Singers": "Indie Pop",
        "The Killers": "Indie Rock",
        "The Knife": "Electronic",
        "The Latency": "Rock",
        "The Legendary Lightness": "Unknown",
        "The Like": "Indie Rock",
        "The Lonely Island": "Comedy",
        "The Maccabees": "Indie Rock",
        "The Monkey Steps": "Unknown",
        "The Old Ceremony": "Indie Pop",
        "The Parisians": "Indie Rock",
        "The Polyphonic Spree": "Choral Pop",
        "The Presets": "Electronic",
        "The Prodigy": "Big Beat",
        "The Pussycat Dolls": "Pop / R&B",
        "The R's": "Unknown",
        "The Red Jumpsuit Apparatus": "Post-Hardcore",
        "The Rocket Summer": "Pop Rock",
        "The Roots": "Hip-Hop",
        "The Rosebuds": "Indie Pop",
        "The Ruby Suns": "Indie Pop",
        "The Saturdays": "Pop",
        "The Script": "Pop Rock",
        "The Sound Of Arrows": "Electropop",
        "The Sounds": "New Wave",
        "The Summer Set": "Pop Punk",
        "The Thermals": "Indie Rock",
        "The Ting Tings": "Indie Pop",
        "The Twilight Hours": "Indie Rock",
        "The Urban Voodoo Machine": "Gypsy Punk",
        "The Used": "Post-Hardcore",
        "The Veronicas": "Pop Rock",
        "The View": "Indie Rock",
        "The Virgins": "Indie Rock",
        "The Whiskey Wailers": "Unknown",
        "The White Tie Affair": "Pop",
        "The Zen Circus": "Folk Punk",
        "The Zolas": "Indie Rock",
        "The xx": "Indie Pop",
        "The-Dream": "R&B",
        "Therapy?": "Alternative Metal",
        "There For Tomorrow": "Pop Punk",
        "These New Puritans": "Art Rock",
        "This Providence": "Pop Punk",
        "Three Days Grace": "Rock",
        "Three-6 Mafia": "Hip-Hop",
        "Thrice": "Post-Hardcore",
        "Tiffany Evans": "R&B",
        "Tiga": "Electronic",
        "Tim McGraw": "Country",
        "Timbaland": "Hip-Hop / R&B",
        "Timber Timbre": "Folk",
        "Timbuktu": "Hip-Hop",
        "Tina Arena": "Pop",
        "Tint Mak": "Unknown",
        "Tinted Windows": "Power Pop",
        "Titãs": "Rock",
        "Tiziano Ferro": "Pop",
        "Tiësto": "Trance",
        "To The Lions": "Unknown",
        "Toby Keith": "Country",
        "Toddla T": "Electronic",
        "Tokio Hotel": "Pop Rock",
        "Tommy Sparks": "Indie Pop",
        "Tone Spliff": "Hip-Hop",
        "Toni Braxton": "R&B",
        "Torche": "Sludge Metal",
        "Tori Amos": "Alternative",
        "Toxic Holocaust": "Thrash Metal",
        "Trabant": "Unknown",
        "Trace Adkins": "Country",
        "Train": "Pop Rock",
        "Tre Allegri Ragazzi Morti": "Indie Rock",
        "Trivium": "Metalcore",
        "Tru-Life": "Hip-Hop",
        "True Ingredients": "Unknown",
        "Tupelo Honey": "Rock",
        "Twin Atlantic": "Rock",
        "Twisted Wheel (2)": "Indie Rock",
        "Two Door Cinema Club": "Indie Rock",
        "U2": "Rock",
        "UGK": "Hip-Hop",
        "UNKLE": "Electronic",
        "Uncle Kracker": "Rock / Country",
        "Undercroft": "Death Metal",
        "Underoath": "Metalcore",
        "Uochi Toki": "Hip-Hop",
        "Usher": "R&B",
        "V.I.C.": "Hip-Hop",
        "VKR": "Unknown",
        "Valencia": "Pop Punk",
        "Vampire Weekend": "Indie Rock",
        "Vanessa Williams": "Pop / R&B",
        "Varsity Fanclub": "Pop",
        "Vatra": "Rock",
        "Velvet (2)": "Pop",
        "VersaEmerge": "Rock",
        "Verse Simmonds": "R&B",
        "Vitalic": "Electronic",
        "Vitas": "Pop / Opera",
        "Voyager": "Progressive Metal",
        "WHY?": "Indie Rock",
        "Wah Companion": "Unknown",
        "Wake Of Destruction": "Unknown",
        "Warpaint": "Indie Rock",
        "Watsky": "Hip-Hop",
        "We Are The World": "Pop",
        "We Have Band": "Electronic",
        "We The Kings": "Pop Punk",
        "Webstar & Jim Jones": "Hip-Hop",
        "Wedlock": "Unknown",
        "Weezer": "Alternative Rock",
        "Weird Al Yankovic": "Comedy",
        "White Denim": "Indie Rock",
        "Whitechapel": "Deathcore",
        "Whitney Houston": "R&B",
        "Whole Wheat Bread": "Punk",
        "Why Not Loser": "Unknown",
        "Will Young": "Pop",
        "William Control": "Electronic",
        "Winny Puhh": "Unknown",
        "Wisin & Yandel": "Reggaeton",
        "Within Temptation": "Symphonic Metal",
        "Wolfmother": "Hard Rock",
        "Woodpecker": "Unknown",
        "Wyclef Jean": "Hip-Hop",
        "X-Marks The Pedwalk": "Industrial",
        "XLR": "Unknown",
        "Xerath": "Groove Metal",
        "Yeah Yeah Yeahs": "Indie Rock",
        "Yo Gotti": "Hip-Hop",
        "You Don't Know Jack": "Unknown",
        "Young Guns": "Rock",
        "Young Money": "Hip-Hop",
        "Young Paper": "Hip-Hop",
        "Youri Skamolov": "Unknown",
        "Yuridia": "Pop",
        "ZALE": "Unknown",
        "Zac Brown Band": "Country",
        "Zahara": "Pop",
        "Zak Sally": "Indie Rock",
        "Zarif": "Soul",
        "Zee Avi": "Singer-Songwriter",
        "Zero Assoluto": "Pop",
        "Zoe Boekbinder": "Folk",
        "Zoe Myers": "Pop",
        "Zola Jesus": "Goth Pop",
        "a-ha": "Pop",
        "esterina": "Indie Rock",
        "fun.": "Indie Pop",
        "múm": "Electronic",
        "t.A.T.u.": "Pop"
    }
    
    for entry in data:
        artist_name = entry.get('artist_name')
        if artist_name in genre_map:
            entry['artist_genre'] = genre_map[artist_name]
        elif entry.get('artist_genre') == 'Desconhecido':
             # pass
             pass

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    enrich_genres('data/2009.json')
