
import json
import os

# Define the genre mapping for 1999
ARTIST_GENRES = {
    # Rock Alternativo / Indie / Grunge / Post-Grunge
    "311": "Rock Alternativo",
    "8Stop7": "Rock Alternativo",
    "Aimee Mann": "Rock Alternativo",
    "Alanis Morissette": "Rock Alternativo",
    "Alkaline Trio": "Punk",
    "Amorphis": "Metal",
    "Anastasia": "Pop",
    "Arch Enemy": "Metal",
    "Artificial Joy Club": "Rock Alternativo",
    "Ash": "Rock Alternativo",
    "Atari Teenage Riot": "Hardcore", # Digital Hardcore
    "Augie March": "Rock Alternativo",
    "Barenaked Ladies": "Rock Alternativo",
    "Beck": "Rock Alternativo",
    "Ben Folds Five": "Rock Alternativo",
    "Ben Lee": "Rock Alternativo",
    "Beth Orton": "Eletronico", # Folktronica
    "Big Fat Snake (2)": "Rock Alternativo",
    "Björk": "Eletronico",
    "Blink-182": "Punk", # Pop Punk
    "Bloodhound Gang": "Rock Alternativo",
    "Blue Rodeo": "Rock Alternativo",
    "Bluvertigo": "Rock Alternativo",
    "Bon Jovi": "Rock Alternativo",
    "Buckcherry": "Rock Alternativo", # Hard Rock
    "Bush": "Rock Alternativo",
    "Cat Power": "Rock Alternativo",
    "Catatonia": "Rock Alternativo",
    "Chantal Kreviazuk": "Rock Alternativo",
    "Cheap Trick": "Rock Alternativo",
    "Chris Cornell": "Rock Alternativo",
    "Citizen King": "Rock Alternativo",
    "Collective Soul": "Rock Alternativo",
    "Counting Crows": "Rock Alternativo",
    "Cradle Of Filth": "Metal",
    "Crash Test Dummies": "Rock Alternativo",
    "Creed": "Rock Alternativo", # Post-Grunge
    "Cristina Donà": "Rock Alternativo",
    "Daniele Silvestri": "Pop",
    "Dave Matthews Band": "Rock Alternativo",
    "Days Of The New": "Rock Alternativo",
    "Def Leppard": "Metal",
    "Deftones": "Metal",
    "Det Brune Punktum": "Pop",
    "Die Ärzte": "Punk",
    "Dinosaur Jr.": "Rock Alternativo",
    "Dog Eat Dog": "Rock Alternativo", # Crossover
    "Donots": "Punk",
    "Dope (4)": "Metal", # Nu Metal / Industrial
    "Dovetail Joint": "Rock Alternativo",
    "Duncan Sheik": "Rock Alternativo",
    "Eagle-Eye Cherry": "Rock Alternativo",
    "Edwin McCain": "Rock Alternativo",
    "Elcka": "Rock Alternativo",
    "Embrace": "Rock Alternativo",
    "Emiliana Torrini": "Eletronico",
    "Eskimo Joe": "Rock Alternativo",
    "Eve 6": "Rock Alternativo",
    "Everclear": "Rock Alternativo",
    "Everlast": "Rock Alternativo",
    "Face To Face": "Punk",
    "Far": "Rock Alternativo",
    "Fastball": "Rock Alternativo",
    "Feeder": "Rock Alternativo",
    "Filter": "Industrial",
    "Fiona Apple": "Rock Alternativo",
    "Foo Fighters": "Rock Alternativo",
    "Francesca Chiara Casellati": "Rock Alternativo",
    "Freundeskreis": "Rap",
    "Fuel": "Rock Alternativo",
    "Garbage": "Rock Alternativo",
    "Gay Dad": "Rock Alternativo",
    "Ginevra Di Marco": "Rock Alternativo",
    "Glay": "Rock Alternativo",
    "Glow (4)": "Rock Alternativo",
    "Godsmack": "Metal",
    "Gomez": "Rock Alternativo",
    "Goo Goo Dolls": "Rock Alternativo",
    "Green Day": "Punk",
    "Guano Apes": "Rock Alternativo",
    "Gustavo Cerati": "Rock Alternativo",
    "HIM": "Rock Alternativo",
    "Hole": "Rock Alternativo",
    "Iggy Pop": "Rock Alternativo",
    "Imperial Teen": "Rock Alternativo",
    "Incubus": "Rock Alternativo",
    "Indochine": "Rock Alternativo",
    "James": "Rock Alternativo",
    "Jars Of Clay": "Rock Alternativo",
    "Jebediah": "Rock Alternativo",
    "Joe Cocker": "Rock Alternativo",
    "John Mellencamp": "Rock Alternativo",
    "Jonny Lang": "Rock Alternativo",
    "Joydrop": "Rock Alternativo",
    "Julie's Haircut": "Rock Alternativo",
    "Keith Caputo": "Rock Alternativo",
    "Kent": "Rock Alternativo",
    "Kid Rock": "Rock Alternativo", # Rap Rock
    "Killing Heidi": "Rock Alternativo",
    "Korn": "Metal",
    "Kreator": "Metal",
    "Kristin Hersh": "Rock Alternativo",
    "Kula Shaker": "Rock Alternativo",
    "Kyosuke Himuro": "Rock Alternativo",
    "La Sintesi": "Rock Alternativo",
    "Len": "Rock Alternativo",
    "Lenny Kravitz": "Rock Alternativo",
    "Limp Bizkit": "Metal",
    "Lit": "Rock Alternativo",
    "Litfiba": "Rock Alternativo",
    "Live": "Rock Alternativo",
    "Luscious Jackson": "Rock Alternativo",
    "Machine Head": "Metal",
    "Man Or Astro-Man?": "Rock Alternativo", # Surf Rock
    "Manic Street Preachers": "Rock Alternativo",
    "Mansun": "Rock Alternativo",
    "Marcy Playground": "Rock Alternativo",
    "Marilyn Manson": "Industrial",
    "Marvelous 3": "Rock Alternativo",
    "Meat Loaf": "Rock Alternativo",
    "Medal": "Rock Alternativo",
    "Megadeth": "Metal",
    "Megaherz": "Industrial", # NDH
    "Melissa Etheridge": "Rock Alternativo",
    "Meredith Brooks": "Rock Alternativo",
    "Meshuggah": "Metal",
    "Metallica": "Metal",
    "Moist (3)": "Rock Alternativo",
    "Moltheni": "Rock Alternativo",
    "Monster Magnet": "Rock Alternativo",
    "Moonspell": "Metal",
    "Muse": "Rock Alternativo",
    "Myslovitz": "Rock Alternativo",
    "Natalia Oreiro": "Pop",
    "Natalie Merchant": "Rock Alternativo",
    "Negrita": "Rock Alternativo",
    "New Found Glory": "Punk",
    "New Radicals": "Rock Alternativo",
    "Nightwish": "Metal",
    "Nine Inch Nails": "Industrial",
    "No Doubt": "Rock Alternativo",
    "Oleander": "Rock Alternativo",
    "Orgy": "Industrial",
    "Our Lady Peace": "Rock Alternativo",
    "P.O.D.": "Metal", # Nu Metal
    "Paradise Lost": "Metal",
    "Pavement": "Rock Alternativo",
    "Pearls": "Rock Alternativo",
    "Placebo": "Rock Alternativo",
    "Powerman 5000": "Industrial",
    "Primal Scream": "Rock Alternativo",
    "Quarashi": "Rock Alternativo",
    "Quintorigo": "Rock Alternativo",
    "R.E.M.": "Rock Alternativo",
    "Radiohead": "Rock Alternativo",
    "Rage Against The Machine": "Rock Alternativo",
    "Red Hot Chili Peppers": "Rock Alternativo",
    "Rednex": "Pop",
    "Reef": "Rock Alternativo",
    "Reggae National Tickets": "Pop", # Reggae
    "Rob Zombie": "Industrial",
    "Rotting Christ": "Metal",
    "Santana": "Rock Alternativo",
    "Savage Garden": "Pop",
    "Scritti Politti": "Pop",
    "Sevendust": "Metal",
    "Shawn Mullins": "Rock Alternativo",
    "Sheryl Crow": "Rock Alternativo",
    "Shooter": "Rock Alternativo",
    "Sigur Rós": "Rock Alternativo", # Post-Rock
    "Silverchair": "Rock Alternativo",
    "Skunk Anansie": "Rock Alternativo",
    "Sleater-Kinney": "Rock Alternativo", # Riot Grrrl / Indie
    "Slipknot": "Metal", # Nu Metal
    "Smash Mouth": "Rock Alternativo",
    "Spiderbait": "Rock Alternativo",
    "Staind": "Metal", # Nu Metal
    "Static-X": "Industrial",
    "Stereophonics": "Rock Alternativo",
    "Stone Temple Pilots": "Rock Alternativo",
    "Subsonica": "Rock Alternativo",
    "Subzonic": "Rock Alternativo",
    "Suede": "Rock Alternativo",
    "Sugar Ray": "Rock Alternativo",
    "Super B": "Rock Alternativo",
    "Super Furry Animals": "Rock Alternativo",
    "Supergrass": "Rock Alternativo",
    "Switchfoot": "Rock Alternativo",
    "System Of A Down": "Metal",
    "Tal Bachman": "Rock Alternativo",
    "Taxiride": "Rock Alternativo",
    "Terrorvision": "Rock Alternativo",
    "The Afghan Whigs": "Rock Alternativo",
    "The Cardigans": "Rock Alternativo",
    "The Charlatans": "Rock Alternativo",
    "The Cranberries": "Rock Alternativo",
    "The Divine Comedy": "Rock Alternativo",
    "The Donnas": "Rock Alternativo", # Garage Rock
    "The Gathering": "Metal",
    "The Jesus And Mary Chain": "Rock Alternativo",
    "The Levellers": "Rock Alternativo",
    "The Lightning Seeds": "Rock Alternativo",
    "The Mavericks": "Country",
    "The Motorhomes": "Rock Alternativo",
    "The Offspring": "Punk",
    "The Roots": "Rap",
    "The Smashing Pumpkins": "Rock Alternativo",
    "The Tragically Hip": "Rock Alternativo",
    "The Verve Pipe": "Rock Alternativo",
    "They Might Be Giants": "Rock Alternativo",
    "Third Eye Blind": "Rock Alternativo",
    "Tom Petty And The Heartbreakers": "Rock Alternativo",
    "Tonic (2)": "Rock Alternativo",
    "Toploader": "Rock Alternativo",
    "Tori Amos": "Rock Alternativo",
    "Toto": "Rock Alternativo",
    "Travis": "Rock Alternativo",
    "Tre Allegri Ragazzi Morti": "Rock Alternativo",
    "Type O Negative": "Metal",
    "U.S. Crush": "Punk",
    "U2": "Rock Alternativo",
    "Ultrasound": "Rock Alternativo",
    "Unwritten Law": "Punk",
    "VAST": "Industrial",
    "Veracocha": "Rap",
    "Verbena": "Rock Alternativo",
    "Verdena": "Rock Alternativo",
    "Vertical Horizon": "Rock Alternativo",
    "Voodoo Glow Skulls": "Punk",
    "Weird Al Yankovic": "Pop",
    "Yo Yo Mundi": "Rock Alternativo",

    # Pop / R&B / Mainstream
    "*NSYNC": "Pop",
    "1000 Clowns": "Pop",
    "2 Brothers On The 4th Floor": "Dance",
    "4 The Cause": "Pop", # R&B
    "A*Teens": "Pop",
    "A1": "Pop",
    "Ace of Base": "Pop",
    "Adam Rickitt": "Pop",
    "Air": "Eletronico",
    "Alan Jackson": "Country",
    "Alcazar": "Dance",
    "Alice Deejay": "Dance",
    "Amel Larrieux": "Pop", # R&B
    "Amyth": "Pop", # R&B
    "Anastacia": "Pop",
    "Andy Griggs": "Country",
    "Angelique (3)": "Pop",
    "Angie Stone": "Pop", # R&B
    "Aphex Twin": "Eletronico",
    "Apollo 440": "Eletronico",
    "Aqua": "Pop",
    "Aquagen": "Dance",
    "Atomic Kitten": "Pop",
    "Ayman (2)": "Pop", # R&B
    "Ayumi Hamasaki": "Pop",
    "B*Witched": "Pop",
    "Backstreet Boys": "Pop",
    "Bacon Popper": "Dance",
    "Basement Jaxx": "Eletronico",
    "BBMak": "Pop",
    "Belinda Carlisle": "Pop",
    "Billy Ray Cyrus": "Country",
    "Black Katt": "Rap",
    "Blackstreet": "Pop", # R&B
    "Blaque (2)": "Pop", # R&B
    "Blessid Union Of Souls": "Pop",
    "Blondie": "Pop", # Pop Rock
    "Blue Nature": "Dance",
    "Blue": "Pop",
    "Bluebob": "Pop",
    "Blümchen": "Dance",
    "BMR": "Dance",
    "Bomfunk MC's": "Eletronico",
    "Boyzone": "Pop",
    "Brad Paisley": "Country",
    "Bree Sharp": "Pop",
    "Brian McKnight": "Pop", # R&B
    "Brian Setzer Orchestra": "Pop",
    "Brighter Touch": "Pop",
    "Britney Spears": "Pop",
    "Brooklyn Bounce": "Dance",
    "Brooks & Dunn": "Country",
    "Bryan Adams": "Pop",
    "C Note": "Pop",
    "C-Note": "Pop",
    "Caprice (6)": "Pop",
    "Captain Jack": "Dance",
    "Caramell": "Dance",
    "Case": "Pop", # R&B
    "Céline Dion": "Pop",
    "Charlotte Church": "Pop", # Classical Crossover
    "Charlotte": "Pop",
    "Chayanne": "Pop",
    "Chely Wright": "Country",
    "Cher": "Pop",
    "Chili Con Carne": "Pop",
    "Chris Perez Band": "Pop", # Latin
    "Chris Rock": "Pop", # Comedy
    "Chris Webber": "Rap",
    "Christina Aguilera": "Pop",
    "Cool Breeze": "Rap",
    "Corey Hart": "Pop",
    "Cree Summer": "Pop",
    "Culture Club": "Pop",
    "Daft Punk": "Eletronico",
    "D’Angelo": "Pop", # R&B
    "Daphne And Celeste": "Pop",
    "Darude": "Dance",
    "Das System": "Eletronico",
    "David Bowie": "Rock Alternativo",
    "Death In Vegas": "Eletronico",
    "Deborah Cox": "Pop", # R&B
    "DeDe Lopez": "Pop",
    "Destiny's Child": "Pop", # R&B
    "Diamond Rio": "Country",
    "Die Prinzen": "Pop",
    "Dixie Chicks": "Country",
    "DJ Session One": "Dance",
    "DJ Spooky": "Eletronico",
    "DJ Taylor & Flow": "Dance",
    "Donell Jones": "Pop", # R&B
    "Donna Summer": "Pop",
    "Dope Smugglaz": "Eletronico",
    "Double Up (2)": "Rap",
    "Dropzone": "Dance",
    "Dru Hill": "Pop", # R&B
    "DuMonde": "Dance",
    "Dwight Yoakam": "Country",
    "Edyta Górniak": "Pop",
    "Eiffel 65": "Dance",
    "Elvis Crespo": "Pop", # Latin
    "Emel": "Dance",
    "Enrique Iglesias": "Pop",
    "Eric Benét": "Pop", # R&B
    "Eric Clapton": "Pop",
    "Eternal": "Pop", # R&B
    "Europe": "Rock Alternativo",
    "Eurythmics": "Pop",
    "Everything But The Girl": "Eletronico",
    "Faith Hill": "Country",
    "Faithless": "Eletronico",
    "Falco": "Pop",
    "Fatboy Slim": "Eletronico",
    "Five": "Pop",
    "Florent Pagny": "Pop",
    "Franco Battiato": "Pop",
    "Funky Green Dogs": "Dance",
    "Gary Allan (2)": "Country",
    "Gary Barlow": "Pop",
    "George Michael": "Pop",
    "Geri Halliwell": "Pop",
    "Gigi D'Agostino": "Dance",
    "GIL": "Pop",
    "Ginuwine": "Pop", # R&B
    "Giorgia (2)": "Pop",
    "Glenn Lewis": "Pop", # R&B
    "Gloria Estefan": "Pop",
    "Groove Armada": "Eletronico",
    "Hank Williams Jr.": "Country",
    "Highland": "Dance",
    "iLL-Connection": "Rap",
    "Imogen Heap": "Rock Alternativo",
    "Ivete Sangalo": "Pop",
    "Jagged Edge": "Pop", # R&B
    "Jam & Spoon": "Dance",
    "Jamelia": "Pop", # R&B
    "Jamiroquai": "Pop", # Funk
    "Janet Jackson": "Pop", # R&B
    "Jennifer Lopez": "Pop",
    "Jennifer Love Hewitt": "Pop",
    "Jennifer Paige": "Pop",
    "Jessica Andrews": "Country",
    "Jessica Simpson": "Pop",
    "Joe Diffie": "Country",
    "Jordan Knight": "Pop",
    "Jovanotti": "Pop", # Rap/Pop
    "Joy Electric": "Eletronico",
    "Juice": "Pop", # R&B
    "K-Ci & JoJo": "Pop", # R&B
    "Keith Urban": "Country",
    "Kelis": "Pop", # R&B
    "Kenny Loggins": "Pop",
    "Kiss Destination": "Dance",
    "Lakuna": "Eletronico",
    "Lamb": "Eletronico",
    "Latin Dance": "Dance",
    "Laura Pausini": "Pop",
    "Laura": "Pop",
    "Lauryn Hill": "Pop", # R&B
    "LeAnn Rimes": "Country",
    "Leftfield": "Eletronico",
    "LFO": "Pop",
    "Lightforce": "Dance",
    "Loona": "Dance",
    "Los Tigres Del Norte": "Country",
    "Lou Bega": "Pop", # Mambo No. 5
    "Luca Carboni": "Pop",
    "M People": "Dance",
    "M2M": "Pop",
    "Mabel": "Dance",
    "Macy Gray": "Pop", # R&B/Soul
    "Made Men": "Rap",
    "Madison Avenue": "Dance",
    "Madonna": "Pop",
    "Mandy Moore": "Pop",
    "Marc Dorsey": "Pop", # R&B
    "Mariah Carey": "Pop", # R&B
    "Mark Wills": "Country",
    "Marta Sánchez": "Pop",
    "Martina McBride": "Country",
    "Mary J. Blige": "Pop", # R&B
    "Mauro Picotto": "Dance",
    "Maxwell": "Pop", # R&B
    "Me & My": "Dance",
    "Melanie B": "Pop",
    "Melanie C": "Pop",
    "Michael Learns To Rock": "Pop",
    "Miss Shiva": "Dance",
    "Mister Jones": "Pop",
    "Moby": "Eletronico",
    "Modern Talking": "Pop",
    "Mojito": "Dance",
    "Moloko": "Eletronico",
    "Monica": "Pop", # R&B
    "Montell Jordan": "Pop", # R&B
    "Montgomery Gentry": "Country",
    "Morcheeba": "Eletronico",
    "Morten Abel": "Pop",
    "Motion Unit": "Eletronico",
    "Mr. Oizo": "Eletronico",
    "Mya": "Pop", # R&B
    "Mythos (3)": "Eletronico", # New Age similar
    "N'Dea Davenport": "Pop", # R&B
    "Natalie Imbruglia": "Pop",
    "Niko": "Pop",
    "No Face (5)": "Rap",
    "Oli P.": "Rap", # Pop Rap
    "Orbital": "Eletronico",
    "Otto": "Pop", # Comedy
    "Phats & Small": "Dance",
    "Phil Collins": "Pop",
    "Pink": "Pop", # R&B era
    "Pras Michel": "Rap",
    "Prince": "Pop",
    "Rahzel": "Rap",
    "Raphael Saadiq": "Pop", # R&B
    "Rappers Against Racism": "Rap",
    "Rapsody": "Rap",
    "Reba McEntire": "Country",
    "Ricky Martin": "Pop",
    "Ricky": "Pop",
    "Robbie Williams": "Pop",
    "Robyn": "Pop",
    "Ronan Keating": "Pop",
    "Roxette": "Pop",
    "RYLZ": "Dance",
    "S Club 7": "Pop",
    "Sammie (2)": "Pop", # R&B
    "Sammy Kershaw": "Country",
    "Sarah McLachlan": "Pop",
    "Sash!": "Dance",
    "Scooter": "Dance",
    "Seal": "Pop",
    "Seiko Matsuda": "Pop",
    "Sequential One": "Dance",
    "Shakira": "Pop",
    "Shania Twain": "Country",
    "Simply Red": "Pop",
    "Sinéad O'Connor": "Pop",
    "Sisqó": "Pop", # R&B
    "Sixpence None The Richer": "Pop",
    "Slick Rick": "Rap",
    "SM-Trax": "Dance",
    "Smokey Robinson": "Pop",
    "Sneaker Pimps": "Eletronico",
    "Sole": "Rap",
    "Spike": "Pop",
    "Steps": "Pop",
    "Sting": "Pop",
    "Sway & King Tech": "Rap",
    "Swift": "Pop",
    "Swirl 360": "Pop",
    "Syleena Johnson": "Pop", # R&B
    "Tarkan": "Pop",
    "Terror Squad": "Rap",
    "Texas": "Pop",
    "The Beatles": "Rock Alternativo", # Anthology
    "The Boomtang Boys": "Dance",
    "The Boyz": "Pop",
    "The Brand New Heavies": "Pop", # Acid Jazz
    "The Chemical Brothers": "Eletronico",
    "The Corrs": "Pop",
    "The Kinleys": "Country",
    "The Moffatts": "Pop",
    "The Tamperer": "Dance",
    "Thievery Corporation": "Eletronico",
    "Tin Tin Out": "Dance",
    "Tina Turner": "Pop",
    "TLC": "Pop", # R&B
    "Toby Keith": "Country",
    "Tom Jones": "Pop",
    "Total": "Pop", # R&B
    "Touché (3)": "Pop",
    "Toy-Box": "Dance",
    "Trisha Yearwood": "Country",
    "Two-Mix": "Pop", # J-Pop
    "Tyrese": "Pop", # R&B
    "UNKLE": "Eletronico",
    "Urban Species": "Rap",
    "Utada Hikaru": "Pop",
    "Vengaboys": "Dance",
    "Vitamin C": "Pop",
    "Wavescope": "Eletronico",
    "Westlife": "Pop",
    "Whigfield": "Dance",
    "Whitney Houston": "Pop", # R&B
    "Will Smith": "Rap",
    "Winans Phase 2": "Pop", # Gospel
    "Wyclef Jean": "Rap",
    "Xzibit": "Rap",
    "Yamboo": "Dance",
    "Yazoo": "Pop", # Synthpop
    "YoungBloodZ": "Rap",
    "Zerozen": "Pop",
    "Zombie Nation": "Dance",

    # Rap / Hip Hop
    "2Pac": "Rap",
    "50 Cent": "Rap",
    "A.K.-S.W.I.F.T.": "Rap",
    "Aceyalone": "Rap",
    "B.G.": "Rap",
    "Big Punisher": "Rap",
    "Black Katt": "Rap",
    "Busta Rhymes": "Rap",
    "C-Block": "Rap",
    "Cam’ron": "Rap",
    "Canibus": "Rap",
    "Charli Baltimore": "Rap",
    "Cool Breeze": "Rap",
    "Cypress Hill": "Rap",
    "Da Brat": "Rap",
    "Da Hawg": "Rap",
    "Def Squad": "Rap",
    "Die Fantastischen Vier": "Rap",
    "Die Firma": "Rap",
    "DJ Quik": "Rap",
    "DMX": "Rap",
    "Down Low": "Rap",
    "Dr. Dre": "Rap",
    "Drag-On": "Rap",
    "Eminem": "Rap",
    "EPMD": "Rap",
    "Eve": "Rap",
    "Foxy Brown": "Rap",
    "Ghetto Concept": "Rap",
    "Ghostface Killah": "Rap",
    "Goodie Mob": "Rap",
    "GZA": "Rap",
    "Hot Boys": "Rap",
    "Ice Cube": "Rap",
    "Ideal J": "Rap",
    "Insane Clown Posse": "Rap",
    "Ja Rule": "Rap",
    "Jay Z": "Rap",
    "Jaymaliq": "Rap",
    "Jungle Brothers": "Rap",
    "Jurassic 5": "Rap",
    "Juvenile": "Rap",
    "Krayzie Bone": "Rap",
    "Lil Wayne": "Rap",
    "LL Cool J": "Rap",
    "Made Men": "Rap",
    "Maestro": "Rap",
    "Master P": "Rap",
    "Memphis Bleek": "Rap",
    "Method Man & Redman": "Rap",
    "Missy Elliott": "Rap",
    "Mobb Deep": "Rap",
    "Mos Def": "Rap",
    "Mystikal": "Rap",
    "Nas": "Rap",
    "Naughty By Nature": "Rap",
    "Oli P.": "Rap",
    "Ol' Dirty Bastard": "Rap",
    "OutKast": "Rap",
    "Pete Rock": "Rap",
    "Puff Daddy": "Rap",
    "Q-Tip": "Rap",
    "R. Kelly": "Pop", # R&B
    "Rahzel": "Rap",
    "Redman": "Rap",
    "Roots Manuva": "Rap",
    "Salt 'N' Pepa": "Rap",
    "Silkk The Shocker": "Rap",
    "Snoop Dogg": "Rap",
    "Sole": "Rap",
    "Terror Squad": "Rap",
    "Tha Eastsidaz": "Rap",
    "The Lox": "Rap",
    "The Notorious B.I.G.": "Rap",
    "The Roots": "Rap",
    "Three-6 Mafia": "Rap",
    "Timbaland": "Rap",
    "Too Short": "Rap",
    "Warren G": "Rap",
    "Will Smith": "Rap",
    "Wu-Tang Clan": "Rap",
    "Wyclef Jean": "Rap",
    "Xzibit": "Rap",
    "YoungBloodZ": "Rap",
    "Zombie Nation": "Eletronico", # Techno
}

def enrich_genres():
    input_path = 'data/1999.json'
    
    if not os.path.exists(input_path):
        print(f"File not found: {input_path}")
        return

    with open(input_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    updated_count = 0
    missing_artists = set()

    for video in data:
        # Normalize key: 'artist_name' -> 'artist'
        if 'artist_name' in video:
            video['artist'] = video.pop('artist_name')
        
        artist = str(video.get('artist', '')).strip()
        
        # Try exact match
        if artist in ARTIST_GENRES:
            video['artist_genre'] = ARTIST_GENRES[artist]
            updated_count += 1
        else:
            # Fallback
            missing_artists.add(artist)
            video['artist_genre'] = "Desconhecido"

    # Save back
    with open(input_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Updated {updated_count} videos.")
    print(f"Missing mappings for {len(missing_artists)} artists.")
    if missing_artists:
        print("Sample missing:", list(missing_artists)[:20])

if __name__ == "__main__":
    enrich_genres()
