import json

# Define genre mappings for 2005 artists
ARTIST_GENRES = {
    # Pop / Pop Rock / Teen Pop
    "Gwen Stefani": "Pop",
    "Kelly Clarkson": "Pop",
    "Mariah Carey": "Pop",
    "Madonna": "Pop",
    "Britney Spears": "Pop",
    "Shakira": "Pop",
    "Rihanna": "Pop",
    "Jennifer Lopez": "Pop",
    "Backstreet Boys": "Pop",
    "The Pussycat Dolls": "Pop",
    "Ciara": "Pop",
    "Hilary Duff": "Pop",
    "Lindsay Lohan": "Pop",
    "Ashlee Simpson": "Pop",
    "Jesse McCartney": "Pop",
    "JoJo": "Pop",
    "Natalie Imbruglia": "Pop",
    "Daniel Powter": "Pop",
    "James Blunt": "Pop",
    "Natasha Bedingfield": "Pop",
    "Robbie Williams": "Pop",
    "Kylie Minogue": "Pop",
    "Girls Aloud": "Pop",
    "Sugababes": "Pop",
    "t.A.T.u.": "Pop",
    "Michael Bublé": "Pop",
    "Westlife": "Pop",
    "Will Smith": "Pop",
    "John Legend": "R&B",
    "Amerie": "R&B",
    "Pussycat Dolls": "Pop",
    "RBD": "Pop",
    "Rouge": "Pop",
    "Sandy & Junior": "Pop",
    "Wanessa Camargo": "Pop",
    "Felipe Dylon": "Pop",
    "Perlla": "Funk Carioca",
    "Kelly Key": "Pop",
    "Luka": "Pop",
    "Marjorie Estiano": "Pop Rock",
    
    # Hip Hop / Rap
    "50 Cent": "Hip Hop",
    "Kanye West": "Hip Hop",
    "Eminem": "Hip Hop",
    "Snoop Dogg": "Hip Hop",
    "The Game": "Hip Hop",
    "Ludacris": "Hip Hop",
    "Lil Wayne": "Hip Hop",
    "T.I.": "Hip Hop",
    "Young Jeezy": "Hip Hop",
    "Juelz Santana": "Hip Hop",
    "Chamillionaire": "Hip Hop",
    "Paul Wall": "Hip Hop",
    "Mike Jones": "Hip Hop",
    "Slim Thug": "Hip Hop",
    "Three 6 Mafia": "Hip Hop",
    "Ying Yang Twins": "Hip Hop",
    "Missy Elliott": "Hip Hop",
    "Busta Rhymes": "Hip Hop",
    "Fat Joe": "Hip Hop",
    "Common": "Hip Hop",
    "Twista": "Hip Hop",
    "Bow Wow": "Hip Hop",
    "Pharrell Williams": "Hip Hop",
    "Nelly": "Hip Hop",
    "Sean Paul": "Dancehall",
    "Daddy Yankee": "Reggaeton",
    "Don Omar": "Reggaeton",
    "Wisin & Yandel": "Reggaeton",
    "Pitbull": "Hip Hop",
    "Black Eyed Peas": "Hip Hop",
    "Gorillaz": "Hip Hop",
    "Fort Minor": "Hip Hop",
    "Marcelo D2": "Hip Hop",
    "Gabriel O Pensador": "Hip Hop",
    "Racionais MC's": "Rap",
    "MV Bill": "Rap",

    # Rock / Alternative / Indie
    "Green Day": "Rock",
    "Coldplay": "Rock",
    "Foo Fighters": "Rock",
    "The Killers": "Rock",
    "Franz Ferdinand": "Rock",
    "Arctic Monkeys": "Indie Rock",
    "Kaiser Chiefs": "Indie Rock",
    "Bloc Party": "Indie Rock",
    "The Strokes": "Indie Rock",
    "The White Stripes": "Rock",
    "Queens of the Stone Age": "Rock",
    "System of a Down": "Metal",
    "Nine Inch Nails": "Industrial",
    "Audioslave": "Rock",
    "Weezer": "Rock",
    "Beck": "Alternative",
    "Oasis": "Rock",
    "U2": "Rock",
    "Bon Jovi": "Rock",
    "The Rolling Stones": "Rock",
    "Red Hot Chili Peppers": "Rock",
    "Pearl Jam": "Rock",
    "R.E.M.": "Rock",
    "Garbage": "Rock",
    "Korn": "Nu Metal",
    "Slipknot": "Nu Metal",
    "Deftones": "Nu Metal",
    "Disturbed": "Nu Metal",
    "Avenged Sevenfold": "Metal",
    "Bullet for My Valentine": "Metal",
    "Trivium": "Metal",
    "My Chemical Romance": "Emo",
    "Fall Out Boy": "Emo",
    "Panic! at the Disco": "Emo",
    "The All-American Rejects": "Emo",
    "Paramore": "Emo",
    "Taking Back Sunday": "Emo",
    "Simple Plan": "Pop Punk",
    "Good Charlotte": "Pop Punk",
    "Blink-182": "Pop Punk",
    "Sum 41": "Pop Punk",
    "Yellowcard": "Pop Punk",
    "Relient K": "Pop Punk",
    "Nickelback": "Rock",
    "3 Doors Down": "Rock",
    "Staind": "Rock",
    "Seether": "Rock",
    "Shinedown": "Rock",
    "Breaking Benjamin": "Rock",
    "Lifehouse": "Rock",
    "The Fray": "Rock",
    "Keane": "Rock",
    "Snow Patrol": "Rock",
    "Death Cab for Cutie": "Indie Rock",
    "Modest Mouse": "Indie Rock",
    "Arcade Fire": "Indie Rock",
    "LCD Soundsystem": "Indie Rock",
    "Interpol": "Indie Rock",
    "Spoon": "Indie Rock",
    "Wilco": "Indie Rock",
    "Bright Eyes": "Indie Rock",
    "The Decemberists": "Indie Rock",
    "Sufjan Stevens": "Indie Rock",
    "Iron & Wine": "Indie Rock",
    "Jack Johnson": "Acoustic",
    "Jason Mraz": "Pop",
    
    # Electronic / Dance
    "Daft Punk": "House",
    "The Chemical Brothers": "Electronic",
    "LCD Soundsystem": "Electronic",
    "Goldfrapp": "Electronic",
    "Röyksopp": "Electronic",
    "M.I.A.": "Electronic",
    "Vitalic": "Electronic",
    "Bob Sinclar": "House",
    "David Guetta": "House",
    "Axwell": "House",
    "Tiësto": "Trance",
    "Armin van Buuren": "Trance",
    "Paul van Dyk": "Trance",
    "Deep Dish": "House",
    "Roger Sanchez": "House",
    "Mylo": "Electronic",
    "Digitalism": "Electronic",
    "Justice": "Electronic",
    "Simian Mobile Disco": "Electronic",
    "Hot Chip": "Electronic",
    "Ladytron": "Electronic",
    "Fischerspooner": "Electronic",
    "The Prodigy": "Electronic",
    "Fatboy Slim": "Electronic",
    "Groove Armada": "Electronic",
    "Basement Jaxx": "Electronic",
    "Faithless": "Electronic",
    "Pendulum": "Drum & Bass",
    "Kasabian": "Indie Rock", 
    "Gorillaz": "Hip Hop", # Hybrid

    # R&B / Soul
    "Mariah Carey": "R&B",
    "John Legend": "R&B",
    "Alicia Keys": "R&B",
    "Mary J. Blige": "R&B",
    "Keyshia Cole": "R&B",
    "Fantasia": "R&B",
    "Trey Songz": "R&B",
    "Ne-Yo": "R&B",
    "Chris Brown": "R&B",
    "Omarion": "R&B",
    "Mario": "R&B",
    "Bobby V": "R&B",
    "Pretty Ricky": "R&B",
    "Destiny's Child": "R&B",
    "112": "R&B",
    "Jagged Edge": "R&B",
    "Joss Stone": "Soul",
    "Amy Winehouse": "Soul", # Early stuff
    "Corinne Bailey Rae": "Soul",

    # Country
    "Carrie Underwood": "Country",
    "Keith Urban": "Country",
    "Rascal Flatts": "Country",
    "Brad Paisley": "Country",
    "Kenny Chesney": "Country",
    "Tim McGraw": "Country",
    "Faith Hill": "Country",
    "Sugarland": "Country",
    "Miranda Lambert": "Country",
    "Dierks Bentley": "Country",
    "Big & Rich": "Country",
    "Brooks & Dunn": "Country",
    "George Strait": "Country",
    "Alan Jackson": "Country",
    "Toby Keith": "Country",
    "Trace Adkins": "Country",
    "Gretchen Wilson": "Country",
    "LeAnn Rimes": "Country",
    "Sheryl Crow": "Rock", # Crossover

    # Other / Brazilian
    "Pitty": "Rock",
    "Charlie Brown Jr.": "Rock",
    "CPM 22": "Rock",
    "Detonautas": "Rock",
    "O Rappa": "Rock",
    "Skank": "Pop Rock",
    "Jota Quest": "Pop Rock",
    "Capital Inicial": "Rock",
    "Titãs": "Rock",
    "Paralamas do Sucesso": "Rock",
    "Engenheiros do Hawaii": "Rock",
    "Los Hermanos": "Indie Rock",
    "Nando Reis": "Pop Rock",
    "Lulu Santos": "Pop",
    "Ivete Sangalo": "Axé",
    "Daniela Mercury": "Axé",
    "Claudia Leitte": "Axé",
    "Babado Novo": "Axé",
    "Chiclete com Banana": "Axé",
    "Asa de Águia": "Axé",
    "Zeca Pagodinho": "Samba",
    "Seu Jorge": "MPB",
    "Marisa Monte": "MPB",
    "Vanessa da Mata": "MPB",
    "Maria Rita": "MPB",
    "Ana Carolina": "MPB",
    "Bruno & Marrone": "Sertanejo",
    "Zezé Di Camargo & Luciano": "Sertanejo",
    "Leonardo": "Sertanejo",
    "Daniel": "Sertanejo",

    # Specifics from 2005 list
    "Die Firma": "Hip Hop",
    "Quarashi": "Rap Rock",
    "Lasgo": "Dance",
    "Indochine": "Rock",
    "Smile.dk": "Dance",
    "Shaggy": "Reggae",
    "Glukoza": "Pop",
    "Matisyahu": "Reggae",
    "Sedat": "Pop",
    "Mudvayne": "Metal",
    "Analogfish": "Rock",
    "Juli": "Pop Rock",
    "Vanitas": "Goth",
    "Sara Evans": "Country",
    "Stereophonics": "Rock",
    "Belanova": "Pop",
    "Skin": "Rock",
    "Sisse Marie": "Pop",
    "Low": "Indie Rock",
    "Gregorian": "New Age",
    "PERKiNS": "Rock",
    "Stack$": "Hip Hop",
    "Soilwork": "Metal",
    "Editors": "Indie Rock",
    "Scooter": "Techno",
    "Chenoa": "Pop",
    "Morningwood": "Rock",
    "Olivia": "R&B",
    "Mew": "Indie Rock",
    "Yamboo": "Dance",
    "Muck Sticky": "Hip Hop",
    "Moby": "Electronic",
    "Alamos": "Rock",
    "Extol": "Metal",
    "Taproot": "Metal",
    "Ayumi Hamasaki": "Pop",
    "Orange Range": "Rock",
    "Cormega": "Hip Hop",
    "Ginferno": "Rock",
    "Raptile": "Hip Hop",
    "The Veronicas": "Pop Rock",
    "Shakespear's Sister": "Pop",
    "Buttons": "Pop",
    "Pachanga": "Reggaeton",
    "David Gray": "Folk",
    "Akon": "R&B",
    "RuPaul": "Dance",
    "Grimfist": "Metal",
    "Caparezza": "Hip Hop",
    "DJ Mahay": "Electronic",
    "Tragédie": "R&B",
    "Faker": "Rock",
    "Himsa": "Metal",
    "Celebration": "Rock",
    "Hedley": "Pop Punk",
    "Feist": "Indie Pop",
    "Jem": "Pop",
    "Fever": "Pop",
    "Cæcilie Norby": "Jazz",
    "D!Nation": "Pop",
    "D12": "Hip Hop",
    "DHT": "Dance",
    "DMX": "Hip Hop",
    "Damn Arms": "Rock",
    "Dan Brodie": "Rock",
    "Daniel Hoppe": "Pop",
    "Daniel Küblböck": "Pop",
    "Dark Tranquillity": "Metal",
    "Darren Hayes": "Pop",
    "Datarock": "Electronic",
    "Dave Matthews Band": "Rock",
    "David Banner": "Hip Hop",
    "David Bisbal": "Pop",
    "David Fascher": "Hip Hop",
    "Death By Stereo": "Punk",
    "Death From Above 1979": "Rock",
    "Death In Vegas": "Electronic",
    "Def Leppard": "Rock",
    "Delta Goodrem": "Pop",
    "Demeter": "Rock",
    "Demo": "Pop",
    "Depeche Mode": "Electronic",
    "Despised Icon": "Metal",
    "Devil Sold His Soul": "Metal",
    "Diane": "Pop",
    "Dido": "Pop",
    "Digitata": "Electronic",
    "Dimma": "Rock",
    "Dimmu Borgir": "Metal",
    "Divine Brown": "R&B",
    "Dogs (3)": "Rock",
    "Donell Jones": "R&B",
    "Doreen": "Pop",
    "Doves": "Indie Rock",
    "Down Low": "Hip Hop",
    "Dredg": "Rock",
    "Dropkick Murphys": "Punk",
    "Dwight Yoakam": "Country",
    "E-Dro": "Hip Hop",
    "Earshot": "Rock",
    "Edoardo Bennato": "Rock",
    "Eels": "Indie Rock",
    "Eighteen Visions": "Metal",
    "Eisley": "Indie Rock",
    "Elbow": "Indie Rock",
    "Elisa": "Pop",
    "Elizabeth \"Yummy\" Bingham": "R&B",
    "Elton John": "Pop",
    "Embrace": "Rock",
    "Emmanuel Moire": "Pop",
    "End Of Fashion": "Rock",
    "Enya": "New Age",
    "Epica (2)": "Metal",
    "Erasure": "Pop",
    "Eric Benét": "R&B",
    "Erika Jo": "Country",
    "Ernesto vs. Bastian": "Trance",
    "Eros Ramazzotti": "Pop",
    "Eurythmics": "Pop",
    "Exilia": "Metal",
    "FLOW": "Rock",
    "Faith Evans": "R&B",
    "Fatty Koo": "R&B",
    "Features, The": "Indie Rock",
    "Feeder": "Rock",
    "Fefe Dobson": "Pop Rock",
    "Finch": "Emo",
    "Finley": "Pop Rock",
    "Fiona Apple": "Alternative",
    "Five O'Clock Heroes": "Indie Rock",
    "Fler": "Hip Hop",
    "Flipsyde": "Hip Hop",
    "Floetry": "R&B",
    "Frankie J": "R&B",
    "Freemasons": "House",
    "Frickin' A": "Pop",
    "G. Love": "Hip Hop",
    "GaGaGa SP": "Punk",
    "George Michael": "Pop",
    "Geri Halliwell": "Pop",
    "Gianluca Grignani": "Pop Rock",
    "Gianni Morandi": "Pop",
    "Ginuwine": "R&B",
    "Giorgia (2)": "Pop",
    "Girls In Hawaii": "Indie Rock",
    "Giusy Ferreri": "Pop",
    "Global Deejays": "Dance",
    "Go-Go's": "New Wave",
    "God Forbid": "Metal",
    "Gogol Bordello": "Punk",
    "Goo Goo Dolls": "Rock",
    "Gorefest": "Metal",
    "Gotthard": "Rock",
    "Grandi Animali Marini": "Rock",
    "Gratitude": "Rock",
    "Gretchen Lieberum": "Pop",
    "Groove Coverage": "Dance",
    "Großstadtgeflüster": "Electronic",
    "Guillemots": "Indie Rock",
    "HIM": "Rock",
    "Hard-Fi": "Indie Rock",
    "Heaven Shall Burn": "Metal",
    "Helloween": "Metal",
    "Hope Partlow": "Pop",
    "Hot Apple Pie": "Country",
    "Hot Hot Heat": "Indie Rock",
    "Hyon Song-wol": "Pop",
    "I Melt": "Pop",
    "Imogen Heap": "Pop",
    "Impaled": "Metal",
    "In Flames": "Metal",
    "Incubus": "Rock",
    "India.Arie": "R&B",
    "Institute": "Rock",
    "Irene Grandi": "Pop",
    "J-Kwon": "Hip Hop",
    "JDiggz": "Hip Hop",
    "Ja Rule": "Hip Hop",
    "Jack Ladder": "Indie Rock",
    "Jaguar Wright": "R&B",
    "Jaheim": "R&B",
    "Jakalope": "Pop",
    "Jamie Cullum": "Jazz",
    "Jamie Foxx": "R&B",
    "Jamie Shaw": "Pop",
    "Jamiroquai": "Funk",
    "Jeanette": "Pop",
    "Jeezy": "Hip Hop",
    "Jeff Bates (2)": "Country",
    "Jermaine Dupri": "Hip Hop",
    "Jessica Simpson": "Pop",
    "Jimmy Eat World": "Emo",
    "Jimmy Edgar": "Electronic",
    "Joana Zimmer": "Pop",
    "Joe Nichols": "Country",
    "John Frusciante": "Rock",
    "Jonas Brothers": "Pop Rock",
    "Josh Kelley": "Pop Rock",
    "Josh Pyke": "Indie Rock",
    "Josh Turner": "Country",
    "Joy Electric": "Electronic",
    "Juanes": "Latin",
    "Jully Black": "R&B",
    "Justin Hawkins": "Rock",
    "KT Tunstall": "Pop Rock",
    "Kamelot": "Metal",
    "Kate Bush": "Alternative",
    "Katrina Elam": "Country",
    "Katy Perry": "Pop",
    "Keisha White": "R&B",
    "Kelly Osbourne": "Pop Rock",
    "Kent": "Rock",
    "Keren Ann": "Pop",
    "Kidz Bop Kids": "Pop",
    "Killer Mike": "Hip Hop",
    "Kings Of Leon": "Rock",
    "Koufax": "Indie Rock",
    "Kreator": "Metal",
    "Kristin Chenoweth": "Pop",
    "Krypteria": "Metal",
    "Kyo": "Rock",
    "L'Aura": "Pop",
    "L.O.C.": "Hip Hop",
    "LAB (2)": "Rock",
    "La Fouine": "Hip Hop",
    "LaLaine": "Pop",
    "Lacrimosa": "Goth",
    "Lamb Of God": "Metal",
    "Laura Bono": "Pop",
    "Laura Pausini": "Pop",
    "Le Tigre": "Electronic",
    "Le Vibrazioni": "Pop Rock",
    "Leela James": "R&B",
    "Lemar": "R&B",
    "Leonard Cohen": "Folk",
    "Les Fils de Teuphu": "Ska",
    "Life Of Agony": "Metal",
    "Ligabue": "Rock",
    "Lil Rob": "Hip Hop",
    "Limp Bizkit": "Nu Metal",
    "Linea 77": "Metal",
    "Liquido": "Rock",
    "Lisa Marie Presley": "Pop Rock",
    "Lisa Stansfield": "R&B",
    "Living Things": "Rock",
    "Liz Phair": "Rock",
    "Loredana Bertè": "Pop",
    "Los Tigres Del Norte": "Latin",
    "Lostprophets": "Rock",
    "Louis Bertignac": "Rock",
    "Louis XIV": "Rock",
    "Lucie Silvas": "Pop",
    "Lud (2)": "Rock",
    "Luis Fonsi": "Latin",
    "Luke Temple": "Folk",
    "M83": "Electronic",
    "Madness": "Ska",
    "Madsen": "Rock",
    "Mai Kuraki": "Pop",
    "Maksim": "Pop",
    "Mambassa": "Rock",
    "Manic Street Preachers": "Rock",
    "Manntis": "Metal",
    "Marc Tenezi": "Pop",
    "Marc Terenzi": "Pop",
    "Maria Mena": "Pop",
    "Marius Müller-Westernhagen": "Rock",
    "Marjorie Fair": "Indie Rock",
    "Mark Morrison": "R&B",
    "Mark Ronson": "Pop",
    "Marlene Kuntz": "Rock",
    "Mashonda": "R&B",
    "Master P": "Hip Hop",
    "Masterplan (2)": "Metal",
    "Max Pezzali": "Pop",
    "Maxim": "Electronic",
    "Maxïmo Park": "Indie Rock",
    "Maya Saban": "Pop",
    "Mazzy Star": "Alternative",
    "McQueen": "Rock",
    "Megan McCauley": "Rock",
    "Melanie C": "Pop",
    "Melissa Etheridge": "Rock",
    "Mellowtoy": "Metal",
    "Ment2B": "Pop",
    "Meshuggah": "Metal",
    "Mest": "Pop Punk",
    "Metric": "Indie Rock",
    "Mia-Sophie": "Pop",
    "Michael W. Smith": "Pop",
    "Mike Doughty": "Rock",
    "Mike Watt": "Rock",
    "Millencolin": "Punk",
    "Mindless Self Indulgence": "Electronic",
    "Mobb Deep": "Hip Hop",
    "Mobile": "Rock",
    "Momus": "Pop",
    "Montgomery Gentry": "Country",
    "Morcheeba": "Electronic",
    "Ms Dynamite": "Hip Hop",
    "Murs & 9th Wonder": "Hip Hop",
    "Muse": "Rock",
    "MxPx": "Pop Punk",
    "My Morning Jacket": "Indie Rock",
    "Mötley Crüe": "Rock",
    "Napalm Death": "Metal",
    "Natalia y La Forquetina": "Pop Rock",
    "Neal McCoy": "Country",
    "Negrita": "Rock",
    "Nek": "Pop",
    "Nena": "Pop",
    "Nephew": "Rock",
    "Nevermore": "Metal",
    "New Order": "Electronic",
    "New Years Day": "Rock",
    "Nightwish": "Metal",
    "Nikki Flores": "Pop",
    "No Address": "Rock",
    "Nocturnal Rites": "Metal",
    "North Of Ping Pong": "Rock",
    "OK Go": "Indie Rock",
    "Of Montreal": "Indie Rock",
    "Offlaga Disco Pax": "Electronic",
    "Okay": "Pop",
    "Olly Meets the Good Fellas": "Jazz",
    "One Chance": "R&B",
    "Opeth": "Metal",
    "Otto Ohm": "Pop",
    "Our Lady Peace": "Rock",
    "Out Hud": "Electronic",
    "Outlandish": "Hip Hop",
    "Overground": "Pop",
    "P.O.S.": "Hip Hop",
    "POETS & PORNSTARS": "Rock",
    "Paola & Chiara": "Pop",
    "Papa Roach": "Rock",
    "Paradise Lost": "Metal",
    "Patrice": "Reggae",
    "Patrick Wolf": "Indie Rock",
    "Paul Brandt": "Country",
    "Paul Cless": "R&B",
    "Paul McCartney": "Rock",
    "Paul Weller": "Rock",
    "Paulina Rubio": "Latin",
    "Pauline": "Pop",
    "Pendulum (3)": "Drum & Bass",
    "Persephone's Bees": "Indie Rock",
    "Perturbazione": "Pop Rock",
    "Peter Kay": "Pop",
    "Piero Pelù": "Rock",
    "Pillar": "Rock",
    "Pink": "Pop",
    "Plain White T's": "Pop Rock",
    "Planet Funk": "Electronic",
    "Platinum Weird": "Pop",
    "Polly Scattergood": "Electronic",
    "Pras Michel": "Hip Hop",
    "Prime Circle": "Rock",
    "Prince": "Funk",
    "Queen Latifah": "Hip Hop",
    "Quicksand (3)": "Rock",
    "R. Kelly": "R&B",
    "Rachel Stevens": "Pop",
    "Rammstein": "Metal",
    "Rapsoul": "Hip Hop",
    "Ray J": "R&B",
    "Razorlight": "Indie Rock",
    "Readers Wifes": "Electronic",
    "Reba McEntire": "Country",
    "Red Cafe": "Hip Hop",
    "Richard Ashcroft": "Rock",
    "Ricki-Lee": "Pop",
    "Ricky Martin": "Latin",
    "Rico Love": "R&B",
    "Rilo Kiley": "Indie Rock",
    "Ringside": "Indie Rock",
    "Rinôçérôse": "Electronic",
    "Rob Thomas": "Pop Rock",
    "Robert Plant": "Rock",
    "Robin Thicke": "R&B",
    "Robyn": "Pop",
    "Rod Stewart": "Rock",
    "Rogue Traders": "Electronic",
    "Rooster": "Rock",
    "Roxing Kafe": "Rock",
    "Roy Paci & Aretuska": "Ska",
    "Ryan Cabrera": "Pop",
    "Róisín Murphy": "Electronic",
    "SIA": "Pop",
    "Sage Francis": "Hip Hop",
    "Sahara Hotnights": "Rock",
    "Sanalejo": "Pop Rock",
    "Santana": "Rock",
    "Sarah Connor": "Pop",
    "Sarah McLachlan": "Pop",
    "Schiller": "Electronic",
    "Scott Stapp": "Rock",
    "Sentenced": "Metal",
    "Seventh Day Slumber": "Rock",
    "She Wants Revenge": "Indie Rock",
    "Sheryl Crow": "Pop Rock",
    "Sigur Rós": "Post-Rock",
    "Silbermond": "Pop Rock",
    "Simple Minds": "Rock",
    "Simply Red": "Pop",
    "Skindred": "Metal",
    "Sleater-Kinney": "Rock",
    "Smitty": "Hip Hop",
    "Smog": "Indie Rock",
    "Social State Revival": "Rock",
    "Soho (2)": "Pop",
    "Sopor Aeternus & The Ensemble Of Shadows": "Goth",
    "Speedy (7)": "Pop",
    "Spiderbait": "Rock",
    "Spike": "Pop",
    "Spleen United": "Electronic",
    "Stan Ridgway": "Rock",
    "Stance Punks": "Punk",
    "Starsailor": "Rock",
    "Static-X": "Metal",
    "Stephen Fretwell": "Folk",
    "Stephen Malkmus": "Indie Rock",
    "Steven Seagal": "Blues",
    "Stevie Wonder": "R&B",
    "Stewie": "Pop",
    "StoneBridge": "House",
    "Story Of The Year": "Emo",
    "Strapping Young Lad": "Metal",
    "Styles P": "Hip Hop",
    "Styx": "Rock",
    "Subsonica": "Electronic",
    "Super Elastic Bubble Plastic": "Rock",
    "Super Furry Animals": "Indie Rock",
    "Superbus (2)": "Pop Rock",
    "Supergrass": "Rock",
    "Sweetbox": "Pop",
    "Switchfoot": "Rock",
    "Syleena Johnson": "R&B",
    "Syria": "Pop",
    "Sébastien Tellier": "Electronic",
    "T-Pain": "Hip Hop",
    "Talib Kweli": "Hip Hop",
    "Tamara Jaber": "Pop",
    "Teairra Marí": "R&B",
    "Team Sleep": "Rock",
    "Terri Clark": "Country",
    "Texas": "Pop Rock",
    "Thalía": "Latin",
    "The 88": "Indie Rock",
    "The Afters": "Rock",
    "The Boat People": "Indie Rock",
    "The BossHoss": "Country",
    "The Brand New Heavies": "Funk",
    "The Bravery": "Indie Rock",
    "The Cat Empire": "Ska",
    "The Dandy Warhols": "Indie Rock",
    "The Darkness": "Rock",
    "The Dead 60s": "Rock",
    "The Dillinger Escape Plan": "Metal",
    "The Donnas": "Rock",
    "The Futureheads": "Indie Rock",
    "The Haunted": "Metal",
    "The Heights": "Rock",
    "The Hives": "Rock",
    "The Juan Maclean": "Electronic",
    "The Knife": "Electronic",
    "The Kooks": "Indie Rock",
    "The Lonely Island": "Comedy",
    "The Mountain Goats": "Indie Rock",
    "The National": "Indie Rock",
    "The New Pornographers": "Indie Rock",
    "The Notorious B.I.G.": "Hip Hop",
    "The Offspring": "Punk",
    "The Polyphonic Spree": "Pop",
    "The Postal Service": "Electronic",
    "The Presets": "Electronic",
    "The Presidents Of The United States Of America": "Rock",
    "The Rasmus": "Rock",
    "The Redwalls": "Rock",
    "The Ruby Suns": "Indie Rock",
    "The Starting Line": "Pop Punk",
    "The Subways": "Indie Rock",
    "The Sunshine": "Pop",
    "The Tears": "Rock",
    "The Used": "Emo",
    "The Wallflowers": "Rock",
    "The Warlocks": "Rock",
    "Thirteen Senses": "Indie Rock",
    "Thrice": "Post-Hardcore",
    "Tiga": "Electronic",
    "Tina Arena": "Pop",
    "Tiromancino": "Pop Rock",
    "Tiziano Ferro": "Pop",
    "Tokio Hotel": "Pop Rock",
    "Tom Novy": "House",
    "Tomoyasu Hotei": "Rock",
    "Toni Braxton": "R&B",
    "Tony Yayo": "Hip Hop",
    "Tori Amos": "Alternative",
    "Tre Allegri Ragazzi Morti": "Indie Rock",
    "Trick Daddy": "Hip Hop",
    "Trina": "Hip Hop",
    "Trisha Yearwood": "Country",
    "Tsunami Relief": "Pop",
    "Tupelo Honey": "Rock",
    "Turin Brakes": "Indie Rock",
    "Tycho": "Electronic",
    "Tyler James": "R&B",
    "U.D.O. (2)": "Metal",
    "UB40": "Reggae",
    "US 5": "Pop",
    "Udo Lindenberg": "Rock",
    "Umbrella Bed": "Ska",
    "Uncle Kracker": "Rock",
    "Underoath": "Post-Hardcore",
    "Unwritten Law": "Punk",
    "Urbi & Orbi": "Pop",
    "Utada Hikaru": "Pop",
    "Valli Girls": "Pop",
    "Velvet (2)": "Dance",
    "Velvet Revolver": "Rock",
    "Vertical Horizon": "Rock",
    "Vitas": "Pop",
    "Warren G": "Hip Hop",
    "Watch Them Die": "Metal",
    "West Indian Girl": "Rock",
    "White Rose Movement": "Indie Rock",
    "Will Young": "Pop",
    "Willie Nelson": "Country",
    "Wir Sind Helden": "Pop Rock",
    "Within Temptation": "Metal",
    "Xiu Xiu": "Experimental",
    "Yoko Ono": "Experimental",
    "Young Buck": "Hip Hop",
    "Young Knives, The": "Indie Rock",
    "Zap Mama": "World",
    "Zed Yago": "Metal",
    "Zeraphine": "Goth",
    "Zwan": "Rock",
    "a-ha": "Pop",
}

def enrich_data():
    try:
        # Load the existing data
        with open('data/2005.json', 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        updated_count = 0
        
        # Iterate through the data and update genres
        for video in data:
            # Handle key migration: artist_name -> artist
            artist_name = video.get('artist_name') or video.get('artist')
            
            if not artist_name:
                continue
                
            # Normalize to 'artist' key
            if 'artist_name' in video:
                del video['artist_name']
            video['artist'] = artist_name

            # Check if we have a genre mapping for this artist
            # Try exact match first
            if artist_name in ARTIST_GENRES:
                video['artist_genre'] = ARTIST_GENRES[artist_name]
                updated_count += 1
            else:
                # Try simple variations (case insensitive)
                found = False
                artist_name_str = str(artist_name).lower()
                for mapped_artist, genre in ARTIST_GENRES.items():
                    if str(mapped_artist).lower() == artist_name_str:
                        video['artist_genre'] = genre
                        updated_count += 1
                        found = True
                        break
                
                # If still not found, leave as is (likely "Desconhecido") or maybe try partial matches if strictly needed,
                # but for now we stick to the explicit map to avoid bad data.
        
        # Save the updated data back to the file
        with open('data/2005.json', 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=4, ensure_ascii=False)
            
        print(f"Successfully updated {updated_count} videos in data/2005.json")
        
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    enrich_data()
