import json

def enrich_genres(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    genre_map = {
        "50 Cent": "Hip-Hop",
        "AFI": "Punk Rock",
        "ATB": "Trance",
        "Aaliyah": "R&B",
        "Adema": "Nu Metal",
        "Against Me!": "Punk Rock",
        "Akercocke": "Black Metal",
        "Alkaline Trio": "Punk Rock",
        "Amy Studt": "Pop",
        "Amy Winehouse": "Soul",
        "Ana Johnsson": "Pop Rock",
        "Andre 3000": "Hip-Hop",
        "Angie Stone": "R&B",
        "Annie Lennox": "Pop",
        "Anthrax": "Thrash Metal",
        "Appleton": "Pop",
        "Arch Enemy": "Melodic Death Metal",
        "Ashanti": "R&B",
        "Atomic Kitten": "Pop",
        "Audioslave": "Rock",
        "Audiover": "Rock", # typo in source maybe? assuming Audiovent
        "Audiobullys": "Electronic",
        "Avril Lavigne": "Pop Punk",
        "B2K": "R&B",
        "Baby Bash": "Hip-Hop",
        "Basement Jaxx": "House",
        "Beenie Man": "Reggae",
        "Ben Harper": "Folk Rock",
        "Ben Moody": "Rock",
        "Benny Benassi": "House",
        "Beyoncé": "R&B / Pop",
        "Big Tymers": "Hip-Hop",
        "Billy Talent": "Punk Rock",
        "Black Rebel Motorcycle Club": "Garage Rock",
        "Black Eyed Peas": "Hip-Hop / Pop",
        "Blink-182": "Pop Punk",
        "Blondie": "New Wave",
        "Blu Cantrell": "R&B",
        "Blue Man Group": "Experimental",
        "Blur": "Britpop",
        "Bone Thugs-N-Harmony": "Hip-Hop",
        "Bon Jovi": "Rock",
        "Boomkat": "Pop",
        "Bowling For Soup": "Pop Punk",
        "Brand New": "Emo",
        "Britney Spears": "Pop",
        "Bubba Sparxxx": "Hip-Hop",
        "Busta Rhymes": "Hip-Hop",
        "Busted": "Pop Punk",
        "Café Tacvba": "Alternative",
        "Caldwell": "R&B",
        "Cali": "Chanson",
        "Cassidy": "Hip-Hop",
        "Cat Power": "Indie Rock",
        "Cave In": "Metalcore",
        "Cesária Évora": "World",
        "Chingy": "Hip-Hop",
        "Christina Aguilera": "Pop",
        "Clay Aiken": "Pop",
        "Coldplay": "Alternative Rock",
        "Common": "Hip-Hop",
        "Craig David": "R&B",
        "Daddy Yankee": "Reggaeton",
        "Dawe": "Hip-Hop",
        "Daft Punk": "House",
        "Damien Rice": "Folk",
        "Daniel Bedingfield": "Pop",
        "Danni Minogue": "Pop",
        "Darkness, The": "Glam Rock",
        "Dashboard Confessional": "Emo",
        "Dave Matthews": "Rock",
        "David Bowie": "Rock",
        "David Guetta": "House",
        "Deftones": "Alternative Metal",
        "Delta Goodrem": "Pop",
        "Dido": "Pop",
        "Dima Bilan": "Pop",
        "Dizzee Rascal": "Grime",
        "Dj Tiesto": "Trance",
        "Donnas, The": "Rock",
        "Duran Duran": "New Wave",
        "E-40": "Hip-Hop",
        "Eels": "Indie Rock",
        "Electric Six": "Garage Rock",
        "Elephant Man": "Dancehall",
        "Enrique Iglesias": "Latin Pop",
        "Evanescence": "Rock / Goth",
        "Eve": "Hip-Hop",
        "Fabolous": "Hip-Hop",
        "Fall Out Boy": "Pop Punk",
        "Fat Joe": "Hip-Hop",
        "Fatman Scoop": "Hip-Hop",
        "Feeder": "Rock",
        "Felix da Housecat": "House",
        "Finger Eleven": "Alternative Rock",
        "Fountains Of Wayne": "Power Pop",
        "Four Tet": "Electronic",
        "Franz Ferdinand": "Indie Rock",
        "Freya": "Pop",
        "Fuel": "Post-Grunge",
        "Funeral For A Friend": "Post-Hardcore",
        "G-Unit": "Hip-Hop",
        "Gareth Gates": "Pop",
        "Gary Allan": "Country",
        "Gavin DeGraw": "Pop Rock",
        "George Michael": "Pop",
        "Ginuwine": "R&B",
        "Girls Aloud": "Pop",
        "Godsmack": "Nu Metal",
        "Goldfrapp": "Electronic",
        "Good Charlotte": "Pop Punk",
        "Goo Goo Dolls": "Alternative Rock",
        "Gorillaz": "Alternative",
        "Gossip": "Indie Rock",
        "Grandaddy": "Indie Rock",
        "Groove Coverage": "Eurodance",
        "Guano Apes": "Alternative Rock",
        "H.I.M.": "Gothic Rock",
        "HIM": "Gothic Rock",
        "Hatebreed": "Metalcore",
        "Hayley Westenra": "Classical Crossover",
        "Hilary Duff": "Pop",
        "Hoobastank": "Rock",
        "Hot Hot Heat": "Indie Rock",
        "Howie Day": "Pop Rock",
        "I Am Kloot": "Indie Rock",
        "Iceman": "Hip-Hop",
        "Ill Niño": "Nu Metal",
        "Interpol": "Post-Punk Revival",
        "Iron Maiden": "Heavy Metal",
        "J-Kwon": "Hip-Hop",
        "Ja Rule": "Hip-Hop",
        "Jack Johnson": "Folk Rock",
        "Jamelia": "R&B",
        "Jamie Cullum": "Jazz Pop",
        "Jane's Addiction": "Alternative Rock",
        "Jason Mraz": "Pop Rock",
        "Jay-Z": "Hip-Hop",
        "Jennifer Lopez": "Pop / R&B",
        "Jessica Simpson": "Pop",
        "Jet": "Rock",
        "Jewel": "Folk / Pop",
        "Joe Budden": "Hip-Hop",
        "John Mayer": "Pop Rock",
        "Johnny Cash": "Country",
        "JoJo": "R&B / Pop",
        "Josh Groban": "Pop",
        "Joss Stone": "Soul",
        "Juanes": "Latin Pop",
        "Junior Senior": "Pop",
        "Justin Timberlake": "Pop",
        "Kanye West": "Hip-Hop",
        "Kasabian": "Indie Rock",
        "Katharine McPhee": "Pop",
        "Katie Melua": "Jazz / Pop",
        "Keith Urban": "Country",
        "Kelis": "R&B",
        "Kelly Clarkson": "Pop Rock",
        "Kelly Rowland": "R&B",
        "Kenny Chesney": "Country",
        "Kid Rock": "Rock / Hip-Hop",
        "Killing Joke": "Post-Punk",
        "Kings Of Leon": "Rock",
        "Kinky": "Electronic",
        "KoRn": "Nu Metal",
        "Korn": "Nu Metal",
        "Kylie Minogue": "Pop",
        "L.P.": "Pop Rock",
        "LCD Soundsystem": "Dance-Punk",
        "LL Cool J": "Hip-Hop",
        "Lacuna Coil": "Gothic Metal",
        "Lamb of God": "Groove Metal",
        "Lasgo": "Trance",
        "Lemar": "R&B",
        "Lenny Kravitz": "Rock",
        "Less Than Jake": "Ska Punk",
        "Lil Jon": "Hip-Hop",
        "Lil' Kim": "Hip-Hop",
        "Limp Bizkit": "Nu Metal",
        "Linkin Park": "Nu Metal",
        "Live": "Alternative Rock",
        "Lostprophets": "Rock",
        "Ludacris": "Hip-Hop",
        "Lumidee": "R&B",
        "M.O.P.": "Hip-Hop",
        "M83": "Electronic",
        "Madonna": "Pop",
        "Mando Diao": "Indie Rock",
        "Marilyn Manson": "Industrial Metal",
        "Mark Ronson": "Pop / Production",
        "Maroon 5": "Pop Rock",
        "Mary J. Blige": "R&B",
        "Massive Attack": "Trip Hop",
        "Matchbox Twenty": "Alternative Rock",
        "Matt Nathanson": "Folk Rock",
        "Mayday Parade": "Pop Punk",
        "Melissa Etheridge": "Rock",
        "Metallica": "Heavy Metal",
        "Michael Bublé": "Jazz / Pop",
        "Michael Jackson": "Pop",
        "Michelle Branch": "Pop Rock",
        "Misfits": "Punk Rock",
        "Missy Elliott": "Hip-Hop",
        "Moby": "Electronic",
        "Moloko": "Electronic",
        "Monica": "R&B",
        "Morcheeba": "Trip Hop",
        "Muse": "Alternative Rock",
        "Musiq": "R&B",
        "My Chemical Romance": "Emo / Rock",
        "N.E.R.D.": "Hip-Hop / Rock",
        "Natalie Imbruglia": "Pop Rock",
        "Natasha Bedingfield": "Pop",
        "Nelly": "Hip-Hop",
        "Nelly Furtado": "Pop",
        "New Found Glory": "Pop Punk",
        "Nickelback": "Post-Grunge",
        "Nightwish": "Symphonic Metal",
        "No Doubt": "Ska / Pop",
        "Norah Jones": "Jazz / Pop",
        "O.A.R.": "Rock",
        "Obie Trice": "Hip-Hop",
        "Ocean Colour Scene": "Britpop",
        "Offspring, The": "Punk Rock",
        "Ok Go": "Indie Rock",
        "OutKast": "Hip-Hop",
        "Outlandish": "Hip-Hop",
        "Owl City": "Electronica", # Maybe too early? Check existence in 2003
        "P.O.D.": "Nu Metal",
        "Panjabi MC": "Bhangra",
        "Papa Roach": "Nu Metal",
        "Passenger": "Folk Rock",
        "Paul Oakenfold": "Trance",
        "Paul van Dyk": "Trance",
        "Pearl Jam": "Grunge",
        "Pennywise": "Punk Rock",
        "Pet Shop Boys": "Synthpop",
        "Peter Gabriel": "Rock",
        "Pharrell Williams": "Hip-Hop",
        "Pink": "Pop",
        "Placebo": "Alternative Rock",
        "Plump DJs": "Breakbeat",
        "Puddle Of Mudd": "Post-Grunge",
        "Pulp": "Britpop",
        "R. Kelly": "R&B",
        "Rachel Stevens": "Pop",
        "Radiohead": "Alternative Rock",
        "Rancid": "Punk Rock",
        "Rascal Flatts": "Country",
        "Red Hot Chili Peppers": "Funk Rock",
        "Reel Big Fish": "Ska Punk",
        "Relient K": "Pop Punk",
        "Ricky Martin": "Latin Pop",
        "Robbie Williams": "Pop",
        "Robert Randolph & The Family Band": "Funk / Soul",
        "Rooney": "Indie Rock",
        "Rosie Thomas": "Folk",
        "Röyksopp": "Electronic",
        "Rufus Wainwright": "Baroque Pop",
        "Ryan Adams": "Alt-Country",
        "S Club 8": "Pop",
        "Saliva": "Nu Metal",
        "Santana": "Rock",
        "Sarah McLachlan": "Pop",
        "Saves The Day": "Emo",
        "Sean Paul": "Dancehall",
        "Seal": "R&B / Soul",
        "Seether": "Post-Grunge",
        "Sense Field": "Emo",
        "Sepultura": "Metal",
        "Shaggy": "Reggae",
        "Shakira": "Latin Pop",
        "Shania Twain": "Country",
        "Sheryl Crow": "Rock",
        "Simple Plan": "Pop Punk",
        "Simply Red": "Soul",
        "Sister Hazel": "Alternative Rock",
        "Skinny Puppy": "Industrial",
        "Skillet": "Christian Rock",
        "Slayer": "Thrash Metal",
        "Smash Mouth": "Pop Rock",
        "Smile Empty Soul": "Post-Grunge",
        "Snoop Dogg": "Hip-Hop",
        "Snow Patrol": "Indie Rock",
        "Sophie Ellis-Bextor": "Pop / Disco",
        "Soulfly": "Metal",
        "Spitalfield": "Emo",
        "Stacie Orrico": "Pop",
        "Staind": "Post-Grunge",
        "Starsailor": "Indie Rock",
        "Static-X": "Industrial Metal",
        "Stereophonics": "Rock",
        "Steveopia": "Unknown",
        "Sting": "Rock",
        "Stone Sour": "Hard Rock",
        "Story of the Year": "Post-Hardcore",
        "Sugababes": "Pop",
        "Sugar Ray": "Pop Rock",
        "Sugarcult": "Pop Punk",
        "Sum 41": "Pop Punk",
        "Super Furry Animals": "Indie Rock",
        "Switchfoot": "Alternative Rock",
        "System of a Down": "Nu Metal",
        "T.I.": "Hip-Hop",
        "TLC": "R&B",
        "Taking Back Sunday": "Emo",
        "Talib Kweli": "Hip-Hop",
        "Tatu": "Pop",
        "Tears For Fears": "New Wave",
        "Tenacious D": "Comedy Rock",
        "Terror Squad": "Hip-Hop",
        "The All-American Rejects": "Pop Punk",
        "The Ataris": "Pop Punk",
        "The Avalanches": "Electronic",
        "The Black Eyed Peas": "Hip-Hop / Pop",
        "The Blood Brothers": "Post-Hardcore",
        "The Bouncing Souls": "Punk Rock",
        "The Calling": "Rock",
        "The Chemical Brothers": "Big Beat",
        "The Cooper Temple Clause": "Alternative Rock",
        "The Coral": "Indie Rock",
        "The Creatures": "Post-Punk",
        "The Dandy Warhols": "Alternative Rock",
        "The Darkness": "Glam Rock",
        "The Datsuns": "Hard Rock",
        "The Distillers": "Punk Rock",
        "The Donnas": "Rock",
        "The Dresden Dolls": "My Dark Cabaret",
        "The Exies": "Rock",
        "The Flaming Lips": "Neo-Psychedelia",
        "The Gathering": "Alternative Rock",
        "The Hives": "Garage Rock",
        "The Isley Brothers": "R&B / Soul",
        "The Knife": "Electronic",
        "The Libertines": "Indie Rock",
        "The Living End": "Punk Rock",
        "The Mars Volta": "Progressive Rock",
        "The Music": "Rock",
        "The Neptune": "Production",
        "The New Pornographers": "Indie Rock",
        "The Nudie Suits": "Indie Rock",
        "The Offspring": "Punk Rock",
        "The Polyphonic Spree": "Choral Rock",
        "The Postal Service": "Indie Pop",
        "The Rapture": "Dance-Punk",
        "The Raveonettes": "Indie Rock",
        "The Rolling Stones": "Rock",
        "The Roots": "Hip-Hop",
        "The Shins": "Indie Rock",
        "The Sounds": "New Wave",
        "The Starting Line": "Pop Punk",
        "The Streets": "UK Garage",
        "The Strokes": "Indie Rock",
        "The Ten Tenors": "Classical Crossover",
        "The Thermals": "Indie Rock",
        "The Thrills": "Indie Rock",
        "The Tokey Tones": "Indie Pop",
        "The Tragically Hip": "Rock",
        "The Used": "Post-Hardcore",
        "The Vines": "Garage Rock",
        "The White Stripes": "Garage Rock",
        "Thirteen Senses": "Indie Rock",
        "Thorns, The": "Rock",
        "Three Days Grace": "Rock",
        "Thrice": "Post-Hardcore",
        "Thursday": "Post-Hardcore",
        "Timbaland": "Hip-Hop",
        "Tina Arena": "Pop",
        "Toby Keith": "Country",
        "Tom Jones": "Pop",
        "Tommi": "Pop",
        "Toni Braxton": "R&B",
        "Toni Cottura": "Eurodance",
        "Traci Lords": "Electronic",
        "Tracy Chapman": "Folk",
        "Train": "Pop Rock",
        "Travis": "Britpop",
        "Travis Tritt": "Country",
        "Tragédie": "R&B",
        "Triple 8": "Pop",
        "Triple Image": "Pop",
        "Turbonegro": "Punk Rock",
        "Turin Brakes": "Indie Folk",
        "Twista": "Hip-Hop",
        "Type O Negative": "Gothic Metal",
        "Tyrese": "R&B",
        "Télépopmusik": "Electronic",
        "U.N.K.L.E.": "Electronic",
        "UNKLE": "Electronic",
        "UPA Dance": "Pop",
        "Umbrella Bed": "Ska",
        "Uncle Kracker": "Rock / Country",
        "Usher": "R&B",
        "Utada Hikaru": "J-Pop",
        "Velhas Virgens": "Rock",
        "Velvet (2)": "Pop",
        "Velvet Revolver": "Hard Rock",
        "Vendetta Red": "Emo",
        "Vengaboys": "Eurodance",
        "Verbena": "Alternative Rock",
        "Victoria Beckham": "Pop",
        "Vince Gill": "Country",
        "Vitas": "Pop",
        "Waikiki": "Rock",
        "Wannadies, The": "Indie Pop",
        "Watch Them Die": "Metal",
        "Wayne Wonder": "Reggae",
        "Weird Al Yankovic": "Comedy",
        "Westlife": "Pop",
        "Westside Connection": "Hip-Hop",
        "Wheatus": "Pop Rock",
        "White Stripes": "Garage Rock",
        "Whitney Houston": "R&B",
        "Will Young": "Pop",
        "Within Temptation": "Symphonic Metal",
        "Wyclef Jean": "Hip-Hop",
        "Yeah Yeah Yeahs": "Indie Rock",
        "Yello": "Electronic",
        "Yellowcard": "Pop Punk",
        "Young Gunz": "Hip-Hop",
        "Zwan": "Alternative Rock",
        "a-ha": "Pop",
        "iiO": "Electronic",
        "t.A.T.u.": "Pop"
    }

    for entry in data:
        artist_name = entry.get('artist_name')
        if artist_name in genre_map:
            entry['artist_genre'] = genre_map[artist_name]
        elif entry.get('artist_genre') == 'Desconhecido':
             # pass
             pass

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    enrich_genres('data/2003.json')
