import json

def enrich_genres(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    genre_map = {
        "30 Seconds To Mars": "Rock",
        "3OH!3": "Electronic Pop",
        "A Fine Frenzy": "Indie Pop",
        "A Place To Bury Strangers": "Shoegaze",
        "A-Trak": "Electronic",
        "AC/DC": "Rock",
        "AFI": "Punk Rock",
        "AaRON": "Alternative Rock",
        "Abingdon Boys School": "J-Rock",
        "Above & Beyond": "Trance",
        "Academy Is..., The": "Pop Punk",
        "Ace Enders and A Million Different People": "Pop Rock",
        "Across Five Aprils": "Post-Hardcore",
        "Adam Lambert": "Pop Rock",
        "Adaya": "World",
        "Adele": "Soul",
        "Aesop Rock": "Hip-Hop",
        "Against Me!": "Punk Rock",
        "Agnes": "Pop",
        "Air": "Electronic",
        "Airborne Toxic Event, The": "Indie Rock",
        "Akala": "Hip-Hop",
        "Akon": "R&B",
        "Alain Bashung": "Chanson",
        "Alanis Morissette": "Alternative Rock",
        "Alborosie": "Reggae",
        "Alejandro Sanz": "Latin Pop",
        "Alela Diane": "Folk",
        "Alesha Dixon": "R&B",
        "Alexisonfire": "Post-Hardcore",
        "Ali Ali": "Unknown",
        "Ali Project": "Dark Wave",
        "Alicia Keys": "R&B / Soul",
        "Alien Ant Farm": "Nu Metal",
        "Alizée": "Pop",
        "All Time Low": "Pop Punk",
        "All-American Rejects, The": "Pop Punk",
        "Aloe Blacc": "Soul",
        "Alphabeat": "Pop",
        "Aly & AJ": "Pop Rock",
        "Amarasri": "Unknown",
        "American Princes": "Indie Rock",
        "Amerie": "R&B",
        "Amon Amarth": "Melodic Death Metal",
        "Amy MacDonald": "Folk Rock",
        "Amy Studt": "Pop",
        "Amy Winehouse": "Soul / R&B",
        "Ana Johnsson": "Pop Rock",
        "Anberlin": "Alternative Rock",
        "And One": "Synthpop",
        "Andrew Bird": "Indie Folk",
        "Angels & Airwaves": "Rock",
        "Ani DiFranco": "Folk",
        "Animal Collective": "Experimental Pop",
        "Anita O'Day": "Jazz",
        "Anna Tsuchiya": "J-Rock",
        "Annie Lennox": "Pop",
        "Antony and the Johnsons": "Chamber Pop",
        "Apocalyptica": "Symphonic Metal",
        "Apples In Stereo": "Indie Pop",
        "Arcade Fire": "Indie Rock",
        "Arch Enemy": "Melodic Death Metal",
        "Architecture In Helsinki": "Indie Pop",
        "Arctic Monkeys": "Indie Rock",
        "Armin van Buuren": "Trance",
        "Army Of Anyone": "Rock",
        "Arsenium": "Pop",
        "Arsonists Get All The Girls": "Deathcore",
        "As I Lay Dying": "Metalcore",
        "Ash": "Indie Rock",
        "Ashlee Simpson": "Pop Rock",
        "Ashley Tisdale": "Pop",
        "Asian Kung-Fu Generation": "J-Rock",
        "Asobi Seksu": "Shoegaze",
        "Atmosphere": "Hip-Hop",
        "Atreyu": "Metalcore",
        "Atwood": "Unknown",
        "Audio Bullys": "Electronic",
        "Augustana": "Pop Rock",
        "Autechre": "Electronic",
        "Avenged Sevenfold": "Heavy Metal",
        "Avril Lavigne": "Pop Punk",
        "Ayumi Hamasaki": "J-Pop",
        "B.o.B": "Hip-Hop",
        "Babyshambles": "Indie Rock",
        "Backstreet Boys": "Pop",
        "Bad Religion": "Punk Rock",
        "Band Of Horses": "Indie Rock",
        "Barenaked Ladies": "Alternative Rock",
        "Basement Jaxx": "House",
        "Basshunter": "Eurodance",
        "Bassnectar": "Electronic",
        "Bat For Lashes": "Indie Pop",
        "Battles": "Math Rock",
        "Beastie Boys": "Hip-Hop",
        "Beatsteaks": "Punk Rock",
        "Beautiful Creatures": "Hard Rock",
        "Beck": "Alternative",
        "Behemoth": "Death Metal",
        "Beirut": "Indie Folk",
        "Belanova": "Latin Pop",
        "Belly": "Hip-Hop",
        "Ben Folds": "Alternative Rock",
        "Ben Harper": "Folk Rock",
        "Ben Lee": "Indie Pop",
        "Ben's Brother": "Pop Rock",
        "Benga": "Dubstep",
        "Benjamin Biolay": "Chanson",
        "Benny Benassi": "House",
        "Berryz Kobo": "J-Pop",
        "Between The Buried And Me": "Progressive Metal",
        "Beyoncé": "R&B / Pop",
        "Biffy Clyro": "Rock",
        "Big & Rich": "Country",
        "Birdman": "Hip-Hop",
        "Björk": "Electronic",
        "Black Kids": "Indie Pop",
        "Black Lips": "Garage Rock",
        "Black Rebel Motorcycle Club": "Garage Rock",
        "Black Stone Cherry": "Rock",
        "Black Veil Brides": "Glam Metal",
        "Blakanova": "Unknown",
        "Bleeding Through": "Metalcore",
        "Bloc Party": "Indie Rock",
        "Blonde Redhead": "Indie Rock",
        "Blood Red Shoes": "Indie Rock",
        "Blue Man Group": "Experimental",
        "Blue October": "Alternative Rock",
        "Blutengel": "Dark Wave",
        "Bob Sinclar": "House",
        "Bobby Valentino": "R&B",
        "Bon Iver": "Indie Folk",
        "Bon Jovi": "Rock",
        "Bone Thugs-N-Harmony": "Hip-Hop",
        "Booka Shade": "Electronic",
        "Bow Wow": "Hip-Hop",
        "Bowling For Soup": "Pop Punk",
        "Boys Like Girls": "Pop Punk",
        "Boyz II Men": "R&B",
        "Brad Paisley": "Country",
        "Brand New": "Emo",
        "Breaking Benjamin": "Post-Grunge",
        "Bree Sharp": "Pop Rock",
        "Brian McKnight": "R&B",
        "Bright Eyes": "Indie Folk",
        "Bring Me The Horizon": "Metalcore",
        "Britney Spears": "Pop",
        "Britt Nicole": "Pop",
        "Broken Social Scene": "Indie Rock",
        "Brother Ali": "Hip-Hop",
        "Brothermandude": "Unknown",
        "Bruce Springsteen": "Rock",
        "Buckcherry": "Hard Rock",
        "Bugo": "Alternative",
        "Bullet For My Valentine": "Metalcore",
        "Busta Rhymes": "Hip-Hop",
        "C-Note": "Unknown",
        "Café Tacvba": "Alternative Rock",
        "Cage The Elephant": "Indie Rock",
        "Cajan": "Unknown",
        "Cake": "Alternative Rock",
        "Calvin Harris": "Electronic",
        "Camera Obscura": "Indie Pop",
        "Camila": "Latin Pop",
        "Candie Payne": "Pop",
        "Caribou": "Electronic",
        "Carrie Underwood": "Country",
        "Cartel": "Pop Punk",
        "Casiotone For The Painfully Alone": "Indie Pop",
        "Cassie": "R&B",
        "Cat Power": "Indie Rock",
        "Cee-Lo Green": "Soul / Hip-Hop",
        "Celine Dion": "Pop",
        "Chaba": "Unknown",
        "Chaka Khan": "R&B / Funk",
        "Chamillionaire": "Hip-Hop",
        "Chapeaumelon": "Pop",
        "Chase & Status": "Drum and Bass",
        "Chemical Brothers, The": "Big Beat",
        "Chenoa": "Pop",
        "Chevelle": "Alternative Metal",
        "Chicane": "Trance",
        "Chimaira": "Groove Metal",
        "Chris Brown": "R&B",
        "Chris Cornell": "Rock",
        "Chrisette Michele": "R&B",
        "Christian Walz": "Pop Soul",
        "Christina Aguilera": "Pop",
        "Chromeo": "Funk / Electronic",
        "Ciara": "R&B",
        "Cinematic Orchestra, The": "Nu Jazz",
        "City And Colour": "Acoustic",
        "City Sleeps": "Rock",
        "Claude VonStroke": "House",
        "Clawfinger": "Rap Metal",
        "Client": "Electronic",
        "Clipse": "Hip-Hop",
        "Cobrastyle": "Electronic",
        "CocoRosie": "Freak Folk",
        "Coheed And Cambria": "Progressive Rock",
        "Colbie Caillat": "Pop",
        "Cold War Kids": "Indie Rock",
        "Coldplay": "Alternative Rock",
        "Colette": "House",
        "Common": "Hip-Hop",
        "Consequence": "Hip-Hop",
        "Control Machete": "Hip-Hop",
        "Corinne Bailey Rae": "Soul",
        "Cornelius": "Experimental",
        "Craig Morgan": "Country",
        "Cradle of Filth": "Extreme Metal",
        "Crash Romeo": "Pop Punk",
        "Cross-Fade": "Post-Grunge",
        "Crossfade": "Post-Grunge",
        "Crystal Castles": "Electronic",
        "Culcha Candela": "Dancehall / Hip-Hop",
        "Cupid": "R&B",
        "Cute Is What We Aim For": "Pop Punk",
        "Cyndi Lauper": "Pop",
        "D-Tent Boys": "Unknown",
        "DJ Khaled": "Hip-Hop",
        "DJ Shadow": "Trip Hop",
        "DJ Tiesto": "Trance",
        "Daft Punk": "House",
        "Damien Rice": "Folk",
        "Dan Deacon": "Electronic",
        "Danity Kane": "Pop / R&B",
        "Dark Tranquillity": "Melodic Death Metal",
        "Datarock": "Dance-Punk",
        "Daughtry": "Rock",
        "Dave Gahan": "Synthpop",
        "Dave Matthews": "Rock",
        "Dave Matthews Band": "Rock",
        "David Banner": "Hip-Hop",
        "David Guetta": "House",
        "David Vendetta": "House",
        "De La Soul": "Hip-Hop",
        "Dead50s": "Ska / Punk", # Typo in list?
        "Deadmau5": "House",
        "Death Cab For Cutie": "Indie Rock",
        "Deathstars": "Industrial Metal",
        "Debbie Harry": "Pop / New Wave",
        "Deerhunter": "Indie Rock",
        "Deftones": "Alternative Metal",
        "Delain": "Symphonic Metal",
        "Delta Goodrem": "Pop",
        "Demeter": "Unknown",
        "Demo": "Pop",
        "Demon Hunter": "Metalcore",
        "Dengue Fever": "Psychedelic Rock",
        "Depeche Mode": "Synthpop",
        "Despina Vandi": "Pop",
        "Devendra Banhart": "Folk",
        "Devian": "Black Metal",
        "DevilDriver": "Groove Metal",
        "Diplo": "Electronic",
        "Dir en grey": "Metal",
        "Dierks Bentley": "Country",
        "Digitalism": "Electronic",
        "Dilated Peoples": "Hip-Hop",
        "Dimmu Borgir": "Black Metal",
        "Dinosaur Jr.": "Alternative Rock",
        "Disco Drive": "Dance-Punk",
        "Dizzee Rascal": "Grime",
        "Dolly Parton": "Country",
        "Don Omar": "Reggaeton",
        "Donkeyboy": "Pop",
        "Down Low": "Hip-Hop",
        "Dragonette": "Electropop",
        "Drake": "Hip-Hop",
        "Dream Theater": "Progressive Metal",
        "Dropkick Murphys": "Celtic Punk",
        "Dropbox": "Rock",
        "Duffy": "Soul",
        "Duran Duran": "New Wave",
        "Dusty Rhodes And The River Band": "Indie Rock",
        "Dwight Yoakam": "Country",
        "Dying Fetus": "Death Metal",
        "EL-P": "Hip-Hop",
        "Eastern Conference Champions": "Indie Rock",
        "Editors": "Indie Rock",
        "Eilay Butner": "Unknown",
        "Elefant": "Indie Pop",
        "Elisa": "Pop Rock",
        "Elliott Smith": "Indie Folk",
        "Emerson Drive": "Country",
        "Emilie Simon": "Electronic",
        "Emily Haines & The Soft Skeleton": "Indie Pop",
        "Eminem": "Hip-Hop",
        "Emma Bunton": "Pop",
        "Emma Pollock": "Indie Rock",
        "Emmon": "Synthpop",
        "Emmure": "Metalcore",
        "End Of Fashion": "Rock",
        "Enrique Iglesias": "Latin Pop",
        "Enter Shikari": "Post-Hardcore",
        "Entombed": "Death Metal",
        "Epica (2)": "Symphonic Metal",
        "Epsilons": "Garage Rock",
        "Eros Ramazzotti": "Pop",
        "Escape The Fate": "Post-Hardcore",
        "Estelle": "R&B",
        "Europe": "Rock",
        "Evanescence": "Rock / Goth",
        "Eve": "Hip-Hop",
        "Evermore": "Rock",
        "Every Time I Die": "Metalcore",
        "Ex-Otago": "Indie Pop",
        "Example": "Electronic",
        "Explosions In The Sky": "Post-Rock",
        "Fabolous": "Hip-Hop",
        "Fabri Fibra": "Hip-Hop",
        "Faith No More": "Alternative Metal",
        "Faithless": "Electronic",
        "Faker": "Indie Rock",
        "Fall Out Boy": "Pop Punk",
        "Fam-Lay": "Hip-Hop",
        "Fantasia": "R&B",
        "Fatal Bazooka": "Comedy",
        "Fear Factory": "Industrial Metal",
        "Feist": "Indie Pop",
        "Fergie": "Pop",
        "Fibes, Oh Fibes!": "Pop",
        "Fine Arts Showcase, The": "Indie Rock",
        "Finger Eleven": "Alternative Rock",
        "Finley": "Pop Punk",
        "Firewind": "Power Metal",
        "Five Finger Death Punch": "Heavy Metal",
        "Flight of the Conchords": "Comedy / Folk",
        "Float": "Unknown",
        "Flogging Molly": "Celtic Punk",
        "Florent Pagny": "Chanson",
        "Flyleaf": "Alternative Metal",
        "Foals": "Indie Rock",
        "Foo Fighters": "Rock",
        "Forgive Durden": "Indie Rock",
        "Freakadelika": "House",
        "Freemasons": "House",
        "Freeway": "Hip-Hop",
        "Fright Ranger": "Unknown",
        "Fuel": "Post-Grunge",
        "Full Blown Chaos": "Metalcore",
        "G. Love": "Alternative Hip-Hop",
        "Gabriella Cilmi": "Pop",
        "Gallows": "Hardcore Punk",
        "Garbage": "Alternative Rock",
        "Gavin DeGraw": "Pop Rock",
        "Geisha": "Pop",
        "Gemelli Diversi": "Hip-Hop",
        "Genki Rockets": "Electronic",
        "Ghost Frequency, The": "Indie Rock",
        "Ghostface Killah": "Hip-Hop",
        "Ghostigital": "Electronic",
        "Gianna Nannini": "Rock",
        "Giardini Di Mirò": "Post-Rock",
        "Gin Wigmore": "Pop Rock",
        "Giorgia (2)": "Pop",
        "Girlicious": "Pop / R&B",
        "Girlband": "Pop",
        "Girls Aloud": "Pop",
        "Girls In Hawaii": "Indie Pop",
        "Giusy Ferreri": "Pop",
        "Glasvegas": "Indie Rock",
        "Gloria Estefan": "Latin Pop",
        "Glukoza": "Pop",
        "Gnarls Barkley": "Soul / Pop",
        "Go Betty Go": "Pop Punk",
        "Gob (3)": "Pop Punk",
        "Godsmack": "Nu Metal",
        "Gogol Bordello": "Gypsy Punk",
        "Gojira": "Death Metal",
        "Goldfinger": "Ska Punk",
        "Goldfrapp": "Electronic",
        "Gonzales": "Electronic",
        "Good Charlotte": "Pop Punk",
        "Gorillaz": "Alternative",
        "Gotye": "Indie Pop",
        "Grace Jones": "New Wave",
        "Graham Colton": "Pop Rock",
        "Grandi Animali Marini": "Pop",
        "Green Day": "Punk Rock",
        "Gregory Darling": "Pop",
        "Grinderman": "Garage Rock",
        "Grizzly Bear": "Indie Folk",
        "Groove Coverage": "Eurodance",
        "Grégoire": "Pop",
        "Guillemots": "Indie Pop",
        "Guns N' Roses": "Hard Rock",
        "Guy Sebastian": "Pop",
        "Gwen Stefani": "Pop",
        "Gym Class Heroes": "Hip-Hop / Rock",
        "Gyroscope (2)": "Rock",
        "Günther": "Eurodance",
        "H-Blockx": "Crossover",
        "HER": "R&B",
        "HIM": "Gothic Rock",
        "Hanson": "Pop Rock",
        "Hard-Fi": "Indie Rock",
        "Harlequin League": "Indie Rock",
        "HateSphere": "Thrash Metal",
        "Hauschka": "Modern Classical",
        "Hawthorne Heights": "Emo",
        "Hedley": "Pop Punk",
        "Hej Matematik": "Pop",
        "Hello Saferide": "Indie Pop",
        "Helloween": "Power Metal",
        "Hellyeah": "Heavy Metal",
        "Heloise & The Savoir Faire": "Indie Pop",
        "Henrik Nordvargr Björkk": "Industrial",
        "Herbert Grönemeyer": "Pop Rock",
        "Hercules & Love Affair": "Disco",
        "Hey Ocean!": "Indie Pop",
        "Hey Rosetta!": "Indie Rock",
        "High On Fire": "Stoner Metal",
        "Hilary Duff": "Pop",
        "Hinder": "Post-Grunge",
        "Hollywood Undead": "Rap Rock",
        "Hoobastank": "Rock",
        "Hood G Fam": "Hip-Hop",
        "Hot Gossip": "Unknown",
        "Hot Hot Heat": "Indie Rock",
        "HotHam n' Cheese": "Unknown",
        "Hunter Valentine": "Indie Rock",
        "I Am Alaska": "Unknown",
        "I Am Kloot": "Indie Rock",
        "I Was A Teenage Satan Worshipper": "Electronic",
        "I-20": "Hip-Hop",
        "Ian Brown": "Indie Rock",
        "Ice Cube": "Hip-Hop",
        "Ida Maria": "Indie Rock",
        "Il Genio": "Electropop",
        "Il Teatro Degli Orrori": "Alternative Rock",
        "Il moro e il quasi biondo": "Unknown",
        "Illa Brown": "Unknown",
        "Imelda May": "Rockabilly",
        "Immanuel Casto": "Pop",
        "In One Year": "Unknown",
        "In This Moment": "Metalcore",
        "Incubus": "Alternative Rock",
        "Indigo": "Unknown",
        "Indochine": "New Wave",
        "Indovena": "Unknown",
        "Infieri": "Unknown",
        "Information Society": "Synthpop",
        "Inna": "Dance",
        "Insite": "Rock",
        "Interpol": "Post-Punk Revival",
        "Invitro": "Rock",
        "Iron & Wine": "Indie Folk",
        "Isabella Soric": "Pop",
        "Islands": "Indie Rock",
        "Israel Houghton": "Gospel",
        "J. Holiday": "R&B",
        "J. Valentine": "R&B",
        "JC Anderson": "Unknown",
        "Ja Rule": "Hip-Hop",
        "Jacinto Canek": "Unknown",
        "Jack Black": "Comedy Rock",
        "Jack Johnson": "Folk Rock",
        "Jackson United": "Punk Rock",
        "Jadakiss": "Hip-Hop",
        "Jade MacRae": "R&B",
        "Jade Valerie": "Pop",
        "Jae Millz": "Hip-Hop",
        "Jagged Edge": "R&B",
        "Jake Owen": "Country",
        "Jamelia": "R&B",
        "James Blunt": "Pop Rock",
        "James Fox": "Pop",
        "James Morrison": "Pop Soul",
        "Jamie Foxx": "R&B",
        "Jamie T": "Indie Rock",
        "Jane 3": "Unknown",
        "Janelle Monáe": "R&B / Funk",
        "Janet Jackson": "R&B / Pop",
        "Janusz Radek": "Pop",
        "Japanese Motors": "Garage Rock",
        "Jason Michael Carroll": "Country",
        "Jay Brannan": "Folk",
        "Jay Rock": "Hip-Hop",
        "Jay Z": "Hip-Hop",
        "Jayden Lyrics": "Unknown",
        "Jazmine Sullivan": "R&B",
        "Jeezy": "Hip-Hop",
        "Jeffrey Butzer": "Unknown",
        "Jennifer Hudson": "R&B",
        "Jennifer Lopez": "Pop / R&B",
        "Jennifer Paige": "Pop",
        "Jesse & Joy": "Latin Pop",
        "Jesse McCartney": "Pop",
        "Jessica Mauboy": "Pop",
        "Jessica Simpson": "Pop",
        "Jessie Baylin": "Folk",
        "Jet": "Rock",
        "Jewel": "Folk / Pop",
        "Jim Jones": "Hip-Hop",
        "Jimi Blue": "Pop",
        "Joanna Wang": "Jazz Pop",
        "Joe": "R&B",
        "Joe Lean And The Jing Jang Jong": "Indie Rock",
        "Joe Nichols": "Country",
        "John Fogerty": "Rock",
        "John Legend": "R&B",
        "John Mellencamp": "Rock",
        "John Merrick": "Unknown",
        "John Vanderslice": "Indie Rock",
        "Johnny Dread": "Reggae",
        "Johnny Foreigner": "Indie Rock",
        "Johnny Hallyday": "Rock",
        "Johnossi": "Indie Rock",
        "Jon Lajoie": "Comedy",
        "Jon McLaughlin": "Pop Rock",
        "Jonas Brothers": "Pop Rock",
        "Jonathan Johansson": "Pop",
        "Jonna Lee": "Electronic",
        "Jordan Galland": "Indie Pop",
        "Jordin Sparks": "Pop / R&B",
        "Josh Groban": "Pop",
        "Josh Turner": "Country",
        "Joshua Radin": "Folk",
        "Joss Stone": "Soul",
        "Jovanotti": "Pop / Hip-Hop",
        "Joy Electric": "Synthpop",
        "Juanes": "Latin Pop",
        "Juelz Santana": "Hip-Hop",
        "Jukebox The Ghost": "Pop Rock",
        "Juli": "Pop Rock",
        "Julianne Hough": "Country",
        "Julie's Haircut": "Indie Rock",
        "Julien Doré": "Pop",
        "Justice": "Electronic",
        "Justin K Broadrick": "Experimental",
        "Justin Martin": "House",
        "Justin Moore": "Country",
        "Justin Timberlake": "Pop",
        "K'naan": "Hip-Hop",
        "KRYŠTOF": "Pop Rock",
        "KT Tunstall": "Pop Rock",
        "Kaal": "Unknown",
        "Kaiser Chiefs": "Indie Rock",
        "Kano (6)": "Grime",
        "Kanye West": "Hip-Hop",
        "Kardinal Offishall": "Hip-Hop",
        "Kassi": "Unknown",
        "Kat DeLuna": "Pop",
        "Kate & Ben": "Unknown",
        "Kate Hall": "Pop",
        "Kate Nash": "Indie Pop",
        "Kate Ryan": "Eurodance",
        "Kate Tucker": "Indie Rock",
        "Katharine McPhee": "Pop",
        "Katy Perry": "Pop",
        "Keane": "Piano Rock",
        "Keaton Simons": "Rock",
        "Keisha White": "R&B",
        "Keith Urban": "Country",
        "Kele Le Roc": "R&B",
        "Kellie Pickler": "Country",
        "Kelly Clarkson": "Pop Rock",
        "Kelly Rowland": "R&B",
        "Ken": "J-Rock",
        "Kenna": "Electronic",
        "Kenny Chesney": "Country",
        "Kent": "Indie Rock",
        "Keri Hilson": "R&B",
        "Kerli": "Pop",
        "Kery James": "Hip-Hop",
        "Keshia Chanté": "R&B",
        "Kevin Rudolf": "Rock / Hip-Hop",
        "Keyshia Cole": "R&B",
        "Keziah Jones": "Funk",
        "Khan": "Electronic",
        "Kid Dakota": "Indie Rock",
        "Kid Gib": "Unknown",
        "Kid Rock": "Rock / Hip-Hop",
        "Kid Sister": "Hip-Hop",
        "Killswitch Engage": "Metalcore",
        "Kimberley Locke": "Pop",
        "Kingdom Of Sorrow": "Sludge Metal",
        "Kings Of Leon": "Rock",
        "Kirk Franklin": "Gospel",
        "Kissaway Trail, The": "Indie Rock",
        "Klaxons": "Indie Rock",
        "Kleerup": "Electronic",
        "Korn": "Nu Metal",
        "Kotipelto": "Power Metal",
        "Kreesha Turner": "Pop",
        "Kristin Chenoweth": "Pop",
        "Kristin Hersh": "Alternative Rock",
        "Kristy Lee Cook": "Country",
        "Krypteria": "Symphonic Metal",
        "Kula Shaker": "Psychedelic Rock",
        "Kumi Koda": "J-Pop",
        "Kylie Minogue": "Pop",
        "Kyo": "Rock",
        "L'Aura": "Pop",
        "L.P.": "Indie Pop",
        "LCD Soundsystem": "Dance-Punk",
        "LIKEHELL": "Unknown",
        "LL Cool J": "Hip-Hop",
        "LP": "Indie Pop",
        "La Fouine": "Hip-Hop",
        "La Sinfonia": "Hip-Hop",
        "Lacuna Coil": "Gothic Metal",
        "Lady Antebellum": "Country",
        "Lady Gaga": "Pop / Dance",
        "Ladyhawke": "Electropop",
        "Ladytron": "Electronic",
        "Lama": "Unknown",
        "Lanre": "Unknown",
        "Lana del Rey": "Pop", # Lizzie Grant era
        "Langhorne Slim": "Folk",
        "Largo": "Unknown",
        "Lasgo": "Eurodance",
        "Late of the Pier": "Electronic Rock",
        "Laura Izibor": "R&B",
        "Laura Pausini": "Pop",
        "Laura Veirs": "Folk",
        "Lauryn Hill": "R&B",
        "Le Luci Della Centrale Elettrica": "Indie Rock",
        "Le Vibrazioni": "Rock",
        "Le man avec les lunettes": "Indie Pop",
        "LeAnn Rimes": "Country",
        "Leb I Sol": "Jazz Fusion",
        "Lee Ann Womack": "Country",
        "Lee Brice": "Country",
        "Leeni": "Chiptune",
        "Leerone": "Pop",
        "Leki": "R&B",
        "Lemar": "R&B",
        "Lemon Ice": "Pop",
        "Lenka": "Pop",
        "Lenny Kravitz": "Rock",
        "Leona Lewis": "Pop",
        "Lexington Bridge": "Pop",
        "Liars": "Experimental Rock",
        "Lifehouse": "Alternative Rock",
        "Lifetime": "Melodic Hardcore",
        "Ligabue": "Rock",
        "Lil Mama": "Hip-Hop",
        "Lil Rob": "Hip-Hop",
        "Lil Wayne": "Hip-Hop",
        "Lil' Boosie": "Hip-Hop",
        "Lily Allen": "Pop",
        "Linea 77": "Nu Metal",
        "Linkin Park": "Nu Metal",
        "Liquido": "Alternative Rock",
        "Lisa Loeb": "Pop",
        "Lissat & Voltaxx": "House",
        "Litfiba": "Rock",
        "Little Dragon": "Electronic",
        "Little Jackie": "Pop / Hip-Hop",
        "Liz Pappademas": "Singer-Songwriter",
        "Lizette &": "Unknown",
        "Lloyd": "R&B",
        "Locos por Juana": "Latin Alternative",
        "Logan Lynn": "Electronic",
        "Lordi": "Hard Rock",
        "Lori Meyers": "Indie Rock",
        "Los Campesinos!": "Indie Pop",
        "Los Claxons": "Pop Rock",
        "Los Creadorez Del Pasito Duranguense": "Regional Mexican",
        "Los Temerarios": "Regional Mexican",
        "Los Tigres Del Norte": "Norteño",
        "Los Tucanes De Tijuana": "Norteño",
        "Lostprophets": "Rock",
        "Lou Reed": "Rock",
        "Louise Attaque": "Folk Rock",
        "Low": "Slowcore",
        "Low vs Diamond": "Indie Rock",
        "Ludacris": "Hip-Hop",
        "Luis Fonsi": "Latin Pop",
        "Lull": "Ambient",
        "Lulu Lewe": "Pop",
        "Lupe Fiasco": "Hip-Hop",
        "Luvi De Andrè": "Folk",
        "Lyfe Jennings": "R&B",
        "Lykke Li": "Indie Pop",
        "Lymbyc Systym": "Post-Rock",
        "M.I.A.": "Hip-Hop / Electronic",
        "M83": "Electronic",
        "MC Frontalot": "Nerdcore",
        "MGMT": "Indie Pop",
        "MIKA": "Pop",
        "Macy Gray": "R&B",
        "Madcon": "Hip-Hop",
        "Madina Lake": "Post-Hardcore",
        "Madonna": "Pop",
        "Majid": "Unknown",
        "Mala Rodríguez": "Hip-Hop",
        "Malika Ayane": "Pop",
        "Manchester Orchestra": "Indie Rock",
        "Manda Rin": "Unknown",
        "Mandy Moore": "Pop",
        "Mange Schmidt": "Hip-Hop",
        "Manic Street Preachers": "Alternative Rock",
        "Manuel Carrasco": "Pop",
        "Marc Terenzi": "Pop",
        "Marco Antonio Solís": "Latin Pop",
        "Marco Notari": "Indie Rock",
        "Marianas Trench": "Pop Rock",
        "Maria Mena": "Pop",
        "Mariah Carey": "R&B / Pop",
        "Marilyn Manson": "Industrial Metal",
        "Marina & The Diamonds": "Pop",
        "Mario": "R&B",
        "Marion Cotillard": "Chanson",
        "Marion Raven": "Pop Rock",
        "Mark Gormley": "Outsider",
        "Mark Mallman": "Indie Rock",
        "Mark Ronson": "Pop / Soul",
        "Marlene Kuntz": "Alternative Rock",
        "Maroon 5": "Pop Rock",
        "Marques Houston": "R&B",
        "Marquess (2)": "Pop",
        "Marracash": "Hip-Hop",
        "Marta Sui Tubi": "Indie Rock",
        "Marta Sánchez": "Pop",
        "Martijn ten Velden": "House",
        "Martina McBride": "Country",
        "Marvin The Robot": "Unknown",
        "Mary J. Blige": "R&B",
        "Mastodon": "Metal",
        "Mat Kearney": "Pop Rock",
        "Matchbox Twenty": "Alternative Rock",
        "Mates Of State": "Indie Pop",
        "Matthew West": "Christian",
        "Mau Mau (2)": "Unknown",
        "Mavado": "Dancehall",
        "Max De Angelis": "Pop",
        "Max Pezzali": "Pop",
        "Maxïmo Park": "Indie Rock",
        "Maya Saban": "Pop",
        "Mayday Parade": "Pop Punk",
        "Mayor's Destiny": "Pop",
        "McFly": "Pop Rock",
        "Meg & Dia": "Indie Rock",
        "Megadeth": "Thrash Metal",
        "Meko": "Dance",
        "Melanie C": "Pop",
        "Melanie Fiona": "R&B",
        "Melissa Etheridge": "Rock",
        "Melody & Mezzo": "Unknown",
        "Melody Fall": "Pop Punk",
        "Melvins": "Sludge Metal",
        "Menomena": "Indie Rock",
        "Mercenary": "Melodic Death Metal",
        "Meshuggah": "Metal",
        "Metallica": "Heavy Metal",
        "Meteor": "Unknown",
        "Metric": "Indie Rock",
        "Metro Station": "Pop Rock",
        "Metronomy": "Electronic",
        "Mi?ko i Keckec": "Unknown",
        "Miami Horror": "Electronic",
        "Michael Bublé": "Jazz / Pop",
        "Michael Mind": "House",
        "Michael W. Smith": "Christian",
        "Mickey Avalon": "Hip-Hop",
        "Micky Green": "Pop",
        "Micol Barsanti": "Pop",
        "Midnight Juggernauts": "Electronic",
        "Miley Cyrus": "Pop",
        "Milk Inc.": "Eurodance",
        "Mindcrime (2)": "Unknown",
        "Mindless Self Indulgence": "Electronic Rock",
        "Ministri": "Indie Rock",
        "Minitel Rose": "Electronic",
        "Mira": "Unknown",
        "Miranda Cosgrove": "Pop",
        "Miranda Lambert": "Country",
        "Misery Signals": "Metalcore",
        "Mishon": "R&B",
        "Missy Elliott": "Hip-Hop",
        "Missy Higgins": "Pop",
        "Mobile": "Alternative Rock",
        "Moby": "Electronic",
        "Modest Mouse": "Indie Rock",
        "Moderatto": "Glam Rock",
        "Moltheni": "Indie Rock",
        "Moneybrother": "Rock",
        "Mom?ilo Bajagi?": "Rock",
        "Monrose": "Pop",
        "Moonbabies": "Indie Pop",
        "Moonspell": "Gothic Metal",
        "Morgan (2)": "Pop",
        "Morningwood": "Alternative Rock",
        "Morrissey": "Indie Pop",
        "Mother Mother": "Indie Rock",
        "Motörhead": "Heavy Metal",
        "Mr. Capone-E": "Hip-Hop",
        "Muck Sticky": "Hip-Hop",
        "Mudcrutch": "Rock",
        "Mudvayne": "Nu Metal",
        "Munk": "Electronic",
        "Murder City Sparrows": "Unknown",
        "Murphy Lee": "Hip-Hop",
        "Murs & 9th Wonder": "Hip-Hop",
        "Muscles": "Electronic",
        "Muse": "Alternative Rock",
        "Mushroomhead": "Industrial Metal",
        "MxPx": "Punk Rock",
        "My Chemical Romance": "Emo / Rock",
        "My Early Mustang": "Rock",
        "My First Tooth": "Indie Folk",
        "My Minds Weapon": "Metalcore",
        "Mya": "R&B",
        "Mötley Crüe": "Glam Metal",
        "N-Dubz": "Hip-Hop",
        "N.E.R.D.": "Hip-Hop / Rock",
        "NLT": "Pop",
        "NYG'z": "Hip-Hop",
        "Nadàr Solo": "Indie Rock",
        "Namosh": "Electronic",
        "Nas": "Hip-Hop",
        "Natali Dizdar": "Pop",
        "Natalie Imbruglia": "Pop",
        "Natasha": "Pop",
        "Natasha Bedingfield": "Pop",
        "Natasha St-Pier": "Pop",
        "Nathan Wiley": "Folk",
        "National Product": "Rock",
        "Ne-Yo": "R&B",
        "Negative Blue": "Rock",
        "Negligence": "Thrash Metal",
        "Negramaro": "Pop Rock",
        "Nell Bryden": "Singer-Songwriter",
        "Nelly": "Hip-Hop",
        "Nelly Furtado": "Pop",
        "Nena": "Neue Deutsche Welle",
        "Neoangin": "Indie Pop",
        "Nesli": "Hip-Hop",
        "Never Shout Never": "Acoustic Pop",
        "New Crash Position": "Unknown",
        "New Kids On The Block": "Pop",
        "New Radiant Storm King": "Indie Rock",
        "New Years Day": "Rock",
        "Newton": "Unknown",
        "Newton Faulkner": "Folk",
        "Niccolò Agliardi": "Pop",
        "Nick Cave & The Bad Seeds": "Alternative Rock",
        "Nickelback": "Post-Grunge",
        "Nico Vega": "Rock",
        "Nicole Atkins": "Indie Pop",
        "Nicole Scherzinger": "Pop",
        "Nightwish": "Symphonic Metal",
        "Nina Kristin": "Pop",
        "Nina Pilots": "Pop",
        "Nine Black Alps": "Alternative Rock",
        "Nine Inch Nails": "Industrial Rock",
        "No Loving Place": "Unknown",
        "No More Kings": "Indie Rock",
        "No and The Maybes": "Indie Pop",
        "Noah And The Whale": "Indie Folk",
        "Noel Gourdin": "R&B",
        "Noisettes": "Indie Rock",
        "Norah Jones": "Jazz / Pop",
        "November Növelet": "Electronic",
        "Ntoumous": "Unknown",
        "Nu GeVe Netcheru": "Unknown",
        "Numero6": "Indie Pop",
        "Nuno & The End": "Unknown",
        "Nussbaum": "Unknown",
        "Nx Zero": "Rock",
        "O'Neal McKnight": "R&B",
        "OOMPH!": "Industrial Metal",
        "Octopus (2)": "Unknown",
        "October Sky": "Rock",
        "Of Montreal": "Indie Pop",
        "Ohad Hitman": "Pop",
        "Old 97's": "Alt-Country",
        "Old Crow Medicine Show": "Folk",
        "One Night Only": "Indie Rock",
        "OneRepublic": "Pop Rock",
        "Opeth": "Progressive Metal",
        "Origin (7)": "Death Metal",
        "Outlandish": "Hip-Hop",
        "Outwork": "House",
        "Ozzy Osbourne": "Heavy Metal",
        "PJ Harvey": "Alternative Rock",
        "PNS": "Unknown",
        "Pale": "Indie Rock",
        "Panic! at the Disco": "Pop Punk / Emo",
        "Paola & Chiara": "Pop",
        "Paolo Nutini": "Pop Rock",
        "Papa Roach": "Nu Metal",
        "Paradise Lost": "Gothic Metal",
        "Paramore": "Pop Punk",
        "Paris Hilton": "Pop",
        "Parry Gripp": "Comedy",
        "Pascal Obispo": "Pop",
        "Patrice": "Reggae / Soul",
        "Patrick Nuo": "Pop",
        "Paul McCartney": "Rock",
        "Paul Weller": "Rock",
        "Paula Fernandes": "Country",
        "Paulina Rubio": "Latin Pop",
        "Pelican": "Post-Metal",
        "Pendulum (3)": "Drum and Bass",
        "People In Planes": "Indie Rock",
        "Per Gessle": "Pop",
        "Peter Björn and John": "Indie Pop",
        "Petrol (2)": "Unknown",
        "Petros Gaitanos": "Unknown",
        "Petter": "Hip-Hop",
        "Phantom Planet": "Alternative Rock",
        "Pharoahe Monch": "Hip-Hop",
        "Phil Stacey": "Country",
        "Philip Morax": "Unknown",
        "Phoenix": "Indie Pop",
        "Piebald": "Emo",
        "Pierce The Veil": "Post-Hardcore",
        "Pierre Lewis": "R&B",
        "Pilot Touhill": "Unknown",
        "Pillar": "Christian Rock",
        "Pink": "Pop",
        "Pissed Jeans": "Hardcore Punk",
        "Pitbull": "Hip-Hop",
        "Pitty": "Rock",
        "Pixie Lott": "Pop",
        "Placebo": "Alternative Rock",
        "Plain White T's": "Pop Punk",
        "Planes Mistaken For Stars": "Post-Hardcore",
        "PlanningToRock": "Electronic",
        "Plants And Animals": "Indie Rock",
        "Plushgun": "Synthpop",
        "Poets Of The Fall": "Rock",
        "Point Blank": "Unknown",
        "Poison": "Glam Metal",
        "Pompeya": "Indie Pop",
        "Pop Evil": "Rock",
        "Populous": "Electronic",
        "Populous with Short Stories": "Electronic",
        "Port O'Brien": "Indie Folk",
        "Porter": "Indie Rock",
        "Powerspace": "Pop Punk",
        "Pquadro": "Pop",
        "Prairie Oyster": "Country",
        "Prince": "Funk / Pop",
        "Private": "Electronic",
        "Professor Elemental": "Chap Hop",
        "Project 86": "Nu Metal",
        "Protest The Hero": "Progressive Metal",
        "Psilodump": "Electronic",
        "Psycho Charger": "Psychobilly",
        "Psyclon Nine": "Industrial",
        "Puddle Of Mudd": "Post-Grunge",
        "Punchline": "Pop Punk",
        "Punkreas (2)": "Punk Rock",
        "PureH": "Unknown",
        "Q-Tip": "Hip-Hop",
        "Quarashi": "Hip-Hop / Rock",
        "Queen": "Rock",
        "Queens Of The Stone Age": "Stoner Rock",
        "Queensberry": "Pop",
        "R. Kelly": "R&B",
        "R.E.M.": "Alternative Rock",
        "RAH Band": "Electronic",
        "RBD": "Pop",
        "RJD2": "Hip-Hop",
        "Rachel Yamagata": "Singer-Songwriter",
        "Radar Bros.": "Indie Rock",
        "Radiohead": "Alternative",
        "RadU": "Unknown",
        "Raf": "Pop",
        "Rakes, The": "Indie Rock",
        "Rammstein": "Industrial Metal",
        "Randy Rogers Band": "Country",
        "Raphael Saadiq": "R&B / Soul",
        "Rapsoul": "Hip-Hop",
        "Raptile": "Hip-Hop",
        "Rascal Flatts": "Country",
        "Ratatat": "Electronic",
        "Ray Lavender": "R&B",
        "Razorlight": "Indie Rock",
        "Realia": "Unknown",
        "Reba McEntire": "Country",
        "Rebekah Joy": "Unknown",
        "Red Hot Chili Peppers": "Funk Rock",
        "Red Light Company": "Indie Rock",
        "Rednex": "Eurodance",
        "Regina Spektor": "Indie Pop",
        "Reh Dogg": "Outsider",
        "Rehab (2)": "Hip-Hop / Rock",
        "Reik": "Pop",
        "Republic Tigers, The": "Indie Rock",
        "Resident Hero": "Rock",
        "Rex The Dog": "Electronic",
        "Ricardo Montaner": "Latin Pop",
        "Rick Ross": "Hip-Hop",
        "Ricki-Lee": "Pop",
        "Rihanna": "Pop / R&B",
        "Rinôçérôse": "Electronic Rock",
        "Rise Against": "Punk Rock",
        "Rizon": "Unknown",
        "Robbie Williams": "Pop",
        "Robert Francis": "Folk Rock",
        "Robin Thicke": "R&B",
        "Robyn": "Pop",
        "Rod Thomas": "Pop",
        "Roger Cicero": "Jazz Pop",
        "Rogue Traders": "Electronic Rock",
        "Rogue Wave": "Indie Rock",
        "Roma": "Indie Pop",
        "Romina Falconi": "Pop",
        "Room 2012": "Pop",
        "Rooney": "Indie Rock",
        "Rory Nunn": "Unknown",
        "Rouge A Lèvres": "Unknown",
        "Rowdy Superstar": "Unknown",
        "RuPaul": "Dance",
        "Ruben Studdard": "R&B",
        "Rufus Wainwright": "Baroque Pop",
        "Róisín Murphy": "Electronic",
        "SHO": "Unknown",
        "SIA": "Pop",
        "SSION": "Electronic",
        "STRFKR": "Electronic",
        "Sabaton": "Power Metal",
        "Saint Motel": "Indie Pop",
        "Saliva": "Nu Metal",
        "Sam Roberts": "Rock",
        "Sam Sparro": "Pop",
        "Samantha Jade": "Pop",
        "Sambomaster": "Rock",
        "Same Difference": "Pop",
        "Sammie (2)": "R&B",
        "Santana": "Rock",
        "Santigold": "Electronic",
        "Saosin": "Post-Hardcore",
        "Sara Bareilles": "Pop Rock",
        "Sara Evans": "Country",
        "Sarah Connor": "Pop",
        "Sarah Fimm": "Trip Hop",
        "Sarah McLachlan": "Pop",
        "Sarah Whatmore": "Pop",
        "Satyricon": "Black Metal",
        "Say Anything": "Pop Punk",
        "Scarlett Johansson": "Pop",
        "Scissor Sisters": "Pop / Disco",
        "Scooter": "Techno",
        "Scooter Smiff": "Hip-Hop",
        "Scorpions": "Rock",
        "Scouting For Girls": "Indie Pop",
        "Sea Wolf": "Indie Folk",
        "Seal": "Soul",
        "Sean Garrett": "R&B",
        "Sean Kingston": "Reggae Fusion",
        "Sean Paul": "Dancehall",
        "Sean Ward": "Unknown",
        "Second Monday": "Unknown",
        "Secondsmile": "Post-Hardcore",
        "Seether": "Post-Grunge",
        "Semargl": "Black Metal",
        "Semi Precious Weapons": "Glam Rock",
        "Senta-Sofia": "Pop",
        "Serj Tankian": "Alternative Metal",
        "Seventeen Evergreen": "Experimental",
        "Shadows Fall": "Metalcore",
        "Shaggy": "Reggae",
        "Shakira": "Latin Pop",
        "Shanadoo": "Eurodance",
        "Shayne Ward": "Pop",
        "She Wants Revenge": "Post-Punk Revival",
        "Sheek Louch": "Hip-Hop",
        "Shekie 'N' Sham": "Unknown",
        "Sheryl Crow": "Rock",
        "Shiny Toy Guns": "Electronic Rock",
        "Shontelle": "R&B",
        "Shroud": "Metal",
        "Shurman": "Country Rock",
        "Shwayze": "Hip-Hop",
        "Sick Puppies": "Rock",
        "Sign": "Unknown",
        "Sigur Rós": "Post-Rock",
        "Sikitikis": "Unknown",
        "Silbermond": "Pop Rock",
        "Silent Civilian": "Metalcore",
        "Silicon Fly": "Unknown",
        "Silverchair": "Alternative Rock",
        "Silversun Pickups": "Alternative Rock",
        "Simian Mobile Disco": "Electronic",
        "Simple Plan": "Pop Punk",
        "Simply Red": "Soul",
        "Sing It Loud": "Pop Punk",
        "Sinik": "Hip-Hop",
        "Sinéad O'Connor": "Alternative Rock",
        "Siouxsie Sioux": "Post-Punk",
        "Sir Ari Gold": "R&B",
        "Sirens (5)": "Unknown",
        "Sisqó": "R&B",
        "Skin": "Rock",
        "Skinnen Bones MC": "Unknown",
        "Slakah the Beatchild": "Soul",
        "Slim K": "Unknown",
        "Slim Thug": "Hip-Hop",
        "Slipknot": "Nu Metal",
        "Slum Peasants": "Unknown",
        "Smoke'n'Soul": "Unknown",
        "Smugg Juggler": "Unknown",
        "Snoop Dogg": "Hip-Hop",
        "Snow": "Reggae",
        "Snow Patrol": "Indie Rock",
        "Sohodolls": "Electronic",
        "Solange": "R&B",
        "Son Pascal": "Pop",
        "Sonic Boom Six": "Ska Punk",
        "Sonic Syndicate": "Melodic Death Metal",
        "Sophia Segal": "Unknown",
        "Sophie Ellis-Bextor": "Pop / Disco",
        "Sothis": "Black Metal",
        "Soular": "Unknown",
        "Soulja Boy": "Hip-Hop",
        "Spice Girls": "Pop",
        "Spoon": "Indie Rock",
        "St. Vincent": "Indie Rock",
        "Stafrænn Hákon": "Post-Rock",
        "Staind": "Post-Grunge",
        "Stance Punks": "Punk Rock",
        "Static-X": "Industrial Metal",
        "Stephanie Mcintosh": "Pop",
        "Stephen Fretwell": "Singer-Songwriter",
        "Sterling Schroeder": "Unknown",
        "Sterling Simms": "R&B",
        "Steve Winwood": "Rock",
        "Steven Flaughers": "Unknown",
        "Stick To Your Guns": "Hardcore",
        "Stone Sour": "Hard Rock",
        "Strapping Young Lad": "Industrial Metal",
        "Stray Dog Cafe": "Unknown",
        "Strayday": "Unknown",
        "Streetlight Manifesto": "Ska Punk",
        "Styles P": "Hip-Hop",
        "Subsonica": "Electronic Rock",
        "Sue Scrofa": "Unknown",
        "Suffocation": "Death Metal",
        "Sugababes": "Pop",
        "Sugarland": "Country",
        "Suicide Silence": "Deathcore",
        "Sum 41": "Pop Punk",
        "Sunblock (2)": "Dance",
        "Sunny Sweeney": "Country",
        "Superbus (2)": "Pop Rock",
        "Supernafamacho": "Hip-Hop",
        "Suspekt (2)": "Unknown",
        "Sven Van Thom": "Pop",
        "Switches": "Indie Rock",
        "Switchfoot": "Alternative Rock",
        "Swizz Beatz": "Hip-Hop",
        "Syria": "Pop",
        "System 7": "Electronic",
        "T-Pain": "R&B / Hip-Hop",
        "T.I.": "Hip-Hop",
        "T13C": "Unknown",
        "TV On The Radio": "Indie Rock",
        "TaintStick": "Comedy Rock",
        "Taio Cruz": "R&B",
        "Take That": "Pop",
        "Tali & Messiah": "Unknown",
        "Tally Hall": "Indie Pop",
        "Tame Impala": "Psychedelic Rock",
        "Taproot": "Nu Metal",
        "Tay Zonday": "Internet",
        "Taylor Dayne": "Pop",
        "Taylor Swift": "Country / Pop",
        "Ted Leo and The Pharmacists": "Indie Rock",
        "Teddybears": "Electronic Rock",
        "Teenagers, The (2)": "Indie Pop",
        "Tegan and Sara": "Indie Pop",
        "Templeton Pek": "Punk Rock",
        "Terror (3)": "Hardcore",
        "Teyana Taylor": "R&B",
        "Thalía": "Latin Pop",
        "Thao & The Get Down Stay Down": "Indie Folk",
        "The Academy Is...": "Pop Punk",
        "The Acorn": "Indie Folk",
        "The Afters": "Christian Rock",
        "The Airborne Toxic Event": "Indie Rock",
        "The All-American Rejects": "Pop Punk",
        "The Almost": "Alternative Rock",
        "The B-52's": "New Wave",
        "The Bangkok Five": "Rock",
        "The Beau Sisters": "Folk",
        "The Bird and the Bee": "Indie Pop",
        "The Black Keys": "Blues Rock",
        "The Bloody Beetroots": "Electronic",
        "The Boat People": "Indie Pop",
        "The BossHoss": "Country Rock",
        "The Bravery": "Post-Punk Revival",
        "The Breeders": "Alternative Rock",
        "The Briggs": "Punk Rock",
        "The Broken Letters": "Indie Rock",
        "The Cab": "Pop Punk",
        "The Casualties": "Punk Rock",
        "The Chemical Brothers": "Big Beat",
        "The Cool Kids": "Hip-Hop",
        "The Count & Sinden": "House",
        "The Cure": "Gothic Rock",
        "The Cute Lepers": "Punk Rock",
        "The DEY": "Hip-Hop / R&B",
        "The Dillinger Escape Plan": "Mathcore",
        "The Drones": "Rock",
        "The Fratellis": "Indie Rock",
        "The Fray": "Pop Rock",
        "The Game": "Hip-Hop",
        "The Gaslight Anthem": "Punk Rock",
        "The Ghost Inside": "Metalcore",
        "The Glitterati": "Rock",
        "The Go! Team": "Indie Pop",
        "The Hush Sound": "Indie Pop",
        "The Ivy Walls": "Indie Pop",
        "The Josh and Pete Band": "Unknown",
        "The Killers": "Indie Rock",
        "The Kills": "Indie Rock",
        "The Knux": "Hip-Hop",
        "The Kooks": "Indie Rock",
        "The Last Days of Disco": "Unknown",
        "The Last Shadow Puppets": "Indie Rock",
        "The Lonely Island": "Comedy",
        "The Loose Kites": "Unknown",
        "The Monarchy": "Unknown",
        "The Music": "Rock",
        "The New Pornographers": "Indie Rock",
        "The New Story": "Pop Punk",
        "The Niro": "Pop",
        "The Offspring": "Punk Rock",
        "The Owls": "Indie Pop",
        "The People People": "Unknown",
        "The Potbelleez": "House",
        "The Presets": "Electronic",
        "The Presidents Of The United States Of America": "Alternative Rock",
        "The Prodigy": "Big Beat",
        "The Pussycat Dolls": "Pop / R&B",
        "The Red Jumpsuit Apparatus": "Post-Hardcore",
        "The Ritz": "Unknown",
        "The Roots": "Hip-Hop",
        "The Saturdays": "Pop",
        "The Script": "Pop Rock",
        "The Seamus": "Unknown",
        "The Smashing Pumpkins": "Alternative Rock",
        "The Storm": "Rock",
        "The Streets": "UK Garage",
        "The Subways": "Indie Rock",
        "The Summerlad": "Indie Pop",
        "The Thomas Nicholas Band": "Rock",
        "The Ting Tings": "Indie Pop",
        "The Truth": "Unknown",
        "The Verve": "Britpop",
        "The View": "Indie Rock",
        "The Weepies": "Folk Pop",
        "The Zen Circus": "Folk Punk",
        "The Zutons": "Indie Rock",
        "There For Tomorrow": "Pop Punk",
        "Thermostatic": "Electronic",
        "These New Puritans": "Art Rock",
        "Thievery Corporation": "Downtempo",
        "Those Dancing Days": "Indie Pop",
        "Three-6 Mafia": "Hip-Hop",
        "Thrice": "Post-Hardcore",
        "Thunderheist": "Electronic",
        "Tift Merritt": "Folk",
        "Timbaland": "Hip-Hop / R&B",
        "Tina Arena": "Pop",
        "Tiromancino": "Pop",
        "Toby Keith": "Country",
        "Tokio Hotel": "Pop Rock",
        "Tomas Marcuzzi": "Unknown",
        "Tommy Sparks": "Indie Pop",
        "Tony Clifton": "Comedy",
        "TooMuchBlond": "Unknown",
        "Torche": "Sludge Metal",
        "Traffik (2)": "Unknown",
        "Trece14": "Unknown",
        "Trina": "Hip-Hop",
        "Trisha Yearwood": "Country",
        "True Ingredients": "Unknown",
        "Tumbledown": "Punk Rock",
        "Tupelo Honey": "Rock",
        "Tyga": "Hip-Hop",
        "U2": "Rock",
        "US 5": "Pop",
        "Udo Lindenberg": "Rock",
        "Ugly Duckling": "Hip-Hop",
        "Ultra Naté": "House",
        "Ultrabeat (2)": "Dance",
        "Unearth": "Metalcore",
        "Union Of Knives": "Electronic",
        "Unleashed": "Death Metal",
        "Useless Wooden Toys": "Electronic",
        "Usher": "R&B",
        "Utada Hikaru": "J-Pop",
        "V V Brown": "Pop",
        "Valencia": "Pop Punk",
        "Vampire Weekend": "Indie Rock",
        "Van Canto": "A Cappella Metal",
        "Van She": "Electronic",
        "Van Zant": "Southern Rock",
        "Vanessa Carlton": "Pop",
        "Vanessa Hudgens": "Pop",
        "Vanilla Sky (2)": "Pop Punk",
        "Vatra": "Rock",
        "Velvet (2)": "Pop",
        "Verdena": "Grunge",
        "Veronica Maggio": "Pop",
        "Veze Skante": "Hip-Hop",
        "Vindetta": "Unknown",
        "Volbeat": "Metal",
        "Volumen Cero": "Rock",
        "WHY?": "Indie Rock",
        "We The Kings": "Pop Punk",
        "Wedlock": "Unknown",
        "Weezer": "Alternative Rock",
        "When the Clouds": "Post-Rock",
        "White Denim": "Indie Rock",
        "White Lies": "Indie Rock",
        "Whitechapel": "Deathcore",
        "Whitney Costner": "Unknown",
        "Wild Sweet Orange": "Indie Rock",
        "Will Young": "Pop",
        "William Control": "Electronic",
        "Willie Nelson": "Country",
        "Wisin & Yandel": "Reggaeton",
        "Witchcraft (6)": "Unknown",
        "Within Temptation": "Symphonic Metal",
        "Wonder Villains": "Indie Pop",
        "Wyclef Jean": "Hip-Hop",
        "Xcese": "Hip-Hop",
        "Xiu Xiu": "Experimental",
        "YELLE": "Pop",
        "Yeah Yeah Yeahs": "Indie Rock",
        "Yelawolf": "Hip-Hop",
        "Yellowcard": "Pop Punk",
        "Young De": "Hip-Hop",
        "Young Knives, The": "Indie Rock",
        "Young Seb": "Unknown",
        "Yumiko": "Pop",
        "Zac Brown Band": "Country",
        "Zimmers Hole": "Metal",
        "Zombie Zombie": "Electronic",
        "Zox": "Reggae Rock",
        "Zucchini Drive": "Indie",
        "a'tris": "Rock",
        "dEUS": "Alternative Rock",
        "eMC": "Hip-Hop",
        "t.A.T.u.": "Pop",
        "will.i.am": "Hip-Hop",
        "Željko Samardži?": "Pop",
        "¡Mayday!": "Hip-Hop"
    }

    for entry in data:
        artist_name = entry.get('artist_name')
        if artist_name in genre_map:
            entry['artist_genre'] = genre_map[artist_name]
        elif entry.get('artist_genre') == 'Desconhecido':
             # pass
             pass

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    enrich_genres('data/2008.json')
