import json

def enrich_genres(file_path):
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    genre_map = {
        "1200 Micrograms": "Psytrance",
        "213": "Hip-Hop",
        "311": "Alternative Rock",
        "A Perfect Circle": "Alternative Rock",
        "AFI": "Punk Rock",
        "ATB": "Trance",
        "Aaliyah": "R&B",
        "Adema": "Nu Metal",
        "Air": "Electronic",
        "Akon": "R&B",
        "Alanis Morissette": "Alternative Rock",
        "Alcazar": "Pop / Dance",
        "Alter Bridge": "Post-Grunge",
        "Ana Johnsson": "Pop Rock",
        "Anastacia": "Pop",
        "And You Will Know Us By The Trail Of Dead": "Indie Rock",
        "Angie Stone": "R&B",
        "Animal Collective": "Experimental Pop",
        "Anna Vissi": "Pop",
        "Arcade Fire": "Indie Rock",
        "Arash": "Pop",
        "Ash": "Indie Rock",
        "Ashanti": "R&B",
        "Ashlee Simpson": "Pop Rock",
        "Asian Dub Foundation": "Electronic",
        "Atreyu": "Metalcore",
        "Avril Lavigne": "Pop Punk",
        "B2K": "R&B",
        "Baby Bash": "Hip-Hop",
        "Bad Religion": "Punk Rock",
        "Band Aid 20": "Pop",
        "Barenaked Ladies": "Alternative Rock",
        "Basement Jaxx": "House",
        "Beastie Boys": "Hip-Hop",
        "Beenie Man": "Reggae",
        "Ben Harper": "Folk Rock",
        "Benassi Bros.": "House",
        "Benny Benassi": "House",
        "Beyoncé": "R&B / Pop",
        "Big & Rich": "Country",
        "Björk": "Electronic",
        "Black Eyed Peas": "Hip-Hop / Pop",
        "Blackfield": "Art Rock",
        "Blake Shelton": "Country",
        "Blink-182": "Pop Punk",
        "Bloc Party": "Indie Rock",
        "Blonde Redhead": "Indie Rock",
        "Blue": "Pop",
        "Bowling For Soup": "Pop Punk",
        "Brand New": "Emo",
        "Brandy": "R&B",
        "Breaking Benjamin": "Post-Grunge",
        "Brian McFadden": "Pop",
        "Britney Spears": "Pop",
        "Brooke Valentine": "R&B",
        "Bryan Adams": "Rock",
        "Busta Rhymes": "Hip-Hop",
        "Caesars": "Indie Rock",
        "Cake": "Alternative Rock",
        "Calogero": "Chanson",
        "Cam'ron": "Hip-Hop",
        "Cassidy": "Hip-Hop",
        "Chevelle": "Alternative Metal",
        "Chingy": "Hip-Hop",
        "Christina Milian": "R&B",
        "Chronic Future": "Nu Metal",
        "Ciara": "R&B",
        "Coheed and Cambria": "Progressive Rock",
        "Coldplay": "Alternative Rock",
        "Converge": "Metalcore",
        "Corneille": "R&B",
        "Counting Crows": "Alternative Rock",
        "Cradle Of Filth": "Extreme Metal",
        "Cross-Fade": "Post-Grunge",
        "Crossfade": "Post-Grunge",
        "Cypress Hill": "Hip-Hop",
        "D12": "Hip-Hop",
        "Daddy Yankee": "Reggaeton",
        "Damien Rice": "Folk",
        "Danzig": "Heavy Metal",
        "Darren Hayes": "Pop",
        "Dashboard Confessional": "Emo",
        "David Guetta": "House",
        "De La Soul": "Hip-Hop",
        "Dead 60s": "Ska / Punk",
        "Death From Above 1979": "Dance-Punk",
        "Delta Goodrem": "Pop",
        "Destiny's Child": "R&B",
        "Diana Krall": "Jazz",
        "Dido": "Pop",
        "Die Toten Hosen": "Punk Rock",
        "Dillinger Escape Plan": "Mathcore",
        "Dizzee Rascal": "Grime",
        "Donavon Frankenreiter": "Folk Rock",
        "Dope": "Nu Metal",
        "Doves": "Indie Rock",
        "Dr. Dre": "Hip-Hop",
        "Drake Bell": "Pop Rock",
        "Dream Theater": "Progressive Metal",
        "Dresden Dolls, The": "Dark Cabaret",
        "Duran Duran": "New Wave",
        "E-Type": "Eurodance",
        "Eamon": "R&B",
        "Earshot": "Nu Metal",
        "Eighteen Visions": "Metalcore",
        "El Canto del Loco": "Pop Rock",
        "Eminem": "Hip-Hop",
        "Enrique Iglesias": "Latin Pop",
        "Eric Prydz": "House",
        "Estopa": "Rumba Rock",
        "Evanescence": "Rock / Goth",
        "Exodus": "Thrash Metal",
        "Fabolous": "Hip-Hop",
        "Faithless": "Electronic",
        "Fall Out Boy": "Pop Punk",
        "Fantasia": "R&B",
        "Fatboy Slim": "Big Beat",
        "Fear Factory": "Industrial Metal",
        "Feist": "Indie Pop",
        "Fergie": "Pop",
        "Ferry Corsten": "Trance",
        "Finger Eleven": "Alternative Rock",
        "Flogging Molly": "Celtic Punk",
        "Florence + The Machine": "Indie Pop", # Too early?
        "Franz Ferdinand": "Indie Rock",
        "Freestylers": "Breakbeat",
        "Futureheads, The": "Post-Punk Revival",
        "G-Unit": "Hip-Hop",
        "Gavin DeGraw": "Pop Rock",
        "George Michael": "Pop",
        "Ghostface Killah": "Hip-Hop",
        "Girls Aloud": "Pop",
        "Global Deejays": "Electronic",
        "Gnarls Barkley": "Soul / Pop", # 2006 actually
        "Go! Team, The": "Indie Pop",
        "Godsmack": "Nu Metal",
        "Goldie Lookin Chain": "Hip-Hop",
        "Good Charlotte": "Pop Punk",
        "Gorillaz": "Alternative",
        "Graham Coxon": "Indie Rock",
        "Green Day": "Punk Rock",
        "Gretchen Wilson": "Country",
        "Groove Coverage": "Eurodance",
        "Gwen Stefani": "Pop",
        "Gym Class Heroes": "Hip-Hop / Rock",
        "HIM": "Gothic Rock",
        "Handsome Boy Modeling School": "Hip-Hop",
        "Hanson": "Pop Rock",
        "Hawthorne Heights": "Emo",
        "Hilary Duff": "Pop",
        "Hoobastank": "Rock",
        "Hope of the States": "Indie Rock",
        "Houston": "R&B",
        "Howie Day": "Pop Rock",
        "Hug": "Unknown",
        "I Am Kloot": "Indie Rock",
        "Incubus": "Alternative Rock",
        "In Flames": "Melodic Death Metal",
        "Infernal": "Dance",
        "Interpol": "Post-Punk Revival",
        "Iron & Wine": "Indie Folk",
        "J-Kwon": "Hip-Hop",
        "J. Holiday": "R&B",
        "Jack Johnson": "Folk Rock",
        "Jadakiss": "Hip-Hop",
        "Jamelia": "R&B",
        "Jamie Cullum": "Jazz Pop",
        "Jamiroquai": "Funk / Acid Jazz",
        "Janet Jackson": "R&B / Pop",
        "Jason Mraz": "Pop Rock",
        "Jay-Z": "Hip-Hop",
        "Jem": "Pop / Trip Hop",
        "Jennifer Lopez": "Pop / R&B",
        "Jesse McCartney": "Pop",
        "Jessica Simpson": "Pop",
        "Jet": "Rock",
        "Jill Scott": "Neo Soul",
        "Jimmy Eat World": "Emo / Rock",
        "JoJo": "R&B / Pop",
        "John Frusciante": "Experimental Rock",
        "John Legend": "R&B",
        "John Mayer": "Pop Rock",
        "JoJo": "R&B / Pop",
        "Josh Groban": "Pop",
        "Joss Stone": "Soul",
        "Juanes": "Latin Pop",
        "Junior Jack": "House",
        "K-Maro": "Hip-Hop",
        "Kaiser Chiefs": "Indie Rock",
        "Kanye West": "Hip-Hop",
        "Kasabian": "Indie Rock",
        "Keane": "Piano Rock",
        "Keith Urban": "Country",
        "Kelis": "R&B",
        "Kelly Clarkson": "Pop Rock",
        "Kenny Chesney": "Country",
        "Kent": "Indie Rock",
        "Keri Hilson": "R&B",
        "Kevin Lyttle": "Soca",
        "Killers, The": "Indie Rock",
        "Killing Joke": "Post-Punk",
        "Kings Of Leon": "Rock",
        "Korn": "Nu Metal",
        "Kylie Minogue": "Pop",
        "LCD Soundsystem": "Dance-Punk",
        "LL Cool J": "Hip-Hop",
        "Lamb of God": "Groove Metal",
        "Lara Fabian": "Pop",
        "Laura Pausini": "Pop",
        "LeAnn Rimes": "Country",
        "Lemar": "R&B",
        "Lenny Kravitz": "Rock",
        "Less Than Jake": "Ska Punk",
        "Libertines, The": "Indie Rock",
        "Lil Flip": "Hip-Hop",
        "Lil Jon": "Hip-Hop",
        "Lil' Romeo": "Hip-Hop",
        "Lil' Scrappy": "Hip-Hop",
        "Limp Bizkit": "Nu Metal",
        "Lindsay Lohan": "Pop",
        "Linkin Park": "Nu Metal",
        "Lloyd": "R&B",
        "Lloyd Banks": "Hip-Hop",
        "Los Lonely Boys": "Rock",
        "Lostprophets": "Rock",
        "Ludacris": "Hip-Hop",
        "M.I.A.": "Hip-Hop / Electronic",
        "M83": "Electronic",
        "Madvillain": "Hip-Hop",
        "Manic Street Preachers": "Alternative Rock",
        "Mario": "R&B",
        "Mario Winans": "R&B",
        "Maroon 5": "Pop Rock",
        "Martin Solveig": "House",
        "Mary J. Blige": "R&B",
        "Mase": "Hip-Hop",
        "Master P": "Hip-Hop",
        "Mastodon": "Metal",
        "Megadeth": "Thrash Metal",
        "Melendi": "Pop Rock",
        "Melissa Etheridge": "Rock",
        "Method Man": "Hip-Hop",
        "Michael Bublé": "Jazz / Pop",
        "Michael Gray": "House",
        "Michelle Branch": "Pop Rock",
        "Midtown": "Pop Punk",
        "Ministry": "Industrial Metal",
        "Missy Elliott": "Hip-Hop",
        "Modest Mouse": "Indie Rock",
        "Monica": "R&B",
        "Morrissey": "Indie Pop",
        "Mos Def": "Hip-Hop",
        "Motörhead": "Heavy Metal",
        "Muse": "Alternative Rock",
        "Musiq": "R&B",
        "My Chemical Romance": "Emo / Rock",
        "Mylo": "Electronic",
        "N.E.R.D.": "Hip-Hop / Rock",
        "N.O.R.E.": "Hip-Hop",
        "Nas": "Hip-Hop",
        "Natasha Bedingfield": "Pop",
        "Nelly": "Hip-Hop",
        "Nelly Furtado": "Pop",
        "New Found Glory": "Pop Punk",
        "Nick Cave & The Bad Seeds": "Alternative Rock",
        "Nickelback": "Post-Grunge",
        "Nightwish": "Symphonic Metal",
        "Nina Sky": "R&B",
        "Nine Inch Nails": "Industrial Rock",
        "Nirvana": "Grunge",
        "No Doubt": "Ska / Pop",
        "Norah Jones": "Jazz / Pop",
        "O-Zone": "Eurodance",
        "Oasis": "Britpop",
        "Omarion": "R&B",
        "OutKast": "Hip-Hop",
        "P.O.D.": "Nu Metal",
        "Papa Roach": "Nu Metal",
        "Paul Oakenfold": "Trance",
        "Paul van Dyk": "Trance",
        "Paulina Rubio": "Latin Pop",
        "Pearl Jam": "Grunge",
        "Pet Shop Boys": "Synthpop",
        "Peter Bjorn and John": "Indie Pop",
        "Petey Pablo": "Hip-Hop",
        "Phantom Planet": "Alternative Rock",
        "Phoenix": "Indie Pop",
        "Pink": "Pop",
        "Pitbull": "Hip-Hop",
        "Placebo": "Alternative Rock",
        "Prince": "Funk / Pop",
        "Prodigy": "Big Beat",
        "Pryda": "House",
        "Puddle Of Mudd": "Post-Grunge",
        "Queen": "Rock",
        "R. Kelly": "R&B",
        "R.E.M.": "Alternative Rock",
        "Rachel Stevens": "Pop",
        "Rammstein": "Industrial Metal",
        "Rascal Flatts": "Country",
        "Ray Charles": "R&B / Soul",
        "Razorlight": "Indie Rock",
        "Red Hot Chili Peppers": "Funk Rock",
        "Relient K": "Pop Punk",
        "Rick Ross": "Hip-Hop",
        "Rise Against": "Punk Rock",
        "Robbie Williams": "Pop",
        "Rammstein": "Industrial Metal",
        "Rooney": "Indie Rock",
        "Roots Manuva": "Hip-Hop",
        "Ruben Studdard": "R&B",
        "Rufus Wainwright": "Baroque Pop",
        "Rush": "Progressive Rock",
        "Ryan Adams": "Alt-Country",
        "Ryan Cabrera": "Pop Rock",
        "S Club 8": "Pop",
        "Saliva": "Nu Metal",
        "Sarah McLachlan": "Pop",
        "Saves The Day": "Emo",
        "Scissor Sisters": "Pop / Disco",
        "Scooter": "Techno",
        "Seether": "Post-Grunge",
        "Shaggy": "Reggae",
        "Shania Twain": "Country",
        "Shapeshifters": "House",
        "Simple Plan": "Pop Punk",
        "Siouxsie Sioux": "Post-Punk",
        "Skindred": "Reggae Metal",
        "Slayer": "Thrash Metal",
        "Slipknot": "Nu Metal",
        "Snoop Dogg": "Hip-Hop",
        "Snow Patrol": "Indie Rock",
        "Social Distortion": "Punk Rock",
        "Sonic Youth": "Alternative Rock",
        "Sophie Ellis-Bextor": "Pop / Disco",
        "Soulwax": "Electronic",
        "Sparta": "Post-Hardcore",
        "Spiderbait": "Alternative Rock",
        "Stars": "Indie Pop",
        "Starsailor": "Indie Rock",
        "Stereophonics": "Rock",
        "Story of the Year": "Post-Hardcore",
        "Streets, The": "UK Garage",
        "Sugababes": "Pop",
        "Sugarland": "Country",
        "Sum 41": "Pop Punk",
        "Super Furry Animals": "Indie Rock",
        "Switchfoot": "Alternative Rock",
        "T.I.": "Hip-Hop",
        "Taking Back Sunday": "Emo",
        "Talib Kweli": "Hip-Hop",
        "Tears For Fears": "New Wave",
        "Terror Squad": "Hip-Hop",
        "The 411": "R&B",
        "The Academy Is...": "Pop Punk",
        "The Arcade Fire": "Indie Rock",
        "The Bees": "Indie Rock",
        "The Black Keys": "Blues Rock",
        "The Bravery": "Post-Punk Revival",
        "The Calling": "Rock",
        "The Chemical Brothers": "Big Beat",
        "The Concretes": "Indie Pop",
        "The Corrs": "Pop Rock",
        "The Cure": "Gothic Rock",
        "The Darkness": "Glam Rock",
        "The Dears": "Indie Rock",
        "The Delgados": "Indie Rock",
        "The Dillinger Escape Plan": "Mathcore",
        "The Distillers": "Punk Rock",
        "The Dresden Dolls": "Dark Cabaret",
        "The Explosion": "Punk Rock",
        "The Faint": "Dance-Punk",
        "The Features": "Indie Rock",
        "The Futureheads": "Post-Punk Revival",
        "The Game": "Hip-Hop",
        "The Go! Team": "Indie Pop",
        "The Hives": "Garage Rock",
        "The Killers": "Indie Rock",
        "The Kills": "Indie Rock",
        "The Libertines": "Indie Rock",
        "The Lonely Island": "Comedy",
        "The Mars Volta": "Progressive Rock",
        "The Music": "Rock",
        "The Ordinary Boys": "Indie Rock",
        "The Polyphonic Spree": "Choral Rock",
        "The Postal Service": "Indie Pop",
        "The Prodigy": "Big Beat",
        "The Rasmus": "Rock",
        "The Roots": "Hip-Hop",
        "The Shins": "Indie Rock",
        "The Sounds": "New Wave",
        "The Streets": "UK Garage",
        "The Strokes": "Indie Rock",
        "The Thrills": "Indie Rock",
        "The Used": "Post-Hardcore",
        "The Vines": "Garage Rock",
        "The Von Bondies": "Garage Rock",
        "The Walkmen": "Indie Rock",
        "The Zutons": "Indie Rock",
        "They Might Be Giants": "Alternative Rock",
        "Three Days Grace": "Rock",
        "Thrice": "Post-Hardcore",
        "Tiësto": "Trance",
        "Tim McGraw": "Country",
        "Tina Turner": "R&B / Rock",
        "Toby Keith": "Country",
        "Tom Waits": "Experimental",
        "Tony Yayo": "Hip-Hop",
        "Trick Daddy": "Hip-Hop",
        "Twista": "Hip-Hop",
        "U2": "Rock",
        "UNKLE": "Electronic",
        "Unwritten Law": "Punk Rock",
        "Usher": "R&B",
        "Utada Hikaru": "J-Pop",
        "VS": "R&B",
        "Van Hunt": "R&B",
        "Velvet Revolver": "Hard Rock",
        "Vitas": "Pop",
        "Von Bondies, The": "Garage Rock",
        "Weezer": "Alternative Rock",
        "Westlife": "Pop",
        "Wilco": "Alternative Rock",
        "Will Young": "Pop",
        "William Hung": "Comedy",
        "Within Temptation": "Symphonic Metal",
        "Wolfman (3)": "Indie",
        "X-zibit": "Hip-Hop",
        "Xzibit": "Hip-Hop",
        "Yeah Yeah Yeahs": "Indie Rock",
        "Yellowcard": "Pop Punk",
        "Ying Yang Twins": "Hip-Hop",
        "Young Buck": "Hip-Hop",
        "Zero 7": "Downtempo",
        "Zutons, The": "Indie Rock",
        "dead prez": "Hip-Hop",
        "mewithoutYou": "Post-Hardcore"
    }

    for entry in data:
        artist_name = entry.get('artist_name')
        if artist_name in genre_map:
            entry['artist_genre'] = genre_map[artist_name]
        elif entry.get('artist_genre') == 'Desconhecido':
             # pass
             pass

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    enrich_genres('data/2004.json')
