import json
import os

# Define the path to the JSON file
file_path = '/Users/andresugai/Desktop/PROJETOS/retroclip/data/2021.json'

# Genre mapping
genre_map = {
    # 2021 Specific / Recent
    "Olivia Rodrigo": "Pop",
    "Måneskin": "Rock Alternativo",
    "Silk Sonic": "R&B",
    "Lil Nas X": "Pop",
    "The Kid LAROI": "Pop",
    "Justin Bieber": "Pop",
    "Doja Cat": "Pop",
    "Glass Animals": "Pop",
    "Masked Wolf": "Rap",
    "Polo G": "Rap",
    "Tiësto": "Eletronico",
    "Bad Bunny": "Latin",
    "Ed Sheeran": "Pop",
    "BTS": "K-Pop",
    "Giveon": "R&B",
    "SZA": "R&B",
    "Kali Uchis": "R&B",
    "Dua Lipa": "Pop",
    "Bella Poarch": "Pop",
    "Poarch": "Pop",
    "Billie Eilish": "Pop",
    "Adele": "Pop",
    "Taylor Swift": "Pop",
    "Coldplay": "Pop",
    "The Weeknd": "Pop",
    "Post Malone": "Pop",
    "Megan Thee Stallion": "Rap",
    "Cardi B": "Rap",
    "Drake": "Rap",
    "Kanye West": "Rap",
    "J. Cole": "Rap",
    "Tyler, The Creator": "Rap",
    "Doja Cat": "Pop",
    "SZA": "R&B",
    "Ariana Grande": "Pop",
    
    # From 2021.json view
    "Moise": "R&B", # Guessing/Generalizing
    "Kemme": "Pop",
    "ISLAND": "Indie",
    "iyla": "R&B",
    "Sylph": "Eletronico",
    "Iceage": "Punk",
    "GURLDOLL": "Pop",
    "Sorry": "Indie",
    "Folknery": "Indie",
    "Afgan": "Pop",
    "oddCouple": "Rap",
    "Quadeca": "Rap",
    "Dotan": "Indie",
    "Eluera": "Pop",
    "tiLLie": "Pop",
    "Zanias": "Eletronico",
    "Onlychild": "Indie",
    "frau": "Pop",
    "Elanur": "Rap",
    "Aventura": "Latin",
    "Esty": "Latin",
    "Zokush": "Rap",
    "Raye": "Pop",
    "Odette": "Indie",
    "NAO": "R&B",
    "Zahara": "Indie",
    "Photay": "Eletronico",
    "Joesef": "Indie",
    "Welshy": "Eletronico",
    "Bahari": "Pop",
    "Roxen": "Pop",
    "FLOSS": "Pop",
    "FINE": "Pop",
    "22Gz": "Rap",
    "Ponette": "Pop",
    "Chiiild": "Indie",
    "Elderbrook": "Dance",
    "Scenes": "Rock Alternativo",
    "Cots": "Indie",
    "ELLIANA": "Pop",
    "Marlhy": "Pop",
    "PUSHER": "Eletronico",
    "Flossing": "Indie",
    "Ameliarose": "Pop",
    "Camie": "Indie",
    "Omotola": "Pop",
    "Remble": "Rap",
    "Poppy": "Metal",
    "carpetgarden": "Indie",
    "Angèle": "Pop",
    "Nectar": "Indie",
    "Haiyti": "Rap",
    "Salmo": "Rap",
    "Bicep": "Eletronico",
    "Shygirl": "Eletronico",
    "Brijean": "Indie",
    "Gallant": "R&B",
    "Télépopmusik": "Eletronico",
    "darkDARK": "Eletronico",
    "R3HAB": "Eletronico",
    "Grouplove": "Indie",
    "Crumb": "Indie",
    "Smerz": "Eletronico",
    "SOULFIA": "Pop",
    "Grae": "Pop",
    "Birdy": "Indie",
    "AYA": "Eletronico",
    "Cassidi": "Pop",
    "CA$HRINA": "Pop",
    "Cappa": "Pop",
    "Asukal": "Pop",
    "Maeta": "R&B",
    "Sumner": "Indie",
    "CFCF": "Eletronico",
    "FLETCHER": "Pop",
    "Swerfey": "Pop",
    "Elisa": "Pop",
    "Bawrut": "Eletronico",
    "Mastodon": "Metal",
    "2TON": "Rap",
    "kiskadee": "Eletronico",
    "Venerus": "Indie",
    "ÄTNA": "Eletronico",
    "Taeyeon": "K-Pop",
    "Aziya": "Rock Alternativo",
    "Ginesse": "Pop",
    "Brothertiger": "Eletronico",
    "moistbreezy": "Pop",
    "Little Big": "Eletronico",
    "Tokio Hotel": "Rock Alternativo",
    "Christina Aguilera": "Pop",
    "Bazzi": "Pop",
    "kenzie": "Pop",
    "Tananai": "Pop",
    "Bugo": "Pop",
    "Mahmood": "Pop",
    "Galeffi": "Pop",
    "Sody": "Pop",
    "Clea": "Pop",
    "Drauve": "Pop",
    "YDE": "Pop",
    "Anto": "Pop",
    "REEZA": "Pop",
    "Gloria": "Pop",
    "Cara": "Pop",
    "NUUXS": "Pop",
    "CXLOE": "Pop",
    "Roshelle": "Pop",
    "Bianco": "Pop",
    "Hurts": "Pop",
    "Nicolina": "Pop",
    "Mothica": "Pop",
    "Cloves": "Pop",
    "renforshort": "Pop",
    "Cher": "Pop",
    "Joji": "Pop",
    "Bastille": "Rock Alternativo",
    "Bleachers": "Rock Alternativo",
    "Beabadoobee": "Rock Alternativo",
    "Samia": "Rock Alternativo",
    "Korine": "Rock Alternativo",
    "Glom": "Rock Alternativo",
    "Zilched": "Rock Alternativo",
    "Gordi": "Rock Alternativo",
    "Stealth": "Rock Alternativo",
    "Lil Uzi Vert": "Rap",
    "Blueface": "Rap",
    "6IX9INE": "Rap",
    "FLOHIO": "Rap",
    "Jackboy": "Rap",
    "Ghali": "Rap",
    "Toosii": "Rap",
    "Merkules": "Rap",
    "Separate": "Rap",
    "Bones": "Rap",
    "P38": "Rap",
    "Arca": "Eletronico",
    "Mentrix": "Eletronico",
    "Porches": "Eletronico",
    "Tennyson": "Eletronico",
    "Lorn": "Eletronico",
    "Tomode": "Eletronico",
    "Delaurentis": "Eletronico",
    "Fakear": "Eletronico",
    "Disclosure": "Eletronico",
    "MYNTH": "Eletronico",
    "SEVDALIZA": "Eletronico",
    "Neumodel": "Eletronico",
    "Laumė": "Eletronico",
    "ONR": "Eletronico",
    "AJR": "Indie",
    "Êmia": "Indie",
    "Sycco": "Indie",
    "Transviolet": "Indie",
    "Mysie": "Indie",
    "Lysandre": "Indie",
    "Mammals": "Indie",
    "Daniela Andrade": "Indie",
    "Prado": "Indie",
    "Gazzelle": "Indie",
    "Deftones": "Metal",
    "Naglfar": "Metal",
    "Lunay": "Latin",
    "Cazzu": "Latin",
    "IZ*ONE": "K-Pop",
    "Nahaze": "Dance",
    "CamelPhat": "Dance",
    "Joel Corry": "Dance",
    "Jax Jones": "Dance",
    "Regard": "Dance",
    "Topic": "Dance",
    "Imanbek": "Dance",
    "SAINt JHN": "Dance",
    "Ciara": "R&B",
    "Niia": "R&B",
    "Zaia": "R&B",
    "John Legend": "R&B",
    "H.E.R.": "R&B",
    "Kehlani": "R&B",
    "Chloe x Halle": "R&B",
    "Jhené Aiko": "R&B",
    "Victoria Monét": "R&B",
    "Thundercat": "R&B",
    "FKA twigs": "R&B",
    "Tinashe": "R&B",
    "Brandy": "R&B",
    "JoJo": "R&B",
    "Snoh Aalegra": "R&B",
    "Anderson .Paak": "R&B",
    "Beyoncé": "R&B",
    "Black Pumas": "R&B",
    "Bruno Mars": "R&B",
    "Chris Brown": "R&B",
    "Frank Ocean": "R&B",
    "Jorja Smith": "R&B",
    "Mariah Carey": "R&B",
    "Solange": "R&B",
    "Summer Walker": "R&B",
    "Teyana Taylor": "R&B",
    "The Internet": "R&B",
    "Ty Dolla $ign": "R&B",
    "Usher": "R&B",
    "Lady Gaga": "Pop",
    "Harry Styles": "Pop",
    "Miley Cyrus": "Pop",
    "Selena Gomez": "Pop",
    "Halsey": "Pop",
    "Katy Perry": "Pop",
    "Shawn Mendes": "Pop",
    "Sam Smith": "Pop",
    "Demi Lovato": "Pop",
    "Camila Cabello": "Pop",
    "Ava Max": "Pop",
    "Charli XCX": "Pop",
    "Rina Sawayama": "Pop",
    "Conan Gray": "Pop",
    "Lauv": "Pop",
    "Troye Sivan": "Pop",
    "Julia Michaels": "Pop",
    "Zara Larsson": "Pop",
    "Little Mix": "Pop",
    "BLACKPINK": "K-Pop",
    "Stray Kids": "K-Pop",
    "TWICE": "K-Pop",
    "Red Velvet": "K-Pop",
    "ITZY": "K-Pop",
    "LOONA": "K-Pop",
    "TXT": "K-Pop",
    "NCT 127": "K-Pop",
    "MONSTA X": "K-Pop",
    "SuperM": "K-Pop",
    "EVERGLOW": "K-Pop",
    "Mamamoo": "K-Pop",
    "GFRIEND": "K-Pop",
    "Lizzo": "Pop",
    "Maroon 5": "Pop",
    "Lewis Capaldi": "Pop",
    "Niall Horan": "Pop",
    "ZAYN": "Pop",
    "Zayn Malik": "Pop",
    "Liam Payne": "Pop",
    "Louis Tomlinson": "Pop",
    "5 Seconds of Summer": "Pop",
    "Jonas Brothers": "Pop",
    "Twenty One Pilots": "Pop",
    "Machine Gun Kelly": "Pop", 
    "YUNGBLUD": "Pop",
    "blackbear": "Pop",
    "Tate McRae": "Pop",
    "FINNEAS": "Pop",
    "BENEE": "Pop",
    "Ashnikko": "Pop",
    "Nicki Minaj": "Rap",
    "Sia": "Pop",
    "Kylie Minogue": "Pop",
    "Sophie Ellis-Bextor": "Pop",
    "Jessie Ware": "Pop",
    "Carly Rae Jepsen": "Pop",
    "Tove Lo": "Pop",
    "Kim Petras": "Pop",
    "Grimes": "Eletronico",
    "Purity Ring": "Eletronico",
    "CHVRCHES": "Eletronico",
    "Gorillaz": "Pop",
    "Tame Impala": "Pop",
    "The 1975": "Pop",
    "LANY": "Pop",
    "The Neighbourhood": "Pop",
    "Wallows": "Pop",
    "COIN": "Pop",
    "Dayglow": "Pop",
    "Clairo": "Pop",
    "girl in red": "Pop",
    "beabadoobee": "Rock Alternativo",
    "Phoebe Bridgers": "Indie",
    "Soccer Mommy": "Indie",
    "Snail Mail": "Indie",
    "Mitski": "Indie",
    "Japanese Breakfast": "Indie",
    "Big Thief": "Indie",
    "HAIM": "Pop",
    "Florence + The Machine": "Pop",
    "Lana Del Rey": "Pop",
    "Lorde": "Pop",
    "Marina": "Pop",
    "St. Vincent": "Rock Alternativo",
    "Fiona Apple": "Rock Alternativo",
    "Perfume Genius": "Indie",
    "Moses Sumney": "Indie",
    "Yves Tumor": "Indie",
    "SOPHIE": "Eletronico",
    "100 gecs": "Eletronico",
    "Dorian Electra": "Pop",
    "Caroline Polachek": "Pop",
    "Christine and the Queens": "Pop",
    "Shura": "Pop",
    "Empress Of": "Pop",
    "U.S. Girls": "Pop",
    "Róisín Murphy": "Pop",
    "Yaeji": "Eletronico",
    "Kelly Lee Owens": "Eletronico",
    "Four Tet": "Eletronico",
    "Caribou": "Eletronico",
    "Kaytranada": "Eletronico",
    "SG Lewis": "Eletronico",
    "ZHU": "Eletronico",
    "Kygo": "Eletronico",
    "Marshmello": "Eletronico",
    "The Chainsmokers": "Eletronico",
    "Diplo": "Eletronico",
    "Major Lazer": "Eletronico",
    "Calvin Harris": "Eletronico",
    "David Guetta": "Eletronico",
    "Martin Garrix": "Eletronico",
    "Alesso": "Eletronico",
    "Zedd": "Eletronico",
    "Galantis": "Eletronico",
    "Clean Bandit": "Eletronico",
    "Years & Years": "Pop",
    "Imagine Dragons": "Pop",
    "OneRepublic": "Pop",
    "The Killers": "Rock Alternativo",
    "The Strokes": "Rock Alternativo",
    "Arctic Monkeys": "Rock Alternativo",
    "Foals": "Rock Alternativo",
    "Biffy Clyro": "Rock Alternativo",
    "Royal Blood": "Rock Alternativo",
    "Nothing But Thieves": "Rock Alternativo",
    "Bring Me The Horizon": "Rock Alternativo",
    "Enter Shikari": "Rock Alternativo",
    "All Time Low": "Rock Alternativo",
    "Paramore": "Rock Alternativo",
    "Fall Out Boy": "Rock Alternativo",
    "Panic! At The Disco": "Pop",
    "Green Day": "Rock Alternativo",
    "Weezer": "Rock Alternativo",
    "The Smashing Pumpkins": "Rock Alternativo",
    "Pearl Jam": "Rock Alternativo",
    "System Of A Down": "Metal",
    "Slipknot": "Metal",
    "Korn": "Metal",
    "Lamb of God": "Metal",
    "Trivium": "Metal",
    "Code Orange": "Metal",
    "Ghostemane": "Rap",
    "Run The Jewels": "Rap",
    "Kendrick Lamar": "Rap",
    "Travis Scott": "Rap",
    "Future": "Rap",
    "Young Thug": "Rap",
    "Lil Baby": "Rap",
    "DaBaby": "Rap",
    "Roddy Ricch": "Rap",
    "Gunna": "Rap",
    "Pop Smoke": "Rap",
    "Juice WRLD": "Rap",
    "XXXTENTACION": "Rap",
    "Lil Uzi Vert": "Rap",
    "Playboi Carti": "Rap",
    "Lil Yachty": "Rap",
    "Trippie Redd": "Rap",
    "6ix9ine": "Rap",
    "Lil Nas X": "Pop",
    "Jack Harlow": "Rap",
    "24kGoldn": "Pop",
    "iann dior": "Pop",
    "J Balvin": "Latin",
    "Maluma": "Latin",
    "Ozuna": "Latin",
    "Anuel AA": "Latin",
    "Daddy Yankee": "Latin",
    "Rosalía": "Latin",
    "KAROL G": "Latin",
    "Becky G": "Latin",
    "Natti Natasha": "Latin",
    "Shakira": "Latin",
    "Jennifer Lopez": "Pop",
    "Ricky Martin": "Latin",
    "Enrique Iglesias": "Latin",
    "Luis Fonsi": "Latin",
    "Marc Anthony": "Latin",
    "Romeo Santos": "Latin",
    "Prince Royce": "Latin",
    "Luke Combs": "Country",
    "Morgan Wallen": "Country",
    "Kane Brown": "Country",
    "Maren Morris": "Country",
    "Kacey Musgraves": "Country",
    "Dan + Shay": "Country",
    "Florida Georgia Line": "Country",
    "Thomas Rhett": "Country",
    "Carrie Underwood": "Country",
    "Miranda Lambert": "Country",
    "The Chicks": "Country",
    "Keith Urban": "Country",
    "Blake Shelton": "Country",
    "Luke Bryan": "Country",
    "Dolly Parton": "Country",
    "Willie Nelson": "Country",
    "Johnny Cash": "Country",
    "070 Shake": "Rap",
    "A$AP Ferg": "Rap",
    "Against The Current": "Rock Alternativo",
    "Alanis Morissette": "Rock Alternativo",
    "Alec Benjamin": "Pop",
    "Alestorm": "Metal",
    "Aloe Blacc": "R&B",
    "Aluna": "Eletronico",
    "Aminé": "Rap",
    "Amyl and the Sniffers": "Punk",
    "Angel Olsen": "Indie",
    "Anne-Marie": "Pop",
    "Anthony Ramos": "Pop",
    "Apocalyptica": "Metal",
    "Arlo Parks": "Indie",
    "Armin van Buuren": "Eletronico",
    "Asking Alexandria": "Metal",
    "August Burns Red": "Metal",
    "Baby Queen": "Pop",
    "Big Sean": "Rap",
    "Billie Joe Armstrong": "Punk",
    "Black Eyed Peas": "Pop",
    "Blink-182": "Punk",
    "Bloc Party": "Indie",
    "Bon Iver": "Indie",
    "Bon Jovi": "Rock Alternativo",
    "Brockhampton": "Rap",
    "Bruce Springsteen": "Rock Alternativo",
    "Bullet For My Valentine": "Metal",
    "Burna Boy": "Pop",
    "Busta Rhymes": "Rap",
    "Cage The Elephant": "Rock Alternativo",
    "Cannibal Corpse": "Metal",
    "Childish Gambino": "Rap",
    "Coin": "Indie",
    "Cold War Kids": "Indie",
    "Denzel Curry": "Rap",
    "Depeche Mode": "Eletronico",
    "Dixie Chicks": "Country",
    "Dominic Fike": "Indie",
    "Duke Dumont": "Eletronico",
    "Easy Life": "Indie",
    "Eminem": "Rap",
    "Evanescence": "Rock Alternativo",
    "Everything Everything": "Indie",
    "Five Finger Death Punch": "Metal",
    "Fleet Foxes": "Indie",
    "Fontaines D.C.": "Punk",
    "Foo Fighters": "Rock Alternativo",
    "Foster The People": "Indie",
    "G-Eazy": "Rap",
    "Gerard Way": "Rock Alternativo",
    "Headie One": "Rap",
    "I DONT KNOW HOW BUT THEY FOUND ME": "Rock Alternativo",
    "IDLES": "Punk",
    "Icona Pop": "Pop",
    "In This Moment": "Metal",
    "Jason Derulo": "Pop",
    "Jeremy Zucker": "Pop",
    "Khruangbin": "Indie",
    "Kid Cudi": "Rap",
    "King Gizzard & The Lizard Wizard": "Rock Alternativo",
    "Kings of Leon": "Rock Alternativo",
    "Kodak Black": "Rap",
    "Lany": "Pop",
    "Lil Peep": "Rap",
    "Lil Wayne": "Rap",
    "Logic": "Rap",
    "London Grammar": "Indie",
    "Love Fame Tragedy": "Indie",
    "Low": "Indie",
    "Mac Miller": "Rap",
    "Madison Beer": "Pop",
    "Maggie Rogers": "Indie",
    "Marilyn Manson": "Rock Alternativo",
    "Maya Jane Coles": "Eletronico",
    "Melanie Martinez": "Pop",
    "Metronomy": "Indie",
    "Migos": "Rap",
    "Milky Chance": "Indie",
    "Missy Elliott": "Rap",
    "Moby": "Eletronico",
    "Mother Mother": "Indie",
    "Mura Masa": "Eletronico",
    "Muse": "Rock Alternativo",
    "My Chemical Romance": "Rock Alternativo",
    "NLE Choppa": "Rap",
    "Noah Cyrus": "Pop",
    "Norah Jones": "Pop",
    "Of Monsters and Men": "Indie",
    "Oliver Tree": "Rock Alternativo",
    "Orville Peck": "Country",
    "Ozzy Osbourne": "Metal",
    "PVRIS": "Rock Alternativo",
    "Paloma Faith": "Pop",
    "Papa Roach": "Rock Alternativo",
    "Parkway Drive": "Metal",
    "Passenger": "Indie",
    "Paul McCartney": "Rock Alternativo",
    "Phoenix": "Indie",
    "Pink": "Pop",
    "Pitbull": "Pop",
    "Pussycat Dolls": "Pop",
    "Quavo": "Rap",
    "Queen": "Rock Alternativo",
    "Radiohead": "Rock Alternativo",
    "Rage Against The Machine": "Rock Alternativo",
    "Rammstein": "Metal",
    "Rex Orange County": "Indie",
    "Rico Nasty": "Rap",
    "Rihanna": "Pop",
    "Rita Ora": "Pop",
    "Saweetie": "Rap",
    "Schoolboy Q": "Rap",
    "Sepultura": "Metal",
    "Skrillex": "Eletronico",
    "Slowthai": "Rap",
    "Snoop Dogg": "Rap",
    "Sofi Tukker": "Eletronico",
    "Steve Aoki": "Eletronico",
    "Stormzy": "Rap",
    "Tegan and Sara": "Indie",
    "Tekashi 6ix9ine": "Rap",
    "The Avalanches": "Eletronico",
    "The Chicks": "Country",
    "The Pussycat Dolls": "Pop",
    "The Strokes": "Rock Alternativo",
    "The xx": "Indie",
    "Tones And I": "Pop",
    "Two Door Cinema Club": "Indie",
    "Tyler, The Creator": "Rap",
    "U2": "Rock Alternativo",
    "Vampire Weekend": "Indie",
    "Vance Joy": "Indie",
    "Washed Out": "Indie",
    "Wiz Khalifa": "Rap",
    "Wolf Alice": "Rock Alternativo",
    "Woodkid": "Indie",
    "Wu-Tang Clan": "Rap",
    "Yellow Days": "Indie",
}

def enrich_genres():
    if not os.path.exists(file_path):
        print(f"Error: File not found at {file_path}")
        return

    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    updated_count = 0
    unknown_artists = set()

    genre_map_lower = {k.lower(): v for k, v in genre_map.items()}

    for entry in data:
        artist = entry.get('artist_name')
        if not artist:
            continue
            
        genre = genre_map.get(artist)
        if not genre:
            genre = genre_map_lower.get(str(artist).lower())
            
        if genre:
            entry['artist_genre'] = genre
            updated_count += 1
        else:
            if entry.get('artist_genre') == 'Desconhecido' or not entry.get('artist_genre'):
                unknown_artists.add(artist)

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Successfully updated {updated_count} entries in {file_path}")
    if unknown_artists:
        print(f"\nArtists without genre mapping ({len(unknown_artists)}):")
        for artist in sorted([str(a) for a in unknown_artists]):
            print(f"- {artist}")

if __name__ == "__main__":
    enrich_genres()
