import json
import os

# Define the path to the JSON file
file_path = '/Users/andresugai/Desktop/PROJETOS/retroclip/data/2024.json'

# Genre mapping
genre_map = {
    # 2024 Specific / Recent Hits
    "Laufey": "Jazz / Pop",
    "Lisa": "K-Pop",
    "Tyla": "R&B",
    "Sabrina Carpenter": "Pop",
    "Chappell Roan": "Pop",
    "Benson Boone": "Pop",
    "Teddy Swims": "R&B",
    "Shaboozey": "Country / Rap",
    "Tommy Richman": "R&B",
    "Kendrick Lamar": "Rap",
    "Future": "Rap",
    "Metro Boomin": "Rap",
    "Hozier": "Rock Alternativo",
    "Post Malone": "Country", # He went country in 2024
    "Morgan Wallen": "Country",
    "Billie Eilish": "Pop",
    "Taylor Swift": "Pop",
    "Ariana Grande": "Pop",
    "Dua Lipa": "Pop",
    "Beyoncé": "Country", # Cowboy Carter
    "Charli XCX": "Pop", # BRAT summer
    "SZA": "R&B",
    "Doja Cat": "Rap",
    "Jack Harlow": "Rap",
    "Tate McRae": "Pop",
    "Flo Milli": "Rap",
    "Ice Spice": "Rap",
    "Sexyy Red": "Rap",
    "Offset": "Rap",
    "Gunna": "Rap",
    "21 Savage": "Rap",
    "Drake": "Rap",
    "The Weeknd": "Pop",
    "Olivia Rodrigo": "Pop",
    "Miley Cyrus": "Pop",
    "Sia": "Pop",
    "Kylie Minogue": "Pop",
    "Troye Sivan": "Pop",
    "Reneé Rapp": "Pop",
    "Victoria Monét": "R&B",
    "Coco Jones": "R&B",
    "Muni Long": "R&B",
    "Jungle": "Eletronico",
    "Fred again..": "Eletronico",
    "Peggy Gou": "Eletronico",
    "Fisher": "Eletronico",
    "Calvin Harris": "Eletronico",
    "David Guetta": "Eletronico",
    "Tiësto": "Eletronico",
    "Dom Dolla": "Eletronico",
    "John Summit": "Eletronico",
    "Peso Pluma": "Latin",
    "Bad Bunny": "Latin",
    "Karol G": "Latin",
    "Shakira": "Latin",
    "Feid": "Latin",
    "Rauw Alejandro": "Latin",
    "Anitta": "Latin",
    "Kali Uchis": "R&B",
    "NewJeans": "K-Pop",
    "Le Sserafim": "K-Pop",
    "Jungkook": "K-Pop",
    "V": "K-Pop",
    "Jimin": "K-Pop",
    "RM": "K-Pop",
    "Agust D": "K-Pop",
    "j-hope": "K-Pop",
    "TxT": "K-Pop",
    "Stray Kids": "K-Pop",
    "Seventeen": "K-Pop",
    "Aespa": "K-Pop",
    "IVE": "K-Pop",
    "(G)I-DLE": "K-Pop",
    "ATEEZ": "K-Pop",
    "ENHYPEN": "K-Pop",
    "ITZY": "K-Pop",
    "NMIXX": "K-Pop",
    "StayC": "K-Pop",
    "Kiss of Life": "K-Pop",
    "BABYMONSTER": "K-Pop",
    "ILLIT": "K-Pop",
    "TWS": "K-Pop",
    "RIIZE": "K-Pop",
    "BOYNEXTDOOR": "K-Pop",
    "ZEROBASEONE": "K-Pop",
    
    # From 2024.json view
    "Fabri Fibra": "Rap",
    "Coma_Cose": "Indie",
    "Jovanotti": "Pop",
    "Booba": "Rap",
    "Go_A": "Eletronico",
    "Bugo": "Rock Alternativo",
    "Lazza": "Rap",
    "Bloodywood": "Metal",
    "Piotta": "Rap",
    "Shinedown": "Rock Alternativo",
    "6IX9INE": "Rap",
    "NIKI": "Pop",
    "Annalisa": "Pop",
    "Tinashe": "R&B",
    "Porches": "Indie",
    "2TON": "Rap",
    "Quavo": "Rap",
    "Tedua": "Rap",
    "Jade": "Pop",
    "Latto": "Rap",
    "Lenie": "Pop",
    "Landmvrks": "Metal",
    "Tananai": "Pop",
    "Baest​": "Metal",
    "Paledusk": "Metal",
    "Blackbriar": "Metal",
    "Tripolare": "Pop",
    "Nabi": "Pop",
    "Lacrim": "Rap",
    "Borknagar": "Metal",
    "Folterkammer": "Metal",
    "ElGrandeToto": "Rap",
    "Maninni": "Pop",
    "Echos": "Eletronico",
    "Blanco": "Pop",
    "REMINA": "Metal",
    "Emilia": "Latin",
    "Anomalie": "Eletronico",
    "Fulminacci": "Indie",
    "Alcest": "Metal",
    "L'Aura": "Pop",
    "Tayc": "R&B",
    "Finneas": "Pop",
    "sangiovanni": "Pop",
    "HAEVN": "Pop",
    "Rori": "Pop",
    "Aurora": "Pop",
    "Halsey": "Pop",
    "Starset": "Rock Alternativo",
    "Twice": "K-Pop",
    "ANKOR": "Metal",
    "Ultimo": "Pop",
    "Lacrimosa": "Metal",
    "Brutus": "Rock Alternativo",
    "Noizy": "Rap",
    "Alfa": "Pop",
    "Shygirl": "Eletronico",
    "Xhensila": "Pop",
    "Avaion": "Eletronico",
    "Zedd": "Eletronico",
    "M.I.A.": "Rap",
    "Olly": "Pop",
    "YUNGBLUD": "Rock Alternativo",
    "Aron": "Pop",
    "Kittie": "Metal",
    "SEVDALIZA": "Eletronico",
    "Jennie": "K-Pop",
    "Cosmo": "Pop",
    "Emma": "Pop",
    "Thornhill": "Metal",
    "Yseult": "Pop",
    "Eminem": "Rap",
    "Shablo": "Rap",
    "Mr.Rain": "Pop",
    "Elodie": "Pop",
    "Rondo": "Rap",
    "Cannons": "Indie",
    "Elmatadormc7": "Rap",
    "Lauv": "Pop",
    "half·alive": "Rock Alternativo",
    "PVRIS": "Rock Alternativo",

    # Inheritance from previous years (generalized)
    "Justin Bieber": "Pop",
    "Shawn Mendes": "Pop",
    "Sam Smith": "Pop",
    "Demi Lovato": "Pop",
    "Camila Cabello": "Pop",
    "Ava Max": "Pop",
    "Bebe Rexha": "Pop",
    "Rita Ora": "Pop",
    "Jessie J": "Pop",
    "Meghan Trainor": "Pop",
    "Fifth Harmony": "Pop",
    "Little Mix": "Pop",
    "One Direction": "Pop",
    "5 Seconds of Summer": "Pop",
    "Jonas Brothers": "Pop",
    "Maroon 5": "Pop",
    "Coldplay": "Pop",
    "Imagine Dragons": "Pop",
    "OneRepublic": "Pop",
    "The Script": "Pop",
    "The 1975": "Pop",
    "LANY": "Pop",
    "Bastille": "Pop",
    "Twenty One Pilots": "Pop",
    "Panic! At The Disco": "Pop",
    "Fall Out Boy": "Rock Alternativo",
    "Paramore": "Rock Alternativo",
    "Green Day": "Rock Alternativo",
    "Blink-182": "Rock Alternativo",
    "Avril Lavigne": "Pop",
    "Linkin Park": "Rock Alternativo",
    "Evanescence": "Rock Alternativo",
    "Bring Me The Horizon": "Rock Alternativo",
    "Slipknot": "Metal",
    "Metallica": "Metal",
    "Iron Maiden": "Metal",
    "Slayer": "Metal",
    "Megadeth": "Metal",
    "Anthrax": "Metal",
    "Pantera": "Metal",
    "Judas Priest": "Metal",
    "Black Sabbath": "Metal",
    "Ozzy Osbourne": "Metal",
    "Motorhead": "Metal",
    "System Of A Down": "Metal",
    "Korn": "Metal",
    "Limp Bizkit": "Metal",
    "Deftones": "Metal",
    "Rage Against The Machine": "Rock Alternativo",
    "Red Hot Chili Peppers": "Rock Alternativo",
    "Foo Fighters": "Rock Alternativo",
    "Nirvana": "Rock Alternativo",
    "Pearl Jam": "Rock Alternativo",
    "Soundgarden": "Rock Alternativo",
    "Alice In Chains": "Rock Alternativo",
    "Stone Temple Pilots": "Rock Alternativo",
    "Radiohead": "Rock Alternativo",
    "The Strokes": "Rock Alternativo",
    "Arctic Monkeys": "Rock Alternativo",
    "The Killers": "Rock Alternativo",
    "Arcade Fire": "Indie",
    "Vampire Weekend": "Indie",
    "Phoenix": "Indie",
    "MGMT": "Indie",
    "Empire of the Sun": "Eletronico",
    "Passion Pit": "Indie",
    "Foster The People": "Indie",
    "Two Door Cinema Club": "Indie",
    "The Kooks": "Indie",
    "The Wombats": "Indie",
    "Florence + The Machine": "Indie",
    "Lana Del Rey": "Pop",
    "Marina": "Pop",
    "Lorde": "Pop",
    "Haim": "Pop",
    "Chvrches": "Eletronico",
    "Grimes": "Eletronico",
    "Purity Ring": "Eletronico",
    "Crystal Castles": "Eletronico",
    "M83": "Eletronico",
    "Daft Punk": "Eletronico",
    "Justice": "Eletronico",
    "Kavinsky": "Eletronico",
    "Disclosure": "Eletronico",
    "Flume": "Eletronico",
    "Odesza": "Eletronico",
    "Kygo": "Eletronico",
    "Avicii": "Eletronico",
    "Zedd": "Eletronico",
    "Calvin Harris": "Eletronico",
    "David Guetta": "Eletronico",
    "Tiësto": "Eletronico",
    "Armin van Buuren": "Eletronico",
    "Deadmau5": "Eletronico",
    "Skrillex": "Eletronico",
    "Diplo": "Eletronico",
    "Major Lazer": "Eletronico",
    "DJ Snake": "Eletronico",
    "The Chainsmokers": "Eletronico",
    "Marshmello": "Eletronico",
    "Martin Garrix": "Eletronico",
    "Alan Walker": "Eletronico",
    "Galantis": "Eletronico",
    "Clean Bandit": "Eletronico",
    "Rudimental": "Eletronico",
    "Sigma": "Eletronico",
    "Netsky": "Eletronico",
    "Chase & Status": "Eletronico",
    "Pendulum": "Eletronico",
    "The Prodigy": "Eletronico",
    "Chemical Brothers": "Eletronico",
    "Fatboy Slim": "Eletronico",
    "Moby": "Eletronico",
    "Massive Attack": "Eletronico",
    "Portishead": "Eletronico",
    "Björk": "Eletronico",
    "Aphex Twin": "Eletronico",
    "Boards of Canada": "Eletronico",
    "Four Tet": "Eletronico",
    "Burial": "Eletronico",
    "Flying Lotus": "Eletronico",
    "Thundercat": "R&B",
    "Kamasi Washington": "Jazz",
    "BadBadNotGood": "Jazz",
    "Kaytranada": "Eletronico",
    "Anderson .Paak": "R&B",
    "Frank Ocean": "R&B",
    "Tyler, The Creator": "Rap",
    "Earl Sweatshirt": "Rap",
    "A$AP Rocky": "Rap",
    "Travis Scott": "Rap",
    "Kid Cudi": "Rap",
    "Kanye West": "Rap",
    "Jay-Z": "Rap",
    "Nas": "Rap",
    "Eminem": "Rap",
    "Lil Wayne": "Rap",
    "Drake": "Rap",
    "Nicki Minaj": "Rap",
    "Cardi B": "Rap",
    "Megan Thee Stallion": "Rap",
    "Doja Cat": "Pop",
    "Lizzo": "Pop",
    "SZA": "R&B",
    "Summer Walker": "R&B",
    "H.E.R.": "R&B",
    "Jhene Aiko": "R&B",
    "Kehlani": "R&B",
    "Tinashe": "R&B",
    "Solange": "R&B",
    "Beyoncé": "R&B",
    "Rihanna": "Pop",
    "Janelle Monáe": "R&B",
    "Erykah Badu": "R&B",
    "Lauryn Hill": "R&B",
    "Alicia Keys": "R&B",
    "John Legend": "R&B",
    "Bruno Mars": "Pop",
    "The Weeknd": "Pop",
    "Pharrell Williams": "Pop",
    "Robin Thicke": "R&B",
    "Justin Timberlake": "Pop",
    "Usher": "R&B",
    "Chris Brown": "R&B",
    "Ne-Yo": "R&B",
    "Trey Songz": "R&B",
    "Jeremih": "R&B",
    "Miguel": "R&B",
    "Frank Ocean": "R&B",
    "Daniel Caesar": "R&B",
    "Giveon": "R&B",
    "Brent Faiyaz": "R&B",
    "6LACK": "R&B",
    "Bryson Tiller": "R&B",
    "PartyNextDoor": "R&B",
    "Tory Lanez": "R&B",
    "Ty Dolla $ign": "R&B",
    "Post Malone": "Pop",
    "Swae Lee": "Rap",
    "Rae Sremmurd": "Rap",
    "Migos": "Rap",
    "Future": "Rap",
    "Young Thug": "Rap",
    "Gunna": "Rap",
    "Lil Baby": "Rap",
    "DaBaby": "Rap",
    "Roddy Ricch": "Rap",
    "Polo G": "Rap",
    "Lil Durk": "Rap",
    "King Von": "Rap",
    "Pop Smoke": "Rap",
    "Fivio Foreign": "Rap",
    "21 Savage": "Rap",
    "Kodak Black": "Rap",
    "NBA YoungBoy": "Rap",
    "Lil Uzi Vert": "Rap",
    "Playboi Carti": "Rap",
    "Trippie Redd": "Rap",
    "Juice WRLD": "Rap",
    "XXXTENTACION": "Rap",
    "Ski Mask The Slump God": "Rap",
    "Lil Yachty": "Rap",
    "Lil Tecca": "Rap",
    "Lil Mosey": "Rap",
    "Iann Dior": "Pop",
    "24kGoldn": "Pop",
    "The Kid LAROI": "Pop",
    "Machine Gun Kelly": "Pop",
    "YUNGBLUD": "Pop",
    "Mod Sun": "Pop",
    "Blackbear": "Pop",
    "Jxdn": "Pop",
    "Willow": "Pop",
    "Maggie Lindemann": "Pop",
    "Avril Lavigne": "Pop",
    "Olivia Rodrigo": "Pop",
    "Billie Eilish": "Pop",
    "Finneas": "Pop",
    "Clairo": "Pop",
    "Girl in Red": "Pop",
    "Beabadoobee": "Rock Alternativo",
    "Phoebe Bridgers": "Indie",
    "Mitski": "Indie",
    "Japanese Breakfast": "Indie",
    "Snail Mail": "Indie",
    "Soccer Mommy": "Indie",
    "Big Thief": "Indie",
    "Boygenius": "Indie",
    "Muna": "Pop",
    "Chappell Roan": "Pop",
    "Reneé Rapp": "Pop",
    "Sabrina Carpenter": "Pop",
    "Tate McRae": "Pop",
    "Dove Cameron": "Pop",
    "Madison Beer": "Pop",
    "Nessa Barrett": "Pop",
    "Bella Poarch": "Pop",
    "Addison Rae": "Pop",
    "Dixie D'Amelio": "Pop",
    "Charli D'Amelio": "Pop",
    "Jojo Siwa": "Pop",
    "Troye Sivan": "Pop",
    "Conan Gray": "Pop",
    "Lauv": "Pop",
    "Jeremy Zucker": "Pop",
    "Alec Benjamin": "Pop",
    "Dean Lewis": "Pop",
    "Lewis Capaldi": "Pop",
    "Ed Sheeran": "Pop",
    "James Arthur": "Pop",
    "Niall Horan": "Pop",
    "Harry Styles": "Pop",
    "Louis Tomlinson": "Pop",
    "Liam Payne": "Pop",
    "Zayn": "Pop",
    "BTS": "K-Pop",
    "Blackpink": "K-Pop",
    "Twice": "K-Pop",
    "Red Velvet": "K-Pop",
    "Itzy": "K-Pop",
    "Aespa": "K-Pop",
    "NewJeans": "K-Pop",
    "Le Sserafim": "K-Pop",
    "IVE": "K-Pop",
    "Stray Kids": "K-Pop",
    "TXT": "K-Pop",
    "Enhypen": "K-Pop",
    "Seventeen": "K-Pop",
    "NCT": "K-Pop",
    "NCT 127": "K-Pop",
    "NCT Dream": "K-Pop",
    "WayV": "K-Pop",
    "SuperM": "K-Pop",
    "EXO": "K-Pop",
    "SHINee": "K-Pop",
    "Super Junior": "K-Pop",
    "Girls' Generation": "K-Pop",
    "2NE1": "K-Pop",
    "BigBang": "K-Pop",
    "Psy": "K-Pop",
    "Bad Bunny": "Latin",
    "J Balvin": "Latin",
    "Maluma": "Latin",
    "Ozuna": "Latin",
    "Daddy Yankee": "Latin",
    "Nicky Jam": "Latin",
    "Wisin & Yandel": "Latin",
    "Don Omar": "Latin",
    "Anuel AA": "Latin",
    "Karol G": "Latin",
    "Becky G": "Latin",
    "Natti Natasha": "Latin",
    "Rosalía": "Latin",
    "Rauw Alejandro": "Latin",
    "Sech": "Latin",
    "Camilo": "Latin",
    "Sebastian Yatra": "Latin",
    "Manuel Turizo": "Latin",
    "Luis Fonsi": "Latin",
    "Enrique Iglesias": "Latin",
    "Ricky Martin": "Latin",
    "Shakira": "Latin",
    "Jennifer Lopez": "Pop",
    "Pitbull": "Pop",
    "Marc Anthony": "Latin",
    "Romeo Santos": "Latin",
    "Prince Royce": "Latin",
    "Aventura": "Latin",
    "Juanes": "Latin",
    "Mana": "Latin",
    "Santana": "Rock Alternativo",
    "Selena": "Latin",
    "Gloria Estefan": "Latin",
    "Celia Cruz": "Latin",
}

def enrich_genres():
    if not os.path.exists(file_path):
        print(f"Error: File not found at {file_path}")
        return

    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    updated_count = 0
    unknown_artists = set()

    genre_map_lower = {k.lower(): v for k, v in genre_map.items()}

    for entry in data:
        artist = entry.get('artist_name')
        if not artist:
            continue
            
        genre = genre_map.get(artist)
        if not genre:
            genre = genre_map_lower.get(str(artist).lower())
            
        if genre:
            entry['artist_genre'] = genre
            updated_count += 1
        else:
            if entry.get('artist_genre') == 'Desconhecido' or not entry.get('artist_genre'):
                unknown_artists.add(artist)

    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Successfully updated {updated_count} entries in {file_path}")
    if unknown_artists:
        print(f"\nArtists without genre mapping ({len(unknown_artists)}):")
        for artist in sorted([str(a) for a in unknown_artists]):
            print(f"- {artist}")

if __name__ == "__main__":
    enrich_genres()
