import json

# Mapping of artists to genres
genre_mapping = {
    "A-ha": "Pop",
    "AC/DC": "Metal",
    "Adventures": "Rock Alternativo",
    "Aerosmith": "Metal",
    "Age Of Chance": "Rock Alternativo",
    "Alabama": "Country",
    "Alice Cooper": "Metal",
    "Alison Moyet": "Pop",
    "All About Eve": "Rock Alternativo",
    "Alphaville": "Pop",
    "Amazulu": "Pop",
    "Amy Grant": "Pop",
    "And The Native Hipsters": "Rock Alternativo",
    "Andy Taylor": "Rock Alternativo",
    "Animotion": "Pop",
    "Anita Baker": "Pop",
    "Annabella Lwin": "Pop",
    "Anthrax": "Metal",
    "Arcadia": "Pop",
    "Aretha Franklin": "Pop",
    "Art Of Noise": "Eletronico",
    "B-Movie": "Rock Alternativo",
    "Bad Brains": "Punk",
    "Bananarama": "Pop",
    "Bangles": "Pop",
    "Beastie Boys": "Rap",
    "Belinda Carlisle": "Pop",
    "Berlin": "Pop",
    "Big Audio Dynamite": "Rock Alternativo",
    "Big Country": "Rock Alternativo",
    "Billy Idol": "Rock Alternativo",
    "Billy Joel": "Pop",
    "Billy Ocean": "Pop",
    "Billy Squier": "Rock Alternativo",
    "Biquini Cavadão": "Rock Alternativo",
    "Blow": "Pop",
    "Blue Blud": "Metal",
    "Bob Seger": "Rock Alternativo",
    "Bon Jovi": "Pop",
    "Boris Grebenshchikov": "Rock Alternativo",
    "Boston": "Rock Alternativo",
    "Boy George": "Pop",
    "Boys Don't Cry": "Pop",
    "Bruce Hornsby": "Pop",
    "Bruce Springsteen": "Rock Alternativo",
    "C.C. Catch": "Pop",
    "Cameo": "Pop",
    "Camouflage": "Eletronico",
    "Candlemass": "Metal",
    "Captain Sensible": "Punk",
    "Carmel": "Pop",
    "Chaka Khan": "Pop",
    "Cheap Trick": "Rock Alternativo",
    "Chicago": "Pop",
    "Chris De Burgh": "Pop",
    "Chris Isaak": "Rock Alternativo",
    "Cinderella": "Metal",
    "Claude Nougaro": "Pop",
    "Cliff Richard": "Pop",
    "Club Nouveau": "Pop",
    "Cock Robin": "Pop",
    "Cocteau Twins": "Rock Alternativo",
    "Communards": "Pop",
    "Corey Hart": "Pop",
    "Crimson Glory": "Metal",
    "Cro-Mags": "Punk",
    "Crowded House": "Rock Alternativo",
    "Culture Club": "Pop",
    "Cutting Crew": "Pop",
    "Cyndi Lauper": "Pop",
    "Daryl Hall": "Pop",
    "David & David": "Rock Alternativo",
    "David Bowie": "Rock Alternativo",
    "David Lee Roth": "Rock Alternativo",
    "David Sylvian": "Rock Alternativo",
    "Dead Or Alive": "Pop",
    "Debbie Harry": "Pop",
    "Deborah Harry": "Pop",
    "Deja": "Pop",
    "Deniece Williams": "Pop",
    "Depeche Mode": "Eletronico",
    "Device": "Pop",
    "Diana Ross": "Pop",
    "Dire Straits": "Rock Alternativo",
    "Doctor & The Medics": "Rock Alternativo",
    "Dokken": "Metal",
    "Don Johnson": "Pop",
    "Double": "Pop",
    "Dr. & The Medics": "Rock Alternativo",
    "Duran Duran": "Pop",
    "Dwight Yoakam": "Country",
    "Eddie Money": "Rock Alternativo",
    "Eddy Huntington": "Pop",
    "Edie Brickell & New Bohemians": "Rock Alternativo",
    "El DeBarge": "Pop",
    "Electric Light Orchestra": "Rock Alternativo",
    "Elton John": "Pop",
    "Erasure": "Pop",
    "Eric Clapton": "Rock Alternativo",
    "Eros Ramazzotti": "Pop",
    "Europe": "Metal",
    "Eurythmics": "Pop",
    "Expose": "Pop",
    "Falco": "Pop",
    "Felt": "Rock Alternativo",
    "Fields Of The Nephilim": "Rock Alternativo",
    "Fine Young Cannibals": "Pop",
    "Fishbone": "Rock Alternativo",
    "Five Star": "Pop",
    "Flesh For Lulu": "Rock Alternativo",
    "Force M.D.'s": "Pop",
    "Freddie Mercury": "Pop",
    "Gary Numan": "Eletronico",
    "Gene Loves Jezebel": "Rock Alternativo",
    "Genesis": "Rock Alternativo",
    "George Michael": "Pop",
    "Georgia Satellites": "Rock Alternativo",
    "Glass Tiger": "Pop",
    "Gloria Estefan": "Pop",
    "Goni": "Pop",
    "Grace Jones": "Pop",
    "Grateful Dead": "Rock Alternativo",
    "Great White": "Metal",
    "Gregory Abbott": "Pop",
    "Gwen Guthrie": "Pop",
    "Hall & Oates": "Pop",
    "Haywoode": "Pop",
    "Heart": "Rock Alternativo",
    "Heaven 17": "Pop",
    "Hipsway": "Pop",
    "Howard Jones": "Pop",
    "Huey Lewis And The News": "Rock Alternativo",
    "Human League": "Pop",
    "Hunter & Collectors": "Rock Alternativo",
    "Icehouse": "Rock Alternativo",
    "Ideola": "Rock Alternativo",
    "Iggy Pop": "Rock Alternativo",
    "INXS": "Rock Alternativo",
    "Iron Maiden": "Metal",
    "It's Immaterial": "Pop",
    "J.M. Silk": "Dance",
    "Jack E. Makossa": "Dance",
    "Jackson Browne": "Rock Alternativo",
    "Janet Jackson": "Pop",
    "Jean-Michel Jarre": "Eletronico",
    "Jennifer Rush": "Pop",
    "Jermaine Stewart": "Pop",
    "Jesse Johnson": "Pop",
    "Jesus And Mary Chain": "Rock Alternativo",
    "Jets": "Pop",
    "Joan Jett & The Blackhearts": "Rock Alternativo",
    "Joe Cocker": "Rock Alternativo",
    "Joe Jackson": "Pop",
    "Joe Strummer": "Punk",
    "John Fogerty": "Rock Alternativo",
    "Johnny Kemp": "Pop",
    "Journey": "Rock Alternativo",
    "Judas Priest": "Metal",
    "Julian Lennon": "Pop",
    "Junior": "Pop",
    "Kaja": "Pop",
    "Kansas": "Rock Alternativo",
    "Kate Bush": "Rock Alternativo",
    "Katrina And The Waves": "Pop",
    "Keel": "Metal",
    "Kenny G": "Pop",
    "Kenny Loggins": "Pop",
    "Kenny Rogers": "Country",
    "Kiki Dee": "Pop",
    "Killer Pussy": "Punk",
    "Killing Joke": "Rock Alternativo",
    "Kim Appleby": "Pop",
    "Kim Carnes": "Pop",
    "Kim Wilde": "Pop",
    "King Diamond": "Metal",
    "Kool & The Gang": "Pop",
    "Kreator": "Metal",
    "Kylie Minogue": "Pop",
    "L.L. Cool J": "Rap",
    "Laberinto": "Rock Alternativo",
    "Lady Pank": "Rock Alternativo",
    "Latin Quarter": "Pop",
    "Laurie Anderson": "Pop",
    "Level 42": "Pop",
    "Levert": "Pop",
    "Limahl": "Pop",
    "Linda Ronstadt": "Pop",
    "Lionel Richie": "Pop",
    "Living In A Box": "Pop",
    "Lizzy Borden": "Metal",
    "Loose Ends": "Pop",
    "Lou Reed": "Rock Alternativo",
    "Love And Rockets": "Rock Alternativo",
    "Luther Vandross": "Pop",
    "Madness": "Pop",
    "Madonna": "Pop",
    "Magnum": "Rock Alternativo",
    "Mancrab": "Pop",
    "Manowar": "Metal",
    "Mantronix": "Eletronico",
    "Marillion": "Rock Alternativo",
    "Marilyn Martin": "Pop",
    "Mark Knopfler": "Rock Alternativo",
    "Martin Stephenson And The Daintees": "Rock Alternativo",
    "Mary Jane Girls": "Pop",
    "Matt Bianco": "Pop",
    "Maxi Priest": "Pop",
    "MC Shan": "Rap",
    "Meat Loaf": "Rock Alternativo",
    "Megadeth": "Metal",
    "Mel & Kim": "Pop",
    "Melba Moore": "Pop",
    "Metal Church": "Metal",
    "Metallica": "Metal",
    "Miami Sound Machine": "Pop",
    "Michael McDonald": "Pop",
    "Michael Sembello": "Pop",
    "Michelle Shocked": "Rock Alternativo",
    "Midge Ure": "Pop",
    "Midnight Oil": "Rock Alternativo",
    "Midnight Star": "Pop",
    "Mike & The Mechanics": "Pop",
    "Miles Davis": "Pop",
    "Modern Talking": "Pop",
    "Mone Love": "Rap",
    "Motley Crue": "Metal",
    "Motorhead": "Metal",
    "Mr. Mister": "Pop",
    "Nancy Martinez": "Pop",
    "Natalie Cole": "Pop",
    "Neil Young": "Rock Alternativo",
    "New Edition": "Pop",
    "New Model Army": "Rock Alternativo",
    "New Order": "Rock Alternativo",
    "Nick Berry": "Pop",
    "Nick Cave & The Bad Seeds": "Rock Alternativo",
    "Nick Kamen": "Pop",
    "Night Ranger": "Rock Alternativo",
    "Nik Kershaw": "Pop",
    "Noiseworks": "Rock Alternativo",
    "Nu Shooz": "Pop",
    "O.M.D.": "Pop",
    "OMD": "Pop",
    "Opus": "Pop",
    "Oran Juice Jones": "Pop",
    "Os Paralamas Do Sucesso": "Rock Alternativo",
    "Otto": "Pop",
    "Outfield": "Rock Alternativo",
    "Owen Paul": "Pop",
    "Ozzy Osbourne": "Metal",
    "Paul McCartney": "Rock Alternativo",
    "Paul Simon": "Pop",
    "Paul Young": "Pop",
    "Paula Abdul": "Pop",
    "Pepsi & Shirlie": "Pop",
    "Pet Shop Boys": "Pop",
    "Peter Gabriel": "Rock Alternativo",
    "Peter Wolf": "Rock Alternativo",
    "Phil Collins": "Pop",
    "Philip Bailey": "Pop",
    "Poison": "Metal",
    "Police": "Rock Alternativo",
    "Pork Dukes": "Punk",
    "Prefab Sprout": "Pop",
    "Pretenders": "Rock Alternativo",
    "Pretty Poison": "Pop",
    "Prince": "Pop",
    "Propaganda": "Eletronico",
    "Public Image Ltd": "Rock Alternativo",
    "Public Image Ltd.": "Rock Alternativo",
    "Queen": "Rock Alternativo",
    "Queensryche": "Metal",
    "Quiet Riot": "Metal",
    "R.E.M.": "Rock Alternativo",
    "Radiohead": "Rock Alternativo",
    "Randy Crawford": "Pop",
    "Ratt": "Metal",
    "Ready For The World": "Pop",
    "Real Life": "Pop",
    "Red Blooded Women": "Eletronico",
    "Red Box": "Pop",
    "Regina": "Pop",
    "Ric Ocasek": "Rock Alternativo",
    "Rick Astley": "Pop",
    "Rick James": "Pop",
    "Rick Springfield": "Rock Alternativo",
    "Robbie Nevil": "Pop",
    "Robert Cray": "Rock Alternativo",
    "Robert Palmer": "Rock Alternativo",
    "Robert Tepper": "Rock Alternativo",
    "Rod Stewart": "Rock Alternativo",
    "Rodney Crowell": "Country",
    "Roger Daltrey": "Rock Alternativo",
    "Roxette": "Pop",
    "Roy Orbison": "Rock Alternativo",
    "Run-DMC": "Rap",
    "Sade": "Pop",
    "Samantha Fox": "Pop",
    "Sandra": "Pop",
    "Sarah Brightman": "Pop",
    "Scritti Politti": "Pop",
    "Semi Twang": "Rock Alternativo",
    "Sheena Easton": "Pop",
    "Simple Minds": "Rock Alternativo",
    "Simply Red": "Pop",
    "Siouxsie & The Banshees": "Rock Alternativo",
    "Skyy": "Pop",
    "Slayer": "Metal",
    "Smiths": "Rock Alternativo",
    "Sonic Youth": "Rock Alternativo",
    "Spandau Ballet": "Pop",
    "Stabilizers": "Pop",
    "Stacey Q": "Pop",
    "Stan Ridgway": "Rock Alternativo",
    "Starship": "Rock Alternativo",
    "Stephanie (3)": "Pop",
    "Steve Winwood": "Rock Alternativo",
    "Stevie Ray Vaughan": "Rock Alternativo",
    "Stevie Ray Vaughan & Double Trouble": "Rock Alternativo",
    "Sting": "Rock Alternativo",
    "Stop": "Pop",
    "Stryper": "Metal",
    "Supertramp": "Rock Alternativo",
    "Survivor": "Rock Alternativo",
    "Suzanne Vega": "Rock Alternativo",
    "Swing Out Sister": "Pop",
    "Talk Talk": "Pop",
    "Talking Heads": "Rock Alternativo",
    "Tease": "Pop",
    "Tesla": "Metal",
    "The Alan Parsons Project": "Rock Alternativo",
    "The B-52's": "Rock Alternativo",
    "The Bangles": "Pop",
    "The Blow Monkeys": "Pop",
    "The Cars": "Rock Alternativo",
    "The Communards": "Pop",
    "The Connells": "Rock Alternativo",
    "The Cramps": "Punk",
    "The Cult": "Rock Alternativo",
    "The Cure": "Rock Alternativo",
    "The Damned": "Punk",
    "The Georgia Satellites": "Rock Alternativo",
    "The Hollies": "Pop",
    "The Hooters": "Rock Alternativo",
    "The Housemartins": "Rock Alternativo",
    "The Human League": "Pop",
    "The Jesus And Mary Chain": "Rock Alternativo",
    "The Jets": "Pop",
    "The Mission": "Rock Alternativo",
    "The Moody Blues": "Rock Alternativo",
    "The Outfield": "Rock Alternativo",
    "The Police": "Rock Alternativo",
    "The Pretenders": "Rock Alternativo",
    "The Psychedelic Furs": "Rock Alternativo",
    "The Rainmakers": "Rock Alternativo",
    "The Rolling Stones": "Rock Alternativo",
    "The Sharks": "Rock Alternativo",
    "The Smiths": "Rock Alternativo",
    "The Stranglers": "Rock Alternativo",
    "The Suburbs": "Rock Alternativo",
    "The Temptations": "Pop",
    "The The": "Rock Alternativo",
    "The Untouchables": "Rock Alternativo",
    "They Might Be Giants": "Rock Alternativo",
    "Thomas Dolby": "Pop",
    "Thompson Twins": "Pop",
    "Tiffany": "Pop",
    "Timbuk 3": "Rock Alternativo",
    "Tina Turner": "Pop",
    "Tom Cochrane": "Rock Alternativo",
    "Tom Petty": "Rock Alternativo",
    "Tone Loc": "Rap",
    "Tonio K": "Rock Alternativo",
    "Toto": "Rock Alternativo",
    "T'Pau": "Pop",
    "Trans-X": "Eletronico",
    "Twisted Sister": "Metal",
    "Two Of Us": "Pop",
    "UB40": "Pop",
    "Ultravox": "Pop",
    "Van Halen": "Metal",
    "Vesta Williams": "Pop",
    "Virginia Wolf": "Rock Alternativo",
    "Vladimir Presnyakov": "Pop",
    "W.A.S.P.": "Metal",
    "Wang Chung": "Pop",
    "Wax": "Pop",
    "Weird Al Yankovic": "Pop",
    "Wham!": "Pop",
    "Whitesnake": "Metal",
    "Whitney Houston": "Pop",
    "Willie Nelson": "Country",
    "World Party": "Rock Alternativo",
    "XTC": "Rock Alternativo",
    "Yello": "Eletronico",
    "Yes": "Rock Alternativo",
    "Zodiac Mindwarp": "Rock Alternativo",
    "ZZ Top": "Rock Alternativo",
    "a-ha": "Pop",
    "'Til Tuesday": "Pop",
    "Alien Sex Fiend": "Rock Alternativo",
    "Baltimora": "Pop",
    "Barnes & Barnes": "Pop",
    "Ben E. King": "Pop",
    "Benjamin Orr": "Pop",
    "Billy Chinook": "Rock Alternativo",
    "Bob Geldof": "Pop",
    "Bobby Brown": "Pop",
    "Bobby Jimmy And The Critters": "Rap",
    "Bonnie Tyler": "Pop",
    "Bronski Beat": "Pop",
    "Camisa de Vênus": "Rock Alternativo",
    "Chris Rea": "Pop",
    "Christian Death": "Rock Alternativo",
    "Corynne Charby": "Pop",
    "Curiosity Killed The Cat": "Pop",
    "Dan Seals": "Country",
    "David Seeger": "Pop",
    "E.G. Daily": "Pop",
    "Etienne Daho": "Pop",
    "Everything But The Girl": "Pop",
    "Exposé": "Pop",
    "Fr?zen Gh?st": "Pop",
    "Full Force (3)": "Pop",
    "Game Theory": "Rock Alternativo",
    "GTR (2)": "Rock Alternativo",
    "Harold Faltermeyer": "Eletronico",
    "Heavy D. & The Boyz": "Rap",
    "Honeymoon Suite": "Rock Alternativo",
    "Huey Lewis": "Rock Alternativo",
    "James Brown": "Pop",
    "Jane Wiedlin": "Pop",
    "Jermaine Jackson": "Pop",
    "John Mellencamp": "Rock Alternativo",
    "John Parr": "Pop",
    "Kiss": "Metal",
    "Kraftwerk": "Eletronico",
    "L.A. Dream Team": "Rap",
    "Leon Patillo": "Pop",
    "Love and Money": "Rock Alternativo",
    "Matthew Sweet": "Rock Alternativo",
    "Michael Cretu": "Pop",
    "Michael Des Barres": "Rock Alternativo",
    "Michael Henderson": "Pop",
    "Mike + The Mechanics": "Pop",
    "Missing Persons": "Pop",
    "My Mine": "Pop",
    "Orchestral Manoeuvres In The Dark": "Pop",
    "Pat Benatar": "Rock Alternativo",
    "Paul Kelly": "Rock Alternativo",
    "Peter Cetera": "Pop",
    "Phil Fearon": "Pop",
    "Plebe Rude": "Rock Alternativo",
    "Procol Harum": "Rock Alternativo",
    "Public Image Limited": "Rock Alternativo",
    "Pulp": "Rock Alternativo",
    "Queensrÿche": "Metal",
    "Ramones": "Punk",
    "Ray Parker Jr.": "Pop",
    "Reba McEntire": "Country",
    "Red Hot Chili Peppers": "Rock Alternativo",
    "Rene & Angela": "Pop",
    "Rifle Sport": "Punk"
}

# Load the 1986.json file
with open('data/1986.json', 'r') as f:
    data = json.load(f)

# Update the artist_genre
updated_count = 0
for item in data:
    artist = item.get('artist_name')
    if artist in genre_mapping:
        item['artist_genre'] = genre_mapping[artist]
        updated_count += 1
    else:
        # Fallback or keep as Desconhecido if not in map
        pass

# Save back to file
with open('data/1986.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {updated_count} entries.")
