import json

# Mapping of artists to genres for 2015
genre_mapping = {
    "Adele": "Pop",
    "Justin Bieber": "Pop",
    "Taylor Swift": "Pop",
    "Drake": "Rap",
    "Kendrick Lamar": "Rap",
    "The Weeknd": "Pop",
    "Ed Sheeran": "Pop",
    "Mark Ronson": "Pop",
    "Bruno Mars": "Pop",
    "Maroon 5": "Pop",
    "Hozier": "Rock Alternativo",
    "Sam Smith": "Pop",
    "Meghan Trainor": "Pop",
    "Fetty Wap": "Rap",
    "Walk The Moon": "Pop",
    "Ellie Goulding": "Pop",
    "Wiz Khalifa": "Rap",
    "Charlie Puth": "Pop",
    "Sia": "Pop",
    "Major Lazer": "Eletronico",
    "DJ Snake": "Eletronico",
    "MØ": "Pop",
    "Selena Gomez": "Pop",
    "Fifth Harmony": "Pop",
    "Kid Ink": "Rap",
    "Omarion": "Rap",
    "Chris Brown": "Pop",
    "Jhené Aiko": "Pop",
    "Nicki Minaj": "Rap",
    "David Guetta": "Eletronico",
    "Afrojack": "Eletronico",
    "Bebe Rexha": "Pop",
    "Ariana Grande": "Pop",
    "One Direction": "Pop",
    "Demi Lovato": "Pop",
    "Shawn Mendes": "Pop",
    "Nick Jonas": "Pop",
    "Calvin Harris": "Eletronico",
    "Disciples": "Eletronico",
    "Florence + The Machine": "Rock Alternativo",
    "Tame Impala": "Rock Alternativo",
    "Alabama Shakes": "Rock Alternativo",
    "Twenty One Pilots": "Rock Alternativo",
    "Coldplay": "Pop",
    "Muse": "Rock Alternativo",
    "Foo Fighters": "Rock Alternativo",
    "Bring Me The Horizon": "Metal",
    "Disturbed": "Metal",
    "Ghost": "Metal",
    "Iron Maiden": "Metal",
    "Slayer": "Metal",
    "Megadeth": "Metal",
    "Lamb of God": "Metal",
    "Parkway Drive": "Metal",
    "Halestorm": "Metal",
    "Papa Roach": "Rock Alternativo",
    "Breaking Benjamin": "Rock Alternativo",
    "Shinedown": "Rock Alternativo",
    "Three Days Grace": "Rock Alternativo",
    "Five Finger Death Punch": "Metal",
    "Marilyn Manson": "Metal",
    "Faith No More": "Rock Alternativo",
    "Refused": "Punk",
    "Deafheaven": "Metal",
    "Baroness": "Metal",
    "Periphery": "Metal",
    "Between The Buried And Me": "Metal",
    "Trivium": "Metal",
    "Kanye West": "Rap",
    "Paul McCartney": "Rock Alternativo",
    "Rihanna": "Pop",
    "Big Sean": "Rap",
    "Future": "Rap",
    "Travi$ Scott": "Rap",
    "Travis Scott": "Rap",
    "A$AP Rocky": "Rap",
    "Vince Staples": "Rap",
    "Action Bronson": "Rap",
    "Joey Bada$$": "Rap",
    "Earl Sweatshirt": "Rap",
    "Tyler, The Creator": "Rap",
    "Mac Miller": "Rap",
    "Logic": "Rap",
    "G-Eazy": "Rap",
    "Meek Mill": "Rap",
    "Rick Ross": "Rap",
    "Dr. Dre": "Rap",
    "Snoop Dogg": "Rap",
    "Pharrell Williams": "Pop",
    "Missy Elliott": "Rap",
    "Ciara": "Pop",
    "Janet Jackson": "Pop",
    "Jason Derulo": "Pop",
    "Pitbull": "Pop",
    "Ne-Yo": "Pop",
    "Trey Songz": "Pop",
    "Jeremih": "Pop",
    "Ty Dolla $ign": "Rap",
    "Post Malone": "Rap",
    "Rae Sremmurd": "Rap",
    "Migos": "Rap",
    "Young Thug": "Rap",
    "Lil Wayne": "Rap",
    "Lil Dicky": "Rap",
    "Fetty Wap": "Rap",
    "Silento": "Rap",
    "OMI": "Pop",
    "Rachel Platten": "Pop",
    "Andy Grammer": "Pop",
    "X Ambassadors": "Rock Alternativo",
    "Elle King": "Rock Alternativo",
    "James Bay": "Rock Alternativo",
    "George Ezra": "Rock Alternativo",
    "Vance Joy": "Rock Alternativo",
    "Halsey": "Pop",
    "Melanie Martinez": "Pop",
    "Troye Sivan": "Pop",
    "Alessia Cara": "Pop",
    "Hailee Steinfeld": "Pop",
    "Daya": "Pop",
    "Zara Larsson": "Pop",
    "MNEK": "Pop",
    "Jess Glynne": "Pop",
    "Years & Years": "Pop",
    "Clean Bandit": "Eletronico",
    "Galantis": "Eletronico",
    "Kygo": "Eletronico",
    "Robin Schulz": "Eletronico",
    "Lost Frequencies": "Eletronico",
    "Felix Jaehn": "Eletronico",
    "Avicii": "Eletronico",
    "Zedd": "Eletronico",
    "Skrillex": "Eletronico",
    "Diplo": "Eletronico",
    "Jack Ü": "Eletronico",
    "Disclosure": "Eletronico",
    "Jamie xx": "Eletronico",
    "Caribou": "Eletronico",
    "Four Tet": "Eletronico",
    "Floating Points": "Eletronico",
    "Grimes": "Pop",
    "CHVRCHES": "Pop",
    "Purity Ring": "Pop",
    "Beach House": "Rock Alternativo",
    "Sufjan Stevens": "Rock Alternativo",
    "Father John Misty": "Rock Alternativo",
    "Courtney Barnett": "Rock Alternativo",
    "Kurt Vile": "Rock Alternativo",
    "Unknown Mortal Orchestra": "Rock Alternativo",
    "Mac DeMarco": "Rock Alternativo",
    "Deerhunter": "Rock Alternativo",
    "Wilco": "Rock Alternativo",
    "Sleater-Kinney": "Rock Alternativo",
    "Björk": "Pop",
    "New Order": "Rock Alternativo",
    "Duran Duran": "Pop",
    "Blur": "Rock Alternativo",
    "The Libertines": "Rock Alternativo",
    "The Vaccines": "Rock Alternativo",
    "Wolf Alice": "Rock Alternativo",
    "Royal Blood": "Rock Alternativo",
    "Catfish and the Bottlemen": "Rock Alternativo",
    "Nothing But Thieves": "Rock Alternativo",
    "Foals": "Rock Alternativo",
    "Everything Everything": "Rock Alternativo",
    "The 1975": "Pop",
    "Bastille": "Pop",
    "Imagine Dragons": "Rock Alternativo",
    "Fall Out Boy": "Rock Alternativo",
    "Panic! At The Disco": "Rock Alternativo",
    "All Time Low": "Rock Alternativo",
    "Sleeping With Sirens": "Rock Alternativo",
    "Pierce The Veil": "Rock Alternativo",
    "Neck Deep": "Punk",
    "State Champs": "Punk",
    "The Story So Far": "Punk",
    "Wonder Years": "Punk",
    "Modest Mouse": "Rock Alternativo",
    "Death Cab for Cutie": "Rock Alternativo",
    "The Decemberists": "Rock Alternativo",
    "Of Monsters and Men": "Rock Alternativo",
    "Mumford & Sons": "Rock Alternativo",
    "Florence + The Machine": "Rock Alternativo",
    "Lana Del Rey": "Pop",
    "Marina And The Diamonds": "Pop",
    "Carly Rae Jepsen": "Pop",
    "Charli XCX": "Pop",
    "Little Mix": "Pop",
    "5 Seconds of Summer": "Pop",
    "Luke Bryan": "Country",
    "Sam Hunt": "Country",
    "Thomas Rhett": "Country",
    "Carrie Underwood": "Country",
    "Miranda Lambert": "Country",
    "Little Big Town": "Country",
    "Chris Stapleton": "Country",
    "Kacey Musgraves": "Country",
    "Eric Church": "Country",
    "Zac Brown Band": "Country",
    "Florida Georgia Line": "Country",
    "Jason Aldean": "Country",
    "Blake Shelton": "Country",
    "Keith Urban": "Country",
    "Brad Paisley": "Country",
    "Tim McGraw": "Country",
    "Dierks Bentley": "Country",
    "Brett Eldredge": "Country",
    "Cole Swindell": "Country",
    "Cam": "Country",
    "Maren Morris": "Country",
    "Old Dominion": "Country",
    "Dan + Shay": "Country",
    "Kelsea Ballerini": "Country",
    "Chris Young": "Country",
    "Lee Brice": "Country",
    "A Great Big World": "Pop",
    "Adam Lambert": "Pop",
    "Pentatonix": "Pop",
    "Tori Kelly": "Pop",
    "Joss Stone": "Pop",
    "Leon Bridges": "Pop",
    "Andra Day": "Pop",
    "Gary Clark Jr.": "Rock Alternativo",
    "Nathaniel Rateliff & The Night Sweats": "Rock Alternativo",
    "The Arcs": "Rock Alternativo",
    "The Black Keys": "Rock Alternativo",
    "Cage The Elephant": "Rock Alternativo",
    "Silversun Pickups": "Rock Alternativo",
    "Metric": "Rock Alternativo",
    "The Wombats": "Rock Alternativo",
    "The Kooks": "Rock Alternativo",
    "The Wombats": "Rock Alternativo",
    "Two Door Cinema Club": "Rock Alternativo",
    "Phoenix": "Rock Alternativo",
    "Passion Pit": "Rock Alternativo",
    "MGMT": "Rock Alternativo",
    "Empire of the Sun": "Eletronico",
    "Foster The People": "Rock Alternativo",
    "Grouplove": "Rock Alternativo",
    "Young the Giant": "Rock Alternativo",
    "Fitz and The Tantrums": "Rock Alternativo",
    "Saint Motel": "Pop",
    "Borns": "Pop",
    "BØRNS": "Pop",
    "Miike Snow": "Pop",
    "Phantogram": "Eletronico",
    "Big Grams": "Rap",
    "Run The Jewels": "Rap",
    "El-P": "Rap",
    "Killer Mike": "Rap",
    "Danny Brown": "Rap",
    "Pusha T": "Rap",
    "Schoolboy Q": "Rap",
    "Ab-Soul": "Rap",
    "Jay Rock": "Rap",
    "Isaiah Rashad": "Rap",
    "SZA": "Pop",
    "Kali Uchis": "Pop",
    "Kehlani": "Pop",
    "Bryson Tiller": "Pop",
    "The Internet": "Pop",
    "Anderson .Paak": "Rap",
    "Kaytranada": "Eletronico",
    "Thundercat": "Pop",
    "Flying Lotus": "Eletronico",
    "Kamasi Washington": "Pop",
    "Hiatus Kaiyote": "Pop",
    "Ibeyi": "Pop",
    "Petit Biscuit": "Eletronico",
    "Flume": "Eletronico",
    "Odesza": "Eletronico",
    "Porter Robinson": "Eletronico",
    "Madeon": "Eletronico",
    "San Holo": "Eletronico",
    "Marshmello": "Eletronico",
    "The Chainsmokers": "Pop",
    "Illenium": "Eletronico",
    "Gryffin": "Eletronico",
    "Seven Lions": "Eletronico",
    "Adventure Club": "Eletronico",
    "Kaskade": "Eletronico",
    "Deadmau5": "Eletronico",
    "Eric Prydz": "Eletronico",
    "Above & Beyond": "Eletronico",
    "Armin van Buuren": "Eletronico",
    "Tiësto": "Eletronico",
    "Hardwell": "Eletronico",
    "Martin Garrix": "Eletronico",
    "Steve Aoki": "Eletronico",
    "Dimitri Vegas & Like Mike": "Eletronico",
    "Oliver Heldens": "Eletronico",
    "Tchami": "Eletronico",
    "Don Diablo": "Eletronico",
    "KSHMR": "Eletronico",
    "R3hab": "Eletronico",
    "Nicky Romero": "Eletronico",
    "W&W": "Eletronico",
    "Yellow Claw": "Eletronico",
    "Borgore": "Eletronico",
    "Pendulum": "Eletronico",
    "Knife Party": "Eletronico",
    "Nero": "Eletronico",
    "Noisia": "Eletronico",
    "Chase & Status": "Eletronico",
    "Rudimental": "Pop",
    "Sigma": "Pop",
    "Wilkinson": "Eletronico",
    "Sub Focus": "Eletronico",
    "Netsky": "Eletronico",
    "Camo & Krooked": "Eletronico",
    "High Contrast": "Eletronico",
    "Fred V & Grafix": "Eletronico",
    "Metrik": "Eletronico",
    "Logistics": "Eletronico",
    "London Elektricity": "Eletronico",
    "Hospital Records": "Eletronico",
    "Ram Records": "Eletronico",
    "Shogun Audio": "Eletronico",
    "Viper Recordings": "Eletronico",
    "Critical Music": "Eletronico",
    "Metalheadz": "Eletronico",
    "Exit Records": "Eletronico",
    "Dispatch Recordings": "Eletronico",
    "Symmetry Recordings": "Eletronico",
    "Spearhead Records": "Eletronico",
    "Liquicity": "Eletronico",
    "UKF": "Eletronico",
    "They Might Be Giants": "Rock Alternativo",
    "Soulja Boy": "Rap",
    "Vybz Kartel": "Rap",
    "Busy Signal": "Rap",
    "The 4onthefloor": "Rock Alternativo",
    "Tyga": "Rap",
    "Stitches": "Rap",
    "Trisha Paytas": "Pop",
    "Kiravell": "Rock Alternativo",
    "Philthy Rich": "Rap",
    "Dark Polo Gang": "Rap",
    "Troy Ave": "Rap",
    "Racoon (2)": "Rock Alternativo",
    "Michael Resin": "Pop",
    "Sheena Ringo": "Pop",
    "Maître Gims": "Rap",
    "T.I.": "Rap",
    "Luke Potter": "Pop",
    "SHO": "Rap",
    "Olamide": "Rap",
    "Tinashe": "Pop",
    "Marracash": "Rap",
    "Felly": "Rap",
    "Yemi Alade": "Pop",
    "Laura Pausini": "Pop",
    "Ice Prince": "Rap",
    "Lindsey Stirling": "Eletronico",
    "2 Chainz": "Rap",
    "Kip Moore": "Country",
    "Charly Black": "Rap",
    "Icewear Vezzo": "Rap",
    "Phora": "Rap",
    "Michael Prins": "Pop",
    "Natalia Lafourcade": "Pop",
    "Taryn Southern": "Pop",
    "Eros Ramazzotti": "Pop",
    "JayteKz": "Rap",
    "KeBlack": "Rap",
    "Skales": "Pop",
    "Spose": "Rap",
    "Miguel": "Pop",
    "Will Young": "Pop",
    "Maaike Ouboter": "Pop",
    "Pablo Alborán": "Pop",
    "Marcus & Martinus": "Pop",
    "Emery": "Rock Alternativo",
    "Spangle Call Lilli Line": "Rock Alternativo",
    "JMSN": "Pop",
    "Iyanya": "Pop",
    "Cairo": "Pop",
    "Orezi": "Pop",
    "Phyno": "Rap",
    "Zibra": "Rock Alternativo",
    "Timeflies": "Pop",
    "Fler": "Rap",
    "Kcee": "Pop",
    "VanVelzen": "Pop",
    "Wisin": "Rap",
    "Chlara": "Pop",
    "Hopsin": "Rap",
    "Belly": "Rap",
    "Hippo Campus": "Rock Alternativo",
    "Yelawolf": "Rap",
    "BT": "Eletronico",
    "Self Provoked": "Rap",
    "Ólafur Arnalds": "Eletronico",
    "Blacko": "Rap",
    "Raury": "Rap",
    "Douwe Bob": "Pop",
    "Soprano (2)": "Rap",
    "Spector": "Rock Alternativo",
    "UpChurch": "Rap",
    "Curren$y": "Rap",
    "Christafari": "Pop",
    "Mike Dece": "Rap",
    "French Montana": "Rap",
    "Tia Ray": "Pop",
    "Burgundy Blood": "Rap",
    "Asian Kung-Fu Generation": "Rock Alternativo",
    "EL B": "Rap",
    "Róisín Murphy": "Pop",
    "Sir Michael Rocks": "Rap",
    "twenty one pilots": "Rock Alternativo",
    "Brandon Flowers": "Rock Alternativo",
    "Chedda da Connect": "Rap",
    "Django Django": "Rock Alternativo",
    "The Go! Team": "Rock Alternativo",
    "Timaya": "Pop",
    "Seafret": "Rock Alternativo",
    "Inna": "Pop",
    "Runtown": "Pop",
    "Thomas Arya": "Pop"
}

# Normalize function
def normalize_artist(name):
    if not name:
        return "Unknown"
    return str(name).strip()

# Load the 2015.json file
with open('data/2015.json', 'r') as f:
    data = json.load(f)

# Update the artist_genre
updated_count = 0
for item in data:
    artist_raw = item.get('artist_name')
    artist = normalize_artist(artist_raw)
    
    if artist in genre_mapping:
        item['artist_genre'] = genre_mapping[artist]
        updated_count += 1
    # Note: We are not setting "Desconhecido" here because the file likely already has it or we want to keep existing if valuable
    # But based on typical retroclip logic, we just map what we know.

# Save back to file
with open('data/2015.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {updated_count} entries.")
