import json

genre_map = {
    '*NSYNC': 'Pop',
    '112': 'R&B',
    '2Pac': 'Rap',
    '3 Doors Down': 'Rock Alternativo',
    '311': 'Rock Alternativo',
    'A*Teens': 'Pop',
    'A.K.-S.W.I.F.T.': 'Hip Hop',
    'A1': 'Pop',
    'AFI': 'Punk',
    'Aaliyah': 'R&B',
    'Aaron Carter': 'Pop',
    'Abandoned Pools': 'Rock Alternativo',
    'Adema': 'Metal',
    'Aerosmith': 'Rock',
    'Afterhours': 'Rock Alternativo',
    'Air': 'Eletronico',
    'Alan Jackson': 'Country',
    'Alcazar': 'Dance',
    'Alex Ubago': 'Pop',
    'Ali': 'Rap',
    'Alice Deejay': 'Dance',
    'Alicia Keys': 'R&B',
    'Alien Ant Farm': 'Rock Alternativo',
    'Alison Krauss & Union Station': 'Country',
    'Alkaline Trio': 'Punk',
    'All Star Tribute': 'Pop',
    'Alsou': 'Pop',
    'Amari': 'Pop',
    'Amorphis': 'Metal',
    'Anahí': 'Latino',
    'Anastacia': 'Pop',
    'Andrew W.K.': 'Rock',
    'Angela Baraldi': 'Rock',
    'Angie Martinez': 'Rap',
    'Apocalyptica': 'Metal',
    'Aqua': 'Pop',
    'Arno Elias': 'Pop',
    'Ash': 'Rock Alternativo',
    'Atomic Kitten': 'Pop',
    'Augie March': 'Indie',
    'Aura (2)': 'Pop',
    'Ayman (2)': 'R&B',
    'Ayumi Hamasaki': 'J-Pop',
    'B-Four': 'Pop',
    'BBMak': 'Pop',
    'Backstreet Boys': 'Pop',
    'Bad Ronald': 'Rap',
    'Badly Drawn Boy': 'Indie',
    'Bananarama': 'Pop',
    'Barthezz': 'Trance',
    'Basement Jaxx': 'Eletronico',
    'Baustelle': 'Indie',
    'Beam vs. Cyrus': 'Trance',
    'Beanie Sigel': 'Rap',
    'Bee Gees': 'Pop',
    'Bell Biv DeVoe': 'R&B',
    'Ben Folds': 'Rock Alternativo',
    'Benjamin Biolay': 'Pop',
    'Big Punisher': 'Rap',
    'Big Wreck': 'Rock',
    'Bilal': 'R&B',
    'Björk': 'Eletronico',
    'Black Rebel Motorcycle Club': 'Rock Alternativo',
    'Blink-182': 'Punk',
    'Blu Cantrell': 'R&B',
    'Blue': 'Pop',
    'Blues Traveler': 'Rock',
    'Bluvertigo': 'Rock Alternativo',
    'Bomfunk MC\'s': 'Eletronico',
    'Bon Jovi': 'Rock',
    'Boris Dlugosch': 'House',
    'Bow Wow': 'Rap',
    'Brad Paisley': 'Country',
    'Brand New': 'Rock Alternativo',
    'Brian Harvey': 'Pop',
    'Brian McKnight': 'R&B',
    'Britney Spears': 'Pop',
    'Brooklyn Bounce': 'Dance',
    'Brooks & Dunn': 'Country',
    'Bubba Sparxxx': 'Rap',
    'Bubbles (5)': 'Pop',
    'Bush': 'Grunge',
    'Busta Rhymes': 'Rap',
    'Butterfly Jones': 'Rock',
    'Butthole Surfers': 'Rock Alternativo',
    'Cake': 'Rock Alternativo',
    'Captain Jack': 'Dance',
    'Caramell': 'Pop',
    'Carolyn Dawn Johnson': 'Country',
    'Case': 'R&B',
    'Catatonia': 'Britpop',
    'Cee-Lo Green': 'R&B',
    'Changing Faces': 'R&B',
    'Chely Wright': 'Country',
    'Cher': 'Pop',
    'Christina Aguilera': 'Pop',
    'Christina Milian': 'Pop',
    'Cold Chains': 'Rock',
    'Coldplay': 'Rock Alternativo',
    'Collective Soul': 'Rock Alternativo',
    'Coo Coo Cal': 'Rap',
    'Cradle Of Filth': 'Metal',
    'Craig David': 'R&B',
    'Crash Test Dummies': 'Rock Alternativo',
    'Craving Theo': 'Rock',
    'Crazy Town': 'Rock Alternativo',
    'Creed': 'Rock Alternativo',
    'Cristiano De André': 'Pop',
    'Crowd Pleasers (2)': 'Rock',
    'Curly': 'Pop',
    'Cypress Hill': 'Rap',
    'D12': 'Rap',
    'DJ Scot Project': 'Trance',
    'DMX': 'Rap',
    'Daft Punk': 'Eletronico',
    'Danko Jones': 'Rock',
    'Darnell': 'R&B',
    'Dave Matthews Band': 'Rock',
    'Dave Navarro': 'Rock Alternativo',
    'David Gray': 'Folk',
    'De La Soul': 'Rap',
    'De-Javu': 'Pop',
    'Dean Burke': 'Rap',
    'Deasonika': 'Rock',
    'Dee Dee (2)': 'Dance',
    'Deftones': 'Metal',
    'Delta Goodrem': 'Pop',
    'Delta V': 'Pop',
    'Depeche Mode': 'Eletronico',
    'Destiny\'s Child': 'R&B',
    'Dido': 'Pop',
    'Die Firma': 'Rap',
    'Die Prinzen': 'Pop',
    'Die Ärzte': 'Punk',
    'Disturbed': 'Metal',
    'Donots': 'Punk',
    'Dope (4)': 'Metal',
    'Down Low': 'Rap',
    'Dream': 'Pop',
    'Dub Pistols': 'Eletronico',
    'Dum Dums': 'Pop',
    'Dungeon Family': 'Rap',
    'E-Rotic': 'Dance',
    'Eden\'s Crush': 'Pop',
    'Eiffel 65': 'Dance',
    'El Chojín': 'Rap',
    'Elbow': 'Rock Alternativo',
    'Elisa': 'Pop',
    'Elton John': 'Pop',
    'Embrace': 'Britpop',
    'Emerson Drive': 'Country',
    'Emma Bunton': 'Pop',
    'Emperor (2)': 'Metal',
    'Enigma': 'New Age',
    'Enrique Iglesias': 'Latino',
    'Entombed': 'Metal',
    'Enya': 'Pop',
    'Eric Clapton': 'Rock',
    'Erick Sermon': 'Rap',
    'Eros Ramazzotti': 'Pop',
    'Erykah Badu': 'R&B',
    'Eskimo Joe': 'Rock Alternativo',
    'Eve': 'Rap',
    'Eve 6': 'Rock Alternativo',
    'Eye Q': 'Pop',
    'Fabolous': 'Rap',
    'Fader Gladiator': 'Eletronico',
    'Faith Evans': 'R&B',
    'Faith Hill': 'Country',
    'Faithless': 'Eletronico',
    'Fatboy Slim': 'Eletronico',
    'Feeder': 'Rock Alternativo',
    'Fischerspooner': 'Eletronico',
    'Five': 'Pop',
    'Five For Fighting': 'Pop',
    'Floorfilla': 'Dance',
    'Florent Pagny': 'Pop',
    'Fonky Family': 'Rap',
    'Foxy Brown': 'Rap',
    'Francesco Boccia': 'Pop',
    'French Affair': 'Pop',
    'Fresh \'n\' Juicy': 'Pop',
    'Fuel': 'Rock Alternativo',
    'Fun Lovin\' Criminals': 'Rock Alternativo',
    'G-Dep': 'Rap',
    'Gabrielle': 'Pop',
    'Garbage': 'Rock Alternativo',
    'Gary Allan (2)': 'Country',
    'Geri Halliwell': 'Pop',
    'Ghetto Concept': 'Rap',
    'Ghostface Killah': 'Rap',
    'Ghoultown': 'Goth',
    'Gianni': 'Pop',
    'Giardini Di Mirò': 'Indie',
    'Ginuwine': 'R&B',
    'Giorgia (2)': 'Pop',
    'Go-Go\'s': 'Pop',
    'Godsmack': 'Metal',
    'Gojira': 'Metal',
    'Goldfrapp': 'Eletronico',
    'Good Charlotte': 'Punk',
    'Good Riddance': 'Punk',
    'Gorillaz': 'Rock Alternativo',
    'Green Day': 'Punk',
    'Groove Armada': 'Eletronico',
    'Guano Apes': 'Rock Alternativo',
    'HIM': 'Rock',
    'Hautnah': 'Pop',
    'Highland': 'Hip Hop',
    'Hoku': 'Pop',
    'Honeydogs': 'Rock',
    'Hoobastank': 'Rock Alternativo',
    'Hooverphonic': 'Eletronico',
    'Hypetraxx': 'Trance',
    'Incubus': 'Rock Alternativo',
    'India.Arie': 'R&B',
    'Inessa': 'Dance',
    'Irene Grandi': 'Pop',
    'Isa Sabani': 'Pop',
    'Ja Rule': 'Rap',
    'Jadakiss': 'Rap',
    'Jagged Edge': 'R&B',
    'James': 'Britpop',
    'Jamie-Lynn Sigler': 'Pop',
    'Jamiroquai': 'Funk',
    'Janet Jackson': 'Pop',
    'Jay Z': 'Rap',
    'Jean-Jacques Goldman': 'Pop',
    'Jeanette': 'Pop',
    'Jennifer Lopez': 'Pop',
    'Jermaine Dupri': 'Rap',
    'Jessica Andrews': 'Country',
    'Jessica Simpson': 'Pop',
    'Jewel': 'Pop',
    'Jimmy Eat World': 'Rock Alternativo',
    'Jive Jones': 'Pop',
    'Joe': 'R&B',
    'John Mellencamp': 'Rock',
    'Journey': 'Rock',
    'Juanes': 'Latino',
    'Judith Bérard': 'Pop',
    'Judy and Mary': 'J-Pop',
    'Julie\'s Haircut': 'Indie',
    'Jump The Sky': 'Pop',
    'K-Ci & JoJo': 'R&B',
    'KRS-One': 'Rap',
    'KRYŠTOF': 'Rock',
    'Kardinal Offishall': 'Rap',
    'Kate Winslet': 'Pop',
    'Keith Urban': 'Country',
    'Kid Rock': 'Rock',
    'Killing Heidi': 'Rock',
    'King África': 'Latino',
    'Kosheen': 'Eletronico',
    'Krayzie Bone': 'Rap',
    'Kreator': 'Metal',
    'Kristin Hersh': 'Indie',
    'Kylie Minogue': 'Pop',
    'LFO': 'Pop',
    'LL Cool J': 'Rap',
    'Ladytron': 'Eletronico',
    'Lasgo': 'Dance',
    'Laura Pausini': 'Pop',
    'Laurent Voulzy': 'Pop',
    'Lenny Kravitz': 'Rock',
    'Leonard Cohen': 'Folk',
    'Liberty City': 'Dance',
    'Lifehouse': 'Rock Alternativo',
    'Lil\' Jon': 'Rap',
    'Lil\' Romeo': 'Rap',
    'Limp Bizkit': 'Metal',
    'Linea 77': 'Metal',
    'Linkin Park': 'Rock Alternativo',
    'Lisa Stansfield': 'R&B',
    'Lit': 'Rock Alternativo',
    'Litfiba': 'Rock',
    'Little Big Town': 'Country',
    'Live': 'Rock Alternativo',
    'LiveonRelease': 'Punk',
    'Lollipop (2)': 'Pop',
    'Los Tigres Del Norte': 'Latino',
    'Lostprophets': 'Rock Alternativo',
    'Lou Bega': 'Pop',
    'Louise': 'Pop',
    'Lovestern Galaktika Project': 'Dance',
    'Luca Carboni': 'Pop',
    'Lucyfire': 'Goth',
    'Ludacris': 'Rap',
    'Luke (2)': 'Rap',
    'M2M': 'Pop',
    'MC Solaar': 'Rap',
    'Machine Head': 'Metal',
    'Mack 10': 'Rap',
    'Macy Gray': 'R&B',
    'Madonna': 'Pop',
    'Malice Mizer': 'Visual Kei',
    'Mandy Moore': 'Pop',
    'Manic Street Preachers': 'Rock Alternativo',
    'Mansun': 'Britpop',
    'Marcia Hines': 'Pop',
    'Marco Antonio Solís': 'Latino',
    'Mariah Carey': 'R&B',
    'Marilyn Manson': 'Industrial',
    'Mark Wills': 'Country',
    'Martina McBride': 'Country',
    'Mary J. Blige': 'R&B',
    'Master P': 'Rap',
    'Matchbox Twenty': 'Rock Alternativo',
    'Matthew Jay': 'Indie',
    'Mauro Picotto': 'Trance',
    'Maximilian Hecker': 'Indie',
    'Maxwell': 'R&B',
    'Megadeth': 'Metal',
    'Melanie Thornton': 'Pop',
    'Melissa Etheridge': 'Rock',
    'Mercury Rev': 'Indie',
    'Method Man': 'Rap',
    'Method Man & Redman': 'Rap',
    'Methrone': 'R&B',
    'Michael Jackson': 'Pop',
    'Michelle Branch': 'Pop',
    'Mick Jagger': 'Rock',
    'Micro Nontschew': 'Pop',
    'Miilkbone': 'Rap',
    'Milk & Sugar': 'House',
    'Miss Machine': 'Rock',
    'Miss Papaya': 'Pop',
    'Missy Elliott': 'Rap',
    'Mobb Deep': 'Rap',
    'Modern Talking': 'Pop',
    'Monica': 'R&B',
    'Montgomery Gentry': 'Country',
    'Moonspell': 'Metal',
    'Morcheeba': 'Trip Hop',
    'Morten Abel': 'Pop',
    'Mr. Big': 'Rock',
    'Mudvayne': 'Metal',
    'Muse': 'Rock Alternativo',
    'My Vitriol': 'Rock Alternativo',
    'Mya': 'R&B',
    'Mylène Farmer': 'Pop',
    'Myra': 'Pop',
    'Mystikal': 'Rap',
    'Mötley Crüe': 'Metal',
    'N.E.R.D.': 'Hip Hop',
    'Naima (2)': 'Pop',
    'Nappy Roots': 'Rap',
    'Natalia Oreiro': 'Latino',
    'Natalie Imbruglia': 'Pop',
    'Nelly Furtado': 'Pop',
    'Nerina Pallot': 'Pop',
    'New Order': 'Eletronico',
    'Nick Cave & The Bad Seeds': 'Rock Alternativo',
    'Nickelback': 'Rock',
    'Nightwish': 'Metal',
    'Nikka Costa': 'R&B',
    'Nine Inch Nails': 'Industrial',
    'No Doubt': 'Rock Alternativo',
    'No Use For A Name': 'Punk',
    'Nonpoint': 'Metal',
    'O-Town': 'Pop',
    'OPM (2)': 'Rap',
    'Oli P.': 'Pop',
    'Opeth': 'Metal',
    'Orbital': 'Eletronico',
    'Our Lady Peace': 'Rock Alternativo',
    'OutKast': 'Rap',
    'Ozzy Osbourne': 'Metal',
    'P. Diddy': 'Rap',
    'P.O.D.': 'Metal',
    'PJ Harvey': 'Rock Alternativo',
    'Papa Roach': 'Metal',
    'Paradise Lost': 'Metal',
    'Pascal Obispo': 'Pop',
    'Passion Fruit': 'Dance',
    'Pastor Troy': 'Rap',
    'Paulina Rubio': 'Latino',
    'Perry Farrell': 'Rock Alternativo',
    'Pete Yorn': 'Indie',
    'Petey Pablo': 'Rap',
    'Phantom Planet': 'Rock Alternativo',
    'Phoenix': 'Indie',
    'Pink': 'Pop',
    'Placebo': 'Rock Alternativo',
    'Plaid': 'Eletronico',
    'Planet Funk': 'Eletronico',
    'Planet Hemp': 'Rap',
    'Powerman 5000': 'Metal',
    'Prefab Sprout': 'Pop',
    'Prince': 'Funk',
    'Prodigy': 'Rap',
    'Profyle': 'R&B',
    'Project Pitchfork': 'Industrial',
    'Prophet Jones': 'R&B',
    'Pru': 'R&B',
    'Puddle Of Mudd': 'Rock Alternativo',
    'Puff Daddy': 'Rap',
    'Pulp': 'Britpop',
    'R\'n\'G': 'Hip Hop',
    'R. Kelly': 'R&B',
    'R.E.M.': 'Rock Alternativo',
    'RL': 'R&B',
    'RZA': 'Rap',
    'Radiohead': 'Rock Alternativo',
    'Rammstein': 'Metal',
    'Rappers Against Racism': 'Hip Hop',
    'Raptile': 'Rap',
    'Ravers On Dope': 'Dance',
    'Ray J': 'R&B',
    'Reach The Sky': 'Punk',
    'Redman': 'Rap',
    'Rednex': 'Pop',
    'Reef': 'Rock',
    'Regurgitator': 'Rock Alternativo',
    'Relish': 'Rock',
    'Remy Zero': 'Rock Alternativo',
    'Res': 'R&B',
    'Richard Lugo': 'Pop',
    'Ricky Martin': 'Latino',
    'Rob Zombie': 'Metal',
    'Robbie Williams': 'Pop',
    'Robert Miles': 'Trance',
    'Rod Stewart': 'Rock',
    'Ronan Keating': 'Pop',
    'Ronnie Jones': 'Soul',
    'Rosenstolz': 'Pop',
    'Roxette': 'Pop',
    'Ruff Endz': 'R&B',
    'Ruff Ryders': 'Rap',
    'Run-DMC': 'Rap',
    'Russell Watson': 'Classical Crossover',
    'Röyksopp': 'Eletronico',
    'S Club 7': 'Pop',
    'S#arp': 'Pop',
    'Sade': 'R&B',
    'Sahara Hotnights': 'Rock',
    'Saliva': 'Metal',
    'Samantha Mumba': 'Pop',
    'Samir': 'Pop',
    'Sammie (2)': 'R&B',
    'Sandra': 'Pop',
    'Sarah Connor': 'Pop',
    'Sarina Paris': 'Dance',
    'Scarface': 'Rap',
    'Schiller': 'Eletronico',
    'Scooter': 'Techno',
    'Semisonic': 'Rock Alternativo',
    'Senait': 'Pop',
    'Shaggy': 'Reggae',
    'Shakira': 'Latino',
    'Shelby Lynne': 'Country',
    'Sick Puppies': 'Rock Alternativo',
    'Sigur Rós': 'Indie',
    'Simple Minds': 'Rock Alternativo',
    'Sisqó': 'R&B',
    'Slayer': 'Metal',
    'Slipknot': 'Metal',
    'Smash Mouth': 'Rock Alternativo',
    'Snoop Dogg': 'Rap',
    'Sophie Ellis-Bextor': 'Pop',
    'SpaceBelle': 'Pop',
    'Sparklehorse': 'Indie',
    'Spiritualized': 'Rock Alternativo',
    'Spooman': 'Rap',
    'St. Lunatics': 'Rap',
    'Staind': 'Metal',
    'Starsailor': 'Britpop',
    'Stella Soleil': 'Pop',
    'Stephen Malkmus': 'Indie',
    'Steps': 'Pop',
    'Stereophonics': 'Britpop',
    'Stina Nordenstam': 'Indie',
    'Stone Temple Pilots': 'Grunge',
    'Storm (10)': 'Trance',
    'Strait Up': 'Metal',
    'Subsonica': 'Eletronico',
    'Sugar Ray': 'Rock Alternativo',
    'Suit Yourself': 'Pop',
    'Sum 41': 'Punk',
    'Sunshine Anderson': 'R&B',
    'Super Furry Animals': 'Indie',
    'Suzanne Vega': 'Folk',
    'Svala': 'Pop',
    'Syria': 'Pop',
    'System Of A Down': 'Metal',
    'Sébastien Tellier': 'Eletronico',
    'T Seven': 'Pop',
    'Tantric': 'Rock Alternativo',
    'Tanya Donelly': 'Rock Alternativo',
    'Ten Foot Pole': 'Punk',
    'Tenacious D': 'Rock',
    'Terrorvision': 'Rock',
    'Texas': 'Pop',
    'Thalía': 'Latino',
    'The Avalanches': 'Eletronico',
    'The Charlatans': 'Britpop',
    'The Chemical Brothers': 'Eletronico',
    'The Cooper Temple Clause': 'Rock Alternativo',
    'The Corrs': 'Pop',
    'The Cranberries': 'Rock Alternativo',
    'The Crystal Method': 'Eletronico',
    'The Cure': 'Rock Alternativo',
    'The Gathering': 'Rock Alternativo',
    'The Hives': 'Rock',
    'The Isley Brothers': 'R&B',
    'The Lonely Island': 'Rap',
    'The Music': 'Rock Alternativo',
    'The Offspring': 'Punk',
    'The Shins': 'Indie',
    'The Smashing Pumpkins': 'Rock Alternativo',
    'The Streets': 'Rap',
    'The Strokes': 'Rock Alternativo',
    'The Supermen Lovers': 'Eletronico',
    'The Verve Pipe': 'Rock Alternativo',
    'The White Stripes': 'Rock Alternativo',
    'Thierry Stremler': 'Pop',
    'Three-6 Mafia': 'Rap',
    'Tina Arena': 'Pop',
    'Toby Keith': 'Country',
    'Tool': 'Metal',
    'Toploader': 'Rock',
    'Torch': 'Rap',
    'Tori Amos': 'Pop',
    'Toy-Box': 'Pop',
    'Trace Adkins': 'Country',
    'Train': 'Rock',
    'Travis': 'Britpop',
    'Tre Allegri Ragazzi Morti': 'Rock Alternativo',
    'Tricky': 'Trip Hop',
    'Trisha Yearwood': 'Country',
    'Turin Brakes': 'Indie',
    'Two In One': 'Pop',
    'Télépopmusik': 'Eletronico',
    'U2': 'Rock Alternativo',
    'Unwritten Law': 'Punk',
    'Usher': 'R&B',
    'Utada Hikaru': 'J-Pop',
    'Valeria Rossi': 'Pop',
    'Velvet (2)': 'Pop',
    'Vengaboys': 'Dance',
    'Verdena': 'Rock Alternativo',
    'Victoria Beckham': 'Pop',
    'Vitamin C': 'Pop',
    'Voltaj': 'Rock',
    'Warren G': 'Rap',
    'Weezer': 'Rock Alternativo',
    'Wheatus': 'Pop',
    'Willa Ford': 'Pop',
    'Willie Nelson': 'Country',
    'Zero 7': 'Eletronico',
    'Zeromancer': 'Industrial',
    'Zoot Woman': 'Eletronico',
    'dj TAKA': 'Eletronico',
    'iiO': 'Eletronico',
    't.A.T.u.': 'Pop'
}

with open('data/2001.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for video in data:
    artist = video.get('artist_name') or video.get('artist')
    if artist in genre_map:
        video['artist_genre'] = genre_map[artist]
    else:
        video['artist_genre'] = 'Desconhecido'
    
    # Normalize artist field name
    if 'artist_name' in video:
        video['artist'] = video.pop('artist_name')

with open('data/2001.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Update complete")
