import json

genre_map = {
    '*NSYNC': 'Pop',
    '2Gether': 'Pop',
    '3 Doors Down': 'Rock Alternativo',
    '702': 'R&B',
    '8STOPS7': 'Rock',
    '98 Degrees': 'Pop',
    '99 Posse': 'Rap',
    '????? ???????': 'Desconhecido',
    'A Perfect Circle': 'Rock Alternativo',
    'A*Teens': 'Pop',
    'A.K.-S.W.I.F.T.': 'Hip Hop',
    'A1': 'Pop',
    'AC/DC': 'Rock',
    'AFI': 'Punk',
    'ATC': 'Dance',
    'Aaliyah': 'R&B',
    'Aaron Carter': 'Pop',
    'Adam Rickitt': 'Pop',
    'Afterhours': 'Rock Alternativo',
    'Agent 51': 'Punk',
    'Air': 'Eletronico',
    'Alabama 3': 'Eletronico',
    'Alcazar': 'Dance',
    'Alice Cooper': 'Rock',
    'Alice Deejay': 'Dance',
    'Alice In Chains': 'Grunge',
    'All Saints': 'Pop',
    'American Hi-Fi': 'Rock Alternativo',
    'Amil': 'Rap',
    'Anahí': 'Latino',
    'Anastacia': 'Pop',
    'Anastasia': 'Pop',
    'Angie Aparo': 'Rock',
    'Angie Stone': 'R&B',
    'Apocalyptica': 'Metal',
    'Aqua': 'Pop',
    'Aquagen': 'Dance',
    'Arch Enemy': 'Metal',
    'Ash': 'Rock Alternativo',
    'Atomic Kitten': 'Pop',
    'Audrey Hannah': 'Pop',
    'Ayman (2)': 'R&B',
    'Ayumi Hamasaki': 'J-Pop',
    'B*Witched': 'Pop',
    'B.B. King': 'Blues',
    'BT': 'Eletronico',
    'Babyboy': 'Rap',
    'Babyface': 'R&B',
    'Backstreet Boys': 'Pop',
    'Badly Drawn Boy': 'Indie',
    'Baha Men': 'Pop',
    'Band Ohne Namen': 'Pop',
    'Barenaked Ladies': 'Rock Alternativo',
    'Basement Jaxx': 'Eletronico',
    'Beanie Sigel': 'Rap',
    'Beck': 'Rock Alternativo',
    'Beenie Man': 'Reggae',
    'Belle & Sebastian': 'Indie',
    'Bentley Rhythm Ace': 'Eletronico',
    'Big Kenny (2)': 'Country',
    'Big Punisher': 'Rap',
    'Big Rory & Morag': 'Folk',
    'Big Tymers': 'Rap',
    'Billie Piper': 'Pop',
    'Billy Gilman': 'Country',
    'Björk': 'Eletronico',
    'Black Eyed Peas': 'Hip Hop',
    'Black Rob': 'Rap',
    'Blaque (2)': 'R&B',
    'Bleach (3)': 'Rock',
    'Bleachin\'': 'Eletronico',
    'Blink-182': 'Punk',
    'Bloodhound Gang': 'Rock Alternativo',
    'Blur': 'Britpop',
    'Bluvertigo': 'Rock Alternativo',
    'Blümchen': 'Dance',
    'Bob Dylan': 'Folk',
    'Bomfunk MC\'s': 'Eletronico',
    'Bon Jovi': 'Rock',
    'Bond (4)': 'Classical Crossover',
    'Bowling For Soup': 'Punk',
    'Boyz II Men': 'R&B',
    'Brad Paisley': 'Country',
    'Britney Spears': 'Pop',
    'Brooklyn Bounce': 'Dance',
    'Bubbles (5)': 'Pop',
    'Buckcherry': 'Rock',
    'Bush': 'Grunge',
    'Busta Rhymes': 'Rap',
    'C-Block': 'Hip Hop',
    'Califone': 'Indie',
    'Cam’ron': 'Rap',
    'Caparezza': 'Rap',
    'Capone-N-Noreaga': 'Rap',
    'Carmen Consoli': 'Rock Alternativo',
    'Catatonia': 'Britpop',
    'Catherine Wheel': 'Rock Alternativo',
    'Chayanne': 'Latino',
    'Chicane': 'Eletronico',
    'Chicane (4)': 'Eletronico',
    'Choclair': 'Rap',
    'Christina Aguilera': 'Pop',
    'Cider': 'Rock',
    'Cleopatra': 'Pop',
    'Cold': 'Metal',
    'Coldplay': 'Rock Alternativo',
    'Collective Soul': 'Rock Alternativo',
    'Collin Raye': 'Country',
    'Common': 'Rap',
    'Counting Crows': 'Rock Alternativo',
    'Cradle Of Filth': 'Metal',
    'Craig David': 'R&B',
    'Creed': 'Rock Alternativo',
    'Cristina Donà': 'Rock Alternativo',
    'Cypress Hill': 'Rap',
    'Céline Dion': 'Pop',
    'D.V. Alias Khrist': 'Rap',
    'D12': 'Rap',
    'DJ Tandu': 'Trance',
    'DJ Taylor & Flow': 'Dance',
    'DMX': 'Rap',
    'Daft Punk': 'Eletronico',
    'Damage': 'R&B',
    'Danacee': 'R&B',
    'Danzig': 'Metal',
    'Darryl Worley': 'Country',
    'Dave Hollister': 'R&B',
    'David Bowie': 'Rock',
    'David Gray': 'Folk',
    'David Holmes (3)': 'Eletronico',
    'De La Soul': 'Rap',
    'Death In Vegas': 'Eletronico',
    'Deftones': 'Metal',
    'Destiny\'s Child': 'R&B',
    'Detroit Grand Pubahs': 'Eletronico',
    'Disturbed': 'Metal',
    'Dixie Chicks': 'Country',
    'Donots': 'Punk',
    'Dope (4)': 'Metal',
    'Doves': 'Indie',
    'Drag On': 'Rap',
    'Drag-On': 'Rap',
    'Dream': 'Pop',
    'Duran Duran': 'Pop',
    'Dwight Yoakam': 'Country',
    'D’Angelo': 'R&B',
    'E-Type (6)': 'Dance',
    'Eagle-Eye Cherry': 'Rock Alternativo',
    'Eels': 'Indie',
    'Eiffel 65': 'Dance',
    'Einstürzende Neubauten': 'Industrial',
    'Elisa': 'Pop',
    'Elliott Smith': 'Indie',
    'Elton John': 'Pop',
    'Elwood': 'Rock',
    'Embrace': 'Britpop',
    'Eminem': 'Rap',
    'En Vogue': 'R&B',
    'Encore (3)': 'Rap',
    'Enrique Iglesias': 'Latino',
    'Entombed': 'Metal',
    'Enuff Z\'nuff': 'Rock',
    'Erasure': 'Pop',
    'Eric Clapton': 'Rock',
    'Eros Ramazzotti': 'Pop',
    'Erykah Badu': 'R&B',
    'Eurythmics': 'Pop',
    'Eve 6': 'Rock Alternativo',
    'Everclear': 'Rock Alternativo',
    'Everlast': 'Rock Alternativo',
    'Everything But The Girl': 'Eletronico',
    'Evil\'s Toy': 'Industrial',
    'Face To Face': 'Punk',
    'Faith Hill': 'Country',
    'Fastball': 'Pop',
    'Fat Lip': 'Punk',
    'Fatboy Slim': 'Eletronico',
    'Field Mob': 'Rap',
    'Filter': 'Industrial',
    'Fiona Apple': 'Rock Alternativo',
    'Fischerspooner': 'Eletronico',
    'Five': 'Pop',
    'Five For Fighting': 'Pop',
    'Florent Pagny': 'Pop',
    'Foo Fighters': 'Rock Alternativo',
    'French Affair': 'Pop',
    'Fuel': 'Rock Alternativo',
    'Funkmaster Flex': 'Rap',
    'GIL': 'Pop',
    'Gardeweg': 'Dance',
    'George Strait': 'Country',
    'Geri Halliwell': 'Pop',
    'Ghostface Killah': 'Rap',
    'Gigi D\'Agostino': 'Dance',
    'Girl Thing': 'Pop',
    'Gloria Estefan': 'Latino',
    'Godsmack': 'Metal',
    'Goldfrapp': 'Eletronico',
    'Good Charlotte': 'Punk',
    'Grand Theft Audio (3)': 'Rock',
    'Grandaddy': 'Indie',
    'Green Day': 'Punk',
    'Groove Armada': 'Eletronico',
    'Guano Apes': 'Rock Alternativo',
    'H-Blockx': 'Rock Alternativo',
    'HIM': 'Rock',
    'Handsome Boy Modeling School': 'Hip Hop',
    'Hangmen 3': 'Rap',
    'Hanson': 'Pop',
    'Harvey Danger': 'Rock Alternativo',
    'Heather Small': 'R&B',
    'Herbert Grönemeyer': 'Rock',
    'Highland': 'Hip Hop',
    'Hoku': 'Pop',
    'Hole': 'Grunge',
    'Hooverphonic': 'Eletronico',
    'Hypetraxx': 'Trance',
    'Ice Cube': 'Rap',
    'Incubus': 'Rock Alternativo',
    'India.Arie': 'R&B',
    'Inessa': 'Dance',
    'Insane Clown Posse': 'Rap',
    'Iron Maiden': 'Metal',
    'Isaac Hayes': 'R&B',
    'Ivete Sangalo': 'Latino',
    'JJ72': 'Indie',
    'Ja Rule': 'Rap',
    'Jagged Edge': 'R&B',
    'Jamelia': 'R&B',
    'Jaw': 'Rock',
    'Jay Z': 'Rap',
    'Jeanette': 'Pop',
    'Jennifer Lopez': 'Pop',
    'Jessica (2)': 'Pop',
    'Jessica Folcker': 'Pop',
    'Jessica Simpson': 'Pop',
    'Jill Scott': 'R&B',
    'Jo Dee Messina': 'Country',
    'Joe': 'R&B',
    'Juanes': 'Latino',
    'Junia': 'Pop',
    'Juvenile': 'Rap',
    'K\'s Choice': 'Rock Alternativo',
    'K-Ci & JoJo': 'R&B',
    'Kathy Mattea': 'Country',
    'Keith Caputo': 'Rock',
    'Keith Urban': 'Country',
    'Kenny Chesney': 'Country',
    'Keno (3)': 'Pop',
    'Kent': 'Rock Alternativo',
    'Kid Koala': 'Eletronico',
    'Killing Heidi': 'Rock',
    'Kim Lukas': 'Dance',
    'Kina Grannis': 'Indie',
    'Korn': 'Metal',
    'Kottonmouth Kings': 'Rap',
    'Kraftwerk': 'Eletronico',
    'Kylie Minogue': 'Pop',
    'Kyosuke Himuro': 'Rock',
    'LL Cool J': 'Rap',
    'La Crus': 'Rock Alternativo',
    'Ladytron': 'Eletronico',
    'Laura (4)': 'Pop',
    'Laura Pausini': 'Pop',
    'LeAnn Rimes': 'Country',
    'Lee Ann Womack': 'Country',
    'Leningrad Cowboys': 'Rock',
    'Lenny Kravitz': 'Rock',
    'Leona Naess': 'Indie',
    'Lil Mo': 'R&B',
    'Limp Bizkit': 'Metal',
    'Linea 77': 'Metal',
    'Litfiba': 'Rock',
    'Live': 'Rock Alternativo',
    'Logan Lynn': 'Indie',
    'Los Tigres Del Norte': 'Latino',
    'Lou Bega': 'Pop',
    'Louise': 'Pop',
    'Lovestern Galaktika Project': 'Dance',
    'Ludacris': 'Rap',
    'M.O.P.': 'Rap',
    'M2M': 'Pop',
    'Mack 10': 'Rap',
    'Macy Gray': 'R&B',
    'Madasun': 'Pop',
    'Madonna': 'Pop',
    'Magnus Uggla': 'Rock',
    'Malice Mizer': 'Visual Kei',
    'Manchild (5)': 'Eletronico',
    'Mando Diao': 'Rock',
    'Mandy Moore': 'Pop',
    'Mansun': 'Britpop',
    'Marc Almond': 'Pop',
    'Marc Anthony': 'Latino',
    'Marco Da Silva': 'Pop',
    'Mariah Carey': 'R&B',
    'Marilyn Manson': 'Industrial',
    'Marius Müller-Westernhagen': 'Rock',
    'Mark Wills': 'Country',
    'Marlene Kuntz': 'Rock Alternativo',
    'Martillo Vago': 'Dance',
    'Mary Mary': 'Gospel',
    'Master P': 'Rap',
    'Matchbox Twenty': 'Rock Alternativo',
    'Matt Bianco': 'Pop',
    'Mau Maus': 'Punk',
    'Mauro Picotto': 'Trance',
    'Maxim': 'Eletronico',
    'Mel B': 'Pop',
    'Melanie C': 'Pop',
    'Melanie Thornton': 'Pop',
    'Mellow': 'Eletronico',
    'Memphis Bleek': 'Rap',
    'Mest': 'Punk',
    'Metallica': 'Metal',
    'Mew': 'Indie',
    'Michael Jackson': 'Pop',
    'Michael Learns To Rock': 'Pop',
    'Mietta': 'Pop',
    'Millencolin': 'Punk',
    'Moby': 'Eletronico',
    'Modern Talking': 'Pop',
    'Moloko': 'Eletronico',
    'Moltheni': 'Indie',
    'Monster Magnet': 'Rock',
    'Montell Jordan': 'R&B',
    'Moonbaby': 'Pop',
    'Morcheeba': 'Trip Hop',
    'Mos Def': 'Rap',
    'Motörhead': 'Metal',
    'Mr. Oizo': 'Eletronico',
    'Mr. X & Mr. Y': 'Trance',
    'Mudvayne': 'Metal',
    'Muse': 'Rock Alternativo',
    'Musiq': 'R&B',
    'MxPx': 'Punk',
    'Mya': 'R&B',
    'Myslovitz': 'Rock Alternativo',
    'Mystikal': 'Rap',
    'Nas': 'Rap',
    'Natalia Oreiro': 'Latino',
    'Nelly': 'Rap',
    'Nelly Furtado': 'Pop',
    'Nevermore': 'Metal',
    'Next': 'R&B',
    'Nickelback': 'Rock',
    'Nicki Nyce': 'Rap',
    'Nine Inch Nails': 'Industrial',
    'No Doubt': 'Ska',
    'OPM (2)': 'Rap',
    'Oasis': 'Britpop',
    'One Nation Crew': 'Gospel',
    'OnePhatDeeva': 'House',
    'Opera IX': 'Metal',
    'Orgy': 'Industrial',
    'Orishas': 'Latino',
    'Our Lady Peace': 'Rock Alternativo',
    'OutKast': 'Rap',
    'P.A.': 'Rap',
    'PJ Harvey': 'Rock Alternativo',
    'Pale 3': 'Eletronico',
    'Pantera': 'Metal',
    'Paola & Chiara': 'Pop',
    'Papa Roach': 'Metal',
    'Paradisio': 'Dance',
    'Passion Fruit': 'Dance',
    'Patrick Bruel': 'Pop',
    'Paula Cole': 'Pop',
    'Paulina Rubio': 'Latino',
    'Peaches': 'Eletronico',
    'Pet Shop Boys': 'Pop',
    'Philly’s Most Wanted': 'Rap',
    'Phoenix': 'Indie',
    'Pia Lund': 'Rock',
    'Pillar': 'Rock',
    'Pink': 'Pop',
    'Piotta': 'Rap',
    'Placebo': 'Rock Alternativo',
    'Powderfinger': 'Rock',
    'Powerman 5000': 'Metal',
    'Prezioso': 'Dance',
    'Primal Scream': 'Rock Alternativo',
    'Primus': 'Rock Alternativo',
    'Prince': 'Funk',
    'Project 86': 'Rock',
    'Project Pitchfork': 'Industrial',
    'Puff Daddy': 'Rap',
    'Punkreas (2)': 'Punk',
    'Pur': 'Pop',
    'Q-Tip': 'Rap',
    'Quannum MC\'s': 'Hip Hop',
    'Queens Of The Stone Age': 'Rock',
    'Queensrÿche': 'Metal',
    'R. Kelly': 'R&B',
    'Rage Against The Machine': 'Rock Alternativo',
    'Rappers Against Racism': 'Hip Hop',
    'Raptile': 'Rap',
    'Rebecca Lynn Howard': 'Country',
    'Red Hot Chili Peppers': 'Rock Alternativo',
    'Rednex': 'Pop',
    'Reef': 'Rock',
    'Rehab (2)': 'Rock',
    'Relient K': 'Punk',
    'Richard Ashcroft': 'Rock Alternativo',
    'Ricky': 'Pop',
    'Ricky Martin': 'Latino',
    'Robbie Williams': 'Pop',
    'Robert Plant': 'Rock',
    'Robin Grubert': 'Pop',
    'Rod Stewart': 'Rock',
    'Ronan Keating': 'Pop',
    'Roni Size': 'Drum and Bass',
    'Rosenstolz': 'Pop',
    'Ruff Endz': 'R&B',
    'S Club 7': 'Pop',
    'Sade': 'R&B',
    'Saliva': 'Metal',
    'Sam Salter': 'R&B',
    'Samantha Mumba': 'Pop',
    'Sammie (2)': 'R&B',
    'Sammie Double L': 'Hip Hop',
    'Sander Kleinenberg': 'House',
    'Sara Evans': 'Country',
    'Sash!': 'Dance',
    'Saturnino': 'Funk',
    'Savage Garden': 'Pop',
    'Scarface': 'Rap',
    'Scisma': 'Rock Alternativo',
    'Scooter': 'Techno',
    'Seal': 'R&B',
    'Sean Paul': 'Reggae',
    'Second Coming': 'Rock',
    'Sevendust': 'Metal',
    'Shade Sheist': 'Rap',
    'Shaggy': 'Reggae',
    'Shakira': 'Latino',
    'Shawn Mullins': 'Rock',
    'Sheena Easton': 'Pop',
    'Shemsi': 'Pop',
    'Shola Ama': 'R&B',
    'Shyne': 'Rap',
    'Sigmatibet': 'Eletronico',
    'Silverchair': 'Grunge',
    'Simply Red': 'Pop',
    'Sinéad O\'Connor': 'Rock Alternativo',
    'Sisqó': 'R&B',
    'Sister Hazel': 'Rock',
    'Ski Oakenfull': 'Eletronico',
    'Sleater-Kinney': 'Punk',
    'Slipknot': 'Metal',
    'Smash Mouth': 'Rock Alternativo',
    'Snoop Dogg': 'Rap',
    'Snow Patrol': 'Indie',
    'Sol y Mar': 'Latino',
    'Sonic Youth': 'Rock Alternativo',
    'Sonique': 'Dance',
    'Sonny Jones': 'Pop',
    'Soraya (4)': 'Latino',
    'Spagna': 'Dance',
    'Sparkle': 'R&B',
    'Sparks': 'Pop',
    'Spice Girls': 'Pop',
    'Spike': 'Pop',
    'Spiller': 'House',
    'Spineshank': 'Metal',
    'Splender': 'Rock',
    'Spooks': 'Hip Hop',
    'Spooman': 'Rap',
    'Spoon': 'Indie',
    'Staind': 'Metal',
    'Static-X': 'Metal',
    'Stephen Gately': 'Pop',
    'Steps': 'Pop',
    'Sting': 'Rock',
    'Stone Temple Pilots': 'Grunge',
    'Subsonica': 'Eletronico',
    'Subzonic': 'Rock',
    'Sugo y sol': 'Latino',
    'Sum 41': 'Punk',
    'Sunna': 'Industrial',
    'Super Furry Animals': 'Indie',
    'Switchfoot': 'Rock Alternativo',
    'Syria': 'Pop',
    'TLC': 'R&B',
    'Take 5': 'Pop',
    'Talib Kweli': 'Rap',
    'Tamia (2)': 'R&B',
    'Tank': 'R&B',
    'Tara MacLean': 'Folk',
    'Tash': 'Pop',
    'Teenage Fanclub': 'Indie',
    'Terri Clark': 'Country',
    'Terry Dexter': 'R&B',
    'Terry Lovique': 'R&B',
    'Texas': 'Pop',
    'Thalía': 'Latino',
    'The 7 Inch Project': 'Eletronico',
    'The Beatles': 'Rock',
    'The Bluetones': 'Britpop',
    'The Charlatans': 'Britpop',
    'The Corrs': 'Pop',
    'The Cranberries': 'Rock Alternativo',
    'The Dandy Warhols': 'Rock Alternativo',
    'The Hives': 'Rock',
    'The Killer Barbies': 'Punk',
    'The Kinleys': 'Country',
    'The Lox': 'Rap',
    'The Mighty Mighty Bosstones': 'Ska',
    'The New Pornographers': 'Indie',
    'The Offspring': 'Punk',
    'The Pharcyde': 'Rap',
    'The Smashing Pumpkins': 'Rock Alternativo',
    'The Temptations': 'R&B',
    'The Tragically Hip': 'Rock',
    'The Tribe': 'Gospel',
    'The Underdog Project': 'Dance',
    'The Vygors': 'Pop',
    'The Wallflowers': 'Rock',
    'The Yo-Yo\'s': 'Rock',
    'They Might Be Giants': 'Rock Alternativo',
    'Thierry Stremler': 'Pop',
    'Thievery Corporation': 'Eletronico',
    'Third Eye Blind': 'Rock Alternativo',
    'Three-6 Mafia': 'Rap',
    'Tim Christensen': 'Rock',
    'Tina Arena': 'Pop',
    'Tina Turner': 'Pop',
    'Tom Jones': 'Pop',
    'Tomcat (5)': 'Pop',
    'Tommy Thompson (2)': 'Country',
    'Toni Braxton': 'R&B',
    'Tonic (2)': 'Rock',
    'Toploader': 'Rock',
    'Torch': 'Rap',
    'Tracy Bonham': 'Rock Alternativo',
    'Travis Tritt': 'Country',
    'Tre Allegri Ragazzi Morti': 'Rock Alternativo',
    'True Steppers': 'Garage',
    'Tyrese': 'R&B',
    'U2': 'Rock Alternativo',
    'Uncle Kracker': 'Rock',
    'Ute Lemper': 'Pop',
    'Vanessa Carlton': 'Pop',
    'Vanessa Paradis': 'Pop',
    'Velvet (2)': 'Pop',
    'Vengaboys': 'Dance',
    'Verdena': 'Rock Alternativo',
    'Vertical Horizon': 'Rock',
    'Videodrone': 'Metal',
    'Violent Femmes': 'Rock Alternativo',
    'Vitamin C': 'Pop',
    'Voltaj': 'Rock',
    'W.I.R.': 'Pop',
    'Wannadies, The': 'Britpop',
    'Westlife': 'Pop',
    'Wheatus': 'Pop',
    'Whitney Houston': 'Pop',
    'Will Smith': 'Rap',
    'Worthy Davis': 'R&B',
    'Wu-Tang Clan': 'Rap',
    'Wyclef Jean': 'Rap',
    'X-Perience': 'Pop',
    'Xzibit': 'Rap',
    'Yamboo': 'Dance',
    'Yannick Noah': 'Pop',
    'Zebrahead': 'Punk',
    'Zorotl': 'Eletronico',
    'a-ha': 'Pop',
    'soulDecision': 'Pop'
}

with open('data/2000.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for video in data:
    artist = video.get('artist_name') or video.get('artist')
    if artist in genre_map:
        video['artist_genre'] = genre_map[artist]
    else:
        video['artist_genre'] = 'Desconhecido'
    
    # Normalize artist field name
    if 'artist_name' in video:
        video['artist'] = video.pop('artist_name')

with open('data/2000.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Update complete")
