import json

genre_map = {
    '38 Special': 'Rock',
    'Accept': 'Metal',
    'Adam Ant': 'Pop',
    'Alarm (3)': 'Rock Alternativo',
    'Alison Moyet': 'Pop',
    'Alphaville': 'Eletronico',
    'Amy Grant': 'Pop',
    'Anne Murray': 'Country',
    'Any Trouble': 'Pop',
    'Art Of Noise': 'Eletronico',
    'Bananarama': 'Pop',
    'Band Aid': 'Pop',
    'Barbra Streisand': 'Pop',
    'Berlin': 'Eletronico',
    'Bette Midler': 'Pop',
    'Big Country': 'Rock Alternativo',
    'Billy Idol': 'Rock',
    'Billy Joel': 'Rock',
    'Billy Ocean': 'R&B',
    'Bone Orchard': 'Goth',
    'Bonnie Tyler': 'Rock',
    'Bronski Beat': 'Eletronico',
    'Bruce Springsteen': 'Rock',
    'Bryan Adams': 'Rock',
    'Carmel': 'Jazz',
    'Chad & Jeremy': 'Pop',
    'Charlotte Gainsbourg': 'Pop',
    'Cheap Trick': 'Rock',
    'Cherrelle': 'R&B',
    'Chicago': 'Rock',
    'Cocteau Twins': 'Rock Alternativo',
    'Cold Chisel': 'Rock',
    'Corey Hart': 'Pop',
    'Corynne Charby': 'Pop',
    'Culture Club': 'Pop',
    'Cyndi Lauper': 'Pop',
    'Dan Hartman': 'Pop',
    'David Bowie': 'Rock',
    'David Lee Roth': 'Rock',
    'Dead Can Dance': 'Rock Alternativo',
    'Dead Or Alive': 'Pop',
    'Deep Purple': 'Rock',
    'Def Leppard': 'Metal',
    'Den Harrow': 'Eletronico',
    'Depeche Mode': 'Eletronico',
    'Diana Ross': 'R&B',
    'Dokken': 'Metal',
    'Don Henley': 'Rock',
    'Donna Summer': 'R&B',
    'Dr. Hook': 'Rock',
    'Duran Duran': 'Pop',
    'Echo & The Bunnymen': 'Rock Alternativo',
    'Eddie Money': 'Rock',
    'Elmo & Patsy': 'Pop',
    'Elton John': 'Pop',
    'Everything But The Girl': 'Eletronico',
    'Falco': 'Eletronico',
    'Fiona Flanagan': 'Rock',
    'Fred Schneider': 'Pop',
    'General Public': 'Rock Alternativo',
    'Genesis': 'Rock',
    'George Michael': 'Pop',
    'Go-Go\'s': 'Pop',
    'Godley & Creme': 'Pop',
    'Hank Williams Jr.': 'Country',
    'Hanoi Rocks': 'Rock',
    'Herbert Grönemeyer': 'Rock',
    'Herbie Hancock': 'Jazz',
    'Honeymoon Suite': 'Rock',
    'Howard Jones': 'Eletronico',
    'Huey Lewis': 'Rock',
    'Hunters & Collectors': 'Rock Alternativo',
    'Ian Hunter': 'Rock',
    'Icehouse': 'Rock Alternativo',
    'In Parallel': 'Pop',
    'Iron Maiden': 'Metal',
    'Isabelle Adjani': 'Pop',
    'Jean-Michel Jarre': 'Eletronico',
    'Jermaine Jackson': 'R&B',
    'Jimmy Cliff': 'Reggae',
    'John Lennon': 'Rock',
    'John Mellencamp': 'Rock',
    'Judas Priest': 'Metal',
    'Julian Cope': 'Rock Alternativo',
    'Julian Lennon': 'Pop',
    'Julien Clerc': 'Pop',
    'Kane Gang': 'Pop',
    'Kenny Loggins': 'Rock',
    'Killing Joke': 'Rock Alternativo',
    'Kim Carnes': 'Pop',
    'Kim Wilde': 'Pop',
    'Kiss': 'Rock',
    'Klymaxx': 'R&B',
    'Kurtis Blow': 'Rap',
    'Laura Branigan': 'Pop',
    'Leonard Cohen': 'Folk',
    'Limahl': 'Pop',
    'Lionel Richie': 'R&B',
    'Lita Ford': 'Rock',
    'Litfiba': 'Rock',
    'Lou Reed': 'Rock',
    'Madness': 'Ska',
    'Madonna': 'Pop',
    'Marilyn': 'Pop',
    'Matt Bianco': 'Pop',
    'Mecano': 'Pop',
    'Mel Brooks': 'Pop',
    'Men Without Hats': 'Eletronico',
    'Mick Smiley': 'Pop',
    'Miko Mission': 'Eletronico',
    'Missing Persons': 'Rock Alternativo',
    'Modern Talking': 'Pop',
    'Motörhead': 'Metal',
    'Mr. Mister': 'Rock',
    'Mötley Crüe': 'Metal',
    'Nena': 'Pop',
    'New Edition': 'R&B',
    'Night Ranger': 'Rock',
    'Nik Kershaw': 'Pop',
    'Orchestral Manoeuvres In The Dark': 'Eletronico',
    'Os Paralamas Do Sucesso': 'Rock',
    'Pat Benatar': 'Rock',
    'Pet Shop Boys': 'Eletronico',
    'Phil Collins': 'Pop',
    'Philip Bailey': 'R&B',
    'Philip Oakey': 'Eletronico',
    'Prefab Sprout': 'Pop',
    'Prince': 'Funk',
    'Public Image Limited': 'Rock Alternativo',
    'Queen': 'Rock',
    'Queensrÿche': 'Metal',
    'R.E.M.': 'Rock Alternativo',
    'REO Speedwagon': 'Rock',
    'Ratt': 'Metal',
    'Ray Parker Jr.': 'R&B',
    'Red Hot Chili Peppers': 'Rock Alternativo',
    'Red Rider': 'Rock',
    'Rhema': 'Pop',
    'Rick Springfield': 'Rock',
    'Ritchie': 'Rock',
    'Rod Stewart': 'Rock',
    'Roger Glover': 'Rock',
    'Romeo Void': 'Rock Alternativo',
    'Run-DMC': 'Rap',
    'Rush': 'Rock',
    'Scandal (4)': 'Rock',
    'Scorpions': 'Rock',
    'Scritti Politti': 'Pop',
    'Shannon': 'Dance',
    'Sheena Easton': 'Pop',
    'Simple Minds': 'Rock Alternativo',
    'Siouxsie & The Banshees': 'Rock Alternativo',
    'Skeletal Family': 'Goth',
    'Spandau Ballet': 'Pop',
    'Sparks': 'Pop',
    'Status Quo': 'Rock',
    'Steve Arrington\'s Hall Of Fame': 'Funk',
    'Steve Perry': 'Rock',
    'Stiff All Stars': 'Pop',
    'Survivor': 'Rock',
    'Swans Way': 'Pop',
    'Talk Talk': 'Eletronico',
    'Tears For Fears': 'Eletronico',
    'The Alan Parsons Project': 'Rock',
    'The Bangles': 'Pop',
    'The Boomtown Rats': 'Rock Alternativo',
    'The Cars': 'Rock',
    'The Cure': 'Rock Alternativo',
    'The Earons': 'Funk',
    'The Fixx': 'Rock Alternativo',
    'The Human League': 'Eletronico',
    'The Jacksons': 'R&B',
    'The Kinks': 'Rock',
    'The Pointer Sisters': 'R&B',
    'The Psychedelic Furs': 'Rock Alternativo',
    'The Rolling Stones': 'Rock',
    'The Smiths': 'Rock Alternativo',
    'The Stranglers': 'Rock',
    'The Twins': 'Eletronico',
    'The Untouchables': 'Ska',
    'This Mortal Coil': 'Rock Alternativo',
    'Thomas Dolby': 'Eletronico',
    'Thompson Twins': 'Eletronico',
    'Timothy B. Schmit': 'Rock',
    'Tina Turner': 'Rock',
    'Toy Dolls': 'Punk',
    'Twisted Sister': 'Metal',
    'U2': 'Rock Alternativo',
    'UB40': 'Reggae',
    'Ultravox': 'Eletronico',
    'Valerie Dore': 'Eletronico',
    'Van Halen': 'Rock',
    'Wang Chung': 'Pop',
    'Weird Al Yankovic': 'Pop',
    'Wham!': 'Pop',
    'Whitesnake': 'Rock',
    'XTC': 'Rock Alternativo',
    'ZZ Top': 'Rock',
    'Zerra One': 'Rock',
    'a-ha': 'Pop'
}

with open('data/1984.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for video in data:
    artist = video.get('artist_name') or video.get('artist')
    if artist in genre_map:
        video['artist_genre'] = genre_map[artist]
    else:
        video['artist_genre'] = 'Desconhecido'
    
    # Normalize artist field name
    if 'artist_name' in video:
        video['artist'] = video.pop('artist_name')

with open('data/1984.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("Update complete")
