import json

# Mapping of artists to genres for 1989
genre_mapping = {
    # Pop
    "Madonna": "Pop",
    "Janet Jackson": "Pop",
    "Paula Abdul": "Pop",
    "Kylie Minogue": "Pop",
    "Phil Collins": "Pop",
    "Billy Joel": "Pop",
    "Elton John": "Pop",
    "Cher": "Pop",
    "Tina Turner": "Pop",
    "Prince": "Pop",
    "Michael Jackson": "Pop",
    "George Michael": "Pop",
    "Whitney Houston": "Pop",
    "Gloria Estefan": "Pop",
    "Roxette": "Pop",
    "Milli Vanilli": "Pop",
    "New Kids On The Block": "Pop",
    "Debbie Gibson": "Pop",
    "Cyndi Lauper": "Pop",
    "Sheena Easton": "Pop",
    "Belinda Carlisle": "Pop",
    "Taylor Dayne": "Pop",
    "Richard Marx": "Pop",
    "Rod Stewart": "Pop",
    "B-52's": "Pop",
    "The B-52's": "Pop",
    "Fine Young Cannibals": "Pop",
    "Tears For Fears": "Pop",
    "Eurythmics": "Pop",
    "Duran Duran": "Pop",
    "Pet Shop Boys": "Pop",
    "Erasure": "Pop",
    "Depeche Mode": "Pop", # Synth-pop
    "New Order": "Pop",
    "The Bangles": "Pop",
    "Bananarama": "Pop",
    "Exposé": "Pop",
    "Martika": "Pop",
    "Jody Watley": "Pop",
    "Lisa Stansfield": "Pop",
    "Vanessa Williams": "Pop",
    "Karyn White": "Pop",
    "Babyface": "Pop", # R&B
    "Bobby Brown": "Pop", # R&B
    "Soul II Soul": "Pop", # R&B
    "Miki Howard": "Pop",
    "Angela Winbush": "Pop",
    "Regina Belle": "Pop",
    "Stephanie Mills": "Pop",
    "Anita Baker": "Pop",
    "Sade": "Pop",
    "Simply Red": "Pop",
    "Rick Astley": "Pop",
    "Jason Donovan": "Pop",
    "Bros": "Pop",
    "Big Fun": "Pop",
    "Sonia": "Pop",
    "Sinitta": "Pop",
    "London Boys": "Pop",
    "Kaoma": "Pop",
    "Jive Bunny And The Mastermixers": "Pop",
    "Black Box": "Pop", # Dance
    "Technotronic": "Pop", # Dance
    "S'Express": "Pop",
    "The KLF": "Pop",
    "Coldcut": "Pop",
    "808 State": "Eletronico", # Acid House
    "Inner City": "Pop",
    "Adeva": "Pop",
    "Lil Louis": "Pop",
    "D-Mob": "Pop",
    "Beatmasters": "Pop",
    "Yello": "Pop",
    "Kon Kan": "Pop",
    "Information Society": "Pop",
    "Camouflage": "Pop",
    "Alphaville": "Pop",
    "Sandra": "Pop",
    "Die Toten Hosen": "Pop", # Punk/Rock
    "Nena": "Pop",
    "Mylène Farmer": "Pop",
    "Patricia Kaas": "Pop",
    "Vanessa Paradis": "Pop",
    "Les Rita Mitsouko": "Pop",
    "Mecano": "Pop",
    "Gipsy Kings": "Pop",
    "Gypsy Kings": "Pop",
    "Kaoma": "Pop",
    "Xuxa": "Pop",
    "Legião Urbana": "Rock Alternativo", # Brazilian Rock
    "Titãs": "Rock Alternativo",
    "Paralamas do Sucesso": "Rock Alternativo",
    "Engenheiros do Hawaii": "Rock Alternativo",
    "RPM": "Pop",
    "Ritchie": "Pop",
    "Kid Abelha": "Pop",
    "Lulu Santos": "Pop",
    "Marina Lima": "Pop",
    "Gal Costa": "Pop",
    "Caetano Veloso": "Pop",
    "Gilberto Gil": "Pop",
    "Djavan": "Pop",
    "Elba Ramalho": "Pop",
    "Fafá de Belém": "Pop",
    "Simone": "Pop",
    "Rosana": "Pop",
    "Sandra de Sá": "Pop",
    "Tim Maia": "Pop",
    "Jorge Ben Jor": "Pop",
    "Zeca Pagodinho": "Pop",
    "Beth Carvalho": "Pop",
    "Alcione": "Pop",
    "Chitãozinho & Xororó": "Country",
    "Leandro & Leonardo": "Country",
    "Zezé Di Camargo & Luciano": "Country",
    "Sérgio Reis": "Country",
    "Roberta Miranda": "Country",
    "Bee Gees": "Pop",
    "Cliff Richard": "Pop",
    "Wet Wet Wet": "Pop",
    "Danny Wilson": "Pop",
    "Hue And Cry": "Pop",
    "Deacon Blue": "Pop",
    "Fairground Attraction": "Pop",
    "Tanita Tikaram": "Pop",
    "Edie Brickell & New Bohemians": "Pop",
    "Tracy Chapman": "Pop",
    "Suzanne Vega": "Pop",
    "10,000 Maniacs": "Pop",
    "Indigo Girls": "Pop",
    "Shawn Colvin": "Pop",
    "Julia Fordham": "Pop",
    "Sarah McLachlan": "Pop",
    "Enya": "Pop", # New Age
    "Clannad": "Pop",
    "Mike + The Mechanics": "Pop",
    "Paul Carrack": "Pop",
    "Wang Chung": "Pop",
    "Cutting Crew": "Pop",
    "Mr. Mister": "Pop",
    "Glass Tiger": "Pop",
    "Corey Hart": "Pop",
    "Honeymoon Suite": "Pop",
    "Gowan": "Pop",
    "Alannah Myles": "Rock Alternativo",
    "Kim Mitchell": "Rock Alternativo",
    "Tom Cochrane": "Rock Alternativo",
    "Blue Rodeo": "Country", # Country Rock
    "The Tragically Hip": "Rock Alternativo",
    "54-40": "Rock Alternativo",
    "Sloan": "Rock Alternativo",
    
    # Rock / Alternativo
    "R.E.M.": "Rock Alternativo",
    "The Cure": "Rock Alternativo",
    "The Smiths": "Rock Alternativo",
    "Morrissey": "Rock Alternativo",
    "New Order": "Rock Alternativo", # Synth-pop
    "Depeche Mode": "Rock Alternativo",
    "Echo & The Bunnymen": "Rock Alternativo",
    "The Jesus and Mary Chain": "Rock Alternativo",
    "The Jesus And Mary Chain": "Rock Alternativo",
    "Pixies": "Rock Alternativo",
    "Sonic Youth": "Rock Alternativo",
    "Dinosaur Jr.": "Rock Alternativo",
    "Hüsker Dü": "Punk",
    "The Replacements": "Rock Alternativo",
    "Violent Femmes": "Rock Alternativo",
    "They Might Be Giants": "Rock Alternativo",
    "Camper Van Beethoven": "Rock Alternativo",
    "The B-52s": "Pop",
    "Talking Heads": "Rock Alternativo",
    "David Byrne": "Rock Alternativo",
    "Tom Petty": "Rock Alternativo",
    "Tom Petty And The Heartbreakers": "Rock Alternativo",
    "Traveling Wilburys": "Rock Alternativo",
    "Roy Orbison": "Rock Alternativo",
    "Bob Dylan": "Rock Alternativo",
    "Neil Young": "Rock Alternativo",
    "Lou Reed": "Rock Alternativo",
    "Elvis Costello": "Rock Alternativo",
    "XTC": "Rock Alternativo",
    "Squeeze": "Pop",
    "Crowded House": "Pop",
    "Split Enz": "Pop",
    "Midnight Oil": "Rock Alternativo",
    "INXS": "Pop", # Rock
    "Men At Work": "Pop",
    "Icehouse": "Rock Alternativo",
    "The Church": "Rock Alternativo",
    "Hunters & Collectors": "Rock Alternativo",
    "The Go-Betweens": "Rock Alternativo",
    "Nick Cave & The Bad Seeds": "Rock Alternativo",
    "The Stone Roses": "Rock Alternativo",
    "Happy Mondays": "Rock Alternativo",
    "Inspiral Carpets": "Rock Alternativo",
    "The Charlatans": "Rock Alternativo",
    "Primal Scream": "Rock Alternativo",
    "The La's": "Rock Alternativo",
    "The Sundays": "Rock Alternativo",
    "Cocteau Twins": "Rock Alternativo",
    "My Bloody Valentine": "Rock Alternativo",
    "Ride": "Rock Alternativo",
    "Lush": "Rock Alternativo",
    "Slowdive": "Rock Alternativo",
    "Spacemen 3": "Rock Alternativo",
    "Galaxie 500": "Rock Alternativo",
    "The Psychedelic Furs": "Rock Alternativo",
    "Love And Rockets": "Rock Alternativo",
    "Bauhaus": "Rock Alternativo",
    "Siouxsie and the Banshees": "Rock Alternativo",
    "The Sisters of Mercy": "Rock Alternativo",
    "The Cult": "Rock Alternativo",
    "Jane's Addiction": "Rock Alternativo",
    "Red Hot Chili Peppers": "Rock Alternativo",
    "Faith No More": "Rock Alternativo",
    "Living Colour": "Rock Alternativo",
    "Fishbone": "Rock Alternativo",
    "24-7 Spyz": "Rock Alternativo",
    "Primus": "Rock Alternativo",
    "Fugazi": "Punk",
    "Bad Brains": "Punk",
    "Minor Threat": "Punk",
    "Dead Kennedys": "Punk",
    "Black Flag": "Punk",
    "Circle Jerks": "Punk",
    "Descendents": "Punk",
    "Bad Religion": "Punk",
    "NOFX": "Punk",
    "The Offspring": "Punk",
    "Green Day": "Punk",
    "Nirvana": "Rock Alternativo",
    "Soundgarden": "Rock Alternativo",
    "Mudhoney": "Rock Alternativo",
    "Tad": "Rock Alternativo",
    "Alice In Chains": "Metal",
    "Mother Love Bone": "Rock Alternativo",
    "Screaming Trees": "Rock Alternativo",
    "The Melvins": "Metal",
    "L7": "Rock Alternativo",
    "Babes in Toyland": "Rock Alternativo",
    "Bikini Kill": "Punk",
    "Hole": "Rock Alternativo",
    "Nine Inch Nails": "Toque Industrial", # Industrial
    "Ministry": "Toque Industrial",
    "Skinny Puppy": "Toque Industrial",
    "Front 242": "Toque Industrial",
    "Nitzer Ebb": "Toque Industrial",
    "KMFDM": "Toque Industrial",
    "My Life With The Thrill Kill Kult": "Toque Industrial",
    "Revolting Cocks": "Toque Industrial",
    "Big Country": "Rock Alternativo",
    "U2": "Rock Alternativo",
    "Simple Minds": "Rock Alternativo",
    "The Alarm": "Rock Alternativo",
    "Alarm (3)": "Rock Alternativo",
    "Hothouse Flowers": "Rock Alternativo",
    "The Waterboys": "Rock Alternativo",
    "The Pogues": "Rock Alternativo", # Folk Punk
    "Sinéad O'Connor": "Rock Alternativo",
    "Kate Bush": "Pop", # Art Pop
    "Peter Gabriel": "Pop", # Art Pop
    "Sting": "Pop",
    "Paul Simon": "Pop",
    "Dire Straits": "Rock Alternativo",
    "Mark Knopfler": "Rock Alternativo",
    "Chris Rea": "Pop",
    "Robert Palmer": "Pop",
    "Steve Winwood": "Pop",
    "Bryan Ferry": "Pop",
    "Roxy Music": "Pop",
    "David Bowie": "Rock Alternativo",
    "Mick Jagger": "Rock Alternativo",
    "Keith Richards": "Rock Alternativo",
    "The Rolling Stones": "Rock Alternativo",
    "Paul McCartney": "Pop",
    "George Harrison": "Pop",
    "Ringo Starr": "Pop",
    "The Beach Boys": "Pop",
    "Brian Wilson": "Pop",
    "Chicago": "Pop",
    "Toto": "Pop",
    "Kenny Loggins": "Pop",
    "Michael McDonald": "Pop",
    "Hall & Oates": "Pop",
    "Daryl Hall": "Pop",
    "John Oates": "Pop",
    "Huey Lewis And The News": "Pop",
    "Starship": "Pop",
    "Starship (2)": "Pop",
    "Jefferson Starship": "Pop",
    "Heart": "Rock Alternativo",
    "Pat Benatar": "Rock Alternativo",
    "Joan Jett": "Rock Alternativo",
    "Lita Ford": "Metal",
    "Vixen": "Metal",
    "Bonnie Raitt": "Pop", # Blues Rock
    "Stevie Nicks": "Pop",
    "Fleetwood Mac": "Pop",
    "Lindsey Buckingham": "Pop",
    "Don Henley": "Pop",
    "Glenn Frey": "Pop",
    "The Eagles": "Pop",
    
    # Metal / Hard Rock
    "Guns N' Roses": "Metal",
    "Mötley Crüe": "Metal",
    "Motley Crue": "Metal",
    "Poison": "Metal",
    "Def Leppard": "Metal",
    "Bon Jovi": "Metal",
    "Aerosmith": "Metal",
    "Van Halen": "Metal",
    "Skid Row": "Metal",
    "Warrant": "Metal",
    "Cinderella": "Metal",
    "Ratt": "Metal",
    "Dokken": "Metal",
    "Quiet Riot": "Metal",
    "Twisted Sister": "Metal",
    "Whitesnake": "Metal",
    "Scorpions": "Metal",
    "Europe": "Metal",
    "W.A.S.P.": "Metal",
    "Alice Cooper": "Metal",
    "Kiss": "Metal",
    "Ozzy Osbourne": "Metal",
    "Judas Priest": "Metal",
    "Iron Maiden": "Metal",
    "Metallica": "Metal",
    "Megadeth": "Metal",
    "Slayer": "Metal",
    "Anthrax": "Metal",
    "Testament": "Metal",
    "Exodus": "Metal",
    "Overkill": "Metal",
    "Sepultura": "Metal",
    "Pantera": "Metal",
    "Motorhead": "Metal",
    "Motörhead": "Metal",
    "Dio": "Metal",
    "Rainbow": "Metal",
    "Deep Purple": "Metal",
    "Black Sabbath": "Metal",
    "Led Zeppelin": "Metal",
    "AC/DC": "Metal",
    "The Cult": "Rock Alternativo", # Hard Rock
    "Great White": "Metal",
    "Tesla": "Metal",
    "Queensryche": "Metal",
    "Queensrÿche": "Metal",
    "Extreme": "Metal",
    "Mr. Big": "Metal",
    "Damn Yankees": "Metal",
    "Bad English": "Pop", # Rock
    "The Black Crowes": "Rock Alternativo",
    "Danrig": "Metal",
    "Danzig": "Metal",
    "Soundgarden": "Rock Alternativo", # Grunge
    
    # Rap / Hip Hop
    "Public Enemy": "Rap",
    "N.W.A": "Rap",
    "Eazy-E": "Rap",
    "Ice Cube": "Rap",
    "Dr. Dre": "Rap",
    "Run-D.M.C.": "Rap",
    "Beastie Boys": "Rap",
    "LL Cool J": "Rap",
    "Slick Rick": "Rap",
    "Big Daddy Kane": "Rap",
    "Rakim": "Rap",
    "Eric B. & Rakim": "Rap",
    "Kool G Rap": "Rap",
    "Boogie Down Productions": "Rap",
    "KRS-One": "Rap",
    "EPMD": "Rap",
    "De La Soul": "Rap",
    "A Tribe Called Quest": "Rap",
    "Jungle Brothers": "Rap",
    "Queen Latifah": "Rap",
    "Monie Love": "Rap",
    "MC Lyte": "Rap",
    "Salt-N-Pepa": "Rap",
    "Salt 'N' Pepa": "Rap",
    "JJ Fad": "Rap",
    "Tone Loc": "Rap",
    "Young MC": "Rap",
    "Rob Base & DJ E-Z Rock": "Rap",
    "DJ Jazzy Jeff & The Fresh Prince": "Rap",
    "Heavy D & The Boyz": "Rap",
    "Heavy D. & The Boyz": "Rap",
    "Digital Underground": "Rap",
    "Biz Markie": "Rap",
    "2 Live Crew": "Rap",
    "Ice-T": "Rap",
    "Too Short": "Rap",
    "Geto Boys": "Rap",
    "Scarface": "Rap",
    "The D.O.C.": "Rap",
    "Grandmaster Flash": "Rap",
    "Melle Mel": "Rap",
    "Afrika Bambaataa": "Rap",
    "Mantronix": "Rap",
    "Stetsasonic": "Rap",
    "Ultramagnetic MCs": "Rap",
    "3rd Bass": "Rap",
    "Nice & Smooth": "Rap",
    "E.U.": "Rap",
    "Strange": "Rap",
    
    # Country
    "George Strait": "Country",
    "Garth Brooks": "Country",
    "Clint Black": "Country",
    "Travis Tritt": "Country",
    "Alan Jackson": "Country",
    "Randy Travis": "Country",
    "Dwight Yoakam": "Country",
    "Keith Whitley": "Country",
    "Reba McEntire": "Country",
    "The Judds": "Country",
    "Dolly Parton": "Country",
    "Kenny Rogers": "Country",
    "Alabama": "Country",
    "Oak Ridge Boys": "Country",
    "Restless Heart": "Country",
    "Shenandoah": "Country",
    "Highwaymen": "Country",
    "Willie Nelson": "Country",
    "Waylon Jennings": "Country",
    "Johnny Cash": "Country",
    "Kris Kristofferson": "Country",
    "Hank Williams Jr.": "Country",
    "Rosanne Cash": "Country",
    "Mary Chapin Carpenter": "Country",
    "K.T. Oslin": "Country",
    "Patty Loveless": "Country",
    "Vince Gill": "Country",
    "Marty Stuart": "Country",
    "Ricky Skaggs": "Country",
    "Steve Earle": "Country",
    "Lyle Lovett": "Country",
    "k.d. lang": "Country",
    "Kentucky Headhunters": "Country",
    "Sawyer Brown": "Country",
    "Exile": "Country",
    "Eddie Rabbitt": "Country",
    "Crystal Gayle": "Country",
    "Tanya Tucker": "Country",
    "Lorrie Morgan": "Country",
    "Baillie & The Boys": "Country",
    "Southern Pacific": "Country",
    "Desert Rose Band": "Country",
    "Nitty Gritty Dirt Band": "Country",
    "Rodney Crowell": "Country",
    "Foster & Lloyd": "Country",
    
    # New additions (Top Unknowns)
    "Queen": "Rock Alternativo",
    "Anne Dorte Michelsen": "Pop",
    "Full Force": "Pop", # R&B
    "Full Force (3)": "Pop",
    "Texas": "Pop", # Pop Rock
    "Tin Machine": "Rock Alternativo",
    "David Hasselhoff": "Pop",
    "Lisa Lisa & Cult Jam": "Pop",
    "Melissa Etheridge": "Rock Alternativo",
    "Transvision Vamp": "Rock Alternativo", # Pop Punk
    "Shakespear's Sister": "Pop",
    "Shakespeare's Sister": "Pop",
    "Del Amitri": "Rock Alternativo",
    "Gun": "Rock Alternativo",
    "Gun (2)": "Rock Alternativo",
    "Swing Out Sister": "Pop",
    "John Mellencamp": "Rock Alternativo",
    "The Kevin McDermott Orchestra": "Rock Alternativo",
    "UB40": "Pop", # Reggae Pop
    "Rush": "Rock Alternativo", # Prog
    "Weird Al Yankovic": "Pop",
    "Cats In Boots": "Metal", # Glam Metal
    "Joe Jackson": "Pop", # New Wave
    "Carmel": "Pop",
    "Trixter": "Metal", # Glam
    "Then Jerico": "Pop",
    "The Outfield": "Pop", # Power Pop
    "Howard Jones": "Pop",
    "Blue Murder": "Metal",
    "Big Trouble House": "Rock Alternativo",
    "The Hooters": "Rock Alternativo",
    "Fish": "Rock Alternativo", # Prog
    "Jermaine Jackson": "Pop",
    "The The": "Rock Alternativo",
    "The Blow Monkeys": "Pop",
    "Nik Kershaw": "Pop",
    "The Big F": "Rock Alternativo",
    "Michael Bolton": "Pop",
    "Ramones": "Punk",
    "Billy Ocean": "Pop",
    "The Jacksons": "Pop",
    "The Godfathers": "Rock Alternativo",
    "Quincy Jones": "Pop",
    "Robyn Hitchcock": "Rock Alternativo",
    "Robyn Hitchcock & The Egyptians": "Rock Alternativo",
    "Anderson Bruford Wakeman Howe": "Rock Alternativo", # Prog
    "Wolfsbane": "Metal",
    "Equinox": "Pop",
    "Eric Clapton": "Rock Alternativo", # Blues Rock
    "Kreator": "Metal", # Thrash
    "Litfiba": "Rock Alternativo",
    "The Lemonheads": "Rock Alternativo",
    "Dr. Baker": "Eletronico", # House
    "Crispin Hellion Glover": "Rock Alternativo", # Outsider
    "Stevie Ray Vaughan": "Rock Alternativo", # Blues
    "Arielle Dombasle": "Pop",
    "Mojo Nixon": "Rock Alternativo", # Cowpunk
    "Giant": "Rock Alternativo",
    "Nitro": "Metal",
    "Grayson Hugh": "Pop",
    "Thomas Dolby": "Pop",
    "Liza Minnelli": "Pop",
    "Serge Gainsbourg": "Pop",
    "Public Image Limited": "Rock Alternativo", # Post-punk
    "PiL": "Rock Alternativo",
    "Poco": "Country", # Country Rock
    "The Georgia Satellites": "Rock Alternativo",
    "Eddie Money": "Rock Alternativo",
    "Agitpop": "Rock Alternativo",
    "Christopher Williams": "Pop", # R&B
    "Vanilla Ice": "Rap",
    "Julian Lennon": "Pop",
    "Peter Himmelman": "Rock Alternativo",
    "Oui Oui": "Pop",
    "All About Eve": "Rock Alternativo",
    "The Wolfgang Press": "Rock Alternativo",
    "Havana Black": "Metal",
    "The Connells": "Rock Alternativo",
    "Diana Ross": "Pop",
    "Wax": "Pop",
    "The Grateful Dead": "Rock Alternativo",
    "Bundock Lanoie": "Rock Alternativo",
    "Big Audio Dynamite": "Rock Alternativo",
    "Matthew Sweet": "Rock Alternativo",
    "Drivin' N' Cryin'": "Rock Alternativo",
    "Marillion": "Rock Alternativo", # Prog
    "Walk On Fire": "Rock Alternativo",
    "Poopshovel": "Rock Alternativo",
    "After 7": "Pop", # R&B
    "MTB": "Country", # Marshall Tucker Band
    "The Afghan Whigs": "Rock Alternativo",
    "Faster Pussycat": "Metal",
    "Steve Stevens": "Rock Alternativo",
    "Clan Of Xymox": "Rock Alternativo", # Goth
    "Animotion": "Pop",
    "Herb Alpert": "Pop", # Jazz Pop
    "Chicken Scratch": "Pop",
    "Cool C": "Rap",
    "Gladys Knight": "Pop",
    "The Lightning Seeds": "Pop",
    "Stan Ridgway": "Rock Alternativo",
    "ABC": "Pop",
    "Fetchin Bones": "Rock Alternativo",
    "Prefab Sprout": "Pop",
    "Thompson Twins": "Pop"
}

# Normalize function
def normalize_artist(name):
    if not name:
        return "Unknown"
    return str(name).strip()

# Load the file
with open('data/1989.json', 'r') as f:
    data = json.load(f)

# Update the artist_genre
updated_count = 0
for item in data:
    artist_raw = item.get('artist_name')
    artist = normalize_artist(artist_raw)
    
    # Direct match
    if artist in genre_mapping:
        item['artist_genre'] = genre_mapping[artist]
        updated_count += 1
    # Check if artist contains mapped artist
    else:
        for mapped_artist, genre in genre_mapping.items():
            if mapped_artist in artist:
                 item['artist_genre'] = genre
                 updated_count += 1
                 break

# Save back to file
with open('data/1989.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Updated {updated_count} entries.")
